In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory






import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/towshintushi/nascinia/train.csv
/kaggle/input/datasets/towshintushi/nascinia/test.csv
/kaggle/input/datasets/towshintushi/new-adaptor/adapter_model.safetensors
/kaggle/input/datasets/towshintushi/new-adaptor/adapter_config.json
/kaggle/input/datasets/towshintushi/new-adaptor/README.md
/kaggle/input/datasets/towshintushi/new-adaptor/tokenizer.json
/kaggle/input/datasets/towshintushi/new-adaptor/tokenizer_config.json
/kaggle/input/datasets/towshintushi/new-adaptor/chat_template.jinja
/kaggle/input/datasets/towshintushi/submission/submission.csv
/kaggle/input/datasets/towshintushi/adapter/bn-doctor-lora/final_adapter/adapter_model.safetensors
/kaggle/input/datasets/towshintushi/adapter/bn-doctor-lora/final_adapter/adapter_config.json
/kaggle/input/datasets/towshintushi/adapter/bn-doctor-lora/final_adapter/README.md
/kaggle/input/datasets/towshintushi/adapter/bn-doctor-lora/final_adapter/tokenizer.json
/kaggle/input/datasets/towshintushi/adapter/bn-doctor-lora/final_adapter/tokenizer_config.json
/kaggle/input/datasets/towshintushi/adapter/bn-doctor-lora/final_adapter/chat_template.jinja

In [2]:
sub=pd.read_csv("/kaggle/input/datasets/towshintushi/submission/submission.csv")

In [3]:
sub.head()

      id                                    doctor_response
0  34654  হেলো ক্যারল, আপনার উদ্বেগের বিষয়ে আমি বলব যে ...
1   3116  হেলো! নাসেনিয়া ডকে আপনাকে স্বাগতম! আমি আপনার ...
2  59478  হেলো! নাসেনিয়া ডকে আপনাকে স্বাগতম! আমি আপনার ...
3  56450  হেলো! নাসেনিয়া ডকে আপনাকে স্বাগতম! আপনার লক্ষ...
4  86380  হেলো! নাসেনিয়া ডকে আপনাকে স্বাগতম! আমি আপনার ...

In [4]:
sub = sub.rename(columns={"doctor_response": "output"})

In [5]:

sub.to_csv("submission.csv", index=False)

In [6]:
sub2=pd.read_csv("/kaggle/working/submission.csv")

In [7]:
sub2.head()

      id                                             output
0  34654  হেলো ক্যারল, আপনার উদ্বেগের বিষয়ে আমি বলব যে ...
1   3116  হেলো! নাসেনিয়া ডকে আপনাকে স্বাগতম! আমি আপনার ...
2  59478  হেলো! নাসেনিয়া ডকে আপনাকে স্বাগতম! আমি আপনার ...
3  56450  হেলো! নাসেনিয়া ডকে আপনাকে স্বাগতম! আপনার লক্ষ...
4  86380  হেলো! নাসেনিয়া ডকে আপনাকে স্বাগতম! আমি আপনার ...

##

In [8]:
train=pd.read_csv("/kaggle/input/datasets/towshintushi/nascinia/train.csv")

In [9]:
test=pd.read_csv("/kaggle/input/datasets/towshintushi/nascinia/test.csv")

In [10]:
train.head()

,id,input,output
0,45361,"হেলো, আমরা গত ৩ মাস ধরে গর্ভধারণের চেষ্টা করছি...","হেলো, পিসিওডি (PCOD) হলো এমন একটি উপসর্গ যা অন..."
1,95550,প্রায় এক মাস আগে আমার পিঠের ডান দিকের কাঁধের হ...,"হেলো, প্রথমে আমাকে আপনাকে ব্যাখ্যা করতে দিন যে..."
2,98599,"হেলো, আমি ২৫ বছর বয়সী অবিবাহিত মেয়ে। আমার কপাল...","হেলো কবিতা, লেখার জন্য ধন্যবাদ। স্কিন লাইটেনিং..."
3,84959,"হেলো, আমার বয়স ২২, উচ্চতা ৫ ফুট ৯ ইঞ্চি এবং ওজ...","হেলো প্রিয়, নাসেনিয়া ডকে আপনাকে স্বাগতম। আপনা..."
4,65169,"হেলো, আমার নানি প্রায়ই অভিযোগ করেন যে তার হৃদপ...","হেলো, আমি আপনার প্রশ্নটি মনোযোগ সহকারে পড়েছি এ..."

In [11]:
test.head()

      id                                              input
0  34654  আমার লাইপেজ লেভেল ১৫৮, যা বেশি। অ্যামাইলেজ লেভ...
1   3116  তিন সপ্তাহ আগে আমার দাঁতে খুব ব্যথা ছিল, ৮ দিন...
2  59478  আমার স্বামীর বয়স ৫৬ বছর, তিনি খুব একটা মিশুক ন...
3  56450  হেলো, আমার বয়স ৩৮ বছর। আমার বাম পায়ে, একই দিকে...
4  86380  গত মঙ্গলবার আমি ফ্লু শট এবং টিবি পরীক্ষা করিয়ে...

Data Cleaning

In [12]:
train.isnull().sum()

id        0
input     0
output    0
dtype: int64

In [13]:
print("Train:", train.shape)
print("Test :", test.shape)

print(train.info())
print(test.info())

print("\nMissing values:")
print(train.isna().sum())
print(test.isna().sum())

print("\nDuplicate rows in train set:", train.duplicated().sum())
print("Duplicate inputs in train set:", train["input"].duplicated().sum())
print("Duplicate ids in train set:", train["id"].duplicated().sum())
print("Duplicate output in train set:", train["output"].duplicated().sum())

Train: (108954, 3)
Test : (1000, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108954 entries, 0 to 108953
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      108954 non-null  int64
 1   input   108954 non-null  object
 2   output  108954 non-null  object
dtypes: int64(1), object(2)
memory usage: 2.5+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1000 non-null   int64
 1   input   1000 non-null   object
dtypes: int64(1), object(1)
memory usage: 15.8+ KB
None

Missing values:
id        0
input     0
output    0
dtype: int64
id       0
input    0
dtype: int64

Duplicate rows in train set: 0
Duplicate inputs in train set: 205
Duplicate ids in train set: 0
Duplicate output in train set: 2836

In [14]:
duplicate_inputs = train[
    train["input"].duplicated(keep=False)
].sort_values("input")

print("Rows involved:", len(duplicate_inputs))
print("Unique duplicated inputs:", duplicate_inputs["input"].nunique())

Rows involved: 255
Unique duplicated inputs: 50

In [15]:
duplicate_inputs = test[
    test["input"].duplicated(keep=False)
].sort_values("input")

print("Rows involved:", len(duplicate_inputs))
print("Unique duplicated inputs:", duplicate_inputs["input"].nunique())

Rows involved: 0
Unique duplicated inputs: 0

In [16]:
# input_output_counts = (
#     duplicate_inputs
#     .groupby("input")["output"]
#     .nunique()
#     .value_counts()
#     .sort_index()
# )

# print(input_output_counts)

In [17]:
# conflicting_inputs = (
#     duplicate_inputs
#     .groupby("input")["output"]
#     .nunique()
# )

# conflicting_inputs = conflicting_inputs[
#     conflicting_inputs > 1
# ]



# print("Inputs with multiple different outputs:",
#       len(conflicting_inputs))

In [18]:
# Find inputs that have multiple different outputs
conflicting = (
    train.groupby("input")["output"]
    .nunique()
    .reset_index(name="num_unique_outputs")
)

conflicting = conflicting[conflicting["num_unique_outputs"] > 1]

# Add input length
conflicting["input_length"] = conflicting["input"].str.len()

# Get suspicious short inputs
suspicious_inputs = conflicting[
    conflicting["input_length"] < 50
]["input"]

# Get their IDs
suspicious_rows = train[
    train["input"].isin(suspicious_inputs)
].sort_values(["input", "id"])

print("Number of suspicious inputs:", len(suspicious_inputs))
print("Number of rows:", len(suspicious_rows))

print(
    suspicious_rows[
        ["id", "input", "output"]
    ].to_string(index=False)
)

Number of suspicious inputs: 38
Number of rows: 231
    id                                            input                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    output
 41769                   আমার এমআরআই রিপোর্টে দেখা গেছে                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                হেলো, নাসেনিয়া ডকে লেখার জন্য ধন্যবাদ। সাধারণত, এক্সট্রুডেড ডিস্কের কারণে যে উপসর্গগুলো দেখা দেয়, তা রক্ষণশীল চিকিৎসায় পুরোপুরি সেরে ওঠে না। যদি আপনার উদ্বেগের কারণ শুধুমাত্র ঝিঁঝিঁ ধরা বা অসাড়তা হয়, তবে প্রেগাবালিন এবং মিথাইলকোবালামিনের সংমিশ্রণ কিছুটা সাহায্য করতে পারে, কিন্তু এটি সম্পূর্ণ নিরাময় প্রদান করবে না। আমি ব্যক্তিগতভাবে মনে করি যে আপনার ক্ষেত্রে সার্জিক্যাল ডিকম্প্রেশন (যেহেতু সংশ্লিষ্ট পেশীগুলোতে দুর্বলতা রয়ে গেছে) প্রয়োজন, যা এন্ডোস্কোপিক ডিসেক্টমি বা মাইক্রোলুম্বার ডিসেক্টমির মাধ্যমে করা যেতে পারে এবং এর ফলাফল চমৎকার। তাই, পরবর্তী চিকিৎসার জন্য আমি আপনাকে একজন স্পাইন সার্জনের সাথে পরামর্শ করার পরামর্শ দিচ্ছি। আশা করি এই তথ্যটি আপনার জন্য সহায়ক হবে। আপনার দিনটি ভালো কাটুক।
 83684                   আমার এমআরআই রিপোর্টে দেখা গেছে                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             আপনি যদি অন্তত আপনার বয়স এবং আপনার কিছু ক্লিনিকাল ইতিহাস আমাদের জানাতেন তবে এটি অনেক সহজ হতো। সেই রিপোর্টের কোনো ফলাফলই জীবন-হুমকিস্বরূপ নয়। প্রথম অংশটি কিছু পুরনো আঘাতের অবশিষ্টাংশকে নির্দেশ করে, অনেকটা ছোট ক্ষতের মতো, যা আর সক্রিয় নয় এবং এর উৎস নির্ণয় করা কঠিন; এটি অতীতে কোনো সংক্রমণ বা রক্ত প্রবাহের অভাবের কারণে ছোট রক্তনালী সরু হয়ে যাওয়ার ফলে সামান্য আঘাত হতে পারে। বয়স ৬৫-এর বেশি হলে পরেরটি হওয়ার সম্ভাবনা বেশি, তাই উচ্চ রক্তচাপ, ডায়াবেটিস, ধূমপান, উচ্চ কোলেস্টেরল ইত্যাদির মতো বিষয়গুলোর দিকে নজর দেওয়া উচিত, যা ভবিষ্যতে আপনার রক্তনালীর আরও ক্ষতির ঝুঁকি বাড়ায়। মাইক্রোহেমোরেজের ক্ষেত্রে, এটি মস্তিষ্কে একটি ছোট রক্তপাত। এরও বেশ কয়েকটি কারণ থাকতে পারে, রিপোর্টটি কারণ হিসেবে একটি ক্যাভারনোমার কথা উল্লেখ করেছে, এটি একটি রক্তনালীর অস্বাভাবিকতা, যা ছোট রক্তপাত বা খিঁচুনি সৃষ্টি করতে পারে, তবে খুব নির্দিষ্ট কিছু স্থানে না হলে এটি সাধারণত জীবন-হুমকিস্বরূপ নয়, আপনার ক্ষেত্রে তেমনটি মনে হচ্ছে না। সাধারণত এটি যেমন আছে তেমনই রাখা হয়, খুব কম ক্ষেত্রেই অস্ত্রোপচার বা খিঁচুনির জন্য চিকিৎসার প্রয়োজন হয়।
 95419                   আমার এমআরআই রিপোর্টে দেখা গেছে                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              হেলো, স্নায়বিক দুর্বলতা যা কমপ্রেশনের কারণে হচ্ছে তার ওপর ভিত্তি করে অস্ত্রোপচারের প্রয়োজনীয়তা মূল্যায়ন করা হয়। যদি এটি কোনো দুর্বলতা সৃষ্টি করে তবে অস্ত্রোপচারের পরামর্শ অবশ্যই দেওয়া হয়। যদি ব্যথা নিয়ন্ত্রণহীন হয় তবে অস্ত্রোপচারের কথা বিবেচনা করা যেতে পারে। চিকিৎসার অন্যান্য পদ্ধতির মধ্যে রয়েছে কঠোরভাবে বিছানায় বিশ্রাম এবং ফিজিওথেরাপি। কখনও কখনও স্থানীয় এলাকায় ইনজেকশন দীর্ঘস্থায়ী আরাম দিতে পারে। ডিস্ক বাল্জের অবস্থানের ওপর ভিত্তি করে অস্ত্রোপচারের ধরন নির্ধারণ করা হয়। মূলত ডিস্কের যে অংশটি স্নায়ুর ওপর চাপ সৃষ্টি করছে তা কেটে অপসারণ করা হয়। শুভকামনা।
 24486                                  আমার প্রশ্ন হলো                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         হেলো, নাসেনিয়া ডকে আপনাকে স্বাগতম। আমি আপনার প্রশ্ন এবং উদ্বেগ বুঝতে পেরেছি। রেনাল ধমনী অবরুদ্ধ হওয়ার কারণ উচ্চ রক্তচাপ হতে পারে। এর জন্য সময়মতো যথাযথ অনুসন্ধানমূলক প্রোটোকল প্রয়োজন। স্টেন্টিং পদ্ধতির মাধ্যমে স্টেনোসিস নিরাময় করা সম্ভব। আপনার হৃদপিণ্ডের প্রাথমিক কার্যক্ষমতা মূল্যায়নের জন্য আমি আপনাকে একটি বেসলাইন টু-ডাইমেনশনাল ইকোকার্ডিওগ্রাফি, ইসিজি এবং লিপিড প্রোফাইল পরীক্ষা করার পরামর্শ দিচ্ছি। লবণের গ্রহণ দৈনিক ৬ গ্রামের নিচে সীমাবদ্ধ রাখুন। সপ্তাহে ৫ দিন ২০ মিনিট করে দ্রুত হাঁটার মতো নিয়মিত শারীরিক ব্যায়াম বেশ উপকারী। নাসেনিয়া ডক। চর্বিযুক্ত এবং ভাজা খাবার গ্রহণ কমান। প্রতিদিন একটি ডালিম রক্ত জমাট বাঁধা রোধ করে আপনার হৃদপিণ্ডকে ভালো রাখতে সাহায্য করবে। স্টেম সেল পদ্ধতি এখনও গবেষণাধীন। আপনার ক্ষেত্রে স্টেন্ট বসানো নিরাময়মূলক হবে। পরবর্তী বিশেষজ্ঞ ব্যবস্থাপনার জন্য একজন কার্ডিওলজিস্টের সাথে পরামর্শ করুন। আপনার আরও কোনো প্রশ্ন থাকলে জানান। ধন্যবাদ।
 39696                                  আমার প্রশ্ন হলো                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            হেলো, আমাদের সাথে যোগাযোগ করার জন্য ধন্যবাদ। আমি আপনার উদ্বেগ বুঝতে পেরেছি। আমি যদি আপনার চিকিৎসাকারী ডাক্তার হতাম, তবে আমি আপনাকে পরামর্শ দিতাম যে নখের ছত্রাক সংক্রমণের জন্য সর্বদা তিন থেকে চার মাসের চিকিৎসার প্রয়োজন হয়। আপনি যে সংমিশ্রণটির কথা উল্লেখ করেছেন তা একটি ভালো সংমিশ্রণ, আপনি এটি ওটিসি সেন্টার থেকে নিতে পারেন। একটি বিষয় মনে রাখবেন যে চিকিৎসা সম্পূর্ণ করা জরুরি, অন্যথায় সংক্রমণ পুনরায় ফিরে আসার সম্ভাবনা থাকে। আমি আপনার আরও উদ্বেগের উত্তর দিতে পারলে খুশি হব, দয়া করে আমাকে জানাবেন। নাসেনিয়া ডকে আপনার সুস্বাস্থ্য কামনা করি। নাসেনিয়া ডক। সংক্রামক রোগ বিশেষজ্ঞ।
 47611                                  আমার প্রশ্ন হলো                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           সংক্ষিপ্ত উত্তর
105742                      আমার বীর্য বিশ্লেষণ রিপোর্ট                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                হেলো, নাসেনিয়া ডক ব্যবহার করার জন্য ধন্যবাদ। বীর্য বিশ্লেষণ বীর্যের বিভিন্ন (তবে সব নয়) দিকগুলো পরীক্ষা করে। এটি মনে রাখা গুরুত্বপূর্ণ যে, স্বাভাবিক বীর্য পরীক্ষার ফলাফল থাকা পুরুষদেরও সন্তান ধারণে সমস্যা হতে পারে এবং অস্বাভাবিক ফলাফল থাকা পুরুষদের ক্ষেত্রে তা নাও হতে পারে। আপনার ফলাফলের ক্ষেত্রে

In [19]:
print(
    train[
        train["input"].isin(suspicious_inputs)
    ][["id", "input"]]
    .sort_values("id")
    .to_string(index=False)
)

    id                                            input
   222                            হেলো, আপনি কেমন আছেন?
   672                                             হেলো
  2295                                         শুভ সকাল
  2812                                             হেলো
  3081              স্যার; আমার মৌলিক বিশ্লেষণ নিম্নরূপ
  3495                                     হেলো ডাক্তার
  3590                                           ইতিহাস
  4702                                              নাম
  5831                                            ধারণা
  6500                                        রোগীর নাম
  6516                                              বয়স
  6522                                             হেলো
  7246              আমি গত ৩ মাস ধরে পেটে ব্যথায় ভুগছি।
  7422                                             হেলো
  7491                                          হেলো ডক
  7667                                              বয়স
  7969                                             হেলো
  8242                                              বয়স
  9141                                              বয়স
  9698                                           পটভূমি
 10812                                              বয়স
 12005                                             হেলো
 12546                                     হেলো ডাক্তার
 12742                                           উচ্চতা
 12838                                     হেলো ডাক্তার
 13091                                            ফলাফল
 13372                                             হেলো
 14590                                             হেলো
 15103                                     কেস হিস্ট্রি
 15227                                              বয়স
 15285                                             হেলো
 15398                                           প্রশ্ন
 15796                                            ধারণা
 16223                            হেলো, আপনি কেমন আছেন?
 16284                                              বয়স
 18044                                             হেলো
 19066                            হেলো, আপনি কেমন আছেন?
 20678                                             হেলো
 21163                                              নাম
 21673                                              বয়স
 21978                                              বয়স
 22099                                              নাম
 22765                                              বয়স
 22811                                            ধারণা
 23116                                             হেলো
 24486                                  আমার প্রশ্ন হলো
 24797                                           প্রশ্ন
 24813                                             থেকে
 25018                                             হেলো
 25725                                             হেলো
 26532                                             হেলো
 26835             রক্ত পরীক্ষার রিপোর্ট নিচে দেওয়া হলো
 27256                                           প্রশ্ন
 27605                                             হেলো
 27954                            হেলো, আপনি কেমন আছেন?
 28073                                             হেলো
 28473                                             হেলো
 29585                                 হেলো ডক্টর গ্রিফ
 29611             রক্ত পরীক্ষার রিপোর্ট নিচে দেওয়া হলো
 30182                                              বয়স
 30717                                           উপসর্গ
 31084                                             হেলো
 31627                                              বয়স
 32350                                              নাম
 33810 হেলো, আমার রক্তে সালমোনেলা ছিল যা নিচে দেওয়া হলো
 34540                                     হেলো ডাক্তার
 34651                                      শুভ সন্ধ্যা
 34934                                             হেলো
 35908                                             হেলো
 35910                                             হেলো
 36020                                             হেলো
 37245                                             রোগী
 37668                                           পটভূমি
 38130                                             হেলো
 39619                                              বয়স
 39696                                  আমার প্রশ্ন হলো
 40512                                             হেলো
 41320                                             হেলো
 41743 হেলো, আমার রক্তে সালমোনেলা ছিল যা নিচে দেওয়া হলো
 41769                   আমার এমআরআই রিপোর্টে দেখা গেছে
 42132                                             হেলো
 42250                                             হেলো
 42284                                   হেলো, আমার বয়স
 42301                                             হেলো
 42350                                         শুভ সকাল
 43133                                 হেলো ডক্টর গ্রিফ
 43245                                             হেলো
 43321                                             হেলো
 44623                          ৭৮৬ আমার নাম রহিমুল্লাহ
 44797                                           ইতিহাস
 45902                                        রোগীর বয়স
 46703              আমি গত ৩ মাস ধরে পেটে ব্যথায় ভুগছি।
 46889                                        বাম কিডনি
 47076                                             হেলো
 47202                                              নাম
 47611                                  আমার প্রশ্ন হলো
 47872                                              বয়স
 49401                                              নাম
 49566                                            যৌনতা
 51219                                             হেলো
 51744                                              বয়স
 52109                                             হেলো
 52595                                       উপসর্গসমূহ
 52728                                              নাম
 54062                                    প্রিয় ডাক্তার
 54576                                             হেলো
 54858                                              নাম
 54967                                           প্রশ্ন
 55250                                             হেলো
 55504                   আমার বীর্য বিশ্লেষণে দেখা গেছে
 55933                                              নাম
 56721                                             হেলো
 57089                                             হেলো
 58732                                             হেলো
 58785                                             হেলো
 58993                                              বয়স
 60178                                             হেলো
 60217                                           সমস্যা
 60237                                           পটভূমি
 60637                                           প্রশ্ন
 61362                                           প্রশ্ন
 61904                                             হেলো
 62419                                              বয়স
 63300                                             হেলো
 65598                                             হেলো
 65967                                             হেলো
 66347                            হেলো, আপনি কেমন আছেন?
 66600                                             হেলো
 66687                                           পটভূমি
 67568                                            যৌনতা
 68539                                             হেলো
 70148                                              বয়স
 71502                                              বয়স
 71854                                             হেলো
 72461                                       উপসর্গসমূহ
 73455                                              বয়স
 73498                                           সমস্যা
 73693                                             হেলো
 76361                                              নাম
 76850                                    প্রিয় ডাক্তার
 77042                                         আমার বয়স
 77520                                              বয়স
 79311                                             হেলো
 79478                                              বয়স
 79580                                              বয়স
 79666                                           ইতিহাস
 79928                                     হেলো ডাক্তার
 80687                                              বয়স
 81015                            হেলো, আপনি কেমন আছেন?
 81206                                     হেলো ডাক্তার
 81245                                             হেলো
 81270                                        রোগীর নাম
 81485                                             হেলো
 81684                                        রোগীর বয়স
 81688                                         শুভ সকাল
 82389                                             হেলো
 83036                                   হেলো, আমার বয়স
 83684                   আমার এমআরআই রিপোর্টে দেখা গেছে
 84204                                             হেলো
 84577                            হেলো, আপনি কেমন আছেন?
 85305                                              বয়স
 85816                                         আমার বয়স
 85837                                           প্রশ্ন
 86149                          ৭৮৬ আমার নাম রহিমুল্লাহ
 86770                                              বয়স
 87054                                           প্রশ্ন
 87157                                             হেলো
 87413                                              বয়স
 87810                                            ফলাফল
 88160                                             হেলো
 88369                                              বয়স
 88405                                              নাম
 89473                                             হেলো
 89624                                             হেলো
 89633                                             হেলো
 89882                                            হেলো!
 89982                                             হেলো
 90046                            হেলো, আপনি কেমন আছেন?
 90164                   আমার বীর্য বিশ্লেষণে দেখা গেছে
 90226                                           উচ্চতা
 91795                                             হেলো
 91823                                             হেলো
 92398                                             থেকে
 92619                                        বাম কিডনি
 93068                                            ধারণা
 93404              স্যার; আমার মৌলিক বিশ্লেষণ নিম্নরূপ
 93458                                            ফলাফল
 93600                                              নাম
 93629                                    প্রিয় ডাক্তার
 93719                                              বয়স
 94379                                       উপসর্গসমূহ
 94574                                             হেলো
 95238                                              বয়স
 95419                   আমার এমআরআই রিপোর্টে দেখা গেছে
 95499                                     কেস হিস্ট্রি
 95662                                           উপসর্গ
 97654                                              বয়স
 98197                                              বয়স
 98242                                           ইতিহাস
 98302                                              নাম
 98352                                              বয়স
 98696                                     হেলো ডাক্তার
 98810                                             রোগী
 99173                                             হেলো
 99279                                             হেলো
100271                                             হেলো
100330                                             হেলো
100392                                             হেলো
100625                                              নাম
100739                                            ফলাফল
101124                                             হেলো
103603                                           প্রশ্ন
103847                                              বয়স
104209                                             হেলো
105488                            হেলো, আপনি কেমন আছেন?
105742                      আমার বীর্য বিশ্লেষণ রিপোর্ট
105939                                            হেলো!
107597                                              নাম
108186                                             হেলো
108936                                             হেলো
109113                                           পটভূমি
109258                                      শুভ সন্ধ্যা
109600                                              নাম
109613                                          হেলো ডক
109801                                           প্রশ্ন
111009                                     হেলো ডাক্তার
111230                                             হেলো
111517                                              বয়স
111887                                             হেলো
111958                                              বয়স
112046                      আমার বীর্য বিশ্লেষণ রিপোর্ট

In [20]:
# Inputs that are very short
short_input_rows = train[
    train["input"].str.len() <= 20
].copy()

print("Number of short-input rows:", len(short_input_rows))

Number of short-input rows: 385

In [21]:
# Inputs that are very short
short_input_rows = test[
    test["input"].str.len() <= 20
].copy()

print("Number of short-input rows:", len(short_input_rows))

Number of short-input rows: 0

In [22]:
train["input_length"] = train["input"].str.len()

print(
    train["input_length"].describe(
        percentiles=[0.01, 0.05, 0.10, 0.25, 0.50]
    )
)

count    108954.000000
mean        439.129798
std         247.672032
min           1.000000
1%           66.000000
5%          234.000000
10%         260.000000
25%         301.000000
50%         372.000000
max       10814.000000
Name: input_length, dtype: float64

In [23]:
short_inputs = train[
    train["input"].str.len() <= 30
].sort_values("input_length")

for _, row in short_inputs.iterrows():
    print("=" * 100)
    print(f"ID     : {row['id']}")
    print(f"INPUT  : {row['input']}")
    print(f"OUTPUT : {row['output']}")

====================================================================================================
ID     : 66179
INPUT  : ।
OUTPUT : হেলো এবং নাসেনিয়া ডকে আপনাকে স্বাগতম। আপনার অনুসন্ধানের জন্য ধন্যবাদ। আপনি যে সমস্যায় ভুগছেন তাকে ইউরিনারি ইনকন্টিনেন্স বা প্রস্রাব ধরে রাখতে না পারার সমস্যা বলা হয়। এই সমস্যার কারণ খুঁজে বের করার জন্য আপনাকে একজন ডাক্তারের কাছে গিয়ে বিস্তারিত পরীক্ষা করাতে হবে। যদি মূত্রাশয়ে কোনো বাধা না থাকে (যার জন্য অস্ত্রোপচারের প্রয়োজন হয়), তবে চিকিৎসার অন্যান্য পদ্ধতির মধ্যে রয়েছে
====================================================================================================
ID     : 101250
INPUT  : ডক
OUTPUT : হেলো, ডেইরি, আমি আপনার প্রশ্নটি দেখেছি। আমি আপনার উদ্বেগ বুঝতে পারছি। তার অ্যাবসোলিউট ইওসিনোফিল কাউন্ট বেশি এবং লার্ভার কিছু অংশ পাওয়া গেছে। তাই তার কোনো পরজীবী সংক্রমণ থাকতে পারে। এর জন্য তার অ্যান্টিবায়োটিক গ্রহণ করা উচিত। ইওসিনোফিলিক ডায়েটারি কার্বামাজেপাইন বা অ্যান্টিহিস্টামিন বা স্টেরয়েড গ্রহণ করা যেতে পারে। আপনার ডাক্তারের সাথে পরামর্শ করুন এবং সেই অনুযায়ী চিকিৎসা নিন। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি, যদি আপনার কোনো সন্দেহ থাকে তবে আমি উত্তর দিতে পেরে খুশি হব। নাসেনিয়া ডক ব্যবহার করার জন্য ধন্যবাদ। আপনার সুস্বাস্থ্য কামনা করি।
====================================================================================================
ID     : 82458
INPUT  : এফ
OUTPUT : হেলো! অনুসন্ধানের জন্য আপনাকে ধন্যবাদ। এইচপিভি সংক্রমণ কোলন ক্যান্সারের একটি প্রমাণিত ঝুঁকি নয়। আপনার জানা উচিত যে আপনি খুব কম বয়সী এবং আপনার বয়সে কোলন ক্যান্সারের ঝুঁকি খুবই কম (যদি আপনার পরিবারে অল্প বয়সে ক্যান্সার হয়ে থাকে তবে ঝুঁকি বেশি হতে পারে)। সাধারণ মানুষের মধ্যে কোলন ক্যান্সারের ঝুঁকি সাধারণত ৩% এর কাছাকাছি। কোলন ক্যান্সারের সাধারণ লক্ষণগুলো হলো
====================================================================================================
ID     : 79478
INPUT  : বয়স
OUTPUT : ১. থাইরয়েড নডিউল সাধারণত বিনাইন বা ক্ষতিকর নয় এবং খুব কম ক্ষেত্রেই ক্যান্সারযুক্ত হয়, যদি না আপনার চিকিৎসক ভিন্ন কিছু মনে করেন।
২. আপনি প্যাথলজি সম্পর্কিত কোনো উপসর্গের কথা উল্লেখ করেননি??
৩. ওজন কমে যাওয়া, অনিদ্রা, বুক ধড়ফড় করা, উদ্বেগ, কাঁপুনি, ক্লান্তি বা বিষণ্নতার কোনো উপসর্গ আছে কি? টিএফটি (TFT) রিপোর্ট।
৪. প্যাথলজিটির কারণে গলায় কোনো ব্যথা বা চাপ, কণ্ঠস্বরের কর্কশতা বা গলার কোমলতা অনুভূত হচ্ছে কি?
৫. সম্ভবত যে গলগণ্ড বা গয়টারটির কথা বলা হচ্ছে তা নন-টক্সিক, তাই আয়োডিনযুক্ত নাসেনিয়া ডক।
৬. আয়ুর্বেদিক ভেষজ শিরিষ এবং জলকুম্ভী দেওয়া বা পরামর্শ দেওয়া যেতে পারে।
====================================================================================================
ID     : 16284
INPUT  : বয়স
OUTPUT : হেলো, এটি নাসেনিয়া ডক। ইনোসেন্ট মারমার সাধারণত ক্ষতিকর নয় এবং যদি ইকো স্বাভাবিক থাকে তবে এটি আপনাকে প্রভাবিত করবে না। কিন্তু তবুও গাঁজা বা এই জাতীয় নেশাজাতীয় দ্রব্য সেবন এই ধরনের ব্যক্তিদের জন্য অত্যন্ত ঝুঁকিপূর্ণ। আপনি যে লক্ষণগুলোর কথা বলছেন তা কেবল গাঁজা সেবনের সাথেই সম্পর্কিত। এটি সেবনের পর অ্যারিথমিয়া (সুপ্রভেন্ট্রিকুলার অ্যারিথমিয়া)-এর ঝুঁকিও থাকে। এই ট্যাকিকার্ডিয়া বা হৃদস্পন্দন বেড়ে যাওয়া বেশিরভাগ সময়েই সমস্যা সৃষ্টি করতে পারে। তাই আমি আপনাকে পরামর্শ দিচ্ছি যে, যতটা সম্ভব গাঁজা সেবন থেকে বিরত থাকুন। এছাড়া, সঠিক সময়ে এটি ছেড়ে না দিলে আপনি এতে আসক্ত হয়ে পড়তে পারেন। তাই সুস্থ থাকুন এবং নিরাপদে থাকুন। শুভেচ্ছা।
====================================================================================================
ID     : 21163
INPUT  : নাম
OUTPUT : হেলো শ্রীনিবাসন রান, আপনি যেমনটি খুব সঠিকভাবে বলেছেন, আপনার উপসর্গগুলো অ্যালার্জির সাথে সম্পর্কিত। এটি আপনার ব্যবহৃত শ্যাম্পু বা কন্ডিশনার অথবা পানি কিংবা পানির তাপমাত্রার কারণে হতে পারে। যেকোনো অ্যালার্জির ক্ষেত্রে, সর্বোত্তম সমাধান হলো যে অ্যালার্জেনটি উপসর্গের কারণ হচ্ছে তা এড়িয়ে চলা। যদি এটি সম্ভব না হয়, তবে উপসর্গ কমাতে অ্যান্টিহিস্টামিন গ্রহণ করতে হবে। একটি দ্বিতীয় প্রজন্মের নন-সিডেটিং অ্যান্টিহিস্টামিন আপনার উপসর্গ কমাতে সাহায্য করবে। আপনার আরও কোনো প্রশ্ন থাকলে আমি উত্তর দিতে পারলে খুশি হব। শুভকামনা।
====================================================================================================
ID     : 22099
INPUT  : নাম
OUTPUT : হেলো, ল্যান্ডিং। আপনি যেহেতু উল্লেখ করেছেন যে আপনার সিস্ট হয়েছে (যেহেতু আপনি বাম দিকের তলপেটে ব্যথার কথা বলেছেন) এবং রোগ নির্ণয় করা হয়েছে। আপনার একমাত্র প্রশ্ন ছিল ওভারিয়ান সিস্টের (সম্ভবত) অস্ত্রোপচারের খরচ নিয়ে। আমি আপনাকে একটি বিষয় জানাতে চাই যে, আমাদের দেশে সিস্টের অস্ত্রোপচারের খরচ পরিবর্তনশীল। হাসপাতাল, শহর এবং সার্জনের ধরনের ওপর নির্ভর করে এটি ৪,০০০ টাকা থেকে ৫০,০০০ টাকা পর্যন্ত হতে পারে। তাই আমি আপনাকে পরামর্শ দিচ্ছি যে, অনুগ্রহ করে ৩-৪টি হাসপাতাল এবং সার্জনের সাথে পরামর্শ করুন এবং নিরাপদ অস্ত্রোপচার ও এর খরচ সম্পর্কে তাদের মতামত নিন। আপনার জন্য শুভকামনা রইল।
====================================================================================================
ID     : 7667
INPUT  : বয়স
OUTPUT : হেলো, অনুসন্ধানের জন্য ধন্যবাদ। আইইউডি (IUD) ব্যবহারের সময় কিছুটা ঋতুস্রাবের অনিয়ম হওয়া স্বাভাবিক। তবে যেহেতু আপনার অতিরিক্ত রক্তপাত হচ্ছে, তাই একজন স্ত্রীরোগ বিশেষজ্ঞের সাথে পরামর্শ করা ভালো। তার পরামর্শ অনুযায়ী অ্যান্টি-ফাইব্রিনোলাইটিক ওষুধ সেবন করুন। এরপর চক্রটিকে নিয়মিত করার জন্য কয়েক দিন অতিরিক্ত হরমোনাল পিল গ্রহণ করতে পারেন। এই সময়ে আইইউডি অপসারণের প্রয়োজন নেই। পিল খাওয়া বন্ধ করার পর আপনি আইইউডি ব্যবহার চালিয়ে যেতে পারেন। ভালো থাকবেন।
====================================================================================================
ID     : 47872
INPUT  : বয়স
OUTPUT : প্রিয় বন্ধু। নাসেনিয়া ডকে আপনাকে স্বাগতম। আমি নাসেনিয়া ডক। আমি আপনার প্রশ্নটি বিস্তারিতভাবে পড়েছি। তাছাড়া, আমি আপনার উদ্বেগ বুঝতে পারছি। মূত্রনালীর সংক্রমণ (ইউটিআই) হওয়ার কারণটি আমাদের প্রথমে নিশ্চিত করতে হবে। যদি নিয়াসিন ইনজেকশনের পরেও আপনি স্বস্তি না পান, তবে আমি আপনাকে পরামর্শ দেব
====================================================================================================
ID     : 73455
INPUT  : বয়স
OUTPUT : হেলো, প্রিয়। আমি আপনার প্রশ্নটি দেখেছি। আমি আপনার উদ্বেগ বুঝতে পারছি। জিওটি (GOT) এবং এসজিপিটি (SGPT) হলো লিভারের এনজাইম। লিভারের যেকোনো ধরনের ক্ষতির ক্ষেত্রে এগুলোর মাত্রা বেড়ে যায়। এর সাধারণ কারণগুলোর মধ্যে রয়েছে অ্যালকোহল, নাসেনিয়া ডক। আপনার মদ্যপানের ইতিহাস রয়েছে। আপনার অ্যালকোহলজনিত লিভারের রোগ থাকতে পারে। এছাড়া, আপনার সম্পূর্ণ লিভার ফাংশন টেস্ট করানো উচিত। অ্যালকোহল পান বন্ধ করুন এবং আপনার ডাক্তারের পরামর্শ অনুযায়ী চিকিৎসা নিন। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি, যদি আপনার কোনো সন্দেহ থাকে তবে আমি উত্তর দিতে খুশি হব। নাসেনিয়া ডক ব্যবহার করার জন্য ধন্যবাদ। আপনার সুস্বাস্থ্য কামনা করি।
====================================================================================================
ID     : 80687
INPUT  : বয়স
OUTPUT : আপনার উপসর্গগুলো খুব একটা সুনির্দিষ্ট নয়, যার অর্থ হলো এগুলো অনেক কিছুর কারণেই হতে পারে, অথবা এগুলো সম্পূর্ণ ক্ষতিকর নয় এমন কোনো কারণেও হতে পারে। আপনার ঋতুস্রাবের কাছাকাছি সময়ে এই উপসর্গগুলো (কাঁপুনি এবং ঘাম) হওয়ার অর্থ হতে পারে যে এটি কেবল আপনার পিরিয়ডের সাথে সম্পর্কিত। প্রতিটি পিরিয়ডের আগে, কিছু মহিলার বিভিন্ন উপসর্গ দেখা দেয় এবং কাঁপুনি/ঘাম হয়তো আপনার পিরিয়ডের আগের উপসর্গ হতে পারে। আইভিএফ (IVF)-এর সময় আপনার উপসর্গগুলো অনেক বেশি খারাপ হওয়ার বিষয়টি হয়তো আইভিএফ চলাকালীন হরমোনের মাত্রা বৃদ্ধির প্রতিফলন মাত্র। ইতিবাচক থাকুন এবং যত দ্রুত সম্ভব একটি প্রেগন্যান্সি টেস্ট করুন। শুভকামনা!
====================================================================================================
ID     : 62419
INPUT  : বয়স
OUTPUT : হিসিমভিভাতে অ্যারোসল স্টেরয়েড থাকে। অ্যালার্জিজনিত কারণে শ্বাসকষ্টের চিকিৎসা দুটি ধাপে করা হয়। প্রথম ধাপ হলো তীব্র সমস্যার অবসান বা রোগীকে দ্রুত আরাম দেওয়া, যার জন্য বিটা-২ অ্যাগোনিস্ট ব্যবহার করা হয়; এগুলো তাৎক্ষণিকভাবে অ্যালভিওলিকে প্রসারিত করে এবং তীব্র শ্বাসকষ্ট থেকে মুক্তি দেয়। দ্বিতীয় ধাপ হলো সমস্যার দীর্ঘমেয়াদী ব্যবস্থাপনা এবং আক্রমণের হার পরিবর্তন করা, যার জন্য সাধারণত দীর্ঘমেয়াদী অ্যারোসল স্টেরয়েড দেওয়া হয় যা আপনাকে ডাক্তাররা প্রেসক্রাইব করেছেন। অ্যারোসল সরাসরি ফুসফুসে পৌঁছায়, তাই পার্শ্বপ্রতিক্রিয়া খুব মৃদু বা প্রায় নগণ্য। যদি আপনি আরাম বোধ করেন, তবে ডাক্তারের নির্দেশিত ডোজ অনুযায়ী ইনহেলার নেওয়া চালিয়ে যান। আপনি এর সাথে ট্যাবলেট মন্টেজ এলসি (লেভোসেটিরিজিন এবং মন্টিলুকাস্ট) যোগ করতে পারেন, যা একটি মাস্ট সেল ইনহিবিটর; এটি আপনার উপসর্গ নিয়ন্ত্রণে সাহায্য করবে।
====================================================================================================
ID     : 21673
INPUT  : বয়স
OUTPUT : হেলো। এটা ভালো যে রক্ত পরীক্ষা, সিটি স্ক্যান এবং প্রস্রাব পরীক্ষা সব স্বাভাবিক এসেছে। তবে আপনার মূল সমস্যা হলো পেটের উপরের অংশে ব্যথা, প্রচণ্ড তৃষ্ণা এবং বুক জ্বালাপোড়া। আমি আপনাকে নিম্নলিখিত পরামর্শ দেবো
====================================================================================================
ID     : 76760
INPUT  : ওজন
OUTPUT : হেলো, আপনার পূর্বের ইতিহাস অনুযায়ী, আপনি আপনার সমস্যার জন্য একজন সেক্স থেরাপিস্টের পরামর্শ নিতে পারেন। তিনি আপনাকে এটি নিয়ন্ত্রণ করার উপায় সম্পর্কে পরামর্শ দেবেন। ততক্ষণ পর্যন্ত, আপনি নিজেকে কোনো না কোনো কাজে ব্যস্ত রাখতে পারেন, পরিবার ও বন্ধুদের সাথে সময় কাটাতে পারেন, একা থাকার সময় কমিয়ে আনতে পারেন, পর্যাপ্ত ঘুম ও স্বাস্থ্যকর খাবার গ্রহণ করতে পারেন, নিয়মিত ব্যায়াম করতে পারেন এবং মেডিটেশন করতে পারেন। ভালো থাকুন, এইচওয়াই নাসেনিয়া ডক। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি। আমি আপনাকে আরও কোনোভাবে সাহায্য করতে পারি কিনা তা আমাকে জানান।
====================================================================================================
ID     : 76361
INPUT  : নাম
OUTPUT : হেলো, যদি আপনার হাঁপানি ধরা পড়ে থাকে এবং বারবার শ্বাসকষ্টের সমস্যা হয়, তবে প্রয়োজনে ব্যবহারের পরিবর্তে নিয়মিত প্রতিদিন রক্ষণাবেক্ষণ ইনহেলার ব্যবহার করা প্রয়োজন। এছাড়া, কোনো অবস্থাতেই নিজে থেকে নিওচ্যাট ট্যাবলেট সেবন করবেন না। একজন পালমোনোলজিস্টের পরামর্শ নেওয়া এবং সম্পূর্ণ শারীরিক মূল্যায়ন ও পালমোনারি ফাংশন টেস্ট করানো বাঞ্ছনীয়, যাতে ইনহেলার এবং ওরাল ওষুধের মাধ্যমে আপনার চিকিৎসা পদ্ধতিটি সঠিকভাবে নির্ধারণ করা যায়। মূল্যায়নের ভিত্তিতে আপনার চিকিৎসা পদ্ধতি একবার ঠিক হয়ে গেলে আপনাকে আর এই ঘন ঘন হাঁপানির সমস্যার সম্মুখীন হতে হবে না। শুভেচ্ছা।
====================================================================================================
ID     : 103847
INPUT  : বয়স
OUTPUT : হেলো, আমাদের কাছে লেখার জন্য ধন্যবাদ। মেরুদণ্ডের ছোট হাড়গুলোর মাঝে ছোট স্পঞ্জের মতো ডিস্ক থাকে। মেরুদণ্ডের বিভিন্ন নড়াচড়া সহজ করতে এবং কুশনের মতো কাজ করার জন্য এই ডিস্কগুলো স্বাভাবিকভাবে সারিবদ্ধ থাকা উচিত। আপনার পিঠের এল ৩-এল ৪, এল ৪-এল ৫ এবং এল ৫-এস ১ স্তরের ডিস্কগুলো পিছনের দিকে ফুলে গেছে, যা আঘাত বা প্রাথমিক ক্ষয়জনিত কারণে হতে পারে। আপনি ফিজিওথেরাপি করার চেষ্টা করতে পারেন এবং ভারী ওজন তোলা এড়িয়ে চলতে পারেন। এই সমস্যাটি পুরোপুরি সেরে যাবে না, তবে আপনি যদি সতর্কতা অবলম্বন করেন, তবে সমস্যার অগ্রগতি ধীর হবে এবং আপনি খুব বেশি সমস্যা ছাড়াই আপনার দৈনন্দিন কাজকর্ম চালিয়ে যেতে পারবেন।
====================================================================================================
ID     : 49401
INPUT  : নাম
OUTPUT : প্রিয় জনাব বিক্রম চেরি, নাসেনিয়া ডকে আপনাকে স্বাগতম। আপনার বাম ফুসফুসে অবস্থিত যে ভরের জন্য আপনি ৬ সাইকেল কেমোথেরাপি নিয়েছেন, অনুগ্রহ করে তার হিস্টোপ্যাথলজিক্যাল/বায়োপসি রিপোর্ট সম্পর্কে জানান। আপনার বায়োপসি রিপোর্ট দেখার পর আমরা এই প্ল্যাটফর্মে আপনাকে আরও ভালোভাবে পরামর্শ দিতে পারব। সম্ভব হলে আপনার ল্যাবরেটরি এবং রেডিওলজিক্যাল রিপোর্টগুলো (সিটি স্ক্যান, পিইটি স্ক্যান) "pgi2010@live.in" এই ইমেইলে পাঠান। আপনার সম্পূর্ণ কেস রিপোর্ট ভালোভাবে দেখার পর আমরা আপনাকে আরও ভালোভাবে সাহায্য করতে পারব। দ্রুত সুস্থ হয়ে উঠুন।
====================================================================================================
ID     : 79580
INPUT  : বয়স
OUTPUT : হেলো, নাসেনিয়া ডকে আপনাকে স্বাগতম। আপনি যে স্থানে ব্যথার কথা বলছেন তা গলস্টোন বা মৃদু কোলেসিস্টাইটিস জাতীয় সমস্যার ইঙ্গিত দেয়। এর জন্য ইউএসজি (USG) পরীক্ষা করুন। ইউএসজি পরীক্ষার মাধ্যমে গ্যাস্ট্রাইটিস বা অন্য কোনো প্রদাহজনিত সমস্যা আছে কি না তাও নিশ্চিত হওয়া যাবে, যা বুকের জ্বালাপোড়ার কারণ হতে পারে। দুই সপ্তাহ খালি পেটে খাবারের আগে ওমেপ্রাজল ক্যাপসুল সেবন করুন। অতিরিক্ত চর্বিযুক্ত খাবার এড়িয়ে চলুন। অতিরিক্ত মশলাযুক্ত খাবার এড়িয়ে চলুন। শারীরিক পরীক্ষার ওপর ভিত্তি করে পরবর্তী পরীক্ষা এবং কারণ অনুযায়ী চিকিৎসা করা হবে। যদি কোনো কারণ খুঁজে পাওয়া না যায়, তবে আপনার সন্দেহ অনুযায়ী ব্যথাটি পেশীর টান থেকেও হতে পারে। ভালো থাকবেন।
====================================================================================================
ID     : 86770
INPUT  : বয়স
OUTPUT : হেলো এবং নাসেনিয়া ডকে আপনাকে স্বাগতম। প্রজনন সংক্রান্ত সমস্যা পুরুষ বা নারী উভয়ের ক্ষেত্রেই হতে পারে। এক বছর অনিরাপদ যৌন মিলনের পরেও গর্ভধারণে ব্যর্থতাকে বন্ধ্যাত্ব হিসেবে সংজ্ঞায়িত করা হয় এবং প্রজননক্ষম বয়সের ১০ থেকে ১৫ শতাংশ দম্পতির ক্ষেত্রে এটি ঘটে থাকে। নারীদের সমস্যার ক্ষেত্রে, যদি কোনো নারীর পিরিয়ড নিয়মিত হয় এবং কোনো পরিচিত স্ত্রীরোগ সংক্রান্ত সমস্যা না থাকে, তবে গর্ভধারণে কোনো সমস্যা হওয়ার কথা নয়।
====================================================================================================
ID     : 54858
INPUT  : নাম
OUTPUT : হেলো প্রিয়, আমি আপনার উদ্বেগ বুঝতে পারছি। আমার মতে লিউকোসাইটের বৃদ্ধিকে অস্বাভাবিক হিসেবে গণ্য নাও করা যেতে পারে। কারণ গর্ভাবস্থায় লিউকোসাইটের সংখ্যা ১৫০০০ পর্যন্ত বৃদ্ধি পেতে পারে। তাই বর্ধিত সংখ্যা নিয়ে আপনার চিন্তার কিছু নেই। নিশ্চিন্ত থাকুন। কলার বোন থেকে পেট পর্যন্ত ব্যথা পেশীর ব্যথার কারণে হতে পারে। গর্ভাবস্থায় বিভিন্ন ধরনের অনির্দিষ্ট ব্যথা দেখা দেয় যা নিজে থেকেই কমে যায়। চিন্তা করবেন না। ব্যথা তীব্র হলে প্যারাডক্স (Paradox) সেবন করুন। ত্বকের জ্বালাপোড়া অ্যান্টিবায়োটিকের প্রতি সংবেদনশীলতার কারণে হতে পারে। ডিহাইড্রেশন রোধ করতে প্রতিদিন পর্যাপ্ত পরিমাণে ৩ লিটার পর্যন্ত তরল পান করুন। আশা করি এটি সাহায্য করবে। শুভেচ্ছা রইল।
====================================================================================================
ID     : 97654
INPUT  : বয়স
OUTPUT : হেলো, অনুসন্ধানের জন্য ধন্যবাদ। আপনি কি ক্লিনিক্যাল ডিপ্রেশনে ভুগছেন বলে নির্ণীত হয়েছেন? যদি হ্যাঁ হয়, তবে আপনি এখন পর্যন্ত কী কী ওষুধ গ্রহণ করেছেন এবং ওষুধে আপনার প্রতিক্রিয়া কেমন ছিল? আপনার বর্তমান উপসর্গের প্রোফাইলের ওপর ভিত্তি করে এবং আপনাকে সুস্থ বিবেচনা করে, ডুলোক্সেটিন (Duloxetine), মিলনাছিপ্রান (Milnacipran)-এর মতো স্যারি (SARI) গ্রুপের অ্যান্টিডিপ্রেসেন্টগুলো আপনাকে দ্রুত উপশমে সাহায্য করতে পারে; বিকল্প হিসেবে একজন চ্যাট ডাক্তারের পরামর্শ নিতে পারেন। রক্তাল্পতার জন্য, আমাদের রক্তাল্পতার কারণ খুঁজে বের করতে হবে, যেমন অতিরিক্ত ঋতুস্রাব, অপর্যাপ্ত খাদ্য, সংক্রমণের কারণে ইত্যাদি এবং প্রথমে সেই কারণটির চিকিৎসা করতে হবে। এর পরে আয়রন ডায়েটারি সাপ্লিমেন্ট গ্রহণ, খাদ্যাভ্যাসের উন্নতি (পালং শাক, পেঁপে, আম, সবুজ শাকসবজি ইত্যাদি খাওয়া), রক্ত সঞ্চালন (আপনার হিমোগ্লোবিনের মাত্রা ও ক্লিনিক্যাল প্রোফাইলের ওপর নির্ভর করে যদি প্রয়োজন হয়) ইত্যাদি করতে হবে। আরও সাহায্যের জন্য যোগাযোগ করুন। শুভকামনা।
====================================================================================================
ID     : 93600
INPUT  : নাম
OUTPUT : হেলো ট্রাজান সান্তা, অনেক নাসেনিয়া ডক আছেন। আপনার ইতিহাস থেকে আমি কেবল পরামর্শ দিতে পারি যে আপনার হাঁপানি নিয়ন্ত্রণে রাখার জন্য প্রতিদিন ইনহেলড কর্টিকোস্টেরয়েড গ্রহণ করা উচিত। আপনি যেমন উল্লেখ করেছেন, যদি আপনি ইতিমধ্যে এটি প্রতিদিন গ্রহণ করে থাকেন, তবে আপনার চিকিৎসকের সাথে পরামর্শ করার পর ডোজ বাড়াতে হবে। আমি আপনাকে একজন অ্যালার্জি বিশেষজ্ঞের সাথে পরামর্শ করার পরামর্শ দেব, যিনি অ্যালার্জি পরীক্ষা করতে পারেন এবং অ্যালার্জেন ইমিউনোথেরাপির পরামর্শ দিতে পারেন, যা দীর্ঘমেয়াদে আপনাকে সাহায্য করবে। আরও একটি বিষয়, অনুগ্রহ করে যোগব্যায়াম এবং প্রাণায়ামকে আপনার দৈনন্দিন রুটিন করে তুলুন। এটি আপনার হাঁপানি নিয়ন্ত্রণে আরও সাহায্য করবে এবং আপনার কর্টিকোস্টেরয়েডের দৈনিক প্রয়োজনীয়তা কমিয়ে দেবে। আশা করি আমার উত্তরটি আপনার কাজে এসেছে। আপনার সুস্বাস্থ্য কামনা করি। শুভেচ্ছা।
====================================================================================================
ID     : 21978
INPUT  : বয়স
OUTPUT : হেলো, নাসেনিয়া ডকে আপনাকে স্বাগতম। আমি নাসেনিয়া ডক। আজ আমি আপনার উদ্বেগের উত্তর দেব। আপনার পিরিয়ড অনিয়মিত কারণ আপনার ওভুলেশন বা ডিম্বস্ফোটন হচ্ছে না। পিসিওএস (PCOS) থাকা সত্ত্বেও গর্ভবতী হওয়া সম্ভব। আপনার বয়স এখনও অনেক কম। চিন্তা করবেন না। ডায়ান (Diane) গর্ভনিরোধক পিলের মতো কাজ করে। তাই আপনি যদি গর্ভধারণ করতে চান, তবে প্রথমে ডায়ান খাওয়া বন্ধ করুন। প্রথমে আপনাকে এবং আপনার স্বামীকে একজন ইনফার্টিলিটি বিশেষজ্ঞের পরামর্শ নিতে হবে। অন্য কোনো সমস্যা আছে কিনা তা জানার জন্য আপনাকে কিছু হরমোন পরীক্ষা, ফ্যালোপিয়ান টিউব প্যাটেন্সি টেস্ট এবং আপনার স্বামীর সিমেন অ্যানালাইসিস বা বীর্য পরীক্ষা করতে হবে। যদি ওভুলেশনই একমাত্র সমস্যা হয়, তবে ওভুলেশন ঘটানোর জন্য ওষুধ রয়েছে। আপনার ডাক্তার এ বিষয়ে আপনাকে নির্দেশনা দেবেন। গর্ভধারণের সম্ভাবনা বাড়াতে স্বাভাবিক বিএমআই (BMI) বজায় রাখুন, ধূমপান ত্যাগ করুন (যদি আপনি ধূমপায়ী হন) এবং সপ্তাহে অন্তত তিনবার মিলন করুন। আশা করি এটি সহায়ক হবে। আপনার আরও কোনো উদ্বেগ থাকলে আমাকে লিখুন। আমি উত্তর দিতে পারলে খুশি হব।
====================================================================================================
ID     : 98352
INPUT  : বয়স
OUTPUT : হেলো, নাসেনিয়া ডকে পোস্ট করার জন্য ধন্যবাদ। আমি দেখছি যে আপনি একাধিক সিটি স্ক্যান এবং রক্ত পরীক্ষা করিয়েছেন। কিন্তু আপনার কলার বোনের উপরে বা বুকের লিম্ফ নোড সম্পর্কে আপনি কিছুই উল্লেখ করেননি। আপনাকে কি কখনও লিম্ফ নোড বায়োপসি করার পরামর্শ দেওয়া হয়নি? আমি ইউএসজি গাইডের মাধ্যমে কলার বোনের লিম্ফ নোড থেকে বায়োপসি বা অ্যাসপিরেশন করার পরামর্শ দিচ্ছি। সংগৃহীত নমুনাটি পরবর্তী পরীক্ষার জন্য পাঠানো যেতে পারে। আপনার শ্বাসকষ্ট, ওজন কমে যাওয়া এবং লিম্ফ নোড ফুলে যাওয়ার মতো লক্ষণগুলোর পরিপ্রেক্ষিতে যক্ষ্মা (টিউবারকিউলোসিস) রোগটি আছে কি না তা নিশ্চিত হওয়া প্রয়োজন। অনুগ্রহ করে লিম্ফ নোড থেকে বায়োপসি করান। আপনার সুস্বাস্থ্য কামনা করছি। শুভেচ্ছা।
====================================================================================================
ID     : 88405
INPUT  : নাম
OUTPUT : আপনার অনুসন্ধানের জন্য ধন্যবাদ। অল্প বয়সে হরমোন এবং কামনার কারণে নাইট ফল (বীর্যপাত) হওয়া বেশ সাধারণ একটি বিষয়। আপনি মাঝে মাঝে হস্তমৈথুন করতে পারেন। হস্তমৈথুন যৌন আকাঙ্ক্ষা হ্রাস করে। স্বাস্থ্যসম্মত উপায়ে করলে এটি এসটিডি (STDs) বা এইচআইভি (HIV) ছড়ায় না। সন্তান ধারণে কোনো সমস্যা হবে না। স্বাস্থ্যবিধি মেনে চলুন। দুর্বলতার জন্য আপনি মাল্টিভিটামিন ট্যাবলেট খেতে পারেন। কোনো প্রশ্ন থাকলে সরাসরি আমার সাথে যোগাযোগ করুন।
====================================================================================================
ID     : 32752
INPUT  : রেফ
OUTPUT : হেলো, অনুগ্রহ করে বিস্তারিত ইতিহাস জানান। তার কি কাশি আছে? বমি হচ্ছে? পাতলা পায়খানা হচ্ছে? প্রস্রাবের পরিমাণ কি বেড়েছে বা কমেছে? প্রস্রাবে জ্বালাপোড়া আছে? জয়েন্টে ফোলাভাব আছে? কোনো র‍্যাশ বা ফুসকুড়ি আছে? কান দিয়ে কি কোনো তরল বের হচ্ছে? ৪৮ ঘণ্টা পর্যন্ত প্যারাসিটামল সিরাপ চালিয়ে যান কারণ এটি সম্ভবত ভাইরাল জ্বর, এবং যদি অবস্থার উন্নতি না হয়, তবে উপরের প্রশ্নগুলোর উত্তরসহ আমার কাছে আবার আসবেন। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি। আমি আপনাকে আর কোনোভাবে সাহায্য করতে পারি কিনা জানাবেন।
====================================================================================================
ID     : 109600
INPUT  : নাম
OUTPUT : হেলো, নাসেনিয়া ডকে জিজ্ঞাসা করার জন্য আপনাকে ধন্যবাদ। আমি আপনার ইতিহাস দেখেছি এবং আপনার জন্য নিম্নলিখিত পরামর্শগুলো দিতে চাই।
====================================================================================================
ID     : 55933
INPUT  : নাম
OUTPUT : হেলো, আপনি ৪৩.৫ মাসের কথা উল্লেখ করেছেন - যা প্রায় ৪ বছর। মনে হচ্ছে আপনার বাচ্চার ভাইরাল ডায়রিয়া হয়েছে। একবার শুরু হলে এটি পুরোপুরি সেরে উঠতে ৫-৭ দিন সময় লাগবে। যদি না বাচ্চার প্রস্রাব কমে যায়, খুব নিস্তেজ বা অতিরিক্ত ঘুম পায়, অথবা মলের সাথে রক্ত বা সবুজ পিত্তযুক্ত বমি হয়, তবে আপনার চিন্তার কিছু নেই। মলের সাথে রক্ত না থাকলে অ্যান্টিবায়োটিক ব্যবহারের প্রয়োজন নেই। অপ্রয়োজনে অ্যান্টিবায়োটিক ব্যবহার করলে তা অ্যান্টিবায়োটিক-জনিত ডায়রিয়া ঘটিয়ে পরিস্থিতি আরও খারাপ করতে পারে। আমি আপনাকে জিঙ্ক সাপ্লিমেন্ট ব্যবহার করার পরামর্শ দিচ্ছি।
====================================================================================================
ID     : 30182
INPUT  : বয়স

In [24]:
short_inputs = test[
    test["input"].str.len() <= 40
].sort_values("input")

for _, row in short_inputs.iterrows():
    print("=" * 100)
    print(f"ID     : {row['id']}")
    print(f"INPUT  : {row['input']}")
    # print(f"OUTPUT : {row['output']}")

====================================================================================================
ID     : 21902
INPUT  : আইভিএফ (IVF)-এর বিস্তারিত জানতে চাই।
====================================================================================================
ID     : 74832
INPUT  : আমার এই কেস স্টাডিটি বোঝা প্রয়োজন।
====================================================================================================
ID     : 73865
INPUT  : আমার এমআরআই-এর উপসংহার
====================================================================================================
ID     : 54011
INPUT  : আমার বোনের টাইফয়েড এইচ ১ হয়েছে।

In [25]:
test["input_len"]=test["input"].str.strip().str.len()

short_df = test[
test["input_len"] <= 60
].copy()
print("Short input rows:", len(short_df))
print(
    short_df[
        ["id", "input", "input_len"]
    ].sort_values("input_len").to_string(index=False)
)

Short input rows: 6
   id                                        input  input_len
73865                       আমার এমআরআই-এর উপসংহার         22
54011             আমার বোনের টাইফয়েড এইচ ১ হয়েছে।         32
74832           আমার এই কেস স্টাডিটি বোঝা প্রয়োজন।         34
21902         আইভিএফ (IVF)-এর বিস্তারিত জানতে চাই।         36
95084    হেলো, আমার সত্যিই তোমার সাহায্য প্রয়োজন!!         41
32945 আমি অজানা অ্যালার্জিতে ভুগছি (উপসর্গগুলো হলো         44

In [26]:
train["input_len"]=train["input"].str.strip().str.len()

short_df = train[
train["input_len"] <= 60
].copy()
print("Short input rows:", len(short_df))
print(
    short_df[
        ["id", "input", "input_len"]
    ].sort_values("input_len").to_string(index=False)
)

Short input rows: 989
    id                                                        input  input_len
 66179                                                            ।          1
101250                                                           ডক          2
 82458                                                           এফ          2
111958                                                          বয়স          3
 93719                                                          বয়স          3
100625                                                          নাম          3
109600                                                          নাম          3
 98352                                                          বয়স          3
 79478                                                          বয়স          3
 16284                                                          বয়স          3
 22765                                                          বয়স          3
 95238                                                          বয়স          3
 21673                                                          বয়স          3
 76760                                                          ওজন          3
103847                                                          বয়স          3
 52728                                                          নাম          3
  6516                                                          বয়স          3
 93600                                                          নাম          3
 21978                                                          বয়স          3
111517                                                          বয়স          3
 22099                                                          নাম          3
 71502                                                          বয়স          3
 30182                                                          বয়স          3
 21163                                                          নাম          3
 32752                                                          রেফ          3
 97654                                                          বয়স          3
  8242                                                          বয়স          3
 98302                                                          নাম          3
 58993                                                          বয়স          3
  4702                                                          নাম          3
 47872                                                          বয়স          3
 76361                                                          নাম          3
 55933                                                          নাম          3
 79580                                                          বয়স          3
 88369                                                          বয়স          3
 88405                                                          নাম          3
 73455                                                          বয়স          3
 80687                                                          বয়স          3
 86770                                                          বয়স          3
 39619                                                          বয়স          3
 54858                                                          নাম          3
 62419                                                          বয়স          3
 49401                                                          নাম          3
  7667                                                          বয়স          3
 10812                                                          বয়স          3
 32350                                                          নাম          3
 51744                                                          বয়স          3
 47202                                                          নাম          3
107597                                                          নাম          3
 98197                                                          বয়স          3
 70148                                                          বয়স          3
 85305                                                          বয়স          3
 87413                                                          বয়স          3
  9141                                                          বয়স          3
 77520                                                          বয়স          3
 15227                                                          বয়স          3
 31627                                                          বয়স          3
 41320                                                         হেলো          4
 47076                                                         হেলো          4
 55250                                                         হেলো          4
 43245                                                         হেলো          4
 58732                                                         হেলো          4
101124                                                         হেলো          4
  7969                                                         হেলো          4
 94574                                                         হেলো          4
 66600                                                         হেলো          4
100392                                                         হেলো          4
100271                                                         হেলো          4
100330                                                         হেলো          4
 20678                                                         হেলো          4
 68539                                                         হেলো          4
 88160                                                         হেলো          4
 98810                                                         রোগী          4
111887                                                         হেলো          4
   672                                                         হেলো          4
 42301                                                         হেলো          4
 42132                                                         হেলো          4
 38130                                                         হেলো          4
 51219                                                         হেলো          4
 61904                                                         হেলো          4
 60178                                                         হেলো          4
 94005                                                         সিসি          4
 89633                                                         হেলো          4
 89982                                                         হেলো          4
 37245                                                         রোগী          4
 54576                                                         হেলো          4
 15285                                                         হেলো          4
 13372                                                         হেলো          4
 25018                                                         হেলো          4
 23116                                                         হেলো          4
  7422                                                         হেলো          4
 65598                                                         হেলো          4
 24813                                                         থেকে          4
 18044                                                         হেলো          4
 14590                                                         হেলো          4
 28073                                                         হেলো          4
 27605                                                         হেলো          4
 92398                                                         থেকে          4
108186                                                         হেলো          4
 63300                                                         হেলো          4
 25725                                                         হেলো          4
111230                                                         হেলো          4
 99279                                                         হেলো          4
 91795                                                         হেলো          4
 52109                                                         হেলো          4
 57089                                                         হেলো          4
 43321                                                         হেলো          4
 89320                                                         সাবা          4
 82389                                                         হেলো          4
 36020                                                         হেলো          4
 26532                                                         হেলো          4
 84204                                                         হেলো          4
 28473                                                         হেলো          4
 65967                                                         হেলো          4
 35910                                                         হেলো          4
 91823                                                         হেলো          4
 89473                                                         হেলো          4
 81485                                                         হেলো          4
 99173                                                         হেলো          4
 89624                                                         হেলো          4
 73693                                                         হেলো          4
 79311                                                         হেলো          4
 81245                                                         হেলো          4
 58785                                                         হেলো          4
 71854                                                         হেলো          4
  6522                                                         হেলো          4
104209                                                         হেলো          4
 56721                                                         হেলো          4
 31084                                                         হেলো          4
 87157                                                         হেলো          4
 35908                                                         হেলো          4
108936                                                         হেলো          4
 12005                                                         হেলো          4
  2812                                                         হেলো          4
 34934                                                         হেলো          4
 42250                                                         হেলো          4
 40512                                                         হেলো          4
100739                                                        ফলাফল          5
 22811                                                        ধারণা          5
 81395                                                        লিঙ্গ          5
 87810                                                        ফলাফল          5
 93068                                                        ধারণা          5
 15796                                                        ধারণা          5
105939                                                        হেলো!          5
 89882                                                        হেলো!          5
104906                                                        হ্যাঁ          5
  7771                                                        প্রিয়          5
 92605                                                        স্যার          5
 90245                                                        এল২-৩          5
 90615                                                        ইমেইল          5
  8016                                                        ১ টায়          5
 67568                                                        যৌনতা          5
 65240                                                        ভলিউম          5
 13091                                                        ফলাফল          5
 56210                                                        ক্ষয়          5
111117                                                        হেলো।          5
 49566                                                        যৌনতা          5
 61789                                                        মহিলা          5
  5831                                                        ধারণা          5
 47212                                                        জরুরি          5
 93458                                                        ফলাফল          5
  7629                                                       ভৌত রঙ          6
 27256                                                       প্রশ্ন          6
 95662                                                       উপসর্গ          6
103603                                                       প্রশ্ন          6
 60217                                                       সমস্যা          6
 59517                                                       জরায়ু          6
 87054                                                       প্রশ্ন          6
111344                                                       কুঁচকি          6
 85837                                                       প্রশ্ন          6
 25989                                                       পুনরায়          6
 15398                                                       প্রশ্ন          6
 79666                                                       ইতিহাস          6
 62145                                                       হেলো (          6
  3590                                                       ইতিহাস          6
 60637                                                       প্রশ্ন          6
 37668                                                       পটভূমি          6
109113                                                       পটভূমি          6
 12742                                                       উচ্চতা          6
 30717                                                       উপসর্গ          6
 24797                                                       প্রশ্ন          6
 60237                                                       পটভূমি          6
 54967                                                       প্রশ্ন          6
 87474                                                       ডিএক্স          6
 90226                                                       উচ্চতা          6
 98242                                                       ইতিহাস          6
 61362                                                       প্রশ্ন          6
 44797                                                       ইতিহাস          6
109801                                                       প্রশ্ন          6
  9698                                                       পটভূমি          6
 73498                                                       সমস্যা          6
 66687                                                       পটভূমি          6
103095                                                      মূল কথা          7
 68394                                                      ডঃ আমির          7
 41708                                                      শুভ দিন          7
  7429                                                      প্রায় ৩          7
 63841                                                      উপসংহার          7
 73324                                                      অনুলিপি          7
  7491                                                      হেলো ডক          7
109613                                                      হেলো ডক          7
 97899                                                      পরীক্ষা          7
 85816                                                     আমার বয়স          8
 98447                                                     এসডিএফসি          8
 77042                                                     আমার বয়স          8
 66174                                                     থিয়েটার          8
 42350                                                     শুভ সকাল          8
  2295                                                     শুভ সকাল          8
 47583                                                     ব্যাখ্যা          8
 74702                                                     শেষ মিলন          8
 11774                                                     বয়স-৭৪.৩          8
 46952                                                     কিছুই না          8
 42942                                                     হেলো বয়স          8
 73969                                                     এসজিপিটি          8
 76669                                                     প্রশ্ন ১          8
 46161                                                     হেলো ডকস          8
 81688                                                     শুভ সকাল          8
 13878                                                     আমার আছে          8
 81684                                                    রোগীর বয়স          9
 92619                                                    বাম কিডনি          9
 46889                                                    বাম কিডনি          9
 60781                                                    হেলো, কিউ          9
 32175                                                    হেলো, বয়স          9
  5424                                                    প্রথম নাম          9
  6500                                                    রোগীর নাম          9
 81270                                                    রোগীর নাম          9
 26073                                                    সেক্সোলজি          9
 54112                                                    এইচটিটিপি          9
 75122                                                    পরিস্থিতি          9
 45902                                                    রোগীর বয়স          9
 42272                                                    অনুসন্ধান          9
 38188                                                    মহিলা বয়স          9
 55043                                                    হেলো, নাম          9
 35191                                                    [URL=http          9
 13962                                                   নিচের দাঁত         10
 57108                                                   সাবিথা ফজল         10
 52595                                                   উপসর্গসমূহ         10
 16995                                                   আমার বন্ধু         10
 11355                                                   হেলো স্যার         10
 72461                                                   উপসর্গসমূহ         10
 45982                                                   অ্যালার্জি         10
 68964                                                   আমার ভাইজি         10
 89479                                                   গতকাল ৫টায়         10
 37763                                                   অনলাইন হোন         10
 94379                                                   উপসর্গসমূহ         10
 80103                                                   নান্দনিকতা         10
 31700                                                   হেলো বিবরণ         10
110897                                                   ঘটনার ক্রম         10
 30281                                                  সতর্কবার্তা         11
 66917                                                  দুটি প্রশ্ন         11
 13677                                                  রোগ নির্ণয়         11
 66224                                                  গতকাল ১০টায়         11

In [27]:
irrelavant_ids=[
    "10326","109483","30821" ,"55381","55871","47770","103459","14397","56474","69721","89953","69624","104899","31229"

    "37239",
]

In [28]:
print(train.loc[train["id"] == 55277, "input"].iloc[0])

হেলো স্যার, আমি বিনোদ এন (বয়স

In [29]:
# Make sure original order is preserved
for target_id in [66178,66179, 101250, 82458, 7667, 93719, 100625]:
    idx = train.index[train["id"] == target_id]

    if len(idx):
        i = idx[0]

        print("\n" + "=" * 100)
        print("TARGET ID:", target_id)

        display(
            train.loc[
                max(0, i-3):min(len(train)-1, i+3),
                ["id", "input", "output"]
            ]
        )

====================================================================================================
TARGET ID: 66178

,id,input,output
81985,55263,আমি আমার পিরিয়ডের পরের রবিবার থেকে ইয়াসমিন খাও...,"হেলো, কার্যকারিতা নির্ভর করে আপনার মাসিক চক্রে..."
81986,23527,"হেলো, আমার ২ মাস আগে ডেঙ্গু জ্বর হয়েছিল... এবং...",হেলো। জ্বর বা দীর্ঘস্থায়ী অসুস্থতার পরে চুল প...
81987,78306,"হেলো, আমার গত ৫ মাস ধরে বুকে ব্যথা হচ্ছে। আমি ...",নাসেনিয়া ডকে আপনার প্রশ্নের জন্য ধন্যবাদ। আমা...
81988,66178,"শুভ সকাল ডাক্তারবাবু, আমি তনুশ্রী দাস, বয়স ৩০-...","হেলো, অনুসন্ধানের জন্য ধন্যবাদ। আপনার ইতিহাস থ..."
81989,15794,আমার হাইপোথাইরয়েডিজম আছে। ইদানীং আমার বুকে ব্...,নাসেনিয়া ডকে আপনার প্রশ্নের জন্য ধন্যবাদ। আমি...
81990,12755,আমার ৫ বছর বয়সী মেয়ে সবসময় ক্ষুধার কথা বলে। রে...,"প্রিয়, চ্যাটডক্টরে আপনাকে স্বাগতম। আমরা আপনার ..."
81991,79758,"হেলো, আমার মাড়ি মাঝে মাঝে কোনো স্পর্শ ছাড়াই রক...",হেলো এবং নাসেনিয়া ডক ফোরামে আপনাকে স্বাগতম। আ...

====================================================================================================
TARGET ID: 66179

,id,input,output
22244,62135,আমার প্রায় ১০ মাস ধরে কাঁধে ব্যথা হচ্ছে যা আমা...,১. প্রাথমিকভাবে একজন অর্থোপেডিক সার্জনের পরামর...
22245,97068,প্রায় ৩ সপ্তাহ আগে আমি পড়ে গিয়ে ফুটপাতে আমার ক...,"হেলো, আমি আপনার কেসটি পর্যালোচনা করেছি এবং আমা..."
22246,54857,"হেলো, আমি ২৫ বছর বয়সী একজন নারী এবং আমার ডাক্ত...","হেলো, ডাইকোরেট-৭৫০ (Dicorate-750) সেবনের উদ্দে..."
22247,66179,।,হেলো এবং নাসেনিয়া ডকে আপনাকে স্বাগতম। আপনার অ...
22248,84260,আমার ১৫ মাস বয়সী ছেলের ডান চোখের পাতায় র‍্যাশে...,হেলো... নাসেনিয়া ডকে পরামর্শের জন্য আপনাকে ধন...
22249,36613,আমার স্বামী গত পরশু রাতে ফুটবল খেলার সময় অন্য ...,"হেলো, আমার মতে সে প্রথম ৪৮ ঘণ্টা সেখানে বরফ সে..."
22250,25591,"আমার কবজিতে একটি কাটা দাগ আছে, যা দুই দিন আগে ...","হেলো, নাসেনিয়া ডকের সাথে যোগাযোগ করার জন্য আপ..."

====================================================================================================
TARGET ID: 101250

,id,input,output
15475,71111,আমার বয়স ৩৯ বছর। আমার ২ সপ্তাহ ধরে প্রচণ্ড কাশ...,নাসেনিয়া ডকে আপনার প্রশ্নের জন্য ধন্যবাদ। আমি...
15476,94931,"প্রিয় ডাক্তার, অনুগ্রহ করে আমার সিমেন অ্যানালা...",হেলো এবং এই অনুসন্ধানের জন্য আপনাকে অনেক ধন্যব...
15477,76546,হেলো... আমার বয়স ২৯ বছর এবং আমার বিয়ের বয়স ২.৫...,"হেলো প্রিয়, নাসেনিয়া ডকে আপনার অনুসন্ধানের জন..."
15478,101250,ডক,"হেলো, ডেইরি, আমি আপনার প্রশ্নটি দেখেছি। আমি আপ..."
15479,52321,আমি সিঙ্কে থুতু ফেললাম এবং আমার লালার সাথে কাল...,"হেলো, আমি আপনার প্রশ্নটি দেখেছি। জিহ্বার উপরিভ..."
15480,20330,"আমার ৫ দিন ধরে বুকে ব্যথা এবং শ্বাসকষ্ট হচ্ছে,...",নাসেনিয়া ডকে আপনার প্রশ্নের জন্য ধন্যবাদ। আমি...
15481,25789,আমার দুটি সন্তান জন্মের আগেই মারা গিয়েছিল... এ...,হেলো। নাসেনিয়া ডকে আপনাকে স্বাগতম। ফেইটন ট্যা...

====================================================================================================
TARGET ID: 82458

,id,input,output
34263,109357,"হেলো, হ্যাঁ, আমি প্রায় এক বছর ধরে পিঠের নিচের...","হেলো, আপনার অনুসন্ধানের জন্য ধন্যবাদ। আমি আপনা..."
34264,70196,"হেলো, আমার বাবার প্রোস্টেট বায়োপসি হয়েছিল এবং ...","হেলো, নাসেনিয়া ডক ব্যবহার করার জন্য ধন্যবাদ। ..."
34265,5499,"হেলো ডাক্তার, আমার ২০ মাস বয়সী ছেলের গত ২ মাস ...",হেলো... নাসেনিয়া ডকে পরামর্শের জন্য আপনাকে ধন...
34266,82458,এফ,হেলো! অনুসন্ধানের জন্য আপনাকে ধন্যবাদ। এইচপিভি...
34267,91122,মাঝে মাঝে আমার শ্বাসকষ্ট হয়। এমনকি শুয়ে থাকলেও...,হেলো। শ্বাসকষ্ট এবং পরিশ্রমজনিত শ্বাসকষ্ট হৃদয...
34268,52198,"আমার স্বামীর পা, পিঠ এবং পেটে খুব ব্যথা হচ্ছে।...",হেলো। আপনার অনুসন্ধানের জন্য এবং একটি বিশদ ইতি...
34269,14683,"স্যার, আমার প্রস্রাবে সংক্রমণ হয়েছে এবং পুঁজ ক...","হেলো বালকৃষ্ণ, আপনার প্রশ্নটি করার জন্য ধন্যবা..."

====================================================================================================
TARGET ID: 7667

,id,input,output
107099,26722,"হেলো, আমার মুখে সব জায়গায় ফুড কালারিং লেগে গিয়...","হেলো, মনে হচ্ছে আপনি যে উপাদানটি ব্যবহার করেছে..."
107100,25462,এক ঘণ্টার মধ্যে শিন বোনের ডান পাশে খুব বড় একটি...,"হেলো! ব্যথাহীন, গায়ের রঙের, টানটান, নরম পায়ের ..."
107101,85934,"হেলো, অনুগ্রহ করে এটি স্বাভাবিক কি না তা পরীক্...","হেলো, আপনার সিমেন অ্যানালাইসিস রিপোর্টের ব্যাখ..."
107102,7667,বয়স,"হেলো, অনুসন্ধানের জন্য ধন্যবাদ। আইইউডি (IUD) ব..."
107103,43906,"হেলো স্যার, আমার বয়স ২৯ বছর। ওজন ৬০ কেজি এবং উ...","প্রিয় ব্যবহারকারী, নাসেনিয়া ডকে লেখার জন্য আপ..."
107104,26209,"হেলো, আমার ননদ বা ভাশুর/দেবর-এর স্ত্রীর সদ্যজা...",চ্যাটডক্টরে আপনাকে স্বাগতম। আমি আপনার প্রশ্নটি...
107105,30089,১৪ বছর বয়সে আমার উভয় হিপ বোন সরে যাওয়ার কার...,"হেলো, আপনার সংক্ষিপ্ত ইতিহাসের জন্য ধন্যবাদ। এ..."

====================================================================================================
TARGET ID: 93719

,id,input,output
63669,24884,বেশ কয়েক বছর ধরে ঘুমানোর সময় আমার পেটের নিচের ...,হেলো। আপনার অনুসন্ধানের জন্য এবং বিস্তারিত ইতি...
63670,107319,আমার পিরিয়ড ৭ দিন দেরি হয়েছে এবং আমি ৩টি প্রেগ...,"হেলো প্রিয়, আমি আপনার প্রশ্নটি দেখেছি এবং আপনা..."
63671,4024,হেলো ডাক্তার। আমার বয়স ৩০ বছর এবং আমার স্ত্রীর...,"প্রিয় বন্ধু, যদি যৌনাঙ্গ স্বাস্থ্যসম্মতভাবে পর..."
63672,93719,বয়স,হেলো! নাসেনিয়া ডকের সাথে আপনার তীব্র স্বাস্থ্...
63673,16848,"হেলো, আমি একজন আফ্রিকান আমেরিকান নারী। আমার মা...","হেলো, আপনার প্রশ্নটি পোস্ট করার জন্য নাসেনিয়া..."
63674,14842,"হেলো স্যার, আমার সমস্যা হলো আমার ডান দিকের দাঁ...",হেলো। নাসেনিয়া ডকে আপনাকে স্বাগতম। আমি আপনার ...
63675,46159,আমার দাঁতের ফোড়া হওয়ার কারণে সম্প্রতি একটি দাঁ...,হেলো... নাসেনিয়া ডকে আপনাকে স্বাগতম। আমি আপনা...

====================================================================================================
TARGET ID: 100625

,id,input,output
63961,94775,আমি গতকাল ৪ মিনিটের জন্য একটি সানবেড ব্যবহার ক...,নাসেনিয়া ডকে আপনার প্রশ্নের জন্য ধন্যবাদ। আপন...
63962,90292,৩ দিন আগে আমার বান্ধবীর সাথে শারীরিক মিলনের পর...,"হেলো, আপনার অনুসন্ধানের জন্য ধন্যবাদ। আপনি যে ..."
63963,92656,"হেলো, ২ রাত আগে প্রতিবেশীর বিড়ালকে খাওয়ানোর সম...","হেলো, নাসেনিয়া ডকে আপনার প্রশ্নটি পোস্ট করার ..."
63964,100625,নাম,"হেলো নিখিল, আপনার অনুসন্ধানের জন্য ধন্যবাদ। অন..."
63965,64289,রাতে ঘুমানোর আগে হস্তমৈথুনের পর আমার ডান অণ্ডক...,"হেলো, যৌনাঙ্গে কোনো প্রদাহ না থাকলে সাধারণত হস..."
63966,61649,"আমার চব্বিশ ঘণ্টা ধরে পেটে প্রচণ্ড ব্যথা ছিল, ...","হেলো, আমি আপনার প্রশ্নটি দেখেছি এবং আপনার উদ্ব..."
63967,15130,পিঠের মাঝখানের নিচের অংশে ব্যথা। মাঝে মাঝে ব্য...,প্রশ্নটির জন্য আপনাকে ধন্যবাদ। যেহেতু আপনি আপন...

In [30]:
train.shape

(108954, 5)

In [31]:
import re

def is_garbage(text):
    text = str(text).strip()

    # Empty
    if not text:
        return True

    # Only punctuation/symbols
    if not re.search(r'[\u0980-\u09FFa-zA-Z0-9]', text):
        return True

    # Random English/Latin characters like ikgbdtk
    if re.fullmatch(r'[a-zA-Z]{5,}', text):
        return True

    # Repeated characters like aaaaaaa / !!!!!!!
    if re.fullmatch(r'(.)\1{4,}', text):
        return True

    return False


garbage_mask = train["input"].apply(is_garbage)

train[garbage_mask][["id", "input"]]

          id         input
22247  66179             ।
98019  68278  bhjkhjkhklhk

In [32]:
import re

def is_garbage(text):
    text = str(text).strip()

    # Empty
    if not text:
        return True

    # Only punctuation/symbols
    if not re.search(r'[\u0980-\u09FFa-zA-Z0-9]', text):
        return True

    # Random English/Latin characters like ikgbdtk
    if re.fullmatch(r'[a-zA-Z]{5,}', text):
        return True

    # Repeated characters like aaaaaaa / !!!!!!!
    if re.fullmatch(r'(.)\1{4,}', text):
        return True

    return False


garbage_mask = test["input"].apply(is_garbage)

test[garbage_mask][["id", "input"]]

Empty DataFrame
Columns: [id, input]
Index: []

irrelavant id

In [33]:
df=train.copy()

In [34]:
# ============================================
# REMOVE IRRELEVANT IDS AND CHECK BEFORE/AFTER
# ============================================

# Your existing irrelevant IDs
irrelevant_ids = [
     74075, 41936, 67479, 46865, 24162, 10367, 58793, 88313, 94005,   # সিসি
    98447,   # এসডিএফসি
    35191,   # [URL=http
    54112,   # এইচটিটিপি
    68278,   # bhjkhjkhklhk
    11619,66179, 68278,
    98365, 92466, 41743, 95663, 106148, 73471, 87911, 14384,
    93916, 14433, 48538, 65294, 37239, 31229, 104899, 69624,
    89953, 69721, 61289, 37439, 56474, 14397, 103459, 87107,
    47770, 55871, 55381, 110270, 30821, 109483, 54039, 10326,

    109038, 22165, 57103, 105740, 20794, 14230, 24287, 11280,
    109315, 73531, 57270, 56900, 102924, 94409, 19699, 28746,
    87630, 67424, 99406, 39215, 63493, 51004, 19251, 45666,
    5858, 24469, 16272, 58659, 6846, 99546, 74680, 86994,
    51307, 71921, 7495, 102902, 2235, 92687, 42153, 72365,

    87500, 11714, 29611, 60633, 58148, 22195, 85619, 109909,
    3362, 88576, 33855, 58652, 36695, 40372, 63743, 104271,
    77078, 84670, 29162, 21957, 58336, 42571, 55846, 68772,
    88197, 48077, 106797, 97535, 48684, 62459, 58654, 49237,
    74590, 4751, 76112, 99917, 72175, 95849, 46623, 73912,
    67088, 54900, 13805, 66324, 15577, 49884, 4359, 87102,
    32319, 95385,

    3454, 17347, 46984, 85231, 90152, 48112, 19302, 52304,
    12039, 85566, 39456, 57612, 101712, 84950, 24251, 29125,
    100362, 10873, 86154, 53030, 85716, 19123, 110001, 8855,
    92342, 55956, 68859, 110057, 37308,

    89633, 65598, 89473, 35910, 99173, 94005, 84204, 100330,
    82389, 43245, 26532, 98810, 88160, 108936, 40512, 41320,
    27605, 42132, 28473, 36020, 57089,

    56210, 90615, 65240, 61789, 22811, 13091, 49566, 89882,
    105939, 93458, 81395, 8016, 104906, 111117, 92605, 7771,
    93068, 67568, 5831, 47212, 100739, 15796, 87810,

    9698, 90226, 12742, 109801, 3590, 25989, 87474, 62145,
    61362, 79666, 44797, 60637, 27256, 15398, 103603, 98242,
    85837, 60237, 87054, 24797, 54967, 60217, 109113, 37668,
    66687, 73498,

    68394, 41708, 7491, 63841, 103095, 97899, 109613, 73324,
    7429,

    46952, 81688, 46161, 77042, 66174, 76669, 11774, 42350,
    2295, 47583, 13878, 74702, 85816, 98447, 42942,

    35191, 32175, 5424, 45902, 55043, 75122, 38188, 42272,
    81684, 26073, 81270, 60781, 54112, 6500, 92619,

    52595, 72461, 89479, 16995, 80103, 37763, 110897, 57108,
    11355, 31700, 13962, 68964, 94379, 45982,

    109258, 66917, 69564, 95039, 13677, 78910, 34651, 66224,
    30281,

    34540, 109495, 36671, 67155, 12546, 32974, 85991, 12838,
    3495, 15103, 68278, 95499, 50951, 100244, 35273, 81206,
    111009, 79928, 98696, 1884, 24229,

    14261, 90300, 944, 28659, 76651, 82966, 76850, 22116,
    102611, 9980, 31761, 93629, 49275, 108091, 54062,

    71244, 45258, 90443, 2835, 63250, 37413, 44626, 70952,
    13097, 3106, 102808, 20679, 83036, 61103, 42284, 96787,

    24486, 100540, 20165, 43732, 78552, 96929, 9944, 14919,
    101928, 63726, 15724, 54297, 47611, 39696,

    105322, 102579, 29585, 43133, 20623, 70169, 5044, 651,

    64629, 3410, 13820, 45955, 24140, 104654, 25540, 96574,
    72749, 69295, 100607, 75239, 40117, 29888, 1413, 86051,
    46112, 39110, 105745,

    85726, 67729, 103408, 24257, 73449, 46534, 76369, 43552,
    13137,

    55893, 104914, 1969, 50552, 102446, 100414, 1399, 96473,
    91542, 6313, 30779, 99537, 35090,

    87692, 8072, 91520, 100765, 9842, 23164, 37215, 65699,
    100056, 32460,

    26333, 16223, 43757, 27954, 27597, 28722, 109872, 66347,
    1259, 26155, 54653, 90046, 11619, 84577, 105488, 78433,
    32895, 19066, 222, 18968, 81015, 89160,

    84448, 41064, 55461, 74835, 64928, 39042, 88522, 78602,
    94666, 6740, 54346, 22623, 96797, 55677,

    39303, 36580, 63050, 86149, 49990, 47157, 79669, 31304,
    75097, 41599, 44623,

    12327, 108446, 49070, 40604, 89282, 43958, 22246, 37029,
    109605,

    34989, 6726, 37557, 48490, 53518, 34237, 62840, 35861,
    10687, 67490,

    96411, 83947, 16104, 8430, 84208, 20833, 47848, 1574,
    78087, 60756, 41810, 91669, 15924, 4829, 83494, 52338,
    79378,

    14212, 60784, 51424, 97485, 74659, 81536, 92453, 105742,
    25295, 108773, 112046, 68716, 48584,

    75713, 12749, 28482, 18339, 100221, 97025, 88420, 84893,
    65390, 85875, 98414,

    3229, 108792, 20685, 67099, 44732, 29923, 79872,

    66179, 82458, 101250, 32350, 47202, 79478, 9141, 87413,
    103847, 85305, 22099, 21163, 98302, 16284, 58993, 8242,
    21978, 80687, 6516, 76361, 62419, 49401, 95238, 21673,
    47872, 76760, 39619, 88369, 73455, 30182, 55933, 71502,
    32752, 97654, 109600, 98352, 93719, 100625, 7667, 77520,
    22765, 111517, 111958, 10812, 31627, 15227, 70148, 98197,
    88405, 54858, 51744, 107597, 52728, 86770, 79580, 4702,
    93600
]


# ============================================
# IDS THAT MUST BE KEPT
# ============================================

keep_ids = [
    92466,
    68716,
    109038,
    49275,
    1413,
    44797,
    54346,
    47848,
    81536,
    22116,
    104654,
    46534,
    45982,
    63493,
    29888,
    40117,
    13137,
    73471,
    24140,
    49070,
    76369,
    82966,
    87692,
    6740,
]


# ============================================
# 1. CONVERT TO SETS
# ============================================

irrelevant_ids = set(irrelevant_ids)
keep_ids = set(keep_ids)


# ============================================
# 2. REMOVE KEEP IDS FROM REMOVAL LIST
# ============================================

irrelevant_ids = irrelevant_ids - keep_ids


# ============================================
# 3. BEFORE
# ============================================

print("BEFORE REMOVAL")
print("----------------")
print("Shape:", df.shape)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])


# ============================================
# 4. MAKE SURE ID FORMAT IS CORRECT
# ============================================

df["id"] = pd.to_numeric(df["id"], errors="coerce")

existing_ids = set(df["id"].dropna().astype(int))

found_ids = irrelevant_ids.intersection(existing_ids)
missing_ids = irrelevant_ids - existing_ids


print("\nID CHECK")
print("--------")
print("Keep IDs:", len(keep_ids))
print("IDs remaining for removal:", len(irrelevant_ids))
print("IDs found in dataframe:", len(found_ids))
print("IDs not found:", len(missing_ids))


# ============================================
# 5. VERIFY KEEP IDS ARE NOT BEING REMOVED
# ============================================

overlap = keep_ids.intersection(irrelevant_ids)

print("\nKEEP/REMOVE CHECK")
print("-----------------")
print("Keep IDs accidentally marked for removal:", len(overlap))

if len(overlap) == 0:
    print("✅ All keep IDs are protected.")
else:
    print("⚠️ These IDs are in both lists:")
    print(sorted(overlap))


# ============================================
# 6. SHOW ROWS THAT WILL BE REMOVED
# ============================================

to_remove = df[df["id"].isin(found_ids)].copy()

print("\nROWS THAT WILL BE REMOVED")
print("-------------------------")
print("Number of rows:", len(to_remove))

pd.set_option("display.max_colwidth", None)

display(to_remove[["id", "input", "output"]])


# ============================================
# 7. REMOVE IRRELEVANT ROWS
# ============================================

df_clean = df[~df["id"].isin(found_ids)].copy()


# ============================================
# 8. AFTER
# ============================================

print("\nAFTER REMOVAL")
print("-------------")
print("Shape:", df_clean.shape)
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])
print("Rows removed:", df.shape[0] - df_clean.shape[0])


# ============================================
# 9. VERIFY KEEP IDS ARE STILL PRESENT
# ============================================

kept_rows = df_clean[df_clean["id"].isin(keep_ids)]

print("\nKEEP IDS CHECK")
print("--------------")
print("Keep IDs found after cleaning:", kept_rows["id"].nunique())
print("Expected keep IDs:", len(keep_ids))

missing_keep_after = keep_ids - set(
    df_clean["id"].dropna().astype(int)
)

if len(missing_keep_after) == 0:
    print("✅ All keep IDs are still present.")
else:
    print("⚠️ These keep IDs are missing after cleaning:")
    print(sorted(missing_keep_after))


# ============================================
# 10. FINAL CHECK
# ============================================

still_present = df_clean[df_clean["id"].isin(found_ids)]

print("\nFINAL REMOVAL CHECK")
print("-------------------")
print("Removed IDs still present:", len(still_present))

if len(still_present) == 0:
    print("✅ All irrelevant IDs were removed successfully.")
else:
    print("⚠️ Some irrelevant IDs are still present:")
    display(still_present[["id", "input", "output"]])

BEFORE REMOVAL
----------------
Shape: (108954, 5)
Rows: 108954
Columns: 5

ID CHECK
--------
Keep IDs: 24
IDs remaining for removal: 563
IDs found in dataframe: 563
IDs not found: 0

KEEP/REMOVE CHECK
-----------------
Keep IDs accidentally marked for removal: 0
✅ All keep IDs are protected.

ROWS THAT WILL BE REMOVED
-------------------------
Number of rows: 563

,id,input,output
63,54062,প্রিয় ডাক্তার,"হেলো, সেরোকুয়েল (কুয়েটিয়াপাইন) এবং লরা (লুরাসাইডোন) দুটি ভিন্ন নাসেনিয়া ডক। আমার ধারণা সেরোকুয়েল লরার চেয়ে সস্তা হবে। এছাড়া, সেরোকুয়েলের জেনেরিক সংস্করণও পাওয়া যায়, যা আরও সস্তা হবে। তবে আপনাকে আপনার ডাক্তারের সাথে যোগাযোগ করে এ বিষয়ে আলোচনা করতে হবে। আপনি উল্লেখ করেছেন যে ওষুধ থেকে আপনি খুব একটা উপকার পাচ্ছেন না। যেহেতু আপনি বিষণ্নতায় ভুগছেন, তাই আপনার অ্যান্টি-ডিপ্রেসেন্ট দিয়ে চিকিৎসার প্রয়োজন হবে। সেরোকুয়েলের মতো অ্যান্টিসাইকোটিক ওষুধ অ্যান্টি-ডিপ্রেসেন্টের কার্যকারিতা বাড়াতে পারে, কিন্তু সেগুলোর বিকল্প হতে পারে না। ওষুধের পাশাপাশি আরও কিছু বিষয় সাহায্য করতে পারে, যেমন কগনিটিভ থেরাপি ইত্যাদি। দয়া করে আশা হারাবেন না। যদি নিজের ক্ষতি করার ইচ্ছা জাগে, তবে অবিলম্বে আপনার ডাক্তার এবং পরিবারের সদস্যদের জানান। শুভকামনা।"
156,55043,"হেলো, নাম","হেলো। এখানে প্রয়োজনীয় ডায়েট হলো উচ্চ চিনিযুক্ত খাবার বর্জন করা। ভাত জাতীয় খাবার এড়িয়ে চলুন এবং ডাক্তারের পরামর্শ নিন। আপনার খাদ্যতালিকায় গমের তৈরি খাবার যোগ করুন। ওটস বা ফাইবারযুক্ত খাবার খান। তৈলাক্ত এবং খুব বেশি মশলাদার খাবার এড়িয়ে চলুন। নিয়মিত ব্যায়াম করুন তবে শুধুমাত্র হালকা থেকে মাঝারি ধরনের ব্যায়াম। আপনি যদি মদ্যপায়ী হন তবে মদ্যপান বন্ধ করতে হবে। ডিমের সাদা অংশসহ প্রোটিনযুক্ত খাবার খান, ব্লুবেরি, আঙুর এবং রামবুটানের মতো ফল খান। এই পদ্ধতিগুলো মেনে চলুন এবং ৫ দিন পর চিনির মাত্রা পরীক্ষা করুন। এর মধ্যে কোনো অসুবিধা হলে এন্ডোক্রিনোলজিস্টের পরামর্শ নিন। আশা করি এটি সাহায্য করবে। ধন্যবাদ।"
356,16223,"হেলো, আপনি কেমন আছেন?","হেলো, এই বয়সসীমার শিশুদের ক্ষেত্রে ৯৫ শতাংশ সময় জ্বর সাধারণত ভাইরাল সংক্রমণের কারণে হয়ে থাকে, তাই আমি অযথা অ্যান্টিবায়োটিক ব্যবহারের পরামর্শ দিই না। যদি শিশুটি জ্বর না থাকার সময় স্বাভাবিক ও চঞ্চল থাকে এবং শ্বাসকষ্ট, বমি বা মলের সাথে রক্ত পড়ার মতো কোনো আশঙ্কাজনক লক্ষণ না থাকে, আর জ্বর কমে গেলে যদি সে ভালো বোধ করে, তবে আপনার চিন্তার কোনো কারণ নেই। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি। আমি আপনাকে আর কোনোভাবে সাহায্য করতে পারি কি না, তা জানাবেন।"
535,42153,রেনাল আল্ট্রাসাউন্ড - ১২/২৭/২০১২ ক্লিনিকাল তথ্য,"হেলো, ইউনিলেটারাল এইচওয়াই নাসেনিয়া ডক। যদিও লিভারের তুলনায় রেনাল কর্টিকাল ইকোজেনিসিটি বৃদ্ধি পাওয়া কিডনির কার্যক্ষমতা হ্রাসের ইঙ্গিত দেয়, তবুও শুধুমাত্র আল্ট্রাসনোগ্রাফির ফলাফলের ভিত্তিতে তীব্র বা দীর্ঘস্থায়ী বিকলতা নির্ণয় করা যায় না। তাই আমি কিছু প্রাথমিক পরীক্ষা যেমন ইউরিন রুটিন, মাইক্রোস্কোপি, কালচার সেনসিটিভিটি, ব্লাড ইউরিয়া, সিরাম ক্রিয়েটিনিন এবং ইলেকট্রোলাইটস পরীক্ষা করার পরামর্শ দেব। একজন নেফ্রোলজিস্টের সাথে পরামর্শ করুন, কারণ কিডনির গঠনগত বা কার্যগত অস্বাভাবিকতা সঠিকভাবে মূল্যায়ন করার জন্য এমভিপি (MVP) এবং রেনাল সিনোগ্রাফির মতো পরীক্ষার প্রয়োজন হতে পারে। শুভেচ্ছা।"
997,65390,"আমি ২০ বছর বয়সী নারী, উচ্চতা","আপনার অনুসন্ধানের জন্য ধন্যবাদ, আমি আপনার অনুসন্ধানটি দেখেছি। মুখের অসামঞ্জস্যতা ম্যান্ডিবলের কোনো ত্রুটি যেমন হেমিম্যান্ডিবুলার হাইপারট্রফি বা হাইপোট্রফি অথবা কন্ডাইলার হাইপোপ্লাস্টিক বা হাইপারপ্লাসিয়ার কারণে ফোলাভাবের জন্য হতে পারে। এটি ম্যাসেটার পেশীর হাইপারট্রফি বা ইন্ট্রাম্যাসেটারিক লিপোমার কারণেও হতে পারে। একজন ওরাল ফিজিশিয়ানের সাথে পরামর্শ করুন এবং দাঁত বা হাড় সম্পর্কিত কোনো রোগ নির্ণয়ের জন্য ওপিজি (OPG)-এর মতো রেডিওগ্রাফ করান এবং লিপোমা আছে কিনা তা নিশ্চিত করতে আল্ট্রাসাউন্ড করান। আশা করি আমার উত্তরটি আপনাকে সাহায্য করবে। ভালো থাকবেন।"
...,...,...,...
107705,19123,"হেলো, আমার প্রশ্নটি নিচে দেওয়া হলো","আপনার অনুসন্ধানের জন্য ধন্যবাদ, আমি আপনার অনুসন্ধানটি দেখেছি। মাড়িতে ব্যথা এবং ফোলাভাব দাঁতের সংক্রমণের কারণে হয়েছে, যার ফলে ফোড়া তৈরি হয়েছে। এই ফোড়া পেনিসিলিনে ভালো হবে না। আপনাকে মেট্রোনিডাজল ৪০০ মিগ্রা দিনে দুইবার করে ৫ দিন খেতে হবে (যদি আপনার অ্যালার্জি না থাকে), সেই সাথে আইবুপ্রোফেন এবং প্যারাসিটামল নিতে হবে। অ্যান্টিবায়োটিকের কোর্স ৩ দিন সম্পন্ন করার পর, রুট ক্যানেল চিকিৎসার মাধ্যমে দাঁতের চিকিৎসা করান। অ্যান্টিবায়োটিক একটি সাময়িক সমাধান, তবে আপনাকে দাঁতের চিকিৎসা করাতে হবে। আশা করি আমার উত্তরটি আপনাকে সাহায্য করবে, ভালো থাকবেন।"
108151,98810,রোগী,"নাসেনিয়া ডকে আপনার প্রশ্নের জন্য ধন্যবাদ। আমি আপনার পরিস্থিতি এবং সমস্যাটি বুঝতে পারছি। যেহেতু রোগী একজন ধূমপায়ী, তাই ফুসফুসের ক্যান্সারের সম্ভাবনা বেশি। এবং ফুসফুসের ক্যান্সারে মেরুদণ্ডে মেটাস্ট্যাসিস খুব সাধারণ। এটি স্পাইনাল কর্ড কমপ্রেশনের দিকে নিয়ে যেতে পারে। আরেকটি সম্ভাবনা হলো মিডিয়াস্টিনাল টিউমার, মূলত লিম্ফোমা। লিম্ফোমা সাধারণত পোস্টেরিয়র মিডিয়াস্টিনামে দেখা যায় তবে এটি অ্যান্টিরিয়র বা মিডল মিডিয়াস্টিনামেও হতে পারে। তাই ফুসফুসের ক্যান্সার বা মিডিয়াস্টিনাল মাস নির্ণয়ের জন্য কন্ট্রাস্টসহ সিটি থোরাক্স করানো ভালো। এছাড়াও স্পাইনাল কর্ড কমপ্রেশনের কারণ হিসেবে মেরুদণ্ডে মেটাস্ট্যাসিস আছে কিনা তা নিশ্চিত করতে এমআরআই স্পাইন করান।"
108305,90046,"হেলো, আপনি কেমন আছেন?","হেলো, আমার সাত দিনের চক্র। আমি কোন দিন ডিম্বস্ফোটন শুরু করব? আমি চিন্তিত কারণ আমি ২৬শে ডিসেম্বর এবং ১লা জানুয়ারি দুইজন পুরুষের সাথে যৌন মিলন করেছি। তবে, এই ব্যক্তিটি বলেছে যে সে আমার ভেতরে বীর্যপাত করেনি। আমি সম্প্রতি ৮ই জানুয়ারি আমার প্রেমিকের কাছে ফিরে এসেছি এবং সেই দিন থেকে অরক্ষিত যৌন মিলন করেছি। আমি শুধু জানতে চাই যে কোন ব্যক্তিটি বাবার হতে পারে। আমি খুব ভয় পাচ্ছি কারণ আমার প্রেমিক বিশ্বাস করে যে বাচ্চাটি তার। সে জানে না যে আমি অন্য একজন পুরুষের সাথে যৌন মিলন করেছি। অনুগ্রহ করে আমাকে সাহায্য করুন। আপনাকে অনেক ধন্যবাদ।"
108393,100414,আমার উপসর্গগুলো হলো,"হেলো! নাসেনিয়া ডকে আপনার প্রশ্নটি করার জন্য ধন্যবাদ। আমি একজন গ্যাস্ট্রোএন্টেরোলজিস্ট। ফ্যাটি লিভারের অনেক কারণ থাকে যেমন হেপাটাইটিস বি, সি, মেটাবলিক ডিসঅর্ডার, এনএএফএলডি (NAFLD), অ্যালকোহল গ্রহণ ইত্যাদি। তাই আমি আপনাকে পরামর্শ দেব একজন হেপাটোলজিস্টের সাথে দেখা করে মূল্যায়ন করার জন্য, যিনি প্রয়োজনীয় পরীক্ষা-নিরীক্ষার পরামর্শ দেবেন এবং সেই অনুযায়ী চিকিৎসা করবেন। ইতিমধ্যে, কিছু ওষুধ যা আমি আমার রোগীদের ক্ষেত্রে খুব কার্যকর পেয়েছি তা হলো আরসোডিওক্সিকোলিক অ্যাসিড এবং ভিটামিন ই। নিয়মিত ব্যায়াম করুন এবং যদি আপনার ওজন বেশি হয় তবে তা কমান, অ্যালকোহল পরিহার করুন। আমি আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি এবং এটি আপনাকে সাহায্য করবে। আপনার সুস্বাস্থ্য কামনা করি।"
108471,71244,সবাইকে শুভ দিন,"হেলো, আপনার রক্তচাপ সাধারণত কম থাকে এবং ঝুঁকে পড়ার সময় মাথা ঝিমঝিম করে, এটি অর্থোস্ট্যাটিক হাইপোটেনশন নামক একটি সমস্যার কারণে হতে পারে। আমাদের পায়ের শিরাগুলো রক্ত জমা রাখার আধার হিসেবে কাজ করে। শিরার সংকোচন রক্তকে হৃদপিণ্ডের দিকে পাম্প করে, যা পরে হৃদপিণ্ড থেকে সারা শরীরে ছড়িয়ে পড়ে এবং রক্তচাপ বজায় থাকে। কোনো কারণে আপনার শরীরে এই প্রক্রিয়াটি সঠিকভাবে কাজ করছে না। আমি আপনাকে কাজ করার সময় স্টকিং পরার পরামর্শ দেব। টাইট স্টকিং পায়ের শিরার ওপর চাপ বাড়াবে এবং রক্তকে হৃদপিণ্ডের দিকে পাম্প করতে সাহায্য করবে। হঠাৎ করে ঝুঁকবেন না, ধীরে ধীরে নড়াচড়া করুন যাতে আপনার শরীর ভঙ্গি পরিবর্তনের সাথে মানিয়ে নিতে পারে। ধন্যবাদ।"

AFTER REMOVAL
-------------
Shape: (108391, 5)
Rows: 108391
Columns: 5
Rows removed: 563

KEEP IDS CHECK
--------------
Keep IDs found after cleaning: 24
Expected keep IDs: 24
✅ All keep IDs are still present.

FINAL REMOVAL CHECK
-------------------
Removed IDs still present: 0
✅ All irrelevant IDs were removed successfully.

In [35]:
df_clean.head()

,id,input,output,input_length,input_len
0,45361,"হেলো, আমরা গত ৩ মাস ধরে গর্ভধারণের চেষ্টা করছি কিন্তু ফলাফল নেতিবাচক। এবার আমি ফলিকুলার মনিটরিং করিয়েছি এবং ১৭তম দিনে ওভুলেশন হয়েছে, কিন্তু তবুও আমি গর্ভবতী নই। যদিও আমার এলও-তে অনেকগুলো ছোট ফলিকল ছিল, এগুলো কি স্বাভাবিক নাকি পিসিওডি? আমি সত্যিই বিভ্রান্ত এবং বুঝতে পারছি না কী করব, আমার কি ডাক্তার পরিবর্তন করা উচিত?","হেলো, পিসিওডি (PCOD) হলো এমন একটি উপসর্গ যা অনিয়মিত বা অনুপস্থিত পিরিয়ড, বন্ধ্যাত্ব, স্থূলতা, অবাঞ্ছিত লোম বৃদ্ধি, ব্রণ, কিছু ক্ষেত্রে ইনসুলিন রেজিস্ট্যান্স, এলএইচ/এফএসএইচ (LH/FSH) অনুপাত উল্টে যাওয়া সহ অস্বাভাবিক হরমোনের প্রোফাইল, আরএইচইএএস (RHEAS) লেভেল বৃদ্ধি, কিছু ক্ষেত্রে অস্বাভাবিক জিটিটি (GTT), কখনও কখনও উচ্চ প্রোল্যাক্টিন এবং অস্বাভাবিক থাইরয়েড প্রোফাইলের সাথে যুক্ত থাকে। এতে ডিম্বাশয়ে একাধিক ফলিকল দেখা যায় কারণ অনেকগুলো ফলিকল একই সময়ে তৈরি হলেও সেগুলো পরিপক্ক হয় না। রোগ নির্ণয়ের জন্য আপনাকে সম্পূর্ণ পরীক্ষা-নিরীক্ষা করাতে হবে। ওভুলেশন বা ডিম্বস্ফোটন সম্ভব হলেও হরমোনের ভারসাম্যহীনতা, টিউব সংক্রান্ত সমস্যা বা পুরুষজনিত কারণের মতো অনেকগুলো বিষয়ের কারণে গর্ভধারণ নাও হতে পারে। আপনার একজন অভিজ্ঞ ইনফার্টিলিটি বিশেষজ্ঞের পরামর্শ নেওয়া উচিত। নিজের যত্ন নেবেন।",317,317
1,95550,"প্রায় এক মাস আগে আমার পিঠের ডান দিকের কাঁধের হাড়ের কাছে বৈদ্যুতিক স্রোতের মতো এক ধরনের অনুভূতি হতে শুরু করেছে। এটি বেশ বিরক্তিকর এবং আমি জানি না কীভাবে এর চিকিৎসা করব। প্রায় ১২ বছর আগে আমার ঘাড়ে সি-৬ এবং সি-৭ ফিউশন হয়েছিল। কী হচ্ছে আমার? আমার বয়স ৬০, আমি বিশেষ চাহিদাসম্পন্ন শিশুদের নিয়ে কাজ করি এবং শারীরিকভাবে সক্রিয় থাকি। প্রায় এক মাস ধরে চলা হাড়কাঁপানো ঠান্ডার সাথে কি এর কোনো সম্পর্ক থাকতে পারে? ধন্যবাদ।","হেলো, প্রথমে আমাকে আপনাকে ব্যাখ্যা করতে দিন যে আপনার মতো একটি নির্দিষ্ট মেডিকেল লক্ষণের বিভিন্ন কারণ থাকতে পারে। পিঠে ব্যথা এবং বিদ্যুৎ প্রবাহের মতো অনুভূতি সার্ভিকাল স্পাইনাল কর্ডের স্পনডাইলোসিস বা অন্যান্য কারণে (যেমন কোনো টিউমার, অবক্ষয়, মেরুদণ্ডের সমস্যা) হতে পারে। বার্ধক্যে এটি স্পনডাইলোসিসের কারণে হতে পারে। সঠিক স্নায়বিক সমস্যা নির্ণয়ের জন্য আপনার একটি বিস্তারিত স্নায়বিক পরীক্ষা প্রয়োজন। বিদ্যুৎ প্রবাহের মতো অনুভূতির উপস্থিতি উদ্বেগের বিষয়, কারণ এটি নির্দেশ করে যে মেরুদণ্ডের কোনো একটি অংশ সংকুচিত হচ্ছে। তাই, জরুরি ভিত্তিতে একজন স্নায়ুরোগ বিশেষজ্ঞের মূল্যায়ন প্রয়োজন এবং পরবর্তীতে পুনরায় ইমেজিং ও নার্ভ কন্ডাকশন স্টাডি (প্রাথমিক মূল্যায়নের ওপর ভিত্তি করে এটি ঐচ্ছিক হতে পারে) করার প্রয়োজন হতে পারে। আপনার চিকিৎসা মূলত কারণের ওপর নির্ভর করবে। আশা করি এই ব্যাখ্যাটি আপনাকে সাহায্য করবে। শুভকামনা।",409,409
2,98599,"হেলো, আমি ২৫ বছর বয়সী অবিবাহিত মেয়ে। আমার কপাল, ঘাড় এবং হাতে কালচে দাগ হয়েছে। আগে এটি রোদে পোড়া দাগের মতো ছিল, কিন্তু আমি এর জন্য চিকিৎসা নিয়েছিলাম এবং ডাক্তার যে মলম দিয়েছিলেন তা স্টেরয়েডযুক্ত ছিল। এর ফলে সমস্যাটি আরও বেড়ে গেছে। আগে এটি খুব একটা বোঝা যেত না, কিন্তু এখন এটি দেখতে খুব খারাপ লাগে। আপনি কি দয়া করে আমাকে কিছু পরামর্শ দিতে পারেন? আমি রোদ এড়িয়ে চলি, কিন্তু কোনো সানস্ক্রিন ব্যবহার করি না কারণ এতে রাসায়নিক থাকে।","হেলো কবিতা, লেখার জন্য ধন্যবাদ। স্কিন লাইটেনিং ক্রিমে ২% এইচওয়াই নাসেনিয়া ডক থাকে। এই উপাদানগুলো ত্বকে স্থায়ী পিগমেন্টেশন ঘটাতে পারে যার ফলে সাদা দাগ হতে পারে। এটি দীর্ঘ সময় ব্যবহার করা উচিত নয়। আমার পরামর্শ হলো - স্টেরয়েডযুক্ত ক্রিম ব্যবহার বন্ধ করুন। দিনের বেলা ভালো সানস্ক্রিন ব্যবহার করুন। আপনি রাতে কালো দাগের ওপর ক্লাইম্যাক্স ক্রিম লাগাতে পারেন, এটি নিরাপদ এবং কার্যকর। গায়ের রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। খাদ্যতালিকায় প্রচুর ভিটামিন সি রাখুন। রোদে যাওয়া এড়িয়ে চলুন। রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। ভবিষ্যতে যেকোনো এইচকিউ (HQ) এবং স্টেরয়েডযুক্ত ক্রিম এড়িয়ে চলুন। আশা করি এটি সাহায্য করবে। ফলো-আপের জন্য আমি উপলব্ধ থাকব। শুভেচ্ছা।",424,424
3,84959,"হেলো, আমার বয়স ২২, উচ্চতা ৫ ফুট ৯ ইঞ্চি এবং ওজন ১৭০ পাউন্ড। আমি সারা জীবন খুব সুস্থ ছিলাম, তেমন কোনো সমস্যা হয়নি। আমার উপরের ঠোঁটের ঠিক উপরে একটি ফোলা চাকা হয়েছে যা ঠোঁটকে স্পর্শ করে আছে। চাপ না দিলে এটি ব্যথা করে না, তবে আমি এটি অনুভব করতে পারছি এবং এটি আমাকে বিরক্ত করছে। বরফ দিলে ফোলা কিছুটা কমে। এটি কোনো খোলা ক্ষত নয়, শুধু একটি চাকা যা যাচ্ছে না। এটি প্রায় ৫ দিন ধরে আছে।","হেলো প্রিয়, নাসেনিয়া ডকে আপনাকে স্বাগতম। আপনার উদ্বেগটি বুঝতে পারছি। আপনার প্রশ্ন অনুযায়ী, উপরের ঠোঁটের উপরে ফোলা অংশটি মূলত ঠোঁট কামড়ানোর কারণে হয়ে থাকে। অসাবধানতাবশত নিচের চোয়ালের দাঁত উপরের ঠোঁটে আঘাত করলে সেই জায়গায় অতিরিক্ত কোলাজেন ফাইবার জমা হয়ে ফোলাভাব সৃষ্টি হয়। এটি হারপিস সিমপ্লেক্স ভাইরাস সংক্রমণের কারণেও হতে পারে, যা ওই এলাকায় কোল্ড সোর বা ঘা সৃষ্টি করতে পারে। যদি আপনি অতিরিক্ত সূর্যের আলোতে থাকেন, তবে এই ফোসকা তার কারণেও হতে পারে। এটি নিয়ে আতঙ্কিত হওয়ার কিছু নেই। বরফের টুকরো নিয়ে এই জায়গায় ১০-১২ মিনিট বিরতি দিয়ে চেপে ধরুন। জায়গাটি পরিষ্কার রাখুন। নাসেনিয়া ডকের সাথেই থাকুন।",376,376
4,65169,"হেলো, আমার নানি প্রায়ই অভিযোগ করেন যে তার হৃদপিণ্ডের চারপাশে গ্যাসের সমস্যা হচ্ছে, যার ফলে তিনি মাথা ঝিমঝিম এবং মাথা ঘোরার অনুভব করেন। তার বয়স ৭৭ বছর এবং তার হার্টের অপারেশন হয়েছে ও নতুন ভালভ বসানো হয়েছে। তিনি ডাক্তারকে বিষয়টি জানালেও ডাক্তার কোনো পদক্ষেপ নিচ্ছেন না। আমি চিন্তিত কারণ এর ফলে তার মাথা ঘোরে এবং এমনিতেই তার হাঁটাচলায় ভারসাম্যহীনতা রয়েছে। এর কারণ কী হতে পারে এবং কী করলে উপকার পাওয়া যাবে, তা কি জানাতে পারবেন? ধন্যবাদ।","হেলো, আমি আপনার প্রশ্নটি মনোযোগ সহকারে পড়েছি এবং ব্যাখ্যা করতে চাই যে তার হৃদযন্ত্রের কার্যকারিতা মূল্যায়ন করা এবং সম্ভাব্য হার্ট ফেইলিওর যা এই ক্লিনিকাল পরিস্থিতির অনুকরণ করতে পারে, তা বাদ দেওয়া প্রয়োজন। গ্যাস্ট্রোইসোফেজিয়াল রিফ্লাক্সও এই পরিস্থিতির অনুকরণ করতে পারে, যদিও মাথা ঘোরা এই রোগের সাধারণ লক্ষণ নয়। এই পর্যায়ে, আমি হার্ট ফেইলিওর আছে কিনা তা তদন্ত করার জন্য একটি কার্ডিয়াক আল্ট্রাসাউন্ড এবং এনটি-প্রো বিএনপি (NT-pro BNP) পরীক্ষা করার পরামর্শ দেব। বিবেচনা করার মতো অন্যান্য পরীক্ষাগুলো হলো",432,432

TRAIN

In [36]:
# ============================================
# CHECK EXTRA SPACES / SYMBOLS / PUNCTUATION
# ============================================

import re
import pandas as pd

check_df = df_clean.copy()

# Make sure input is string
check_df["input"] = check_df["input"].fillna("").astype(str)


# ============================================
# 1. LEADING / TRAILING SPACES
# ============================================

check_df["leading_space"] = check_df["input"].str.match(r"^\s")
check_df["trailing_space"] = check_df["input"].str.match(r"\s$")

print("Leading spaces:", check_df["leading_space"].sum())
print("Trailing spaces:", check_df["trailing_space"].sum())


# ============================================
# 2. MULTIPLE / EXTRA SPACES
# ============================================

check_df["multiple_spaces"] = check_df["input"].str.contains(
    r"\s{2,}",
    regex=True
)

print("Multiple consecutive spaces:", check_df["multiple_spaces"].sum())


# ============================================
# 3. PUNCTUATION / SYMBOLS
# ============================================

# Anything that is NOT:
# Bengali characters, English letters, numbers, or whitespace
check_df["has_symbols"] = check_df["input"].str.contains(
    "[^\u0980-\u09FFa-zA-Z0-9\s]",
    regex=True
)

print("Rows containing symbols/punctuation:", check_df["has_symbols"].sum())


# ============================================
# 4. SHOW ROWS WITH EXTRA SPACES
# ============================================

space_issues = check_df[
    check_df["leading_space"]
    | check_df["trailing_space"]
    | check_df["multiple_spaces"]
]

print("\nROWS WITH SPACE ISSUES")
print("----------------------")
display(
    space_issues[
        ["id", "input", "leading_space",
         "trailing_space", "multiple_spaces"]
    ]
)


# ============================================
# 5. SHOW ROWS WITH SYMBOLS / PUNCTUATION
# ============================================

symbol_issues = check_df[check_df["has_symbols"]]

print("\nROWS WITH SYMBOLS / PUNCTUATION")
print("--------------------------------")
display(
    symbol_issues[
        ["id", "input"]
    ]
)


# ============================================
# 6. SUMMARY
# ============================================

print("\nSUMMARY")
print("-------")
print("Total rows:", len(check_df))
print("Leading space:", check_df["leading_space"].sum())
print("Trailing space:", check_df["trailing_space"].sum())
print("Multiple spaces:", check_df["multiple_spaces"].sum())
print("Symbols/punctuation:", check_df["has_symbols"].sum())

Leading spaces: 0
Trailing spaces: 0

<>:44: SyntaxWarning: invalid escape sequence '\s'
<>:44: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_189/1924297170.py:44: SyntaxWarning: invalid escape sequence '\s'
  "[^\u0980-\u09FFa-zA-Z0-9\s]",

Multiple consecutive spaces: 398
Rows containing symbols/punctuation: 108212

ROWS WITH SPACE ISSUES
----------------------

,id,input,leading_space,trailing_space,multiple_spaces
52,73098,"আমি সবেমাত্র আমার মেরুদণ্ডের এমআরআই করিয়েছি এবং নিম্নলিখিত রিপোর্টটি পেয়েছি। এটি বুঝতে আমাকে সাহায্য করুন।\n\nL3/L4 লেভেলে ডিস্ক ডেসিকেশন (ডিস্কের জলীয় অংশ কমে যাওয়া)।\nL3/L4 লেভেলে সামান্য ডিফিউজ পোস্টেরিয়র বাল্জ, যার ফলে স্পাইনাল থেকায় চাপ সৃষ্টি হচ্ছে, ল্যাটারাল রিসেস সামান্য সংকুচিত হয়েছে এবং ট্রাভার্সিং নার্ভ রুটগুলোতে সামান্য চাপ পড়ছে।\nL4/5 লেভেলে ডিফিউজ পোস্টেরিয়র বাল্জ, যার ফলে স্পাইনাল থেকায় চাপ সৃষ্টি হচ্ছে, ল্যাটারাল রিসেস সামান্য সংকুচিত হয়েছে, ট্রাভার্সিং ও এক্সিটিং নার্ভ রুটগুলোতে সামান্য চাপ পড়ছে এবং উভয় নিউরাল ফোরামেন সামান্য সরু হয়ে গেছে।\nL5/S1 লেভেলে সামান্য ডিফিউজ পোস্টেরিয়র বাল্জ, যার ফলে স্পাইনাল থেকায় চাপ সৃষ্টি হচ্ছে, ল্যাটারাল রিসেস সামান্য সংকুচিত হয়েছে এবং ট্রাভার্সিং নার্ভ রুটগুলোতে খুব সামান্য চাপ পড়ছে।",False,False,True
264,30020,"হেলো, আমি বুঝতে পারছি আপনি খুব দুশ্চিন্তায় আছেন। তবে এটি পরিষ্কার করা জরুরি যে, অনিরাপদ মিলনের ৪৮ ঘণ্টা পর বাড়িতে এমন কোনো ঘরোয়া উপায় বা পদ্ধতি নেই যা গর্ভাবস্থা প্রতিরোধ করতে পারে। গর্ভনিরোধক বড়ি বা ইমার্জেন্সি পিল ছাড়া অন্য কোনো ঘরোয়া টোটকা কার্যকর নয়।\n\nআপনার এখন যা করা উচিত:\n\n১. দ্রুত কোনো সরকারি হাসপাতাল, ফ্যামিলি প্ল্যানিং ক্লিনিক বা নিকটস্থ ফার্মেসিতে যোগাযোগ করুন। অনেক জায়গায় বিনামূল্যে বা কম খরচে ইমার্জেন্সি পিল পাওয়া যায়। ৪৮ ঘণ্টা পার হয়ে গেলেও কিছু পিল ৭২ ঘণ্টা বা তার বেশি সময় পর্যন্ত কাজ করতে পারে, তাই দেরি না করে আজই চিকিৎসকের পরামর্শ নিন।\n\n২. যদি পিল পাওয়ার কোনো উপায় না থাকে, তবে পরবর্তী পদক্ষেপের জন্য একজন চিকিৎসকের সাথে কথা বলুন।\n\n৩. আপনার পিরিয়ড মিস হলে বা নির্ধারিত সময়ের চেয়ে দেরি হলে একটি প্রেগন্যান্সি টেস্ট কিট দিয়ে পরীক্ষা করুন।\n\nদয়া করে কোনো ভুল বা অনিরাপদ ঘরোয়া পদ্ধতির ওপর নির্ভর করবেন না, কারণ এতে আপনার স্বাস্থ্যের ক্ষতি হতে পারে। দ্রুত একজন বিশেষজ্ঞের পরামর্শ নিন।",False,False,True
273,76825,"প্রিয় মহোদয়, আমার মেরুদণ্ডের শেষ প্রান্তে ব্যথা এবং মাঝে মাঝে পায়েও ব্যথা হয়। তাই আমি এমআরআই করিয়েছি, যার ফলাফল নিচে দেওয়া হলো:\n* L5/S1 লাম্বার-আইভি ডিস্ক T2W ইমেজে হাইপো-ইনটেন্স দেখাচ্ছে, যা ডিহাইড্রেশনের ইঙ্গিত দেয়।\n* L5/S1 আইভি ডিস্ক থিকাল স্যাকের দিকে পোস্টেরিয়র বাল্জ বা স্ফীতি দেখাচ্ছে।\n\nঅনুগ্রহ করে আমাকে পরামর্শ দিন যে উপরের ফলাফলগুলোর অর্থ কী এবং আমার কী ধরনের চিকিৎসার প্রয়োজন, নাকি অস্ত্রোপচারের প্রয়োজন আছে। যদি কোনো ওষুধ সেবনের প্রয়োজন হয়, তবে দয়া করে পরামর্শ দিন। আপনার কাছে আমি অত্যন্ত কৃতজ্ঞ।",False,False,True
510,16559,"হেলো! আমি সবেমাত্র একটি এমআরআই করিয়েছি এবং এর ইমপ্রেশন বা ফলাফল ব্যাখ্যা করার জন্য আমি এখনও কোনো ডাক্তারের সাথে দেখা করতে পারিনি। অনুগ্রহ করে এর অর্থ বুঝিয়ে বলুন। নিচে বিস্তারিত দেওয়া হলো। ধন্যবাদ।\n\nগ্রেড ১ স্পন্ডাইলোলিস্থেসিস, এল৫ থেকে এস১ কশেরুকা। এল৪-এল৫ লেভেলে ডান প্যারাসেন্ট্রাল ডিস্ক এবং পোস্টেরোলেটারাল অ্যানুলার ফিশার, যার ফলে ভেন্ট্রাল থিকাল স্যাক সংকুচিত হয়েছে, ডানদিকের নিউরোফোরামিনা সরু হয়ে গেছে এবং ডানদিকের ডিসেন্ডিং এল৫ নার্ভ রুট বা স্নায়ুমূলের ওপর চাপ সৃষ্টি হয়েছে। ফাইলাম টার্মিনালি লিপোমা।",False,False,True
852,34743,"হেলো, আপনার পিরিয়ড ৭ দিন দেরি হয়েছে এবং অনিরাপদ শারীরিক সম্পর্কের ইতিহাস থাকায় গর্ভবতী হওয়ার সম্ভাবনা উড়িয়ে দেওয়া যায় না। আপনার উপসর্গগুলো যেমন পেটে ব্যথা এবং বমি ভাব গর্ভাবস্থার প্রাথমিক লক্ষণ হতে পারে। আপনার যা করা উচিত:\n\n১. দ্রুত একটি প্রেগন্যান্সি টেস্ট কিট কিনে পরীক্ষা করুন। এটি সকালে ঘুম থেকে ওঠার পর প্রথম প্রস্রাব দিয়ে করলে সবচেয়ে সঠিক ফলাফল পাওয়া যায়।\n২. যদি ফলাফল পজিটিভ আসে, তবে দেরি না করে একজন গাইনোকোলজিস্ট বা স্ত্রীরোগ বিশেষজ্ঞের সাথে পরামর্শ করুন।\n৩. নিজে থেকে কোনো ওষুধ বা ঘরোয়া পদ্ধতি অবলম্বন করবেন না, কারণ এটি আপনার স্বাস্থ্যের জন্য ঝুঁকিপূর্ণ হতে পারে। ডাক্তার আপনার শারীরিক অবস্থা পরীক্ষা করে নিরাপদ এবং আইনি সমাধান বা পরবর্তী পদক্ষেপ সম্পর্কে সঠিক পরামর্শ দিতে পারবেন।\n\nদয়া করে দ্রুত একজন ডাক্তারের সাথে যোগাযোগ করুন।",False,False,True
...,...,...,...,...,...
108000,93811,"আমার মায়ের দাঁতে প্রচণ্ড ব্যথা এবং তার মুখ কিছুটা ফুলে গেছে। বাইরে প্রবল বৃষ্টি এবং হারিকেনের আশঙ্কার কারণে কোথাও যাওয়া সম্ভব হচ্ছে না। বিকেলে একজন ডেন্টিস্ট জানিয়েছিলেন যে এটি ইনফেকশন হতে পারে। অনুগ্রহ করে কিছু প্রতিকার বা পরামর্শ দিন।\n\nদাঁতের ব্যথার জন্য কিছু প্রাথমিক পরামর্শ:\n\n১. লবণ-পানি দিয়ে কুলকুচি: এক গ্লাস হালকা গরম পানিতে আধা চা চামচ লবণ মিশিয়ে দিনে কয়েকবার কুলকুচি করুন। এটি ইনফেকশন কমাতে এবং ব্যথা উপশমে সাহায্য করতে পারে।\n\n২. বরফের সেঁক: গালের যে পাশে ব্যথা বা ফোলা আছে, সেখানে বাইরে থেকে বরফের প্যাক বা ঠান্ডা কাপড় দিয়ে ১০-১৫ মিনিট ধরে সেঁক দিন। এটি ফোলা ও ব্যথা কমাতে সাহায্য করবে।\n\n৩. মাথা উঁচু করে ঘুমানো: শোয়ার সময় মাথার নিচে অতিরিক্ত বালিশ দিয়ে মাথা উঁচু করে রাখুন, এতে দাঁতের গোড়ায় রক্তচাপ কমে ব্যথা কিছুটা কম অনুভূত হতে পারে।\n\n৪. ব্যথানাশক ওষুধ: যদি সম্ভব হয়, প্যারাসিটামল বা আইবুপ্রোফেন জাতীয় ব্যথানাশক ওষুধ খেতে পারেন (যদি আগে থেকে কোনো অ্যালার্জি না থাকে)। তবে অবশ্যই ওষুধের প্যাকেটের নির্দেশিকা মেনে চলবেন।\n\n৫. শক্ত খাবার এড়িয়ে চলা: ব্যথাযুক্ত দাঁত দিয়ে কোনো কিছু চিবাবেন না এবং খুব গরম বা খুব ঠান্ডা খাবার এড়িয়ে চলুন।\n\nসতর্কতা:\nযদি তার শ্বাস নিতে কষ্ট হয়, জ্বর আসে বা ফোলা দ্রুত বাড়তে থাকে, তবে এটি জরুরি অবস্থা। হারিকেনের পরিস্থিতির মধ্যেও যদি সম্ভব হয়, তবে নিকটস্থ জরুরি সেবা বা কোনো হেল্পলাইনের সাথে যোগাযোগ করুন। পরিস্থিতি স্বাভাবিক হওয়া মাত্রই দ্রুত একজন ডেন্টিস্টের সাথে দেখা করে অ্যান্টিবায়োটিক বা প্রয়োজনীয় চিকিৎসা গ্রহণ করা জরুরি, কারণ দাঁতের ইনফেকশন অবহেলা করা বিপজ্জনক হতে পারে।",False,False,True
108297,86952,"হেলো, পায়ের জয়েন্টের কাছে এই ধরনের সমস্যা সাধারণত ঘাম এবং আর্দ্রতার কারণে ছত্রাক বা ব্যাকটেরিয়ার সংক্রমণের ফলে হয়ে থাকে। যেহেতু আপনি অন্তর্বাস পরে হস্তমৈথুন করা বন্ধ করেছেন, এটি একটি ভালো পদক্ষেপ। এই সমস্যা দূর করতে আপনি নিচের পদক্ষেপগুলো নিতে পারেন:\n\n১. আক্রান্ত স্থানটি সবসময় পরিষ্কার এবং শুকনো রাখুন। গোসলের পর নরম তোয়ালে দিয়ে জায়গাটি আলতো করে মুছে নিন।\n২. সুতির ঢিলেঢালা অন্তর্বাস পরুন যাতে বাতাস চলাচল করতে পারে।\n৩. কোনো অ্যান্টি-ফাঙ্গাল পাউডার বা ক্রিম (যেমন ক্লোট্রিমাজল) ব্যবহার করতে পারেন, তবে ব্যবহারের আগে একজন ফার্মাসিস্ট বা চিকিৎসকের পরামর্শ নেওয়া ভালো।\n৪. যদি সমস্যাটি বেশি হয় বা চুলকানি ও ব্যথা থাকে, তবে দেরি না করে একজন চর্মরোগ বিশেষজ্ঞের (Dermatologist) পরামর্শ নিন।\n\nঅন্তর্বাসের দাগের বিষয়ে চিন্তা করবেন না, সংক্রমণের চিকিৎসা করলে এবং জায়গাটি শুকনো রাখলে ধীরে ধীরে এই সমস্যা ও দাগ কমে যাবে। ব্যক্তিগত পরিচ্ছন্নতা বজায় রাখলে এটি দ্রুত সেরে উঠবে।",False,False,True
108341,37757,"আমি আমার প্রিয় স্ত্রীকে নিয়ে একটি সমস্যা নিয়ে আপনার সাথে আলোচনা করতে চেয়েছিলাম। সে পিজি মেডিকেল মাইক্রোবায়োলজির ছাত্রী এবং পড়াশোনায় বেশ ভালো। সে হোস্টেলে থাকে। আমাদের বিয়ের এক বছর হয়েছে। সে বিপিডি (বাইপোলার ডিজঅর্ডার) রোগী। সে আমাকে প্রায়ই বলত যে সে সন্ধ্যার সময় খুব ভয় পায়, অর্থাৎ সে মনে করে সন্ধ্যা শুরু হলেই রাতে তার বিছানা কাঁপবে, সে তার দরজা এবং টেবিলের কাছে কারো উপস্থিতি অনুভব করে। যখন সে বিছানায় ঘুমাতে যায়, তখন তার মনে হয় কেউ তার বিছানা নাড়াচ্ছে, সে বিছানায় লাফিয়ে ওঠে এবং তার ঘুম ভেঙে যায়। এই ভয়ের সমস্যার কারণে সে ঠিকমতো ঘুমাতে পারে না এবং ঘুমের জন্য ওষুধ নিতে হয়।\n\nআমি খুব ধৈর্য ধরে তার কথা শুনি, কিন্তু তাকে কষ্টে থাকতে দেখলে আমি বিচলিত হয়ে পড়ি। তাকে আশ্বাস দেওয়া ছাড়া আমি আর কিছুই করতে পারছি না। আমি গতকাল রাতে তার সাথে আলোচনা করেছি যে সে যখন আমার সাথে থাকে তখনো কি সে একই রকম ভয় পায় কিনা। সে বলল না। সে যখন একা থাকে তখনই কেবল এই ধরনের স্বপ্ন দেখে। আমি তাকে হোস্টেলে মানুষের সাথে মেলামেশা করতে বলেছি। সে বলল সে তা-ই করে। যখন সে ফোনে আমার সাথে কথা বলে তখন তার মাথায় এসব আসে না, কিন্তু একা হওয়ার সাথে সাথেই সে আবার একই রকম চিন্তা করতে শুরু করে।\n\nআমি এই আশায় আপনাকে লিখছি যে আপনি হয়তো কোনোভাবে আমাকে সাহায্য করতে পারবেন। দয়া করে আমাকে পরামর্শ দিন কীভাবে এই পরিস্থিতি সামলাব যাতে আমি তাকে সুখী দেখতে পাই। আমি তাকে কষ্টে দেখতে পারি না। আমি আপনার কাছে অত্যন্ত কৃতজ্ঞ থাকব।",False,False,True
108458,67725,"প্রিয় ডাক্তার, আমার বয়স ২৯ বছর, বিবাহিত এবং ৫ বছর বয়সী একটি ছেলে আছে। ২০০৮ সালের নভেম্বরে আমার প্রথম সন্তান জন্মের পর আমি কপার টি ব্যবহার করেছিলাম। আমি ২০১৩ সালের সেপ্টেম্বরে এই ইমপ্ল্যান্টটি অপসারণ করি। (আমার পিরিয়ড সবসময় নিয়মিত ছিল)। আমি ০১/১১/২০১৩ তারিখ থেকে প্রথমবারের মতো ওভরল এল (২১ দিনের) গর্ভনিরোধক ট্যাবলেট খাওয়া শুরু করি। (আমার শেষ পিরিয়ড ছিল ২৫/১০/২০১৩ থেকে ৩১/১০/২০১৩ পর্যন্ত)। এবং ২১/১১/২০১৩ তারিখে আমি ২১ দিনের কোর্সটি সম্পন্ন করি। আজ (২৬/১১/২০১৩) আমার পিরিয়ড শুরু হয়েছে। সাধারণত আমার পিরিয়ডের চক্র ছোট। এই বিষয়ে আমার দুটি প্রশ্ন ও সন্দেহ আছে:\n\n১. আমি ওভরল এল-এর পরবর্তী কোর্সটি কখন শুরু করব?\n\n২. আমি ০৯/১২/২০১৩ তারিখে আমার স্বামীর সাথে ছাড়া একটি ভ্রমণে যাচ্ছি এবং ০৩/০১/২০১৪ তারিখে ফিরে আসব। পিরিয়ডের সময় আমি শারীরিক মিলন করি না। আমার পিরিয়ড ০২/১২/২০১৩ তারিখে শেষ হবে বলে আশা করছি। (আমার পিরিয়ড সাধারণত ৭ দিন স্থায়ী হয়)। এই সময়ে কি আমার পিল খাওয়া প্রয়োজন?\n\nঅনুগ্রহ করে পরামর্শ দিন। ধন্যবাদ!",False,False,True
108816,81516,"হেলো। আমি জানি আপনি খুব কঠিন সময়ের মধ্য দিয়ে যাচ্ছেন। ২০১৩ সালের অস্ত্রোপচারের পর থেকে দীর্ঘস্থায়ী ব্যথার সাথে লড়াই করা অত্যন্ত কষ্টসাধ্য। যেহেতু ইনজেকশন বা ব্যথানাশক ওষুধে কাজ হচ্ছে না, তাই আপনার একজন বিশেষজ্ঞ চিকিৎসকের সাথে পরামর্শ করা জরুরি।\n\nআপনার এই পরিস্থিতির জন্য আপনি নিচের পদক্ষেপগুলো বিবেচনা করতে পারেন:\n\n১. পেইন ম্যানেজমেন্ট বিশেষজ্ঞ (Pain Management Specialist): সাধারণ চিকিৎসকের পরিবর্তে একজন পেইন ম্যানেজমেন্ট বিশেষজ্ঞের কাছে যান। তারা ব্যথার উৎস নির্ণয়ে উন্নত পরীক্ষা এবং মাল্টি-ডিসিপ্লিনারি চিকিৎসার পরামর্শ দিতে পারেন।\n\n২. ইন্টারভেনশনাল পেইন ক্লিনিক: মন্টগোমারি, আলাবামাতে অনেক উন্নত পেইন ক্লিনিক রয়েছে। আপনি 'UAB Medicine' বা স্থানীয় বড় হাসপাতালের পেইন ম্যানেজমেন্ট সেন্টারে যোগাযোগ করতে পারেন। তারা নার্ভ স্টিমুলেশন বা অন্যান্য আধুনিক পদ্ধতির মাধ্যমে দীর্ঘস্থায়ী ব্যথা নিয়ন্ত্রণে সাহায্য করতে পারে।\n\n৩. মানসিক স্বাস্থ্য সহায়তা: দীর্ঘস্থায়ী ব্যথা মানুষের মেজাজ এবং পারিবারিক সম্পর্কের ওপর মারাত্মক প্রভাব ফেলে। একজন সাইকোলজিস্ট বা থেরাপিস্টের সাথে কথা বলা আপনাকে এই মানসিক চাপ সামলাতে এবং পরিবারের সাথে সম্পর্ক উন্নত করতে সাহায্য করবে।\n\n৪. সাপোর্ট গ্রুপ: দীর্ঘস্থায়ী ব্যথায় আক্রান্ত রোগীদের জন্য সাপোর্ট গ্রুপে যোগ দিন। সেখানে অন্যদের অভিজ্ঞতা থেকে আপনি নতুন কোনো চিকিৎসার পথ খুঁজে পেতে পারেন।\n\n৫. জরুরি অবস্থা: যদি আপনার মনে হয় আপনি নিজেকে বা অন্য কাউকে আঘাত করতে পারেন, তবে দেরি না করে অবিলম্বে স্থানীয় জরুরি সেবা বা মেন্টাল হেলথ ক্রাইসিস হটলাইনে যোগাযোগ করুন।\n\nআপনার বর্তমান অবস্থার জন্য একজন নিউরোসার্জন বা পেইন স্পেশালিস্টের কাছে নতুন করে রেফারেল চেয়ে নিন এবং আপনার মানসিক অবস্থার কথা তাদের স্পষ্টভাবে জানান। আপনি একা নন, সঠিক চিকিৎসা এবং সহায়তার মাধ্যমে পরিস্থিতির উন্নতি সম্ভব।",False,False,True

ROWS WITH SYMBOLS / PUNCTUATION
--------------------------------

,id,input
0,45361,"হেলো, আমরা গত ৩ মাস ধরে গর্ভধারণের চেষ্টা করছি কিন্তু ফলাফল নেতিবাচক। এবার আমি ফলিকুলার মনিটরিং করিয়েছি এবং ১৭তম দিনে ওভুলেশন হয়েছে, কিন্তু তবুও আমি গর্ভবতী নই। যদিও আমার এলও-তে অনেকগুলো ছোট ফলিকল ছিল, এগুলো কি স্বাভাবিক নাকি পিসিওডি? আমি সত্যিই বিভ্রান্ত এবং বুঝতে পারছি না কী করব, আমার কি ডাক্তার পরিবর্তন করা উচিত?"
1,95550,"প্রায় এক মাস আগে আমার পিঠের ডান দিকের কাঁধের হাড়ের কাছে বৈদ্যুতিক স্রোতের মতো এক ধরনের অনুভূতি হতে শুরু করেছে। এটি বেশ বিরক্তিকর এবং আমি জানি না কীভাবে এর চিকিৎসা করব। প্রায় ১২ বছর আগে আমার ঘাড়ে সি-৬ এবং সি-৭ ফিউশন হয়েছিল। কী হচ্ছে আমার? আমার বয়স ৬০, আমি বিশেষ চাহিদাসম্পন্ন শিশুদের নিয়ে কাজ করি এবং শারীরিকভাবে সক্রিয় থাকি। প্রায় এক মাস ধরে চলা হাড়কাঁপানো ঠান্ডার সাথে কি এর কোনো সম্পর্ক থাকতে পারে? ধন্যবাদ।"
2,98599,"হেলো, আমি ২৫ বছর বয়সী অবিবাহিত মেয়ে। আমার কপাল, ঘাড় এবং হাতে কালচে দাগ হয়েছে। আগে এটি রোদে পোড়া দাগের মতো ছিল, কিন্তু আমি এর জন্য চিকিৎসা নিয়েছিলাম এবং ডাক্তার যে মলম দিয়েছিলেন তা স্টেরয়েডযুক্ত ছিল। এর ফলে সমস্যাটি আরও বেড়ে গেছে। আগে এটি খুব একটা বোঝা যেত না, কিন্তু এখন এটি দেখতে খুব খারাপ লাগে। আপনি কি দয়া করে আমাকে কিছু পরামর্শ দিতে পারেন? আমি রোদ এড়িয়ে চলি, কিন্তু কোনো সানস্ক্রিন ব্যবহার করি না কারণ এতে রাসায়নিক থাকে।"
3,84959,"হেলো, আমার বয়স ২২, উচ্চতা ৫ ফুট ৯ ইঞ্চি এবং ওজন ১৭০ পাউন্ড। আমি সারা জীবন খুব সুস্থ ছিলাম, তেমন কোনো সমস্যা হয়নি। আমার উপরের ঠোঁটের ঠিক উপরে একটি ফোলা চাকা হয়েছে যা ঠোঁটকে স্পর্শ করে আছে। চাপ না দিলে এটি ব্যথা করে না, তবে আমি এটি অনুভব করতে পারছি এবং এটি আমাকে বিরক্ত করছে। বরফ দিলে ফোলা কিছুটা কমে। এটি কোনো খোলা ক্ষত নয়, শুধু একটি চাকা যা যাচ্ছে না। এটি প্রায় ৫ দিন ধরে আছে।"
4,65169,"হেলো, আমার নানি প্রায়ই অভিযোগ করেন যে তার হৃদপিণ্ডের চারপাশে গ্যাসের সমস্যা হচ্ছে, যার ফলে তিনি মাথা ঝিমঝিম এবং মাথা ঘোরার অনুভব করেন। তার বয়স ৭৭ বছর এবং তার হার্টের অপারেশন হয়েছে ও নতুন ভালভ বসানো হয়েছে। তিনি ডাক্তারকে বিষয়টি জানালেও ডাক্তার কোনো পদক্ষেপ নিচ্ছেন না। আমি চিন্তিত কারণ এর ফলে তার মাথা ঘোরে এবং এমনিতেই তার হাঁটাচলায় ভারসাম্যহীনতা রয়েছে। এর কারণ কী হতে পারে এবং কী করলে উপকার পাওয়া যাবে, তা কি জানাতে পারবেন? ধন্যবাদ।"
...,...,...
108949,78957,"আমার ৮ বছর বয়সী ছেলে গত রাতে তার বগলে ব্যথার কথা জানিয়েছিল। সে হাত উপরে তুললে গলফ বলের আকারের একটি ফোলা অংশ দেখা যায়। সম্প্রতি তাকে একটি মৌমাছি হুল ফুটিয়েছে এবং তার সর্দি ও হালকা জ্বরও ছিল। সে খাওয়া-দাওয়া করছে, কিন্তু ক্লান্তিবোধের অভিযোগ করছে। আমার এখন কী করা উচিত?"
108950,111475,"আমার বয়স ৪০-এর বেশি এবং গত কয়েক বছর ধরে আমার চিবুকে পিগমেন্টেশনের সমস্যা রয়েছে। আমার এক বন্ধু, যে দীর্ঘদিন পিগমেন্টেশনের সমস্যায় ভুগেছিল এবং মেলাকিয়ার (Melacare) ব্যবহার করে উপকৃত হয়েছে, সে আমাকে এটি ব্যবহার করার পরামর্শ দিয়েছে। কোনো চর্মরোগ বিশেষজ্ঞের পরামর্শ ছাড়া কি আমি এটি ব্যবহার করতে পারি?"
108951,104289,"হেলো ডাক্তার, আমার মায়ের বয়স ৮২ বছর। গত পনেরো দিন ধরে তিনি তার বাম পায়ের উরু থেকে আঙুল পর্যন্ত তীব্র ব্যথা অনুভব করছেন। ৪ঠা জুলাই শুক্রবার থেকে ডাক্তার তাকে দিনে দুবার প্রিগালিন এক্স ৭৫ এবং অ্যানাফ্লান সেবনের পরামর্শ দিয়েছেন। প্রিগালিন খাওয়ার পর তিনি ঝিমুনি এবং অস্বস্তি বোধ করছেন। এটি কি ওষুধের প্রভাব? আমি এই ওষুধের পার্শ্বপ্রতিক্রিয়াগুলো জানতে চাই। এছাড়াও এই ওষুধটি কী উদ্দেশ্যে ব্যবহৃত হয় তা-ও জানতে চাই।"
108952,861,"স্যার, আক্কেল দাঁতে ক্যাভিটি থাকার কারণে কি টিনিটাস এবং শ্রবণশক্তি হ্রাস পাওয়ার কোনো সম্ভাবনা আছে? আমার বয়স ৪৮ বছর, উচ্চতা ১৬৫ সেমি এবং ওজন ৬৮ কেজি। গত ১ বছর ধরে আমি আমার বাম কানে টিনিটাসের মতো কিছু উপসর্গ অনুভব করছি এবং আমার শ্রবণশক্তি ৬০% কমে গেছে। আমার একটি আক্কেল দাঁতে (বাম নিচের চোয়াল) ক্যাভিটি আছে এবং ব্যথা করছে।"
108953,15817,"আমার পাঁচ বছর বয়সী মেয়ে তিন দিন ধরে পেটে ব্যথার অভিযোগ করছে। তার উচ্চতা ৪৪ ইঞ্চি এবং ওজন ৪০ পাউন্ড। গত বছর একটি এবং এই বছর তিনটি স্ট্যাফ সংক্রমণের ঘটনা ছাড়া সে সবসময়ই সুস্থ ছিল, যা প্রতিরোধের জন্য আমি সবরকম চেষ্টা করেছি। তিন দিন আগে স্কুল থেকে ফেরার পর সে পেটে ব্যথার কথা জানায় এবং সেই রাতে বমি করে। এরপর সে প্রচুর খাবার খায়। পরের দিনও সে খেয়েছে এবং খেলাধুলা করেছে, কিন্তু পরে আবার ব্যথা ফিরে আসে। প্রতিদিন এই একই রুটিন চলছে। আমি তাকে ডাক্তারের কাছে নিয়ে গিয়েছিলাম এবং তারা পেটের এক্স-রে করেছে, যার রিপোর্ট স্বাভাবিক এসেছে। তারা প্রস্রাব পরীক্ষা করেছে এবং কোনো সংক্রমণ পাওয়া যায়নি, তবে কিটোন পাওয়া গেছে। তাই তারা তার গ্লুকোজ পরীক্ষা করেছে এবং তা ছিল ৬৬। আগামীকাল তার আবার অ্যাপয়েন্টমেন্ট আছে। তার পেটে আবার ব্যথা করছে এবং আমি সত্যিই খুব চিন্তিত।"

SUMMARY
-------
Total rows: 108391
Leading space: 0
Trailing space: 0
Multiple spaces: 398
Symbols/punctuation: 108212

In [37]:
import re
import pandas as pd

# Work on a copy
df_check = df_clean.copy()

# Make sure input is string
df_check["input"] = df_check["input"].fillna("").astype(str)


# ============================================
# ENGLISH CHARACTERS / WORDS
# ============================================

df_check["has_english"] = df_check["input"].str.contains(
    r"[A-Za-z]",
    regex=True
)


# ============================================
# NUMBERS
# English + Bangla digits
# ============================================

df_check["has_numbers"] = df_check["input"].str.contains(
    r"[0-9০-৯]",
    regex=True
)


# ============================================
# POSSIBLE DATES
# Examples:
# 01/11/2013
# ০১/১১/২০১৩
# 2008 সালের নভেম্বরে
# ============================================

df_check["has_date"] = df_check["output"].str.contains(
    r"""
    (
        [0-9০-৯]{1,4}[-/.][0-9০-৯]{1,2}[-/.][0-9০-৯]{1,4}
        |
        [0-9০-৯]{1,4}\s*সালের
    )
    """,
    regex=True,
    flags=re.VERBOSE
)


# ============================================
# SYMBOLS / PUNCTUATION
# ============================================

df_check["has_symbols"] = df_check["input"].str.contains(
    r"""[!"#$%&'()*+,\-./:;<=>?@\[\]\\^_`{|}~]""",
    regex=True
)


# ============================================
# EXTRA SPACES
# ============================================

df_check["has_extra_spaces"] = df_check["input"].str.contains(
    r"\s{2,}",
    regex=True
)


# ============================================
# SHOW COUNTS
# ============================================

print("English present :", df_check["has_english"].sum())
print("Numbers present :", df_check["has_numbers"].sum())
print("Dates present   :", df_check["has_date"].sum())
print("Symbols present :", df_check["has_symbols"].sum())
print("Extra spaces    :", df_check["has_extra_spaces"].sum())

/tmp/ipykernel_189/328171474.py:40: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_check["has_date"] = df_check["output"].str.contains(

English present : 22078
Numbers present : 77171
Dates present   : 242
Symbols present : 106955
Extra spaces    : 398

In [38]:
#test df
import re
import pandas as pd

# Work on a copy
df_check_test = test.copy()

# Make sure input is string
df_check_test["input"] = df_check_test["input"].fillna("").astype(str)


# ============================================
# ENGLISH CHARACTERS / WORDS
# ============================================

df_check_test["has_english"] = df_check_test["input"].str.contains(
    r"[A-Za-z]",
    regex=True
)


# ============================================
# NUMBERS
# English + Bangla digits
# ============================================

df_check_test["has_numbers"] = df_check_test["input"].str.contains(
    r"[0-9০-৯]",
    regex=True
)


# ============================================
# POSSIBLE DATES
# Examples:
# 01/11/2013
# ০১/১১/২০১৩
# 2008 সালের নভেম্বরে
# ============================================

df_check_test["has_date"] = df_check_test["input"].str.contains(
    r"""
    (
        [0-9০-৯]{1,4}[-/.][0-9০-৯]{1,2}[-/.][0-9০-৯]{1,4}
        |
        [0-9০-৯]{1,4}\s*সালের
    )
    """,
    regex=True,
    flags=re.VERBOSE
)


# ============================================
# SYMBOLS / PUNCTUATION
# ============================================

df_check_test["has_symbols"] = df_check_test["input"].str.contains(
    r"""[!"#$%&'()*+,\-./:;<=>?@\[\]\\^_`{|}~]""",
    regex=True
)


# ============================================
# EXTRA SPACES
# ============================================

df_check_test["has_extra_spaces"] = df_check_test["input"].str.contains(
    r"\s{2,}",
    regex=True
)


# ============================================
# SHOW COUNTS
# ============================================

print("English present :", df_check_test["has_english"].sum())
print("Numbers present :", df_check_test["has_numbers"].sum())
print("Dates present   :", df_check_test["has_date"].sum())
print("Symbols present :", df_check_test["has_symbols"].sum())
print("Extra spaces    :", df_check_test["has_extra_spaces"].sum())

English present : 215
Numbers present : 713
Dates present   : 23
Symbols present : 986
Extra spaces    : 5

/tmp/ipykernel_189/2976042953.py:41: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_check_test["has_date"] = df_check_test["input"].str.contains(

TEST DF

In [39]:
# ============================================
# CHECK EXTRA SPACES / SYMBOLS / PUNCTUATION
# ============================================

import re
import pandas as pd

check_test = test.copy()

# Make sure input is string
check_test["input"] = check_test["input"].fillna("").astype(str)


# ============================================
# 1. LEADING / TRAILING SPACES
# ============================================

check_test["leading_space"] = check_test["input"].str.match(r"^\s")
check_test["trailing_space"] = check_test["input"].str.match(r"\s$")

print("Leading spaces:", check_test["leading_space"].sum())
print("Trailing spaces:", check_test["trailing_space"].sum())


# ============================================
# 2. MULTIPLE / EXTRA SPACES
# ============================================

check_test["multiple_spaces"] = check_test["input"].str.contains(
    r"\s{2,}",
    regex=True
)

print("Multiple consecutive spaces:", check_test["multiple_spaces"].sum())


# ============================================
# 3. PUNCTUATION / SYMBOLS
# ============================================

# Anything that is NOT:
# Bengali characters, English letters, numbers, or whitespace
check_test["has_symbols"] = check_test["input"].str.contains(
    "[^\u0980-\u09FFa-zA-Z0-9\s]",
    regex=True
)

print("Rows containing symbols/punctuation:", check_test["has_symbols"].sum())


# ============================================
# 4. SHOW ROWS WITH EXTRA SPACES
# ============================================

space_issues = check_test[
    check_test["leading_space"]
    | check_test["trailing_space"]
    | check_test["multiple_spaces"]
]

print("\nROWS WITH SPACE ISSUES")
print("----------------------")
display(
    space_issues[
        ["id", "input", "leading_space",
         "trailing_space", "multiple_spaces"]
    ]
)


# ============================================
# 5. SHOW ROWS WITH SYMBOLS / PUNCTUATION
# ============================================

symbol_issues = check_test[check_test["has_symbols"]]

print("\nROWS WITH SYMBOLS / PUNCTUATION")
print("--------------------------------")
display(
    symbol_issues[
        ["id", "input"]
    ]
)


# ============================================
# 6. SUMMARY
# ============================================

print("\nSUMMARY")
print("-------")
print("Total rows:", len(check_test))
print("Leading space:", check_test["leading_space"].sum())
print("Trailing space:", check_test["trailing_space"].sum())
print("Multiple spaces:", check_test["multiple_spaces"].sum())
print("Symbols/punctuation:", check_test["has_symbols"].sum())

Leading spaces: 0
Trailing spaces: 0
Multiple consecutive spaces: 5
Rows containing symbols/punctuation: 1000

ROWS WITH SPACE ISSUES
----------------------

<>:44: SyntaxWarning: invalid escape sequence '\s'
<>:44: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_189/401862442.py:44: SyntaxWarning: invalid escape sequence '\s'
  "[^\u0980-\u09FFa-zA-Z0-9\s]",

,id,input,leading_space,trailing_space,multiple_spaces
7,105223,"এক বছর আগে আমি এইচবিএসএজি এইচবিভি (পজিটিভ) এবং অ্যান্টি-এইচবিই পজিটিভ হিসেবে শনাক্ত হয়েছিলাম, কিন্তু পরপর তিনটি ডিএনএ পরীক্ষায় এটি এখন নন-রিঅ্যাক্টিভ এসেছে। আমি কি চিরতরে নিরাপদ নাকি আমার এখনও ওষুধের প্রয়োজন আছে? আমি কি এইচবিভি-এর টিকা নিতে পারি?\n\nশুভেচ্ছান্তে,\nসফর মোহাম্মদ খান\nমুম্বাই",False,False,True
332,23110,"প্রিয় ডাক্তার, আমার ছেলের বয়স ২১ বছর, তাকে অ্যাকিউট সাইকোসিসের জন্য চিকিৎসা দেওয়া হচ্ছে। সে ইঞ্জিনিয়ারিংয়ের শেষ বর্ষের ছাত্র। এক মাস ধরে তার মেজাজ খুব চড়া ছিল, এরপর ৩/৪ দিন ধরে তার স্নায়বিক বিপর্যয় ঘটে, যার লক্ষণ ছিল অসংলগ্ন ও অপ্রাসঙ্গিক কথাবার্তা। এরপরই মনোরোগ বিশেষজ্ঞের অধীনে তার ওষুধ শুরু হয়। আমাদের মনে হয়, বারবার একাডেমিক লক্ষ্য অর্জনে ব্যর্থ হওয়ার কারণেই এসব শুরু হয়েছে। আজ সে নিজেকে অসহায় মনে করছে এবং ভবিষ্যৎ নিয়ে চিন্তিত, যা তার উদ্বেগ বাড়িয়ে দিচ্ছে।\n\nক্যাপ জিপসিডন ২০ মিগ্রা ০-০-১\nট্যাব রিসডোন প্লাস ০-০-১/২\nট্যাব লোনাজেপ ০-১-০\nট্যাব ম্যাকোরেট সিআর ৩০০ মিগ্রা ০-১-১\nট্যাব প্যাসিটোন ২ মিগ্রা ১-০-০\n\nআমরা এখনও তার রোগ নির্ণয় সম্পর্কে নিশ্চিত নই। দয়া করে পরামর্শ দিন যে মেডিটেশন, সেলফ বা গাইডেড হিপনোসিস বা ব্যায়ামের মতো বিকল্প থেরাপিগুলো পরিপূরক হিসেবে কতটা কার্যকর হতে পারে। এছাড়া অন্য কোনো থেরাপি যা তার জন্য সহায়ক হতে পারে, তা-ও জানান। সে যেন স্বাভাবিক জীবনযাপন করতে পারে, তার জন্য আমরা যেকোনো কিছু করতে প্রস্তুত। আপনার মূল্যবান পরামর্শের অপেক্ষায় রইলাম।",False,False,True
591,67681,"হেলো স্যার। আমি আমার মুখের বাদামী দাগ দূর করার জন্য ডেপিহোয়াইট ক্রিম ব্যবহার করছি এবং অনেক মাস ধরে এটি ব্যবহার করছি। শুরুতে ব্যবহারের সময় আমি সামান্য উন্নতি দেখেছিলাম। কিন্তু এখন আর কোনো উন্নতি দেখতে পাচ্ছি না। আমি নাইট শিফটে কাজ করি এবং কম্পিউটারের সামনে কাজ করতে হয়। আমি জানতে চাই, আমি কি সারা রাত আমার মুখের আক্রান্ত স্থানে এই ক্রিমটি লাগিয়ে রাখতে পারি এবং কম্পিউটারে কাজ করতে পারি? কম্পিউটার কি এমন কোনো ইউভি রশ্মি তৈরি করে যা আমার ত্বকের ক্ষতি করতে পারে, নাকি উন্নতি না দেখার কারণে আমার এটি ব্যবহার বন্ধ করে দেওয়া উচিত? অনুগ্রহ করে পরামর্শ দিন।\n\nশুভেচ্ছান্তে,\nদীনেশ",False,False,True
807,5652,"আমার ভাই (বয়স ২০) ২০১০ সালের জুলাই মাসে আর জি কর হাসপাতালে ভর্তি হয়েছিল এবং চিকিৎসকের পরামর্শ অনুযায়ী ৭ মাসের ডটস কোর্স সম্পন্ন করেছিল। কিন্তু এখন এক্স-রে রিপোর্টে পুনরায় তার বুকে জল জমার বিষয়টি নিশ্চিত হওয়া গেছে। অনুগ্রহ করে পরামর্শ দিন এখন কী করা উচিত এবং কলকাতা, পশ্চিমবঙ্গে যক্ষ্মা রোগের চিকিৎসার জন্য অন্য কোনো সরকারি বিশেষায়িত হাসপাতাল আছে কি না।\n\nশুভেচ্ছান্তে,\nরাজু দাস",False,False,True
812,46139,"আমাদের ছেলে, গ্রেগরি হুইটকম্ব, প্রায় ১৫ বছর আগে সিজোঅ্যাফেক্টিভ ডিসঅর্ডারে আক্রান্ত বলে নির্ণীত হয়। আল্টা বেটস হাসপাতালের মানসিক বিভাগে ভর্তি হওয়ার পর সে ওকল্যান্ড, ক্যালিফোর্নিয়ার রয়্যাল কলোনিতে বেশ কয়েক বছর কাটিয়েছে। তাকে সাহায্য করার জন্য আমরা ফ্লোরিডা থেকে লিংকন, ক্যালিফোর্নিয়ার সান সিটিতে চলে আসি। রয়্যাল কলোনিতে থাকার সময় সে বহু বছর ধরে ওষুধ খেয়েছে এবং তার অবস্থার অনেক উন্নতি হয়েছিল। সে একা থাকতে চেয়েছিল, যা সেই সময়ে ঠিকই মনে হয়েছিল। কিন্তু অল্প সময়ের মধ্যেই সে ওষুধ খাওয়া বন্ধ করে দেয়। এরপর তার স্বাস্থ্যের অবনতি ঘটে, তার মধ্যে বিভ্রান্তি বেড়ে যায় এবং সে ফেসবুকে অগ্রহণযোগ্য সব লেখালেখি শুরু করে। বেশ কয়েকবার তাকে অল্প সময়ের জন্য মানসিক হাসপাতালে ভর্তি করা হয়েছিল। সে ওষুধ খেতে অস্বীকার করত এবং এরপর তাকে হাসপাতাল থেকে ছেড়ে দেওয়া হতো। তার আচরণ আরও খারাপ হতে থাকে এবং সে বেশ কয়েকবার রাস্তায় রাত কাটিয়েছে। অতি সম্প্রতি, সে ভ্যালেজো, ক্যালিফোর্নিয়ার একটি মানসিক হাসপাতালে ছিল। ডাক্তাররা তাকে ওষুধ দিয়েছিলেন, যার জন্য আমরা কৃতজ্ঞ। তাকে এমন একটি বাড়িতে রাখা হয়েছিল যেখানে কয়েকজন বোর্ডার থাকে, কিন্তু সেখানেও সে আবার ওষুধ খাওয়া বন্ধ করে দেয়। ফেসবুকে তার লেখাগুলো অ্যাশল্যান্ড, ওরেগনের তার ভাই (ডুয়েন হুইটকম্ব) এবং অন্যদের জন্য অবমাননাকর ছিল। সে প্রায় ১২ বছর ধরে যে চার্চে যেত, সেখান থেকে তার বিরুদ্ধে একটি রেস্ট্রেনিং অর্ডার জারি করা হয়েছে। এই সমস্যাগুলোর কারণে পারিবারিক সম্পর্ক অনেক খারাপ হয়ে গেছে। সে হাজার হাজার ডলার অযথা খরচ করেছে এবং এখনও ওষুধ বা ডাক্তারের সাহায্য নিতে অস্বীকার করছে কারণ সে মনে করে সে সুস্থ। আমরা মনে করি তার চিকিৎসা সহায়তা প্রয়োজন, কিন্তু আমাদের বলা হয়েছে যে প্রয়োজনীয় ওষুধ ও থেরাপির জন্য তাকে নিজেই ভর্তি হতে হবে। গ্রেগ আমাদের কথা শোনে না, তাই এই পরিস্থিতিতে কীভাবে সাহায্য পাওয়া যায় তা দয়া করে আমাদের জানান।\n\nবিনীত,\nম্যারিয়ন এবং আর্নেস্ট হুইটকম্ব এবং ডুয়েন ডব্লিউ. ও লরেটা জ্যাকবস (ভাই ও বোন)\n১১৮৬ হথর্ন লেন, লিংকন, সিএ ০০০\nফোন: ৯১৬-৫৪৩-৫৩৯৯\n(YYYY@YYYY)\n\nপুনশ্চ: আমরা, তার বাবা-মা, এখন আশির কোঠায় এবং আমাদের নিজেদের স্বাস্থ্য সমস্যার কারণে তাকে আমাদের বাড়িতে রাখা বা তার যত্ন নেওয়া সম্ভব নয়।\nম্যারিয়ন হুইটকম্ব",False,False,True

ROWS WITH SYMBOLS / PUNCTUATION
--------------------------------

,id,input
0,34654,"আমার লাইপেজ লেভেল ১৫৮, যা বেশি। অ্যামাইলেজ লেভেল ৮২, যা স্বাভাবিক। এর কারণ কী হতে পারে? আমার বর্তমান ডাক্তার এবং আগের প্রাইমারি কেয়ার ডাক্তার কেউই এ নিয়ে চিন্তিত নন। অন্তত ১১ বছর ধরে এমনটাই চলছে। আমার গ্লুটেন এবং গমের প্রতি সংবেদনশীলতা আছে। এর সাথে কি কোনো সম্পর্ক থাকতে পারে? আমার পেটে কোনো ব্যথা নেই, শুধু গম, গ্লুটেন এবং কিছু দুগ্ধজাত খাবারের প্রতি সংবেদনশীলতা আছে। অনেক ধন্যবাদ! ক্যারল অ্যান ট্রাইফিলিটি।"
1,3116,"তিন সপ্তাহ আগে আমার দাঁতে খুব ব্যথা ছিল, ৮ দিন ধরে ৫০০ মিলিগ্রামের অ্যামোক্সিসিলিন ক্যাপসুল খেয়েছিলাম, এখন তিন দিন ধরে আমার মুখে খুব বাজে স্বাদ লাগছে। রাতে একই সময়ে প্রায় ২০ মিনিটের জন্য আমার শ্বাসকষ্ট হয় এবং এখন দিন যত যাচ্ছে আমার বমি বমি ভাব বাড়ছে। আমার কি চিন্তিত হওয়া উচিত?"
2,59478,"আমার স্বামীর বয়স ৫৬ বছর, তিনি খুব একটা মিশুক নন। তিনি সবসময় আমার চরিত্রের ওপর সন্দেহ করেন। তিনি আমাকে কখনোই একা বাইরে যেতে দেন না এবং বাড়িতে কোনো পুরুষ কর্মচারী রাখতে দেন না। তিনি সবসময় অন্যদের কাছে বলেন যে তিনি তার স্ত্রীকে নিয়ে বিরক্ত। এমনকি তিনি আমার প্রতিবেশী, তার নিজের ভাই, এমনকি প্রতিবেশী শিশুদের নিয়েও সন্দেহ করেন। অথচ আমার পরিবারের সবাই জানে যে এসবের কোনো ভিত্তি নেই। আমার সন্দেহ হচ্ছে তার কোনো মানসিক সমস্যা আছে। তিনি সুপ্রিম কোর্ট অফ ইন্ডিয়ার একজন অত্যন্ত সফল এবং ধনী আইনজীবী। দয়া করে সাহায্য করুন।"
3,56450,"হেলো, আমার বয়স ৩৮ বছর। আমার বাম পায়ে, একই দিকের উরুতে, নিতম্বে এবং কোমরের নিচের অংশে ব্যথা আছে। আমি অনেক ডাক্তার দেখিয়েছি, তারা ব্যথার জন্য আমাকে অক্সিকন্টিন ১০ মিগ্রা দিয়েছেন। ৪ থেকে ৫ বার এমআরআই করা হয়েছে, কিন্তু কিছু ধরা পড়েনি। এখন আমার ত্বকে মাঝে মাঝে খুব চুলকানি হয় এবং চুলকানোর পর র‍্যাশ বের হয়। দয়া করে সাহায্য করুন, আমার এখন কী করা উচিত?"
4,86380,"গত মঙ্গলবার আমি ফ্লু শট এবং টিবি পরীক্ষা করিয়েছিলাম, শুক্রবার থেকে আমার জিহ্বায় একটি অদ্ভুত অনুভূতি লক্ষ্য করছি। এটি অনেকটা অসাড়, ঝিনঝিন না করা এক ধরনের অনুভূতি এবং জিহ্বার বাম দিকে এটি বেশি বোঝা যাচ্ছে। এছাড়া, এখন আমার ঠোঁটের বাম দিকেও এই অনুভূতি হচ্ছে। আমার বয়স ৩৮ বছর এবং আমার অন্য কোনো লক্ষণ বা উপসর্গ নেই। এটি কি কোনো ইনজেকশনের পার্শ্বপ্রতিক্রিয়া হতে পারে? টিবি পরীক্ষার জায়গাটি লাল হয়ে ফুলে গিয়েছিল। আমার প্রথম টিবি পরীক্ষাটি নেগেটিভ ছিল (১০ বছরেরও বেশি আগে), দ্বিতীয়টি পজিটিভ, তৃতীয়টি নেগেটিভ এবং এই সাম্প্রতিক পরীক্ষাটি পজিটিভ এসেছে। আমি পড়েছি যে নির্দিষ্ট প্রস্তুতকারকের ওষুধের প্রতি অ্যালার্জির কারণে দ্বিতীয়বার এটি পজিটিভ হতে পারে। ধন্যবাদ।"
...,...,...
995,72254,"হেলো, আমার পিত্তথলিতে পাথর আছে এবং একটি পিত্তনালীতে আটকে আছে। ১০-১৪ দিন ধরে আমার মলত্যাগ হয়নি, আমি হাসপাতালে ছিলাম এবং পিত্তনালী থেকে পাথরটি অপসারণের জন্য আমাকে আবার সেখানে যেতে হবে। কিন্তু গত ২ দিন ধরে আমার কোনো ব্যথা নেই এবং ৩ বার মলত্যাগ হয়েছে, এটি কি নিজে থেকেই বেরিয়ে গেছে?"
996,98077,প্রায় এক সপ্তাহ আগে একটি গাড়ি দুর্ঘটনার কারণে আমার মস্তিষ্কের সিটি স্ক্যান করা হয়েছিল। স্ক্যানে দেখা গেছে যে আমার মস্তিষ্কে একটি বায়ুর পকেট (এয়ার পকেট) রয়েছে। আমার প্রাথমিক চিকিৎসক বায়ুর পকেটে কোনো পরিবর্তন হয়েছে কিনা তা দেখার জন্য প্রায় ২ সপ্তাহ পর দ্বিতীয় একটি সিটি স্ক্যান করার নির্দেশ দিয়েছেন। বায়ুর পকেট হওয়ার সাধারণ কারণগুলো কী এবং এটি কি গুরুতর কোনো বিষয়?
997,96905,"গত দুই বছর ধরে আমার কব্জি ও হাতে মাঝে মাঝে ব্যথা হচ্ছে। এই মাসে ব্যথাটা মূলত আমার হাতে এবং মধ্যমার সাথে যুক্ত মেটাকার্পাল হাড়টি অন্যদের চেয়ে বেশি উঁচু হয়ে আছে, আর যেখানে সেই মেটাকার্পাল ও কব্জি যুক্ত হয়েছে সেখানেই সবচেয়ে বেশি ব্যথা। আমি যখন আমার কব্জি সামনের দিকে বাঁকানোর চেষ্টা করি, তখন পারি না এবং মনে হয় যেন কব্জিটি ভেঙে যাবে। যখনই ব্যথা হয়, আমি আমার মাকে ডাক্তার দেখানোর জন্য নিয়ে যেতে বলি, কিন্তু তিনি রাজি হন না। ১৫ই আগস্ট আমার একটি চেকআপ আছে, কিন্তু ততদিনে ৯০% সম্ভাবনা আছে যে ব্যথা চলে যাবে এবং এটি কখন আবার ফিরে আসবে তা আমি জানি না। মাঝে মাঝে ব্যথা অন্য সময়ের চেয়ে বেশি হয়।"
998,107470,"স্ট্রোকের কারণে আমার স্পাস্টিসিটির (পেশীর আড়ষ্টতা) মারাত্মক সমস্যা রয়েছে। ব্যাক্লোফেন আমার জন্য উপযুক্ত ছিল না। আমার রক্তচাপ নিয়ন্ত্রণ করা খুব কঠিন হয়ে পড়েছে। অনেক ওষুধ ট্রায়াল দেওয়ার পর, এখন আমি সকালে ৮০ মিগ্রা এডারবি, রাতে ২.৫ মিগ্রা অ্যামলোডিপাইন এবং সিস্টোলিক ১৫০-এর উপরে বা ডায়াস্টোলিক ১০০-এর উপরে গেলে ০.১ মিগ্রা ক্লোনিডিন নিচ্ছি। ক্লোনিডিন সবসময়ই রক্তচাপ কমাতে সফল হয়েছে। আমাকে কারণ না জানিয়েই আমার ডাক্তার এটি ঘনঘন নিতে নিষেধ করেছেন, শুধুমাত্র যখন রক্তচাপ নিয়ন্ত্রণ করতে পারি না তখনই নিতে বলেছেন। ক্লোনিডিনে আমার কোনো পার্শ্বপ্রতিক্রিয়া হয়নি। আমি পড়েছি যে ক্লোনিডিন স্পাস্টিসিটি কমাতেও ব্যবহৃত হয়। আমি কি এই ওষুধটি নিরাপদে ব্যবহার করতে পারি এবং আমার ডাক্তারকে আমাকে ক্লোনিডিনে স্থানান্তর করতে বলতে পারি?"
999,82760,হেলো ডাক্তার। আমার ৪ বছর বয়সী একটি সন্তান আছে। সম্প্রতি আমার একটোপিক প্রেগন্যান্সি হয়েছিল এবং ল্যাপারোস্কোপি করা হয়েছে। এখন আমি আবার গর্ভবতী হতে চাই। ৩ মাস ধরে ওভাসেট এবং প্রজেস্টেরন ট্যাবলেট খাচ্ছি কিন্তু গর্ভবতী হতে পারছি না। উল্টো প্রতি মাসে আমার ওজন ৩ কেজি করে বাড়ছে। আপনি কি দয়া করে কোনো পরামর্শ দেবেন? ধন্যবাদ।

SUMMARY
-------
Total rows: 1000
Leading space: 0
Trailing space: 0
Multiple spaces: 5
Symbols/punctuation: 1000

In [40]:
import re

# df_clean = df_clean.copy()

# Make sure input is string
df_clean["input"] = df_clean["input"].fillna("").astype(str)

# Replace newlines/tabs/multiple spaces with ONE space
df_clean["input"] = (
    df_clean["input"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

print("Shape after whitespace cleaning:", df_clean.shape)

Shape after whitespace cleaning: (108391, 5)

In [41]:
print("Rows:", len(df_clean))
print("Columns:", df_clean.shape[1])

# Check remaining extra whitespace
remaining_extra_spaces = df_clean["output"].str.contains(
    r"\s{2,}",
    regex=True
).sum()

print("Remaining extra spaces:", remaining_extra_spaces)

Rows: 108391
Columns: 5
Remaining extra spaces: 1233

In [42]:
df_clean.head()

,id,input,output,input_length,input_len
0,45361,"হেলো, আমরা গত ৩ মাস ধরে গর্ভধারণের চেষ্টা করছি কিন্তু ফলাফল নেতিবাচক। এবার আমি ফলিকুলার মনিটরিং করিয়েছি এবং ১৭তম দিনে ওভুলেশন হয়েছে, কিন্তু তবুও আমি গর্ভবতী নই। যদিও আমার এলও-তে অনেকগুলো ছোট ফলিকল ছিল, এগুলো কি স্বাভাবিক নাকি পিসিওডি? আমি সত্যিই বিভ্রান্ত এবং বুঝতে পারছি না কী করব, আমার কি ডাক্তার পরিবর্তন করা উচিত?","হেলো, পিসিওডি (PCOD) হলো এমন একটি উপসর্গ যা অনিয়মিত বা অনুপস্থিত পিরিয়ড, বন্ধ্যাত্ব, স্থূলতা, অবাঞ্ছিত লোম বৃদ্ধি, ব্রণ, কিছু ক্ষেত্রে ইনসুলিন রেজিস্ট্যান্স, এলএইচ/এফএসএইচ (LH/FSH) অনুপাত উল্টে যাওয়া সহ অস্বাভাবিক হরমোনের প্রোফাইল, আরএইচইএএস (RHEAS) লেভেল বৃদ্ধি, কিছু ক্ষেত্রে অস্বাভাবিক জিটিটি (GTT), কখনও কখনও উচ্চ প্রোল্যাক্টিন এবং অস্বাভাবিক থাইরয়েড প্রোফাইলের সাথে যুক্ত থাকে। এতে ডিম্বাশয়ে একাধিক ফলিকল দেখা যায় কারণ অনেকগুলো ফলিকল একই সময়ে তৈরি হলেও সেগুলো পরিপক্ক হয় না। রোগ নির্ণয়ের জন্য আপনাকে সম্পূর্ণ পরীক্ষা-নিরীক্ষা করাতে হবে। ওভুলেশন বা ডিম্বস্ফোটন সম্ভব হলেও হরমোনের ভারসাম্যহীনতা, টিউব সংক্রান্ত সমস্যা বা পুরুষজনিত কারণের মতো অনেকগুলো বিষয়ের কারণে গর্ভধারণ নাও হতে পারে। আপনার একজন অভিজ্ঞ ইনফার্টিলিটি বিশেষজ্ঞের পরামর্শ নেওয়া উচিত। নিজের যত্ন নেবেন।",317,317
1,95550,"প্রায় এক মাস আগে আমার পিঠের ডান দিকের কাঁধের হাড়ের কাছে বৈদ্যুতিক স্রোতের মতো এক ধরনের অনুভূতি হতে শুরু করেছে। এটি বেশ বিরক্তিকর এবং আমি জানি না কীভাবে এর চিকিৎসা করব। প্রায় ১২ বছর আগে আমার ঘাড়ে সি-৬ এবং সি-৭ ফিউশন হয়েছিল। কী হচ্ছে আমার? আমার বয়স ৬০, আমি বিশেষ চাহিদাসম্পন্ন শিশুদের নিয়ে কাজ করি এবং শারীরিকভাবে সক্রিয় থাকি। প্রায় এক মাস ধরে চলা হাড়কাঁপানো ঠান্ডার সাথে কি এর কোনো সম্পর্ক থাকতে পারে? ধন্যবাদ।","হেলো, প্রথমে আমাকে আপনাকে ব্যাখ্যা করতে দিন যে আপনার মতো একটি নির্দিষ্ট মেডিকেল লক্ষণের বিভিন্ন কারণ থাকতে পারে। পিঠে ব্যথা এবং বিদ্যুৎ প্রবাহের মতো অনুভূতি সার্ভিকাল স্পাইনাল কর্ডের স্পনডাইলোসিস বা অন্যান্য কারণে (যেমন কোনো টিউমার, অবক্ষয়, মেরুদণ্ডের সমস্যা) হতে পারে। বার্ধক্যে এটি স্পনডাইলোসিসের কারণে হতে পারে। সঠিক স্নায়বিক সমস্যা নির্ণয়ের জন্য আপনার একটি বিস্তারিত স্নায়বিক পরীক্ষা প্রয়োজন। বিদ্যুৎ প্রবাহের মতো অনুভূতির উপস্থিতি উদ্বেগের বিষয়, কারণ এটি নির্দেশ করে যে মেরুদণ্ডের কোনো একটি অংশ সংকুচিত হচ্ছে। তাই, জরুরি ভিত্তিতে একজন স্নায়ুরোগ বিশেষজ্ঞের মূল্যায়ন প্রয়োজন এবং পরবর্তীতে পুনরায় ইমেজিং ও নার্ভ কন্ডাকশন স্টাডি (প্রাথমিক মূল্যায়নের ওপর ভিত্তি করে এটি ঐচ্ছিক হতে পারে) করার প্রয়োজন হতে পারে। আপনার চিকিৎসা মূলত কারণের ওপর নির্ভর করবে। আশা করি এই ব্যাখ্যাটি আপনাকে সাহায্য করবে। শুভকামনা।",409,409
2,98599,"হেলো, আমি ২৫ বছর বয়সী অবিবাহিত মেয়ে। আমার কপাল, ঘাড় এবং হাতে কালচে দাগ হয়েছে। আগে এটি রোদে পোড়া দাগের মতো ছিল, কিন্তু আমি এর জন্য চিকিৎসা নিয়েছিলাম এবং ডাক্তার যে মলম দিয়েছিলেন তা স্টেরয়েডযুক্ত ছিল। এর ফলে সমস্যাটি আরও বেড়ে গেছে। আগে এটি খুব একটা বোঝা যেত না, কিন্তু এখন এটি দেখতে খুব খারাপ লাগে। আপনি কি দয়া করে আমাকে কিছু পরামর্শ দিতে পারেন? আমি রোদ এড়িয়ে চলি, কিন্তু কোনো সানস্ক্রিন ব্যবহার করি না কারণ এতে রাসায়নিক থাকে।","হেলো কবিতা, লেখার জন্য ধন্যবাদ। স্কিন লাইটেনিং ক্রিমে ২% এইচওয়াই নাসেনিয়া ডক থাকে। এই উপাদানগুলো ত্বকে স্থায়ী পিগমেন্টেশন ঘটাতে পারে যার ফলে সাদা দাগ হতে পারে। এটি দীর্ঘ সময় ব্যবহার করা উচিত নয়। আমার পরামর্শ হলো - স্টেরয়েডযুক্ত ক্রিম ব্যবহার বন্ধ করুন। দিনের বেলা ভালো সানস্ক্রিন ব্যবহার করুন। আপনি রাতে কালো দাগের ওপর ক্লাইম্যাক্স ক্রিম লাগাতে পারেন, এটি নিরাপদ এবং কার্যকর। গায়ের রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। খাদ্যতালিকায় প্রচুর ভিটামিন সি রাখুন। রোদে যাওয়া এড়িয়ে চলুন। রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। ভবিষ্যতে যেকোনো এইচকিউ (HQ) এবং স্টেরয়েডযুক্ত ক্রিম এড়িয়ে চলুন। আশা করি এটি সাহায্য করবে। ফলো-আপের জন্য আমি উপলব্ধ থাকব। শুভেচ্ছা।",424,424
3,84959,"হেলো, আমার বয়স ২২, উচ্চতা ৫ ফুট ৯ ইঞ্চি এবং ওজন ১৭০ পাউন্ড। আমি সারা জীবন খুব সুস্থ ছিলাম, তেমন কোনো সমস্যা হয়নি। আমার উপরের ঠোঁটের ঠিক উপরে একটি ফোলা চাকা হয়েছে যা ঠোঁটকে স্পর্শ করে আছে। চাপ না দিলে এটি ব্যথা করে না, তবে আমি এটি অনুভব করতে পারছি এবং এটি আমাকে বিরক্ত করছে। বরফ দিলে ফোলা কিছুটা কমে। এটি কোনো খোলা ক্ষত নয়, শুধু একটি চাকা যা যাচ্ছে না। এটি প্রায় ৫ দিন ধরে আছে।","হেলো প্রিয়, নাসেনিয়া ডকে আপনাকে স্বাগতম। আপনার উদ্বেগটি বুঝতে পারছি। আপনার প্রশ্ন অনুযায়ী, উপরের ঠোঁটের উপরে ফোলা অংশটি মূলত ঠোঁট কামড়ানোর কারণে হয়ে থাকে। অসাবধানতাবশত নিচের চোয়ালের দাঁত উপরের ঠোঁটে আঘাত করলে সেই জায়গায় অতিরিক্ত কোলাজেন ফাইবার জমা হয়ে ফোলাভাব সৃষ্টি হয়। এটি হারপিস সিমপ্লেক্স ভাইরাস সংক্রমণের কারণেও হতে পারে, যা ওই এলাকায় কোল্ড সোর বা ঘা সৃষ্টি করতে পারে। যদি আপনি অতিরিক্ত সূর্যের আলোতে থাকেন, তবে এই ফোসকা তার কারণেও হতে পারে। এটি নিয়ে আতঙ্কিত হওয়ার কিছু নেই। বরফের টুকরো নিয়ে এই জায়গায় ১০-১২ মিনিট বিরতি দিয়ে চেপে ধরুন। জায়গাটি পরিষ্কার রাখুন। নাসেনিয়া ডকের সাথেই থাকুন।",376,376
4,65169,"হেলো, আমার নানি প্রায়ই অভিযোগ করেন যে তার হৃদপিণ্ডের চারপাশে গ্যাসের সমস্যা হচ্ছে, যার ফলে তিনি মাথা ঝিমঝিম এবং মাথা ঘোরার অনুভব করেন। তার বয়স ৭৭ বছর এবং তার হার্টের অপারেশন হয়েছে ও নতুন ভালভ বসানো হয়েছে। তিনি ডাক্তারকে বিষয়টি জানালেও ডাক্তার কোনো পদক্ষেপ নিচ্ছেন না। আমি চিন্তিত কারণ এর ফলে তার মাথা ঘোরে এবং এমনিতেই তার হাঁটাচলায় ভারসাম্যহীনতা রয়েছে। এর কারণ কী হতে পারে এবং কী করলে উপকার পাওয়া যাবে, তা কি জানাতে পারবেন? ধন্যবাদ।","হেলো, আমি আপনার প্রশ্নটি মনোযোগ সহকারে পড়েছি এবং ব্যাখ্যা করতে চাই যে তার হৃদযন্ত্রের কার্যকারিতা মূল্যায়ন করা এবং সম্ভাব্য হার্ট ফেইলিওর যা এই ক্লিনিকাল পরিস্থিতির অনুকরণ করতে পারে, তা বাদ দেওয়া প্রয়োজন। গ্যাস্ট্রোইসোফেজিয়াল রিফ্লাক্সও এই পরিস্থিতির অনুকরণ করতে পারে, যদিও মাথা ঘোরা এই রোগের সাধারণ লক্ষণ নয়। এই পর্যায়ে, আমি হার্ট ফেইলিওর আছে কিনা তা তদন্ত করার জন্য একটি কার্ডিয়াক আল্ট্রাসাউন্ড এবং এনটি-প্রো বিএনপি (NT-pro BNP) পরীক্ষা করার পরামর্শ দেব। বিবেচনা করার মতো অন্যান্য পরীক্ষাগুলো হলো",432,432

In [43]:
# ============================================
# CHECK UNUSUAL CONTENT IN INPUT + OUTPUT
# ============================================

import re
import pandas as pd

df_cleaned = df_clean.copy()

for col in ["input", "output"]:
    df_cleaned[col] = df_cleaned[col].fillna("").astype(str)


# ============================================
# 1. EMPTY / MISSING
# ============================================

print("=" * 60)
print("1. EMPTY / MISSING VALUES")
print("=" * 60)

for col in ["input", "output"]:
    empty = df_cleaned[col].str.strip().eq("").sum()
    missing = df_cleaned[col].isna().sum()

    print(f"{col}: empty={empty}, missing={missing}")


# ============================================
# 2. VERY LONG TEXT
# ============================================

print("\n" + "=" * 60)
print("2. VERY LONG TEXT")
print("=" * 60)

for col in ["input", "output"]:
    lengths = df_cleaned[col].str.len()

    print(f"\n{col}")
    print("Max length :", lengths.max())
    print("95th percentile:", lengths.quantile(0.95))
    print("99th percentile:", lengths.quantile(0.99))


# ============================================
# 3. VERY SHORT TEXT
# ============================================

print("\n" + "=" * 60)
print("3. VERY SHORT TEXT")
print("=" * 60)

for col in ["input", "output"]:
    short = df_cleaned[col].str.strip().str.len() <= 2

    print(f"\n{col}: {short.sum()} rows")

    display(
        df_cleaned.loc[short, ["id", col]].head(100)
    )


# ============================================
# 4. ENGLISH CHARACTERS
# ============================================

print("\n" + "=" * 60)
print("4. ENGLISH TEXT")
print("=" * 60)

for col in ["input", "output"]:
    mask = df_cleaned[col].str.contains("[A-Za-z]", regex=True)

    print(f"{col}: {mask.sum()} rows")

    display(
        df_cleaned.loc[mask, ["id", col]].head(100)
    )


# ============================================
# 5. URLS / HTTP
# ============================================

print("\n" + "=" * 60)
print("5. URLS / HTTP")
print("=" * 60)

url_pattern = r"(https?://|www\.|[A-Za-z0-9.-]+\.(com|org|net|edu)\b)"

for col in ["input", "output"]:
    mask = df_cleaned[col].str.contains(
        url_pattern,
        regex=True,
        case=False,
        na=False
    )

    print(f"{col}: {mask.sum()} rows")

    display(
        df_cleaned.loc[mask, ["id", col]].head(100)
    )


# ============================================
# 6. EMAIL ADDRESSES
# ============================================

print("\n" + "=" * 60)
print("6. EMAIL ADDRESSES")
print("=" * 60)

email_pattern = r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b"

for col in ["input", "output"]:
    mask = df_cleaned[col].str.contains(
        email_pattern,
        regex=True,
        na=False
    )

    print(f"{col}: {mask.sum()} rows")

    display(
        df_cleaned.loc[mask, ["id", col]].head(100)
    )


# ============================================
# 7. HTML / BBCode / MARKUP
# ============================================

print("\n" + "=" * 60)
print("7. HTML / MARKUP")
print("=" * 60)

markup_pattern = r"(<[^>]+>|\[/?[A-Za-z]+[^\]]*\])"

for col in ["input", "output"]:
    mask = df_cleaned[col].str.contains(
        markup_pattern,
        regex=True,
        na=False
    )

    print(f"{col}: {mask.sum()} rows")

    display(
        df_cleaned.loc[mask, ["id", col]].head(100)
    )


# ============================================
# 8. REPEATED SYMBOLS
# ============================================

print("\n" + "=" * 60)
print("8. REPEATED SYMBOLS")
print("=" * 60)

repeated_symbol_pattern = "([!?.,:;])\1{2,}"

for col in ["input", "output"]:
    mask = df_cleaned[col].str.contains(
        repeated_symbol_pattern,
        regex=True,
        na=False
    )

    print(f"{col}: {mask.sum()} rows")

    display(
        df_cleaned.loc[mask, ["id", col]].head(100)
    )


# ============================================
# 9. REPEATED WORDS
# Example: "আমি আমি খুব অসুস্থ"
# ============================================

print("\n" + "=" * 60)
print("9. REPEATED WORDS")
print("=" * 60)

repeated_word_pattern = r"\b(\S+)(?:\s+\1){1,}\b"

for col in ["input", "output"]:
    mask = df_cleaned[col].str.contains(
        repeated_word_pattern,
        regex=True,
        na=False,
        flags=re.IGNORECASE
    )

    print(f"{col}: {mask.sum()} rows")

    display(
        df_cleaned.loc[mask, ["id", col]].head(100)
    )


# ============================================
# 10. CONTROL / INVISIBLE CHARACTERS
# ============================================

print("\n" + "=" * 60)
print("10. CONTROL CHARACTERS")
print("=" * 60)

control_pattern = r"[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]"

for col in ["input", "output"]:
    mask = df_cleaned[col].str.contains(
        control_pattern,
        regex=True,
        na=False
    )

    print(f"{col}: {mask.sum()} rows")

    display(
        df_cleaned.loc[mask, ["id", col]].head(100)
    )

============================================================
1. EMPTY / MISSING VALUES
============================================================
input: empty=0, missing=0
output: empty=0, missing=0

============================================================
2. VERY LONG TEXT
============================================================

input
Max length : 10814
95th percentile: 869.0
99th percentile: 1373.0

output
Max length : 3322
95th percentile: 1058.0
99th percentile: 1430.1000000000058

============================================================
3. VERY SHORT TEXT
============================================================

input: 0 rows

Empty DataFrame
Columns: [id, input]
Index: []

output: 0 rows

Empty DataFrame
Columns: [id, output]
Index: []

============================================================
4. ENGLISH TEXT
============================================================
input: 22078 rows

,id,input
5,12341,"হেলো, আমার এক বন্ধুর অ্যালকোহলের আসক্তি আছে এবং তার রক্ত পরীক্ষায় জিজিপি (GGT) লেভেল ৩৭0, যেখানে স্বাভাবিক মাত্রা ০-৬০। তার এখন আর কোনো ক্ষুধা নেই এবং সে দিনে প্রায় ৩০ গ্লাস ওয়াইন পান করে। তার পায়ে কোনো অনুভূতি নেই এবং পা ফুলে গেছে। সে দিনে ৫টি ৮০০ মিলিগ্রামের গ্যাবাফেন্টিন বড়ি খায়। সে আর কী করতে পারে? সে ডাক্তারের কাছে গিয়েছিল এবং ডাক্তার তাকে মদ্যপান বন্ধ করে সাহায্য নিতে বলেছিলেন, কিন্তু সে তা প্রত্যাখ্যান করছে।"
7,18267,"আমার বয়স ৫৯ বছর এবং আমি একজন পুরুষ, আমার টি৭-টি১১ প্যারাপ্লেজিয়া রয়েছে। আমার বাম নিতম্বে ৫ সেমি বাই ৫ সেমি বাই ৩.৫ সেমি গভীর একটি ক্ষত রয়েছে। একটি শক্ত পিণ্ড থেকে এই ক্ষতের সৃষ্টি হয়েছিল, যা কাটার পর সংক্রমিত হয়। আমি বর্তমানে একটি উন্ড ভ্যাক (wound vac) ব্যবহার করছি এবং এটি ছোট হয়ে আসছে বলে মনে হচ্ছে, তবে প্রতিদিন বিকেল ৩টার দিকে আমার কাঁপুনি দিয়ে জ্বর আসে এবং বিকেল ৫টার মধ্যে তাপমাত্রা ১০০ ডিগ্রি ফারেনহাইটের কাছাকাছি পৌঁছায়। আমি টাইলেনল গ্রহণ করলে জ্বর স্বাভাবিক হয়ে যায়, কিন্তু রাতে আমার প্রচণ্ড ঘাম হয়। আমি কি এর জন্য কিছু করতে পারি?"
18,78246,"হেলো স্যার, আমার বয়স ৩৪ বছর। আজ আমার বিলিরুবিনের মাত্রা ১.৯০। ১৫ দিন আগে এটি ২.৩ ছিল। আমার এসজিওটি (SGOT) ৯৬ এবং এসজিপিটি (SGPT) ৮৬। গত ৩ দিন ধরে আমি ওষুধ খাচ্ছি। বিলিরুবিনের মাত্রা দ্রুত কমানোর জন্য দয়া করে পরামর্শ দিন। আমি গত ১৫ দিন ধরে কঠোর ডায়েট মেনে চলছি, কোনো আমিষ বা তেলযুক্ত খাবার খাচ্ছি না এবং প্রচুর ফলমূল খাচ্ছি।"
23,65321,"আমি একজন সাধারণ হাই স্কুলের ছাত্রী এবং আমার কোর্সগুলোর মধ্যে পিই (PE) একটি। বুধবার আমাদের এক মাইল দৌড়াতে হয়। সাধারণত দৌড়ানোর পর আমার শ্বাস নিতে কষ্ট হয় এবং পানির প্রয়োজন হয়। তবে এই সপ্তাহে আমি স্বাভাবিকের চেয়ে বেশি জোরে দৌড়েছিলাম, যার ফলে আমার হৃদস্পন্দন অনেক বেড়ে গিয়েছিল এবং আমার শ্বাসকষ্ট হচ্ছিল। এর ফলে আমি দুর্বল হয়ে প্রায় অচেতন হয়ে পড়েছিলাম। কিছুটা পানি পান করার পর, জ্ঞান ফিরে না আসা পর্যন্ত আমাকে কিছুক্ষণ শুয়ে থাকতে হয়েছিল। আমি যখন স্বাভাবিকের চেয়ে দ্রুত দৌড়াই, তখন সাধারণত এমনটা ঘটে। আমার কি হাঁপানির কোনো লক্ষণ থাকতে পারে?"
26,82407,"হেলো, আমি ডাক্তারের কাছে গিয়েছিলাম এবং তারা আমাকে বলেছে যে আমার হৃদপিণ্ডের ডান দিকে হয়তো কোনো সমস্যা আছে এবং তিনি বলেছেন এটি আমার শ্বাস-প্রশ্বাসের সাথে সম্পর্কিত। তিনি আমার ইকেজি (EKG) রিপোর্ট দেখেছেন। এটি কি খুব বড় কোনো সমস্যা নাকি আমার চিন্তার কিছু নেই?"
...,...,...
382,110072,"দয়া করে আমার মেয়েকে সাহায্য করুন। আমার মেয়ের বয়স ৪ বছর এবং গত চার বছর ধরে তার অজ্ঞান হয়ে যাওয়া বা খিঁচুনির সমস্যা রয়েছে এবং সে জ্ঞান হারিয়ে ফেলে। তার গ্রেড ৪ রিফ্লাক্স (VUR) এবং মূত্রাশয়ের সমস্যাও (urology) রয়েছে। তার অনেক পরীক্ষা করা হয়েছে কিন্তু সবগুলোর ফলাফল নেগেটিভ এসেছে। সে একজন নিউরোলজিস্টের কাছে যাচ্ছে কিন্তু তারা খুব একটা ভালো ডাক্তার নন এবং এই ঘটনা বারবার ঘটছে। গতবার সে ৩০ মিনিট অজ্ঞান ছিল এবং তার শরীর নীল ও বেগুনি হয়ে গিয়েছিল। আমার এমন একজন ডাক্তার প্রয়োজন যিনি সাহায্য করতে পারবেন, অন্তত আমার কথা শুনবেন এবং কী কারণে এমন হচ্ছে তা খুঁজে বের করার প্রক্রিয়ায় সাহায্য করবেন। আপনি কি দয়া করে কয়েক মিনিটের জন্য ফোন করে আমার কিছু প্রশ্নের উত্তর দিতে পারবেন? এই বৃহস্পতিবার তার নিউরোলজি অ্যাপয়েন্টমেন্ট আছে, কিন্তু ডাক্তার আমার প্রশ্নের উত্তর দিতে চান না। আপনার সময়ের জন্য ধন্যবাদ, আমি কৃতজ্ঞ। আপনি আমার সাথে (949) 742-0453 নম্বরে যোগাযোগ করতে পারেন, আমার নাম লিনেট এল। ধন্যবাদ।"
384,76433,"আমি এবং আরও অনেক নারী একটি অত্যন্ত বিরল স্তন ক্যান্সারে আক্রান্ত, এটিকে স্তন ক্যান্সার হিসেবে গণ্য করা না হলেও এটি স্তনেই হয়। একে ফাইলোডস (Phyllodes) বলা হয়। অনলাইনে আমাদের এমন নারীদের একটি দল রয়েছে। আমার মনে হয় আমাদের অন্যদেরও এ বিষয়ে জানানো প্রয়োজন। আমার মনে হয় অনেক নারীকে কেবল এই টিউমারটি পর্যবেক্ষণ করতে বলা হয়, যতক্ষণ না এটি এত বড় হয়ে যায় যে তা অপসারণ করতেই হয়। আমার ক্ষেত্রে, পাঁচ বছর ধরে কোনো পদক্ষেপ না নিয়ে এটি পর্যবেক্ষণ করা হয়েছিল এবং একদিন এটি বড় হয়ে গেলে তারা লুম্পেক্টমি করে, কিন্তু পরে দেখা যায় যে টিউমারটি পুরোপুরি অপসারণের জন্য আবার অস্ত্রোপচার করে মাস্টেক্টমি করতে হয়েছে। এটি ফুসফুস এবং হাড় পর্যন্ত ছড়িয়ে পড়তে পারে। আমি শুধু চাই বিশ্বের নারীরা এবং চিকিৎসকরাও এটি সম্পর্কে জানুক। অনেক চিকিৎসকই এর নাম শোনেননি বা এটি কীভাবে চিকিৎসা করতে হয় তা জানেন না। এই বার্তাটি ছড়িয়ে দিতে আমাদের আপনাদের সাহায্য প্রয়োজন। ধন্যবাদ।"
385,96741,"প্রিয় ডাক্তার, আমার সামনের দাঁতগুলো ভেঙে গিয়েছিল যা একজন ভালো ডেন্টিস্টের মাধ্যমে সম্প্রতি ঠিক করা হয়েছে, কারণ একজন খারাপ ডেন্টিস্ট সেগুলো নষ্ট করে ফেলেছিলেন। এছাড়া, আমি দীর্ঘদিন ট্রাম্পেট বাজানোর কারণে আমার দাঁতগুলো ভেতরের দিকে বেঁকে গেছে। এই আঁকাবাঁকা দাঁতের কারণে আমার খাওয়ার ধরনে পরিবর্তন এসেছে এবং আমি এখন আর আমার দাঁতগুলো ঠিকমতো মেলাতে পারি না। দাঁতগুলো এখন আর সঠিকভাবে একে অপরের সাথে লাগে না এবং এগুলো আমার মুখের ভারসাম্যের ওপরও প্রভাব ফেলছে; মাঝে মাঝে কোনো কারণ ছাড়াই আমার মুখে লালা চলে আসে এবং আমি মাঝে মাঝে ভারসাম্যহীন ও বমি বমি অনুভব করি। আমি ইনভিসালাইন (invisalign) নামক একটি সমাধান সম্পর্কে পড়েছি, কিন্তু হার্ভার্ডের একজন ডেন্টিস্ট আমার সাথে খুব খারাপ ব্যবহার করেছিলেন; তিনি আমার তিনটি সামনের দাঁত না তোলা পর্যন্ত চিকিৎসা করতে অস্বীকার করেছিলেন। তিনি আরও দাবি করেছিলেন যে আমি কখনোই আমার দাঁতের সংশোধন সহ্য করতে পারব না, কারণ তার একজন ক্লায়েন্ট ছিল যে ওভারবাইট সংশোধনের সাথে তার এমবুশারের (embouchure) সমন্বয় করতে পারেনি এবং তিনি আমাকে সেই ক্লায়েন্টের সাথে তুলনা করেছিলেন। তিনি একজন জঘন্য মানুষ ছিলেন, যিনি দাবি করেছিলেন যে ইনভিসালাইন কেবল প্লাস্টিকের টুকরো ছাড়া আর কিছুই নয়। আমি কেবল দেখতে এবং অনুভব করতে ভালো বোধ করতে চাই এবং আমি রিসেট করা এমবুশারের জন্য খুব ভালোভাবে প্রশিক্ষিত, কারণ আমার দাঁত একাধিকবার ভেঙেছে, আমি বার্কলি শিলিঙ্গার এবং জিরো প্রেশার পদ্ধতি ব্যবহার করেছি। আমার খুব ভালো শিক্ষকও ছিলেন এবং আমি অনেক ভিন্ন পরিস্থিতির সাথে মানিয়ে নিতে পারি। তবে আমি কোনো কৃত্রিম পরিবর্তন নয়, বরং একটি জৈবিক সমাধান খুঁজছি কারণ আমি জানি যে মানুষ প্রাকৃতিকভাবেই ভারসাম্যের মধ্যে থাকে, এটি এমনই হওয়ার কথা। মানুষের নিজের সাথে এবং স্বাচ্ছন্দ্যের মধ্যে শান্তিতে ও ভারসাম্যে থাকার কথা; ডাক্তাররা মানুষকে সেই স্বাচ্ছন্দ্যের অবস্থানে ফিরিয়ে আনতে সাহায্য করতে পারেন।"
391,88100,"হেলো, আমি কয়েক বছর ধরে BEYAZ সেবন করছি। এই মাসে আমার পিরিয়ড শুরু হয়নি এবং আমি ইতিমধ্যে আমার সব সুগার পিল শেষ করে নতুন প্যাকেটের দ্বিতীয় সক্রিয় পিলটি খাচ্ছি। সাধারণত আমার পিরিয়ড খুব হালকা হয় বা শুধু স্পটিং হয়, কখনো কখনো প্রায় কিছুই হয় না, কিন্তু এবার আমার কিছুই হয়নি। কোনো স্পটিং বা অন্য কিছু নেই। আমি ইদানীং খুব মানসিক চাপে আছি। গত মাসেও এমনটা হওয়ায় আমি প্রেগনেন্সি টেস্ট করেছিলাম, কিন্তু চতুর্থ সুগার পিল খাওয়ার পর আমার পিরিয়ড শুরু হয়েছিল। সেই টেস্টের পর থেকে আমি শারীরিক সম্পর্ক করিনি, তাই আমার গর্ভবতী হওয়ার সম্ভাবনা নেই বললেই চলে। আমি খুব কমই শারীরিক সম্পর্ক করি। আমি সবসময় সময়মতো পিল খাই। বছরে হয়তো একবার কোনো পিল মিস হতে পারে, তবে মনে পড়ার সাথে সাথেই আমি তা খেয়ে নিই, যা সাধারণত পরের দিন সকালে হয়।"
394,64932,"আমার ছেলের অ্যাপেন্ডিসাইটিসের সমস্ত লক্ষণ দেখা যাচ্ছে। গতকাল আমি তাকে আমাদের নিয়মিত চিকিৎসকের কাছে নিয়ে গিয়েছিলাম এবং তিনি বলেছিলেন যে আমরা সঠিক সময়ে ধরতে পেরেছি, তাই অ্যান্টিবায়োটিক দিয়েই এটি সেরে যাবে। আমরা গত রাতে অ্যান্টিবায়োটিক শুরু করেছি। ডাক্তার বলেছিলেন ব্যথা অব্যাহত থাকলে তাকে জরুরি বিভাগে (ER) নিয়ে যেতে, তাই আমরা তা-ই করেছি। জরুরি বিভাগের ডাক্তার একটি সিটি স্ক্যান করতে দিয়েছিলেন এবং সেটির রিপোর্ট স্বাভাবিক এসেছে। এখন কী করব বুঝতে পারছি না। আপনার কি কোনো পরামর্শ আছে?"

output: 31441 rows

,id,output
0,45361,"হেলো, পিসিওডি (PCOD) হলো এমন একটি উপসর্গ যা অনিয়মিত বা অনুপস্থিত পিরিয়ড, বন্ধ্যাত্ব, স্থূলতা, অবাঞ্ছিত লোম বৃদ্ধি, ব্রণ, কিছু ক্ষেত্রে ইনসুলিন রেজিস্ট্যান্স, এলএইচ/এফএসএইচ (LH/FSH) অনুপাত উল্টে যাওয়া সহ অস্বাভাবিক হরমোনের প্রোফাইল, আরএইচইএএস (RHEAS) লেভেল বৃদ্ধি, কিছু ক্ষেত্রে অস্বাভাবিক জিটিটি (GTT), কখনও কখনও উচ্চ প্রোল্যাক্টিন এবং অস্বাভাবিক থাইরয়েড প্রোফাইলের সাথে যুক্ত থাকে। এতে ডিম্বাশয়ে একাধিক ফলিকল দেখা যায় কারণ অনেকগুলো ফলিকল একই সময়ে তৈরি হলেও সেগুলো পরিপক্ক হয় না। রোগ নির্ণয়ের জন্য আপনাকে সম্পূর্ণ পরীক্ষা-নিরীক্ষা করাতে হবে। ওভুলেশন বা ডিম্বস্ফোটন সম্ভব হলেও হরমোনের ভারসাম্যহীনতা, টিউব সংক্রান্ত সমস্যা বা পুরুষজনিত কারণের মতো অনেকগুলো বিষয়ের কারণে গর্ভধারণ নাও হতে পারে। আপনার একজন অভিজ্ঞ ইনফার্টিলিটি বিশেষজ্ঞের পরামর্শ নেওয়া উচিত। নিজের যত্ন নেবেন।"
2,98599,"হেলো কবিতা, লেখার জন্য ধন্যবাদ। স্কিন লাইটেনিং ক্রিমে ২% এইচওয়াই নাসেনিয়া ডক থাকে। এই উপাদানগুলো ত্বকে স্থায়ী পিগমেন্টেশন ঘটাতে পারে যার ফলে সাদা দাগ হতে পারে। এটি দীর্ঘ সময় ব্যবহার করা উচিত নয়। আমার পরামর্শ হলো - স্টেরয়েডযুক্ত ক্রিম ব্যবহার বন্ধ করুন। দিনের বেলা ভালো সানস্ক্রিন ব্যবহার করুন। আপনি রাতে কালো দাগের ওপর ক্লাইম্যাক্স ক্রিম লাগাতে পারেন, এটি নিরাপদ এবং কার্যকর। গায়ের রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। খাদ্যতালিকায় প্রচুর ভিটামিন সি রাখুন। রোদে যাওয়া এড়িয়ে চলুন। রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। ভবিষ্যতে যেকোনো এইচকিউ (HQ) এবং স্টেরয়েডযুক্ত ক্রিম এড়িয়ে চলুন। আশা করি এটি সাহায্য করবে। ফলো-আপের জন্য আমি উপলব্ধ থাকব। শুভেচ্ছা।"
4,65169,"হেলো, আমি আপনার প্রশ্নটি মনোযোগ সহকারে পড়েছি এবং ব্যাখ্যা করতে চাই যে তার হৃদযন্ত্রের কার্যকারিতা মূল্যায়ন করা এবং সম্ভাব্য হার্ট ফেইলিওর যা এই ক্লিনিকাল পরিস্থিতির অনুকরণ করতে পারে, তা বাদ দেওয়া প্রয়োজন। গ্যাস্ট্রোইসোফেজিয়াল রিফ্লাক্সও এই পরিস্থিতির অনুকরণ করতে পারে, যদিও মাথা ঘোরা এই রোগের সাধারণ লক্ষণ নয়। এই পর্যায়ে, আমি হার্ট ফেইলিওর আছে কিনা তা তদন্ত করার জন্য একটি কার্ডিয়াক আল্ট্রাসাউন্ড এবং এনটি-প্রো বিএনপি (NT-pro BNP) পরীক্ষা করার পরামর্শ দেব। বিবেচনা করার মতো অন্যান্য পরীক্ষাগুলো হলো"
5,12341,"হেলো, খারাপ খাদ্যাভ্যাস (চর্বিযুক্ত খাবার, মশলাদার খাবার), অ্যালকোহল গ্রহণ, কিছু ওষুধের ব্যবহার (বেশিরভাগ ব্যথানাশক), পিত্তথলির রোগ (যেমন পিত্তথলিতে পাথর), লিভারের ভাইরাল সংক্রমণ (এইচবিভি, এইচসিভি সংক্রমণ) ইত্যাদির কারণে লিভার এনজাইম বেড়ে যেতে পারে। যেহেতু আপনার জিজিপিটি (GGT) লেভেল আবার বেড়েছে, তাই খাদ্যাভ্যাস ছাড়াও এর বৃদ্ধির অন্যান্য সম্ভাব্য কারণগুলো খতিয়ে দেখা উচিত। জিটিপি, এপি, অ্যামাইলেজ, লাইপেজ, ইউরিন অ্যামাইলেজ, ব্যাগ, অ্যান্টিওক লেভেল পরীক্ষা করা উচিত। পেটের একটি আল্ট্রাসাউন্ডও করা প্রয়োজন। আপনার চর্বিযুক্ত খাবার, ভাজা খাবার, মশলাদার খাবার, অ্যালকোহল এবং ওষুধ এড়িয়ে চলা উচিত। প্রেসক্রিপশন ছাড়াই পাওয়া যায় এমন লিভারের কার্যকারিতা বৃদ্ধিকারী সাপ্লিমেন্টগুলোও লিভার পুনর্গঠনে সহায়ক হতে পারে। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি। আমি আপনাকে আরও কোনোভাবে সাহায্য করতে পারি কিনা তা জানাবেন।"
10,82782,"হেলো, আপনার সংক্ষিপ্ত ইতিহাস প্রদানের জন্য ধন্যবাদ। একটি পুঙ্খানুপুঙ্খ নিউরোমাসকুলার মূল্যায়ন করার পরামর্শ দেওয়া হচ্ছে। আপনার লক্ষণগুলো অনুযায়ী, সাধারণত এই ধরনের লক্ষণ কেবল পেশীর দুর্বলতার কারণে হয় এবং ব্যায়ামের মাধ্যমে তা ঠিক করা সম্ভব। তবে যদি এতে কাজ না হয়, তবে লক্ষণগুলো আরও ভালোভাবে বোঝার জন্য মস্তিষ্কের এমআরআই (MRI)-এর পাশাপাশি একটি নিউরোলজিক্যাল মূল্যায়নের পরামর্শ দেওয়া হচ্ছে। এই ধরনের পরিস্থিতিতে আতঙ্কিত হওয়ার কিছু নেই। সঠিক ক্লিনিক্যাল মূল্যায়ন এবং ডায়াগনস্টিক পদ্ধতির সাহায্যে সবকিছু বোঝা এবং সমাধান করা সম্ভব। শুভেচ্ছা, জে ইন নাসেনিয়া ডক।"
...,...,...
371,47311,"হেলো, আপনার উদ্বেগগুলো আমি বুঝতে পেরেছি এবং আপনার বিস্তারিত তথ্যগুলো দেখেছি। প্রস্রাবের সাথে বীর্যপাত হওয়া খুবই স্বাভাবিক, প্রাকৃতিক এবং অনিচ্ছাকৃত একটি প্রক্রিয়া, এর জন্য স্বাস্থ্যগত কোনো উদ্বেগের কারণ নেই। আপনি যখন যৌন উত্তেজিত হন, তখন আপনার শরীর বীর্য তৈরি করে। উৎপাদিত বীর্য আপনার শরীরের ভেতরে জমা থাকে এবং এটি একটি বর্জ্য পদার্থ। শরীরকে এই বর্জ্য পদার্থ বের করে দিতে হয়। সাধারণত হস্তমৈথুন বা যৌন মিলনের মাধ্যমে শরীর এই বর্জ্য বের করে দেয়। যদি আপনি তা না করেন, তবে শরীর প্রস্রাব বা স্বপ্নদোষের মাধ্যমে এই বর্জ্য বের করার নিজস্ব উপায় খুঁজে নেয়। চিন্তা করবেন না বা উদ্বিগ্ন হবেন না। আপনার ক্লান্তি, ঘুমের অভাব ইত্যাদির কারণ বীর্যপাত নয়, বরং অতিরিক্ত চিন্তার কারণে সৃষ্ট উদ্বেগ। অনুগ্রহ করে কাউন্সেলিংয়ের জন্য একজন মনোবিজ্ঞানীর পরামর্শ নিন। এই বিষয়ে আপনার আরও সাহায্যের প্রয়োজন হলে, অনুগ্রহ করে এই ইউআরএলটি ব্যবহার করুন। http"
372,91354,"আমার মতে আপনার শিশুর খিটখিটে স্বভাবের জন্য ফেনকিড (Fend kid) ভালো পছন্দ নয়। এতে প্রোমেথাজিন রয়েছে যা অতিরিক্ত ঘুম ভাব সৃষ্টি করে এবং দেড় মাস বয়সী শিশুর জন্য এটি নিরাপদ নয়। আপনার শিশুর কান্নার কারণ খুঁজে বের করার চেষ্টা করুন। এটি অপর্যাপ্ত খাবার, হাইপার ল্যাকটেশনের কারণে অতিরিক্ত ফোর-মিল্ক যা পেটে অস্বস্তি তৈরি করে, পরিবেশের অনুপযুক্ত তাপমাত্রা, আঁটসাঁট পোশাক বা খাওয়ানোর পর ঠিকমতো ঢেকুর না তোলার কারণে হতে পারে। শিশুর খিটখিটে হওয়ার এগুলো খুব সাধারণ কারণ। কারণটি খুঁজে বের করে তার চিকিৎসা করুন। এ বিষয়ে আরও তথ্যের প্রয়োজন হলে পুনরায় কল করুন।"
376,32922,"নাসেনিয়া ডকে আপনার প্রশ্নের জন্য ধন্যবাদ। আমি আপনার সমস্যাটি বুঝতে পারছি। আমার মতে, আপনার সম্ভবত ভাইরাল আপার রেসপিরেটরি ট্র্যাক্ট ইনফেকশন (ইউআরআই) হয়েছে। অ্যাঞ্জিওএডেমার কারণে ইউআরআই-এর সাথে উপরের ঠোঁট ফুলে যেতে দেখা যায়। এটি একটি অ্যালার্জিক প্রতিক্রিয়া। এবং অ্যান্টিহিস্টামিন ও ওরাল স্টেরয়েড দিয়ে দ্রুত চিকিৎসা প্রয়োজন। তাই একজন ডাক্তারের সাথে পরামর্শ করে এই বিষয়গুলো আলোচনা করা এবং যথাযথ চিকিৎসা শুরু করা ভালো। সঠিক চিকিৎসায় ২-৩ দিনের মধ্যে ঠোঁটের ফোলা কমে যাবে। তাই খুব বেশি চিন্তা করবেন না, শুধু চিকিৎসা শুরু করুন। এবং আপনার ডটস (DOTS) চিকিৎসা চালিয়ে যান।"
377,30265,"হেলো। নাসেনিয়া ডকে আপনার প্রশ্নটি পোস্ট করার জন্য ধন্যবাদ। সাধারণত এএলটি (ALT) বা এএসটি (AST) এর মান ""স্বাভাবিক ঊর্ধ্বসীমার দ্বিগুণের"" বেশি হলে তা অস্বাভাবিক বলে গণ্য করা হয় (কিছু দেশে, এএলটি বা এএসটি এর মান ১০০-এর বেশি হলে তা অস্বাভাবিক ধরা হয়)। এএসটি বা এএলটি এর মান ৮৫ বা তার বেশি হলে তা আরও পরীক্ষা করা প্রয়োজন হতে পারে। অ্যালকোহল গ্রহণ এবং স্থূলতা ফ্যাটি লিভার রোগের সাধারণ কারণ। আপনার প্রশ্নে মান (সংখ্যা) উল্লেখ করা হয়নি। আপনি বিস্তারিত তথ্যসহ আপনার প্রশ্নটি আবার পোস্ট করতে পারেন, ধন্যবাদ। অথবা আপনি নাসেনিয়া ডক পোর্টালের মাধ্যমে সরাসরি আমাকে প্রশ্ন করতে পারেন। http"
378,55401,"হেলো! আমি আপনার প্রশ্নটি বুঝতে পেরেছি। আপনার প্রশ্নের জন্য ধন্যবাদ। হ্যাঁ, আপনার মেয়ে এমআরএসএ (MRSA) দ্বারা সংক্রমিত হতে পারে, শুধু আপনি নন, পুরো পরিবারও সংক্রমিত হতে পারে। সে গর্ভবতী এবং সে যদি সংক্রমিত হয় তবে তার অনাগত সন্তানের সুস্থতার ওপরও এর প্রভাব পড়তে পারে। মেথিসিলিন-প্রতিরোধী স্ট্যাফাইলোকক্কাস অরিয়াস (MRSA) সংক্রমণ এক ধরণের স্ট্যাফ ব্যাকটেরিয়ার কারণে হয়, যা সাধারণ স্ট্যাফ সংক্রমণের চিকিৎসায় ব্যবহৃত অনেক অ্যান্টিবায়োটিকের বিরুদ্ধে প্রতিরোধ ক্ষমতা গড়ে তুলেছে। এমআরএসএ কাটাছেঁড়া এবং ত্বকের সংস্পর্শের মাধ্যমেও সহজেই ছড়িয়ে পড়তে পারে। এটি অত্যন্ত সংক্রামক এবং একাধিক অ্যান্টিবায়োটিকের বিরুদ্ধে খুব প্রতিরোধী। আশা করি এটি আপনাকে সাহায্য করবে, ধন্যবাদ।"

============================================================
5. URLS / HTTP
============================================================

/tmp/ipykernel_189/1923704581.py:93: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df_cleaned[col].str.contains(

input: 50 rows

            id  \
6316     54834
6472     79290
9834     55377
13076    95815
15979     2378
16118    65249
17047   111831
18077    76137
22373    53974
22964    11592
26291    12411
26753    56978
26986    85694
29336   109375
36893    69458
37523   100120
37739    97482
38245    28204
39740    52326
45938    67054
46073    42454
46405    69288
46987    47006
52350    26879
57245    46813
59261   105248
61445    17514
62441    46713
62642   104360
64557   104386
73153    19707
74922    10294
75381    48879
75648    58666
78911    30937
81211     1948
82509     6511
84221    79240
85227    82539
85233    42373
85917    29049
98507    36634
101338   14625
101948  109312
102350   88345
103343   22620
104821   77958
105162     194
107969   19991
108377   69905

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  input
6316                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             আমার হাত ও পায়ে এবং বুক ও পিঠের কিছু অংশে অনেক ছোট ছোট লাল দানা দেখা দিয়েছে। মনে হচ্ছে লাল দানাগুলো শরীরের লোমকূপের গোড়ায় হয়েছে। বাতাস বা ঘামের সংস্পর্শে এলে এগুলো খুব চুলকায়। এই সমস্যার কারণে আমি প্রায়ই প্যান্ট পরে থাকি, কারণ বাইরে অল্প সময় হাঁটাহাঁটি করলেও আমার পা খুব চুলকায়। আমি অনলাইনে এই সমস্যাটি সম্পর্কে খোঁজার চেষ্টা করেছি, কিন্তু অনেকগুলো একই ধরনের সমস্যা থাকায় আমি নিশ্চিত হতে পারিনি যে আমার আসলে কী হয়েছে। আমি বহু বছর ধরে এই সমস্যায় ভুগছি এবং আমার মনে হয় এখন আমার রোগ নির্ণয় ও চিকিৎসার জন্য ডাক্তারের পরামর্শ নেওয়া প্রয়োজন। রোগ নির্ণয়ে সহায়তার জন্য এখানে একটি ছবি দেওয়া হলো। WWW.WWWW.WW
6472                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         হেলো, আমি আমার লিঙ্গে একটি ফোলা অংশ দেখতে পেয়েছি যা দেখতে অনেকটা এইরকম WWW.WWWW.WW। অরক্ষিত যৌন মিলনের কয়েক ঘণ্টা পর এটি আমার চোখে পড়ে। সেই সময় আমার বোনের চিকেন পক্স ছিল এবং তার তিন দিন ছিল, আমার নিজের চিকেন পক্স ৩ বছর আগে হয়েছিল এবং আমার প্রেমিকার চেক-আপে কোনো এসটিডি-র লক্ষণ পাওয়া যায়নি। এরপর কয়েক দিন পর, আমার উপরের ঠোঁটে জ্বালাপোড়া অনুভব করি এবং ছোট ছোট সাদা দাগ দেখা দেয়। এগুলো দেখতে ফোর্ডাইস স্পটসের মতো। ছুটির দিন হওয়ায় চর্মরোগ বিশেষজ্ঞের অ্যাপয়েন্টমেন্ট নিতে পারিনি।
9834                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             আমি হাঁটু এবং হাঁপানি সংক্রান্ত সমস্যার সমাধানে আকুপাংচার/লেজার থেরাপির কথা শুনেছি। আমার মা (৭০-এর কোঠায়) এই সমস্যাগুলোতে ভুগছেন। আমি সম্প্রতি ভারতের একটি গ্রুপ WWW.WWWW.WW সম্পর্কে জানতে পেরেছি যারা সফলভাবে এই ধরনের থেরাপি প্রদান করছে। এ বিষয়ে আপনার মতামত জানতে চাই। ধন্যবাদ।

/tmp/ipykernel_189/1923704581.py:93: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df_cleaned[col].str.contains(

output: 310 rows

,id,output
35,48796,"পায়ের নখের অস্ত্রোপচারের পর এই লক্ষণগুলো থাকা অস্বাভাবিক। প্রদত্ত তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনাকে বিস্তারিতভাবে পরীক্ষা ও পর্যবেক্ষণ করতে চাই। ডায়াবেটিস, উচ্চ রক্তচাপ বা অন্য কোনো বিপাকীয় ব্যাধি আছে কিনা তা নিশ্চিত করুন। যাই হোক, আপনি সংক্রমণ নিয়ন্ত্রণে অ্যান্টিবায়োটিক ব্যবহার করে দেখতে পারেন। লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে, ৫ দিনের জন্য। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিনের জন্য। (এই ওষুধগুলো পেতে আপনার স্থানীয় ডাক্তারের সাহায্য নিতে পারেন।) গরম সেঁক দিন। নরম বিছানায় শক্ত বিছানায় ঘুমান। বেদনাদায়ক কাজ ও কার্যকলাপ এড়িয়ে চলুন। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন।) মাথার নিচে কোনো বালিশ ব্যবহার করবেন না। অবহেলা করবেন না, এটি যেন কোনো বড় সমস্যার শুরু না হয়। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে উপশম না হলে, আমার সাথে আবার যোগাযোগ করুন। (ফোন: ৯১ ৯৮১০০১২৬৮৮) অনুগ্রহ করে নিশ্চিত করুন যে এই ওষুধগুলোর কোনোটিতে আপনার অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন।) জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি, আপনার আরও কোনো প্রশ্ন থাকলে আমি সাহায্য করতে পেরে খুশি হব। অনুগ্রহ করে প্রশ্নটি রেট করুন। আপনার দ্রুত আরোগ্য ও সুস্বাস্থ্য কামনা করি।"
389,44494,"ভ্যারিকোসেল হলো অণ্ডকোষের শিরাগুলোর একটি কাঠামোগত পরিবর্তন, যেখানে সেগুলো দীর্ঘ এবং প্যাঁচানো হয়ে যায়। তাই, যদিও হোমিওপ্যাথিক ওষুধ সমস্যাটি কমাতে সাহায্য করতে পারে, তবে হোমিওপ্যাথির কার্যকারিতা সমস্যার কারণ এবং তীব্রতার ওপর নির্ভর করে। কিছু ক্ষেত্রে অস্ত্রোপচারের প্রয়োজন হতে পারে। আপনার দ্রুত কনস্টিটিউশনাল চিকিৎসার জন্য একজন অভিজ্ঞ হোমিওপ্যাথিক বিশেষজ্ঞের পরামর্শ নেওয়া উচিত। আপনার যা করা প্রয়োজন তা হলো, অণ্ডকোষকে সাপোর্ট দেওয়ার জন্য একটি সাপোর্টার বা টি-ব্যান্ডেজ ব্যবহার করা। ঢিলেঢালা সুতির প্যান্ট পরলে অণ্ডকোষ অতিরিক্ত গরম হওয়া থেকে রক্ষা পাবে। সাঁতারের মতো কার্যকলাপ অণ্ডকোষের তাপমাত্রা কম রাখতে সাহায্য করবে। গরম পানি দিয়ে গোসল করা বা স্টিম-বাথ নেওয়া এড়িয়ে চলুন। এটি আপনাকে বন্ধ্যাত্বের ঝুঁকি কমাতে সাহায্য করবে। ""ভ্যারিকোসেল সাধারণত ক্ষতিকারক নয়, তবে বন্ধ্যাত্বের ক্ষেত্রে এটি সমস্যা সৃষ্টি করতে পারে""। আশা করি আপনি দ্রুত সুস্থ হয়ে উঠবেন। নাসেনিয়া ডক। rs787878@gmail.com"
982,21747,"হেলো, আপনার প্রশ্নটি পড়েছি এবং আপনার উদ্বেগ বুঝতে পেরেছি। মেলিসা মেডিকেল ফাউন্ডেশন রোগীদের উপকারের জন্য কাজ করে। তাদের কাছে রোগীর রক্তের নমুনা সরাসরি তাদের টেস্ট সেন্টারে পাঠানোর বিকল্প রয়েছে। আপনি হয় নিকটস্থ টেস্ট সেন্টারে গিয়ে অথবা তাদের পাঠানো স্যাম্পল কালেকশন কিট ব্যবহার করে ডাকযোগে নমুনা পাঠাতে পারেন। মেলিসা ডট ওআরজি (MELISA.org)-এর অফিসিয়াল ওয়েবসাইটে যান এবং ল্যাবরেটরি বা অনুমোদিত ক্লিনিকে পরীক্ষা করানোর অথবা টেস্ট কিটের জন্য অনুরোধ করার বিষয়টি নির্বাচন করুন। অ্যালার্জি না থাকলে উপসর্গের কারণ সম্পর্কে আরও ভালো ধারণা পাওয়া যাবে এবং রোগীর আস্থা ও অন্যান্য রোগ নির্ণয় পদ্ধতি চিকিৎসার ক্ষেত্রে অবশ্যই সাহায্য করবে। আশা করি আপনার উদ্বেগের উত্তর পেয়েছেন। ধন্যবাদ।"
1617,35410,"হেলো... শিশুদের মাথাব্যথাকে তখনই গুরুতর হিসেবে বিবেচনা করা উচিত যখন নিচের লক্ষণগুলো থাকে - ১. ক্রমাগত বমি হওয়া ২. খিঁচুনি ৩. কান ও নাক দিয়ে জলীয় বা রক্তমিশ্রিত নিঃসরণ ৪. অজ্ঞান হয়ে যাওয়া ৫. সংবেদনশীলতা বা আচরণে পরিবর্তন। উপরের সতর্কতামূলক লক্ষণগুলো ছাড়া, কেবল শক্তির মাত্রা কম অনুভব করা মাইগ্রেন এবং অন্যান্য ধরনের টেনশন হেডেক নির্দেশ করে, যা বর্তমান পরিস্থিতিতে অতিরিক্ত পড়াশোনা এবং সহপাঠীদের চাপের কারণে শিশুদের মধ্যে বাড়ছে। আপনার জন্য আমার কিছু প্রশ্ন আছে - ১. কতদিন ধরে মাথাব্যথা হচ্ছে? ২. এটি কি সবসময় কপালে হয় নাকি স্থান পরিবর্তন করে? ৩. এর সাথে কি ঝাপসা দেখা, দ্বৈত দৃষ্টি বা মাথা ঘোরা আছে? ৪. পরিবারে কি মাইগ্রেন বা একপার্শ্বীয় মাথাব্যথার কোনো ইতিহাস আছে? ৫. মাথাব্যথার সময় সে কি খুব রাগান্বিত থাকে এবং ভালো ঘুমের পর কি ব্যথা কমে যায়? ৬. মাথাব্যথার সময় কি সে বমি করে? অনুগ্রহ করে উপরের প্রশ্নগুলোর উত্তর দিন এবং তার ওজন জানান যাতে আমি আপনাকে ভালো ওষুধ সাজেস্ট করতে পারি। তবে আপাতত - আপনি ১৫ মিগ্রা/কেজি/ডোজ (সর্বোচ্চ ৫০০ মিগ্রা) হিসেবে প্রতি ৪-৬ ঘণ্টা অন্তর প্যারাসিটামল খাওয়াতে পারেন। আপনি নিচের লিঙ্কে আমার সাথে যোগাযোগ করতে পারেন। অনুগ্রহ করে নিচের লিঙ্কটি দেখুন - www.ChatDoctor .com/doctors/ Chat Doctor."
1655,7885,"আপনার উদ্বেগগুলো আমি বুঝতে পেরেছি এবং আপনার বর্ণনা পড়েছি। আমি পরামর্শ দেব যে আপনি খুব বেশি চিন্তা করবেন না। ঘুমানোর আগে অনেকেই হস্তমৈথুন করেন। মূত্রনালীর সংবেদনশীলতার কারণে তাদের বেশিরভাগই প্রস্রাবের বেগ অনুভব করেন। এটি সম্পূর্ণ স্বাভাবিক। মাঝে মাঝে ব্যথা এবং অস্বস্তি হওয়াও স্বাভাবিক। তবে যদি ব্যথা বারবার হতে থাকে, তবে আপনার একজন চিকিৎসকের পরামর্শ নেওয়া উচিত। তবে আমার মনে হয়, ব্যথা এবং অস্বস্তি আপনার চিন্তার মধ্যেই সীমাবদ্ধ। আপাতত এগুলো উপেক্ষা করে গুরুত্বপূর্ণ কাজে মনোযোগ দেওয়াই ভালো। আপনার মনস্তাত্ত্বিক পরামর্শের প্রয়োজন হতে পারে। নাসেনিয়া ডকের মাধ্যমে টেলিফোনে মনস্তাত্ত্বিক পরামর্শ দিতে পারলে আমি খুশি হব। কাস্টমার কেয়ারের মাধ্যমে আমার সাথে যোগাযোগ করুন, www.ChatDoctor.com। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আরও কোনো স্পষ্টীকরণের প্রয়োজন হলে আমি আছি। শুভকামনা।"
...,...,...
35487,100912,"আপনার উদ্বেগগুলো আমি বুঝতে পেরেছি এবং আপনার বর্ণনা পড়েছি। আমি আপনাকে খুব বেশি চিন্তা না করার পরামর্শ দিচ্ছি। আপনি প্রোস্টেট গ্রন্থি নিয়ে কেন চিন্তিত? আপনি কি এটি সম্পর্কে কিছু জানেন? আপনার কি এ বিষয়ে কোনো অভিজ্ঞতা আছে? যদি আপনার সন্দেহ থাকে, তবে অনুগ্রহ করে একজন চিকিৎসকের পরামর্শ নিন। নিজে নিজে রোগ নির্ণয় করবেন না এবং নিজে নিজে ওষুধ সেবন করবেন না। নিজে রোগ নির্ণয় এবং দুশ্চিন্তা অযথা উদ্বেগ ও ভয়ের সৃষ্টি করতে পারে, যা থেকে মানসিক ব্যাধি হতে পারে। আপনার মনস্তাত্ত্বিক পরামর্শের প্রয়োজন হতে পারে। আমি নাসেনিয়া ডকের মাধ্যমে টেলিফোনে মনস্তাত্ত্বিক পরামর্শ দিতে পেরে খুশি হব। গ্রাহক সেবার মাধ্যমে আমার সাথে যোগাযোগ করুন, www.ChatDoctor.com। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আরও স্পষ্টীকরণের জন্য আমি উপলব্ধ আছি। শুভকামনা।"
35586,102944,"হেলো মিস্টার আরএনকে, আপনি কেমন আছেন? আমার নাম নাসেনিয়া ডক। আমি একজন লিভার ট্রান্সপ্ল্যান্ট সার্জন এবং আমি আশা করি আজ আপনার প্রশ্নের উত্তর দিতে পারব। আপনার ছেলের রোগ নির্ণয়ের কথা শুনে আমি অত্যন্ত দুঃখিত। হেপাটাইটিস বি সংক্রমণ শরীরের তরল বিনিময়ের মাধ্যমে অথবা জন্মের সময় মা থেকে সন্তানের মধ্যে হয়ে থাকে। তবে হেপাটাইটিস বি-তে আক্রান্ত সব রোগীর চিকিৎসার প্রয়োজন হয় না। হেপাটাইটিস বি-তে আক্রান্ত ৮০-৯০% রোগী প্রাকৃতিকভাবেই ভাইরাসটি শরীর থেকে দূর করে ফেলে এবং তাদের কোনো চিকিৎসার প্রয়োজন হয় না। প্রায় ৮% রোগীর শরীরে ভাইরাসটি স্থায়ীভাবে থাকে কিন্তু তারা ভাইরাসের কোনো ক্ষতিকর প্রভাবে ভোগেন না (ক্যারিয়ার)। দুর্ভাগ্যবশত ১% রোগীর ক্ষেত্রে ভাইরাসের দীর্ঘমেয়াদী প্রভাব দেখা দেয়, যা লিভারকে আক্রান্ত করে এবং ক্ষতিগ্রস্ত করে। এই রোগীদের শেষ পর্যন্ত চিকিৎসার প্রয়োজন হয়। রক্ত পরীক্ষার মাধ্যমে লিভারের ক্ষতি স্পষ্ট বোঝা যায়। এছাড়া রক্ত পরীক্ষার (HBeAg, Anti-HBe, Core antigen, Viral Load ইত্যাদি) মাধ্যমে সংক্রমণের পর্যায়ও জানা সম্ভব। আমি নিশ্চিত যে আপনার চিকিৎসকরা সব প্রয়োজনীয় পরীক্ষা করছেন। আরও বিস্তারিত জানার জন্য আমার সাথে যোগাযোগ করতে দ্বিধা করবেন না। rxsuresh@gmail.com আশা করি এটি আপনাকে সাহায্য করবে এবং আশা করি আপনি ভালো বোধ করবেন। আপনার দিনটি দারুণ কাটুক।"
35994,62607,"হেলো, নাসেনিয়া ডকে আপনাকে স্বাগতম। হ্যালুসিনেশনের কারণের ওপর চিকিৎসা নির্ভর করে। এই বয়সে যদি হ্যালুসিনেশন নতুন শুরু হয়ে থাকে, তবে কোনো শারীরিক অসুস্থতার কারণে ডেলিরিয়াম হচ্ছে কি না তা নিশ্চিত করার জন্য পরীক্ষা-নিরীক্ষার প্রয়োজন। যদি এটি দীর্ঘস্থায়ী হয়, তবে মনোরোগ বিশেষজ্ঞের তত্ত্বাবধানে রিসপেরিডোন-এর মাত্রা বাড়ানো যেতে পারে অথবা ওলানজাপাইন বা ক্লোজাপাইন-এর মতো অন্যান্য ওষুধ ব্যবহার করা যেতে পারে। আপনার সুস্বাস্থ্য ও মঙ্গল কামনা করি। www.99doctor.com"
36108,36109,"হেলো, আপনার রামসে-হান্ট সিনড্রোম (Ramsay-Hunt syndrome) আছে কিনা তা পরীক্ষা করার জন্য আপনার একজন নিউরোলজিস্ট বা ইএনটি (ENT) বিশেষজ্ঞের সাথে দেখা করা উচিত। আপনার উপসর্গগুলো এই ধরনের সমস্যার সাথে সামঞ্জস্যপূর্ণ, যা সময়ের সাথে সাথে নিজে থেকেই সেরে যায়। তবে ভাইরাসটি তার গতিপথ শেষ না করা পর্যন্ত আপনাকে আরাম দেওয়ার জন্য কিছু ওষুধ রয়েছে। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি। আমি আপনাকে আরও সাহায্য করতে পারি কিনা তা জানাতে www.bit.ly/ লিঙ্কে গিয়ে আমাকে প্রশ্ন পাঠান।"
36537,15703,"হেলো, আপনি কেমন আছেন? আমি নিশ্চিত যে আপনি যখন কালো জন্ডিসের কথা বলছেন তখন আপনি হেপাটাইটিস সি (কালি-পিলিয়া)-এর কথাই বোঝাচ্ছেন। তার জন্য সর্বোত্তম চিকিৎসার পরামর্শ দেওয়ার আগে কিছু পরীক্ষা করা প্রয়োজন। একটি সিভি আরএনএ পিসিআর (CV RNA PCR) এবং ভাইরাসের জেনোটাইপিং করা আবশ্যক, কারণ বিভিন্ন জেনোটাইপের জন্য ভিন্ন ভিন্ন চিকিৎসার প্রয়োজন হয় এবং চিকিৎসার প্রতি তাদের প্রতিক্রিয়াও ভিন্ন হয়। বেশিরভাগ গ্যাস্ট্রোএন্টেরোলজিস্ট হেপাটাইটিস সি-এর চিকিৎসায় বিশেষজ্ঞ এবং দিল্লির বেশিরভাগ হাসপাতালেও এর চিকিৎসার ব্যবস্থা রয়েছে। মানুষ চিকিৎসার জন্য লুধিয়ানাতেও যায়, কারণ পাঞ্জাবে হেপাটাইটিস সি-এর প্রকোপ বেশি এবং অনেক ডাক্তার এর চিকিৎসায় বিশেষজ্ঞ। আশা করি এটি সাহায্য করবে, এবং আরও কোনো তথ্যের প্রয়োজন হলে নির্দ্বিধায় আমার সাথে যোগাযোগ করুন - rxsuresh@gmail.com"

============================================================
6. EMAIL ADDRESSES
============================================================
input: 15 rows

,id,input
13076,95815,"আমার স্বামীর অগ্ন্যাশয়ের ক্যান্সার যা নিরাময়যোগ্য নয়... তার ডব্লিউবিসি ৪.৪, লিম্ফোসাইট ০.৪, গ্রানুলোসাইট ৮৬.০%, আরবিসি ৪.০৪, হিমোগ্লোবিন ১১.০, এইচসিটি ৩৫.৩ এবং এমসিএইচসি ৩১.২... আমি খুব চিন্তিত... তার নার্স প্র্যাকটিশনার আমাকে এগুলো ব্যাখ্যা করেননি... কোনো সাহায্য পেলে কৃতজ্ঞ থাকব... আমার ইমেইল angelicgaston@yahoo.com... ধন্যবাদ।"
18077,76137,"স্যার শুভ অপরাহ্ন, আমি একজন রোগী এবং আমি সুগারের জন্য ওষুধ সেবন করছি, কিন্তু এখন আমি জানতে পেরেছি যে আমি গর্ভবতী। তাই আমার কি ইনসুলিন ইনজেকশন প্রয়োজন? যদি প্রয়োজন হয়, তবে দয়া করে গুণমান এবং নামের বিবরণসহ পরামর্শ দিন। আমার যোগাযোগের বিবরণ নিচে দেওয়া হলো: 0000 bsingh228@gmail.com ধন্যবাদান্তে, সঙ্গীতা মোহান্তি।"
22373,53974,"আমি একজন কিডনি রোগী এবং আমার এইচবি ১১.৪০, কোলেস্টেরল ১১৮, ক্যালসিয়াম ৯.৫০, ফসফরাস ৩.৫০, ইউরিয়া ৭২, ক্রিয়েটিনিন ৩.৪৯। অনুগ্রহ করে আমাকে খাদ্যাভ্যাস সম্পর্কে পরামর্শ দিন এবং সম্ভব হলে ওষুধের বিষয়ে জানান। আমি নতুন দিল্লির ডঃ আর.এম.এল. হাসপাতালের নেফ্রোলজিস্ট ডঃ মহাপাত্রের অধীনে চিকিৎসাধীন আছি। অনুগ্রহ করে আমার ইমেইল nandapradeep2010@hotmail.com-এ উত্তরটি পাঠান। আমি এ বিষয়ে আপনার কাছে অত্যন্ত কৃতজ্ঞ থাকব।"
26986,85694,"আমার স্ত্রীর বয়স ২৫ বছর এবং তিনি বাইল্যাটারাল পিসিওডি (PCOD)-তে ভুগছেন, যা পেরিফেরাল ফ্যাশনে বিন্যস্ত। ডান ডিম্বাশয়ের আকার ৩৩.৫ মিমি * ২০.৫ মিমি (কোনো ফলিকল নেই) এবং বাম ডিম্বাশয়ের আকার ৩৬.৫ মিমি * ১৯.৫ মিমি (কোনো ফলিকল নেই)। আমাদের বিয়ের বয়স ২ বছর, এখনো কোনো সন্তান নেই। আমরা কি সন্তান জন্মদানে সফল হতে পারব? আমার ইমেইল আইডি arbind8@gmail.com।"
45938,67054,"আমার ছোট ভাই, যার বয়স প্রায় ২৮ বছর, তার ৮ বছর আগে যক্ষ্মা মেনিনজাইটিসের কারণে হাইড্রোসেফালাসের অস্ত্রোপচার হয়েছিল। মস্তিষ্কের বাধাগ্রস্ত অংশ দিয়ে সিএসএফ (CSF) প্রবাহের জন্য একটি শান্ট (নমনীয় টিউব) স্থাপন করা হয়েছিল। শান্টের টিউবটি শরীরের অন্য অংশে, যেমন পেটে নিয়ে যাওয়া হয়েছে। বর্তমানে তার অবস্থা ভালো, তবে মাঝে মাঝে সে দুর্বলতা ও শরীরে ব্যথা অনুভব করে। শান্টের টিউবটি কি অপসারণ করা সম্ভব? অনুগ্রহ করে আমাকে পরামর্শ দিন। nescoorganisation@yahoomail.com"
46405,69288,"হেলো, আমার বয়স ৩১, উচ্চতা ১.৮ মিটার এবং ওজন ৮৫ কেজি। আমার সমস্যা হলো, আমার প্রায়ই মাথার অর্ধেক অংশে প্রচণ্ড ব্যথা হয়, বিশেষ করে দিনের বেলায়, এবং তখন আমার মাড়ি থেকে রক্ত বের হতে দেখি। আমি এক্স-রে করিয়েছিলাম, কিন্তু ডেন্টিস্ট বলেছিলেন যে সমস্যাটি দাঁতের নয়, বরং মাড়ির। তাই আমাকে ৭ দিনের জন্য অ্যান্টিবায়োটিক (অ্যামোক্সিসিলিন) দেওয়া হয়েছিল। ঠিক এক বছর পর, আমি আবার সেই একই সমস্যায় (মাথার অর্ধেক অংশে প্রচণ্ড ব্যথা) ভুগছি। আমি আমার ডেন্টিস্টের কাছে গিয়েছিলাম এবং তিনি আমাকে ডাইক্লোফেনাক ও ক্লিনডামাইসিন দিয়েছেন। দয়া করে আমাকে পরামর্শ দিন এবং সাহায্য করুন। আমার ইমেইল হলো konnshira@yahoo.com।"
52350,26879,"স্যার, আমার লিভারে চর্বি জমার রোগ ধরা পড়েছে পাঁচ মাসেরও বেশি সময় আগে। তখন থেকেই রক্তে এসজিপিটি (SGPT) মাত্রা বেশি থাকার জন্য আমার চিকিৎসা চলছে। কিন্তু এটি এখনও স্বাভাবিক মাত্রার চেয়ে বেশি। শুরুতে একজন সুপরিচিত গ্যাস্ট্রোএন্টেরোলজিস্ট আমার চিকিৎসা করেছিলেন এবং এসজিপিটি মাত্রা অনেক কমে গিয়েছিল। কিন্তু পরবর্তীতে তা আবার বেড়ে যায় এবং তিনি সমস্যাটি খুঁজে বের করতে না পারার বিষয়ে তার অসহায়ত্বের কথা জানান। এরপর থেকে আমি একজন সরকারি আয়ুর্বেদিক ডাক্তারের কাছে চিকিৎসা নিচ্ছি। এখনও এটি স্বাভাবিক মাত্রার চেয়ে বেশি এবং তিনি আমাকে বলেছেন চিন্তার কিছু নেই, এটি ধীরে ধীরে কমে যাবে। স্যার, আপনি কি দয়া করে আমাকে সাহায্য করতে পারেন? আমার ইমেইল হলো= thoniummertk@gmail.com উম্মর টি কে, কেরালা।"
61445,17514,"হেলো, আমার বয়স ২২ বছর এবং আমার স্বামীর বয়স ২৪ বছর। দুই মাস আগে আমি গর্ভবতী হয়েছিলাম কিন্তু আমার গর্ভপাত হয়ে যায়। আমরা আবারও চেষ্টা করছি কিন্তু এটি অসম্ভব মনে হচ্ছে। গত মাসে আমি ক্লোমিড খেয়েছিলাম কিন্তু কোনো কাজ হয়নি। বর্তমানে আমি গর্ভধারণের জন্য নারীদের একটি ওষুধ খাচ্ছি। আমার প্রশ্ন হলো, এই ওষুধ কি কাজ করবে? joannereagan8@gmail.com"
62642,104360,"আমার ১৬ বছর বয়সী মেয়ের ২ মাস ধরে তীব্র পেটে ব্যথা হচ্ছে। তার পেলভিস ও পেটের আল্ট্রাসাউন্ড স্ক্যান, সিটি স্ক্যান, রক্ত ও প্রস্রাব পরীক্ষা করা হয়েছে। আমরা অন্য একজন ডাক্তারের পরামর্শ নিয়েছি এবং আবারও পরীক্ষা ও স্ক্যান করিয়েছি, কিন্তু কোনো কিছু ধরা পড়েনি। তার প্রস্রাবে ভাসমান সাদা কণা দেখা যাচ্ছে, সেই সাথে বমি ভাব ও তীব্র ব্যথা রয়েছে। সে ট্রামাল খাচ্ছে। একজন বিশেষজ্ঞের কাছে অ্যাপয়েন্টমেন্ট নেওয়া হয়েছে, কিন্তু আরও ছয় সপ্তাহ দেরি আছে। আমি তার কী হয়েছে তা জানার জন্য মরিয়া হয়ে আছি। তার এক শিক্ষক বলেছিলেন এটি মূত্রাশয়ে থ্রাশ হতে পারে, তাই গত শুক্রবার আমি ওরাল থ্রাশের ওষুধও খাইয়েছি, কিন্তু কোনো পরিবর্তন হয়নি। দয়া করে আমাদের সাহায্য করুন। ধন্যবাদ, অ্যালউইন ওয়াটসন, alwynwatson@msn.com"
64557,104386,"আমার স্ত্রী দীর্ঘ দিন ধরে (১৫ বছর) সোরিয়াসিসে ভুগছেন। তার বয়স ৪৮ বছর এবং দুই সন্তানের মা। তার ওজন ৮৬ কেজি এবং উচ্চতা ৫ ফুট ৩ ইঞ্চি। তিনি ডায়াবেটিসেও আক্রান্ত। আমি তার চিকিৎসার জন্য আপনার সাথে দেখা করতে চাই। আপনি কি অনুগ্রহ করে জানাবেন কখন এবং কীভাবে আমি আপনার সাথে যোগাযোগ করতে পারি? প্রাথমিক চিকিৎসা কী হবে? অনুগ্রহ করে আমাকে abdulmaleque@yahoo.com ইমেইল ঠিকানায় জানাবেন। ধন্যবাদ, আব্দুল মালেক।"
75648,58666,"আমার মনে হয় আমার হয়তো আলঝেইমার রোগ হচ্ছে। আমি কি আমার ক্যাশিয়ারের কাজ ঠিকমতো করতে পারব? আমার বসকে জিজ্ঞেস করেছিলাম, তিনি বলেছেন কোনো সমস্যা নেই—সামনের অফিস বন্ধ করা, দোকান লক করা, অ্যালার্ম সেট করা ইত্যাদি সব ঠিকঠাকই চলছে। কথা বলার সময় সমস্যা হচ্ছে, সঠিক শব্দটি খুঁজে পাচ্ছি না। শব্দ উল্টে যাচ্ছে, যেমন সকালের নাস্তাকে রাতের খাবার বলে ফেলছি, তবে বলার সাথে সাথেই নিজেকে শুধরে নিচ্ছি। গাড়ি চালানো, চেক বইয়ের হিসাব মেলানো, সপ্তাহে ৩ থেকে ৪ বার ব্যায়াম করা এবং বন্ধুদের সাথে সময় কাটানোয় কোনো সমস্যা নেই। আমার স্বামীর গত ৩ বছরে অনেক স্বাস্থ্য সমস্যা হয়েছে, ৪টি বড় অস্ত্রোপচার হয়েছে। এটি আমার জন্য খুব চাপের। আমার বয়স ৬৬ বছর, পার্ট-টাইম কাজ করি। আমি বেশ স্বাস্থ্যকর খাবার খাই, ধূমপান বা মদ্যপান করি না, কফি বা কোমল পানীয় খাই না, শুধু পানি পান করি এবং কোনো ওষুধ খাই না। আমার কি ডাক্তারের কাছে যাওয়া উচিত? ইমেইল ঠিকানা janrob4040@gmail.com"
85227,82539,"স্যার, আমার ৭ বছরের একটি কন্যা সন্তান আছে। আমি লক্ষ্য করেছি যে তার আচরণ একই বয়সী অন্যান্য শিশুদের তুলনায় স্বাভাবিক নয়। আমি এখন কী করতে পারি? অনুগ্রহ করে সাহায্য করুন। সঞ্জয় পাধি ০৯৭৭১১০২৪ sanjaybapu1@rediffmail.com"
101338,14625,"আমার নাকে ছোট ছোট দানা হয়েছে যা প্রথমে চুলকায়, তারপর নাকে দাগ ফেলে দেয়। এটি মিলিয়ে যেতে এক বা দুই সপ্তাহ সময় লাগে। এখন তিন সপ্তাহ পর আবার আমার নাকে চুলকানি হচ্ছে এবং দানাগুলো ফিরে আসছে। আমার বয়স ৩৫ বছর। আমার জানা দরকার আসলে কী হচ্ছে। আমার ইমেইল ঠিকানা হলো misstbutler@yahoo.com"
101948,109312,"আমার কাঁধের হাড় এবং বাহু বেয়ে নিচে ব্যথা হচ্ছে। ঘাড়ের দিকেও ব্যথা অনুভব করছি। বাম পায়ে অসাড়তাও আছে, আমার পিঠের সমস্যা আগে থেকেই ছিল। যখনই আমি আমার হাত কাঁধের উপরে তোলার চেষ্টা করি, তখন প্রচণ্ড ব্যথা হয়। দয়া করে আমার সাথে jmblakeney10@yahoo.com এ যোগাযোগ করুন। আমি পরামর্শের জন্য ওয়েবএমডি (WebMD) দেখেছিলাম। আমি এখন কাজ করছি না এবং আমার স্বামীর এমএস (MS) আছে, আমাদের কোনো টাকা নেই এবং এই মুহূর্তে আমার কোনো বিমাও নেই।"
107969,19991,"স্যার, আমার বয়স ২৫ বছর কিন্তু আমার মানসিক শক্তি খুব দুর্বল। প্রাকৃতিক বা ভেষজ সাপ্লিমেন্টের মাধ্যমে মানসিক শক্তি বৃদ্ধির জন্য আমাকে সাহায্য করুন। মস্তিষ্কের শক্তি বৃদ্ধির জন্য জিঙ্কগো বিলোবা এবং জিনসেং ব্যবহারের বিষয়ে আমাকে পরামর্শ দিন। আমার imransindhuonline@gmail.com ঠিকানায় জানান।"

output: 147 rows

,id,output
389,44494,"ভ্যারিকোসেল হলো অণ্ডকোষের শিরাগুলোর একটি কাঠামোগত পরিবর্তন, যেখানে সেগুলো দীর্ঘ এবং প্যাঁচানো হয়ে যায়। তাই, যদিও হোমিওপ্যাথিক ওষুধ সমস্যাটি কমাতে সাহায্য করতে পারে, তবে হোমিওপ্যাথির কার্যকারিতা সমস্যার কারণ এবং তীব্রতার ওপর নির্ভর করে। কিছু ক্ষেত্রে অস্ত্রোপচারের প্রয়োজন হতে পারে। আপনার দ্রুত কনস্টিটিউশনাল চিকিৎসার জন্য একজন অভিজ্ঞ হোমিওপ্যাথিক বিশেষজ্ঞের পরামর্শ নেওয়া উচিত। আপনার যা করা প্রয়োজন তা হলো, অণ্ডকোষকে সাপোর্ট দেওয়ার জন্য একটি সাপোর্টার বা টি-ব্যান্ডেজ ব্যবহার করা। ঢিলেঢালা সুতির প্যান্ট পরলে অণ্ডকোষ অতিরিক্ত গরম হওয়া থেকে রক্ষা পাবে। সাঁতারের মতো কার্যকলাপ অণ্ডকোষের তাপমাত্রা কম রাখতে সাহায্য করবে। গরম পানি দিয়ে গোসল করা বা স্টিম-বাথ নেওয়া এড়িয়ে চলুন। এটি আপনাকে বন্ধ্যাত্বের ঝুঁকি কমাতে সাহায্য করবে। ""ভ্যারিকোসেল সাধারণত ক্ষতিকারক নয়, তবে বন্ধ্যাত্বের ক্ষেত্রে এটি সমস্যা সৃষ্টি করতে পারে""। আশা করি আপনি দ্রুত সুস্থ হয়ে উঠবেন। নাসেনিয়া ডক। rs787878@gmail.com"
2724,110463,"হেলো, আপনি যে ইসিজি রিপোর্টটি পাঠিয়েছেন তা মেশিনে তৈরি, তাই অনেক সময় এটি ভুল হতে পারে। তবে তার বয়স এবং আপনার দেওয়া তথ্যের ভিত্তিতে আমি তাকে একটি টু-ডি ইকো (2D Echo) করার পরামর্শ দেব। যদি সেটি স্বাভাবিক থাকে, তবে স্ট্রেস টেস্ট করতে পারেন। কারণ আপনি যে ইসিজি পাঠিয়েছেন তাতে প্রোলংড পিআর (prolonged PR) দেখা গেছে, যা খুব একটা গুরুত্বপূর্ণ নয়, এবং অ্যান্টেরোল্যাটারাল পরিবর্তন দেখা গেছে, যার অর্থ হৃদপিণ্ডের এই অংশগুলোতে রক্ত সঞ্চালন কম হতে পারে। আরও স্পষ্ট ব্যাখ্যার জন্য আপনার ইসিজি রিপোর্টটি Priyankmody86@gmail.com-এ মেইল করুন। শুভেচ্ছা, নাসেনিয়া ডক।"
3127,61877,"হেলো মিস্টার মেইসি, সাত মাস ধরে মদ্যপান থেকে বিরত থাকার জন্য আপনাকে অবশ্যই অভিনন্দন জানাতে হয়। খুব বেশি মানুষ এটি করতে সক্ষম হয় না। আপনার ল্যাবের ফলাফল দেখে আমি বলব যে, আপনার পিত্তনালীতে কিছুটা স্লাজ বা কাদা জমেছিল, যা পিত্ত প্রবাহে বাধা সৃষ্টি করেছিল (উচ্চ এএলকে ফস)। এটি সম্ভবত আপনার লিভারের কোষগুলোকে ক্ষতিগ্রস্ত করেছে, যার ফলে আপনার লিভার এনজাইমের মাত্রা বৃদ্ধি পেয়েছে। আপনার সাম্প্রতিক ল্যাব রিপোর্টগুলো দেখাচ্ছে যে লিভারের ক্ষতি বেশ ভালোভাবেই সেরে উঠছে। একজন ডাক্তার হিসেবে আমি আপনাকে নাসেনিয়া ডকের পরামর্শ নিতে কঠোরভাবে নিষেধ করব। তবে যেহেতু আপনি ছুটিতে যাচ্ছেন, তাই এক-দুটি বিয়ার খেলে খুব একটা ক্ষতি হবে না। আশা করি আপনি আপনার ছুটি উপভোগ করবেন, এবং আরও কোনো প্রশ্ন থাকলে নির্দ্বিধায় আমার সাথে যোগাযোগ করবেন - rxsuresh@gmail.com"
3917,20158,"হেলো, নাসেনিয়া ডকে আপনাকে স্বাগতম! ফ্যাক্ট অয়েন্টমেন্টের সক্রিয় উপাদান হলো পলিক্রেসুলেন। এটি অর্শ এবং মলদ্বারের অন্যান্য সমস্যার সাথে সম্পর্কিত রক্তপাত, চুলকানি এবং জ্বালাপোড়া কমাতে সাহায্য করে। ফ্যাক্ট অয়েন্টমেন্ট চুলকানি এবং জ্বালাপোড়াও কমাতে পারে। তবে, এটি এনাল ফিশারের জন্য নির্দেশিত নয়। আমি আপনাকে সঠিক সময়ে রোগ নির্ণয় ও চিকিৎসার জন্য একজন বিশেষজ্ঞের (সার্জন) পরামর্শ নেওয়ার অনুরোধ করব। আপনার সুস্বাস্থ্য কামনা করছি! নাসেনিয়া ডক। ২০, প্যাচৌলি। kansalnaveen@gmail.com"
4799,89288,"হেলো, আপনি কেমন আছেন? আমার নাম নাসেনিয়া ডক। আমি লিভার এবং অগ্ন্যাশয় বিশেষজ্ঞ এবং আমি আশা করি আজ আপনার প্রশ্নের উত্তর দিতে পারব। ফ্যাটি লিভার অতিরিক্ত মদ্যপান (অ্যালকোহলিক স্টিয়াটো হেপাটাইটিস, এএসএইচ) বা অতিরিক্ত চর্বিযুক্ত খাবার গ্রহণ এবং অলস জীবনযাত্রার (নন-অ্যালকোহলিক স্টিয়াটো হেপাটাইটিস, এনএএসএইচ) কারণে হতে পারে। মানুষের খাদ্যাভ্যাসের অবনতি এবং অলস জীবনযাত্রার কারণে বর্তমানে এনএএসএইচ অনেক বেশি নির্ণয় করা হচ্ছে। ক্রমাগত মদ্যপান, উচ্চ ক্যালোরি গ্রহণ, উচ্চ চর্বিযুক্ত খাবার গ্রহণ এবং ব্যায়ামের অভাব লিভারের টিস্যুতে চর্বি জমার দিকে পরিচালিত করে, যার ফলে ফ্যাটি লিভার হয় (যা ইউএসজি-তে বর্ধিত ইকো টেক্সচার হিসেবে দেখা যায়)। রোগী যদি একটি স্বাস্থ্যকর জীবনধারা গ্রহণ করেন, মদ্যপান ত্যাগ করেন, ক্যালোরি গ্রহণ সীমিত করেন এবং নিয়মিত ব্যায়াম করেন তবে ফ্যাটি লিভার সম্পূর্ণভাবে নিরাময়যোগ্য। কিন্তু যদি এটি নিয়ন্ত্রণ না করা হয়, তবে রোগীরা সাধারণত স্থূল এবং ডায়াবেটিক হয়ে পড়েন এবং শেষ পর্যায়ে এটি লিভার সিরোসিসের দিকে নিয়ে যেতে পারে, যার জন্য লিভার প্রতিস্থাপনের প্রয়োজন হতে পারে। আপনার হার্নিয়াও রয়েছে বলে মনে হচ্ছে, যার অর্থ মূলত আপনার পেটের প্রাচীর দুর্বল হয়ে গেছে এবং অঙ্গগুলো বাইরের দিকে বেরিয়ে আসছে। আমি আপনাকে অবিলম্বে একজন সার্জনের সাথে পরামর্শ করার পরামর্শ দেব, বিশেষ করে অস্ত্রোপচারের প্রয়োজনীয়তার বিষয়ে মূল্যায়ন করার জন্য। আশা করি এটি সাহায্য করেছে, এবং আরও বিস্তারিত জানার জন্য আমার সাথে যোগাযোগ করতে দ্বিধা করবেন না - rxsuresh@gmail.com"
...,...,...
71598,40039,"হেলো, নাসেনিয়া ডকে আপনাকে স্বাগতম। কেমো এবং রেডিওথেরাপি না নেওয়ার সিদ্ধান্তের জন্য আমি আপনার প্রশংসা করছি। এটি তার রোগ প্রতিরোধ ক্ষমতা বাড়ানোর সময়, যাতে তার শরীর নিজেই রোগাক্রান্ত কোষগুলোর সাথে লড়াই করতে পারে। কেমো এবং রেডিও ক্যান্সার কোষের পাশাপাশি রোগ প্রতিরোধকারী কোষগুলোকেও মেরে ফেলে। তাই আপনার এমন একটি চিকিৎসার পরিকল্পনা করা উচিত যা রোগ প্রতিরোধ ক্ষমতা বাড়ায় এবং ক্যান্সার কোষের পুনরুৎপাদন রোধ করে। আমরা হোমো ইও (HOMO EO) এবং ওজোন থেরাপির সমন্বয়ে খুব ভালো ফলাফল পেয়েছি। যেকোনো সাহায্যের জন্য sufia_banu@yahoo.com-এ যোগাযোগ করুন।"
72155,8112,"হেলো, হেলথ কেয়ার ম্যাজিকে আপনাকে স্বাগতম। প্রথমত, আপনি গর্ভধারণ করতে পারেন। এর জন্য যদি আপনার ওজন বেশি থাকে তবে তা কমান এবং সব ধরনের দুশ্চিন্তা দূর করুন, কারণ মানসিক চাপ আপনার স্বাস্থ্যের ওপর প্রভাব ফেলতে পারে। আপনাকে থাইরয়েড, আরবিসি, এফএসএইচ, এলএইচ, প্রজেস্টেরন, ইস্ট্রোজেন এবং প্রোল্যাকটিনের মতো কিছু রক্ত পরীক্ষা করাতে হবে এবং একজন বিশেষজ্ঞ চিকিৎসকের পরামর্শ নিতে হবে, যিনি আপনাকে সঠিক ওষুধ দিতে পারবেন। আশা হারাবেন না। নিয়মিত ব্যায়াম এবং যোগব্যায়াম করুন। ধন্যবাদ, নাসেনিয়া ডক। shah84@yahoo.in"
72175,61387,"হেলো স্বাগতম, ডিস্কের সমস্যার কারণে চিন্তার কিছু নেই, শুধু এই সময়ে আপনাকে বিশ্রামে থাকতে হবে। ইনসুলিন বেড়ে যাওয়ার জন্য আপনাকে অবশ্যই ওষুধ খেতে হবে, অন্যথায় গর্ভধারণে সমস্যা হতে পারে। যাই হোক, এই ডিস্কের সমস্যাকে কখনোই সাধারণ বিষয় হিসেবে দেখবেন না এবং অস্ত্রোপচারের দিকেও যাবেন না, কারণ এটি কোনো বাড়তি বৃদ্ধি বা অপ্রয়োজনীয় অংশ নয় যা অপসারণ করতে হবে। এছাড়া আয়ুর্বেদ এবং পঞ্চকর্মের মাধ্যমে এর কার্যকর চিকিৎসা রয়েছে। আরও স্পষ্টীকরণের জন্য যোগাযোগ রাখুন christyjoseph1@gmail.com।"
73057,89090,"হেলো! নাসেনিয়া ডকের পক্ষ থেকে শুভেচ্ছা। আপনি কেন ভাবছেন যে আপনার ব্রেন টিউমার হয়েছে? ব্রেন টিউমারের লক্ষণগুলো টিউমারের অবস্থান এবং আকারের ওপর নির্ভর করে। যদি আকার বড় হয়, তবে এটি ইন্ট্রাক্রেনিয়াল চাপ বাড়িয়ে দেয়। এতে আপনার তীব্র মাথাব্যথা এবং বমি হতে পারে। শারীরিক লক্ষণগুলো পুরোপুরি টিউমারের অবস্থান এবং আকারের ওপর নির্ভর করে। নাক দিয়ে রক্ত পড়া মানেই যে ব্রেন টিউমার, তা নয়। ক্লান্তি এবং মনোযোগের অভাব আপনার অতিরিক্ত মানসিক চাপ বা সময়মতো খাবার না খাওয়ার ফলে হাইপোগ্লাইসেমিয়ার কারণে হতে পারে। গ্যাসের সমস্যা আপনার খাবারের ধরন, খাওয়ার সময় এবং কোনো ওষুধ সেবনের ওপর নির্ভর করে। বিষণ্নতা এবং উদ্বেগ বুক ধড়ফড়ানির কারণ। উদ্বেগ এবং রক্তস্বল্পতা শ্বাসকষ্টের অন্যতম কারণ। তাই আপনি যে লক্ষণগুলোর কথা বলছেন, তার সবই যে ব্রেন টিউমারের লক্ষণ তা নয়। ব্রেন টিউমার শুধুমাত্র মস্তিষ্কের সিটি স্ক্যান বা এমআরআই-এর মাধ্যমেই নিশ্চিত করা সম্ভব। আপনার সব লক্ষণ সঠিক চিকিৎসার মাধ্যমে নিয়ন্ত্রণ করা সম্ভব। যদি আপনার কোনো ইন্স্যুরেন্স না থাকে, তবে আমি আপনাকে হোমিওপ্যাথি চিকিৎসা শুরু করার পরামর্শ দেব। সঠিক হোমিওপ্যাথি চিকিৎসার মাধ্যমে এটি ভালোভাবে নিয়ন্ত্রণ করা সম্ভব। আপনি যদি হোমিওপ্যাথি চিকিৎসা নেওয়ার সিদ্ধান্ত নেন, তবে আমার সাথে যোগাযোগ করতে পারেন। আপনার স্বাস্থ্যকে স্বাভাবিক অবস্থায় ফিরিয়ে আনতে পারলে আমি খুশি হব। আমার সাথে যোগাযোগ করুন multicare.homeo@yahoo.com এই ঠিকানায় অথবা ভিজিট করুন www.multicarehomeopathy.com ধন্যবাদ।"
73107,110539,"হেলো, নাসেনিয়া ডকে পোস্ট করার জন্য আপনাকে ধন্যবাদ। আপনার ভাইয়ের ত্বকের ক্ষত নিয়ে আপনার উদ্বেগ আমি বুঝতে পারছি। মনে হচ্ছে তার কোনো ছত্রাকজনিত ত্বকের সংক্রমণ (টিনিয়া) হয়েছে, তবে সরাসরি শারীরিক পরীক্ষা ছাড়া সুনির্দিষ্ট রোগ নির্ণয় করা কঠিন। তাই, আমি আপনাকে অনুরোধ করছি ভালো মানের কিছু ছবি এখানে পোস্ট করার জন্য, যাতে আমি আপনাকে আরও ভালোভাবে সাহায্য করতে পারি। আপনি attachments@ChatDoctor.com এই ঠিকানায় ইমেইল করতে পারেন এবং সাবজেক্টে লিখবেন ATTN Chat Doctor। ধন্যবাদ।"

============================================================
7. HTML / MARKUP
============================================================

/tmp/ipykernel_189/1923704581.py:142: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df_cleaned[col].str.contains(

input: 3 rows

,id,input
13994,42897,"স্যার, আমি আজ ইসিজি করিয়েছি, রিপোর্টে লেখা আছে ""অ্যান্টেরোল্যাটারাল ইস্কেমিয়ার সাথে সামঞ্জস্যপূর্ণ এসটি এবং টি ওয়েভ অস্বাভাবিকতা [I/AVL/V3-V6 এ -0.5+MV টি ওয়েভ], এসটি এবং টি ওয়েভ অস্বাভাবিকতা, সম্ভাব্য ইনফেরিয়র ইস্কেমিয়া [II/AVF এ -0.1+MV টি ওয়েভ]। ট্রেডমিল এফোর্ট টলারেন্স ভালো। আমি বিপি ওষুধ (কোভেন্স ২৫) খাই। আমি অ্যালকোহল পান করি। আমার বুকে কোনো ব্যথা নেই তবে মাঝে মাঝে সামান্য মাথা ঘোরা অনুভব করি। আপনার পরামর্শ কী?"
60827,62330,"আমি বাম ভেন্ট্রিকুলার এ-ফিব (a-fib)-এ ভুগেছিলাম। কার্ডিওভার্সনের মাধ্যমে এটি পুরোপুরি সেরে গেছে। চিকিৎসার পর থেকে বেশ কয়েক বছর ধরে বাইস্টোলিক (Bystolic) সেবন করছি। আমার পেরিফেরাল নিউরোপ্যাথি দেখা দিয়েছে যা ক্রমশ খারাপ হচ্ছে। আমার সীমিত গবেষণায় মনে হচ্ছে এটি ওষুধের একটি পার্শ্বপ্রতিক্রিয়া। আমি আমার রক্তে শর্করার পরীক্ষা করিয়েছি এবং তা স্বাভাবিক আছে। এছাড়া আমি খুব ভালো স্বাস্থ্যের অধিকারী। সঠিক খাবার খাই, ব্যায়াম করি ইত্যাদি। (মেট্রোপোল [metropolol]-এ আমার খুব খারাপ প্রতিক্রিয়া হয়েছিল - হাঁপানি। বাইস্টোলিক আমার জন্য দারুণ কাজ করেছে।) (১) নিউরোপ্যাথি কি নিরাময়যোগ্য (যদি বাইস্টোলিক এর কারণ হয়)? (২) এর সমতুল্য অন্য কোনো ওষুধ আছে কি?"
63769,82531,"হেলো ডাক্তার, আমি ভারতের ২৪ বছর বয়সী একজন পুরুষ। ২৯ জানুয়ারি ২০০৯ তারিখের আমার এমআরআই রিপোর্টে লেখা আছে: [u][b] Diffuse L3/4, L4/L5 disc bulge along with primary lumbar canal stenosis compressing thecal sac & bilateral exiting nerve roots [/b][/u]। স্যার, আমি বেশ কয়েক বছর ধরে পিঠের ব্যথায় ভুগছি। গত দুই বছর মোটামুটি ভালোই ছিলাম, কিন্তু গত এক মাস ধরে অবস্থা খুব খারাপ। আমি একজন সফটওয়্যার ইঞ্জিনিয়ার, তাই দিনে ৮ ঘণ্টার বেশি কম্পিউটারের সামনে বসে থাকতে হয়। আমার উচ্চতা ৬ ফুট। ছয় মাস আগে আমার ওজন ছিল ৯০ কেজি, আমি তখন অতিরিক্ত ওজনের ছিলাম। এরপর ডায়েট কন্ট্রোল, ট্রেডমিলে দৌড়ানো এবং বিভিন্ন কার্ডিও ব্যায়াম, অ্যাবস এক্সারসাইজ, পুশ-আপ, পুল-আপ, চিন-আপ এবং হালকা ওয়েট ট্রেনিংয়ের মাধ্যমে সাড়ে ৩ মাসে ২০ কেজি ওজন কমিয়ে ফেলি। সেই সময় আমি আমার পিঠের ব্যথা নিয়ে খুব আত্মবিশ্বাসী ছিলাম, ভেবেছিলাম অতিরিক্ত ওজন কমানোর সাথে সাথে ব্যথাও চলে গেছে। এরপর আমি পেশী গঠনের জন্য বিভিন্ন ওয়েট ট্রেনিং শুরু করি। তখন কোনো ব্যথা ছিল না এবং আমি খুব খুশি ছিলাম। কিন্তু এক মাস পর আবার খুব বাজেভাবে পিঠের ব্যথা শুরু হয়। তখন আমি ব্যায়াম বন্ধ করে ফিজিওথেরাপিস্ট এবং ইন্টারনেটের সাহায্য নিয়ে বাড়িতে স্ট্রেচিং শুরু করি, তাতে কিছুটা আরাম পাই। কিন্তু আবার হালকা ব্যায়াম শুরু করতেই ব্যথা ফিরে আসে। এখন আমি ব্যায়াম বন্ধ করে বাড়িতে স্ট্রেচিং করছি, কিন্তু ব্যথা এখনো রয়ে গেছে। আপনি কি আমাকে পথ দেখাতে পারেন যে আমার কী করা উচিত? আমার জন্য কোন ধরনের ব্যায়াম ভালো এবং কোনগুলো করা একদমই উচিত নয়? আমি ফিট থাকতে চাই এবং পেশী গঠন করতে চাই কারণ আমি এখন খুব রোগা দেখাচ্ছি, কিন্তু তা করতে পারছি না। দয়া করে আমাকে সাহায্য করুন। আমি কীভাবে এই ব্যথা থেকে মুক্তি পাব এবং কোন কাজগুলো আমার একেবারেই করা উচিত নয়? স্বাভাবিক জীবনে, অর্থাৎ অফিসে এবং জিমে ব্যথা ছাড়া ফিরে যাওয়ার জন্য আমার কী ধরনের চিকিৎসা বা ওষুধ প্রয়োজন? গতবার যখন একজন স্পাইন বিশেষজ্ঞের কাছে গিয়েছিলাম, তিনি আমাকে সামনের দিকে ঝুঁকতে বলেছিলেন এবং পরীক্ষা করে বলেছিলেন যে আমি ঠিক আছি, আমার খুব ধীরে ধীরে কিছু ব্যায়াম করা উচিত। তিনি আমাকে কোনো ওষুধ দেননি।"

/tmp/ipykernel_189/1923704581.py:142: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df_cleaned[col].str.contains(

output: 26 rows

,id,output
7039,27417,"হেলো, আপনার সংক্ষিপ্ত ইতিহাস প্রদানের জন্য ধন্যবাদ। প্যানহাইপোপিটুইটারিজম কী তা জানার জন্য নিচে উল্লিখিত তথ্য আপনাকে বুঝতে সাহায্য করবে। পটভূমি: পিটুইটারি গ্রন্থিকে শরীরের প্রধান এন্ডোক্রাইন গ্রন্থি বলা হয় কারণ এটি অন্যান্য এন্ডোক্রাইন অঙ্গের কার্যকারিতা নিয়ন্ত্রণ করে। অগ্র পিটুইটারি থাইরোট্রপিন (থাইরয়েড-স্টিমুলেটিং হরমোন [TSH]), কর্টিকোট্রপিন উৎপাদন করে। অগ্র পিটুইটারি নির্দিষ্ট হাইপোথ্যালামিক-রিলিজিং হরমোন দ্বারা নিয়ন্ত্রিত হয়। পশ্চাৎ পিটুইটারি ডেস্মোপ্রেসিন (অ্যান্টিডিউরেটিক হরমোন [ADH]) এবং অক্সিটোসিন উৎপাদন করে। প্যানহাইপোপিটুইটারিজম হলো এমন একটি অবস্থা যেখানে অগ্র পিটুইটারি হরমোনের উৎপাদন অপর্যাপ্ত বা অনুপস্থিত থাকে। এটি প্রায়শই অন্যান্য সমস্যার ফলাফল যা পিটুইটারি গ্রন্থিকে প্রভাবিত করে এবং এর কার্যকারিতা হ্রাস বা ধ্বংস করে অথবা বিভিন্ন পিটুইটারি-রিলিজিং হরমোনের হাইপোথ্যালামিক নিঃসরণে বাধা দেয়। প্যানহাইপোপিটুইটারিজম বিভিন্ন ক্লিনিকাল পরিস্থিতির চূড়ান্ত ফলাফল হতে পারে। এর লক্ষণ ও উপসর্গগুলো বৈচিত্র্যময়। যেহেতু পিটুইটারি গ্রন্থি সবকিছুর প্রধান, তাই এতে যেকোনো অস্বাভাবিকতা গ্রোথ হরমোনসহ বিভিন্ন সমস্যার সৃষ্টি করতে পারে। একজন চিকিৎসকের পরামর্শ নিলে পরিস্থিতির গভীরতা সম্পর্কে আরও জানা যাবে। এছাড়াও, বিপাক বিঘ্নিত হওয়ার কারণে ক্লান্তি সাধারণ বিষয় এবং এটি পেশী ও জয়েন্টে ব্যথা এবং যন্ত্রণার কারণ হতে পারে। ফিজিওথেরাপি গ্রহণ করলে বিপাক ও রোগ প্রতিরোধ ক্ষমতা উন্নত করতে সাহায্য করবে। শুভেচ্ছা, জে ইন।"
20113,52206,"হেলো, আমি আপনার প্রশ্নটি পড়েছি। এটি কার্পাল টানেল রোগের কারণে হতে পারে। কার্পাল টানেলে কব্জির ফ্লেক্সর রেটিনাকুলামের নিচে টেন্ডনে শোথ বা ইডিমা হয়। চাপের বৃদ্ধির কারণে মিডিয়ান নার্ভ সংকুচিত হয়, যা অসাড়তার সৃষ্টি করে। আপনি আপনার ফিজিওথেরাপিস্টকে কার্পাল টানেলের থেরাপির জন্য জিজ্ঞাসা করতে পারেন। আল্ট্রাসাউন্ড এবং টেন্স (TENS) সহ ফিজিওথেরাপি আপনাকে সাহায্য করবে। দ্রুত নিরাময়ের জন্য আপনি ট্যাব কোলিন [it C] এবং অ্যান্টি-ইনফ্ল্যামেটরি সহ অ্যান্টিঅক্সিডেন্ট [ট্যাব এনজাইমিক প্লাস] নিতে পারেন। আপনার ডাক্তারের পরামর্শ নিয়ে মিথাইলকোবালামিন এবং প্রিগাবালিনের মতো ওষুধ শুরু করা যেতে পারে। আরেকটি সম্ভাবনা হলো সার্ভিকাল ডিস্ক বাল্জ, যা কব্জির সমস্যার কারণ হতে পারে। আপনার ডাক্তারের ক্লিনিকাল পরীক্ষা রোগ নির্ণয় নিশ্চিত করবে। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আপনার যদি আরও কোনো প্রশ্ন বা ফলো-আপ জিজ্ঞাসা থাকে, তবে আমাদের লিখতে দ্বিধা করবেন না। আমি আপনার প্রশ্নের উত্তর দিতে পেরে খুশি হব। আপনার সুস্বাস্থ্য কামনা করছি। ভালো থাকবেন। শুভেচ্ছা, নাসেনিয়া ডক।"
21318,90452,"১. যেহেতু আপনার কোমরের নিচের অংশ [L4/L5] শরীরের বেশিরভাগ ওজন বহন করে, তাই এটি নিম্ন পিঠের ব্যথার (LBA) ক্ষেত্রে সবচেয়ে বেশি আক্রান্ত এলাকা। ২. এমনকি যদি আপনি ডাক্তার দেখাতে পছন্দ না করেন, তবুও অস্ত্রোপচার বা রক্ষণশীল (দ্বিতীয় মতামত) চিকিৎসার আগে সমস্ত প্রাসঙ্গিক পরীক্ষা-নিরীক্ষা [প্রোল্যাপসড ইন্টারভার্টিব্রাল ডিস্ক বা স্নায়ুর ওপর চাপ আছে কিনা তা দেখার জন্য] নিশ্চিত করুন। এর ভিত্তিতে আপনার রোগের জন্য আয়ুর্বেদিক চিকিৎসা পদ্ধতি নিচে নির্দেশিত হবে।"
26098,21029,"হেলো, আমাদের কাছে লেখার জন্য ধন্যবাদ। রেনাল অ্যাঞ্জিওমায়োলিপোমা হলো চর্বি, পেশী এবং রক্তনালী দ্বারা গঠিত এক ধরনের বিনাইন বা নিরীহ টিউমার। এর চিকিৎসা নির্ভর করে অ্যাঞ্জিওমায়োলিপোমার আকারের ওপর। ছোট এবং উপসর্গহীন টিউমারগুলো (< ৪ সেমি) সাধারণত স্থিতিশীল থাকে, তবে পর্যায়ক্রমে সেগুলোর মূল্যায়ন করা উচিত। মাঝারি আকারের টিউমারগুলোর (৪-৮ সেমি) ক্ষেত্রে আচরণ সবচেয়ে পরিবর্তনশীল হতে পারে। এই টিউমারগুলোকে নিয়মিত ইমেজিং পরীক্ষার মাধ্যমে নিবিড় পর্যবেক্ষণে রাখা উচিত। যদি আকারে উল্লেখযোগ্য পরিবর্তন বা কোনো উপসর্গ দেখা দেয়, অথবা রোগীর কোমরের দিকে আঘাত পাওয়ার ঝুঁকি থাকে, তবে কিডনি বাঁচানোর সম্ভাবনা বাড়াতে দ্রুত ঐচ্ছিক চিকিৎসার ব্যবস্থা নেওয়া উচিত। বড় আকারের উপসর্গহীন অ্যাঞ্জিওমায়োলিপোমাগুলো (> ৮ সেমি) খুব সম্ভবত ভবিষ্যতে উপসর্গ তৈরি করবে, তাই উপসর্গ এবং সম্ভাব্য জটিলতা দেখা দেওয়ার আগেই সেগুলোর ঐচ্ছিক চিকিৎসা করা উচিত। যেহেতু আপনার মায়ের টিউমারটির আকার ৬.৭ সেমি, তাই অস্ত্রোপচারের কথা ভাবার আগে আগামী ৬ মাস এর আকার বৃদ্ধি এবং মূত্রনালীর কোনো উপসর্গ আছে কি না, তা পর্যবেক্ষণ করার জন্য অপেক্ষা করা যেতে পারে।"
31271,19796,"হেলো, টেনোসিনোভাইটিস কব্জিতে ব্যথার কারণ হতে পারে। টেনোসিনোভাইটিস টেন্ডনের প্রদাহ এবং ফোলাভাবের কারণে হয়। শুধুমাত্র ওষুধের মাধ্যমে টেন্ডনের ফোলাভাব নাও কমতে পারে। লোকাল স্টেরয়েড ইনজেকশন ভালো ফলাফল দিতে পারে, এর সাথে ফিজিওথেরাপি মেশিনের প্রোটোকল আপনার ব্যথা এবং ফোলাভাব কমাতে পারে, আপনি আপনার ফিজিওথেরাপিস্টকে ওয়াক্স বাথ থেরাপির কথা জিজ্ঞাসা করতে পারেন। ফোলাভাব, প্রদাহ এবং ব্যথা কমাতে আইস প্যাক ব্যবহার করুন। আল্ট্রাসাউন্ড এবং টেন্স (TENS) সহ ফিজিওথেরাপি আপনাকে সাহায্য করবে। দ্রুত নিরাময়ের জন্য আপনি ট্যাব কোলিন [it C] এবং অ্যান্টি-ইনফ্ল্যামেটরি সহ অ্যান্টিঅক্সিডেন্ট [ট্যাব এনজাইমিক প্লাস] নিতে পারেন। যদি সমস্যার সমাধান না হয় তবে আপনার এমআরআই (MRI) প্রয়োজন হতে পারে। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আপনার যদি আরও কোনো প্রশ্ন বা ফলো-আপ জিজ্ঞাসা থাকে তবে আমাদের লিখতে দ্বিধা করবেন না। আমি আপনার প্রশ্নের উত্তর দিতে পেরে খুশি হব। আপনার সুস্বাস্থ্য কামনা করছি। ভালো থাকবেন।"
31303,97939,"হেলো স্যার/ম্যাডাম। শুভ সন্ধ্যা। অনুসন্ধানের জন্য ধন্যবাদ। আপনার দেওয়া তথ্য অনুযায়ী, দুটি বিষয় স্পষ্ট ১. ডায়াবেটিক ২. রক্তস্বল্পতা <হিমোগ্লোবিন ৭>। কিন্তু সিবিসি <টিএলসি, ডিএলসি>, এলএফটি, কেএফটি এবং বুকের এক্স-রে সম্পর্কে কোনো তথ্য নেই, তাই মৃত্যুর কারণ সম্পর্কে মন্তব্য করা খুব কঠিন। তিনি ইনসুলিন নিচ্ছিলেন কি না বা উল্লিখিত সমস্যার জন্য কী চিকিৎসা নিচ্ছিলেন তা স্পষ্ট নয়। অনিয়ন্ত্রিত ডায়াবেটিস রোগীদের ক্ষেত্রে সংক্রমণ, হাইপোগ্লাইসেমিক এপিসোড এবং সাইলেন্ট হার্ট অ্যাটাক সাধারণ বিষয়। কম হিমোগ্লোবিনের মাত্রা, মুখ দিয়ে ফেনা ওঠা এবং হাত-পা ঠান্ডা হয়ে যাওয়া সাইলেন্ট হার্ট অ্যাটাকের দিকে ইঙ্গিত করে। ধন্যবাদ।"
31593,77000,"হেলো। প্রথমে আমি আপনাকে এক্স-রে করার পরামর্শ দেব যাতে আপনার আঙুলে কোনো ইউনিকর্টিক্যাল ফ্র্যাকচার আছে কিনা তা নিশ্চিত হওয়া যায়। আপনার বর্ণনা অনুযায়ী, আঘাতের কারণে নরম টিস্যুতে চোট পাওয়ার সম্ভাবনা রয়েছে। যদি আপনার ফোলাভাব এবং ব্যথা থাকে, তবে জয়েন্টকে সঠিক বিশ্রাম দেওয়ার জন্য আপনি আপনার আঙুলটি স্ট্র্যাপ দিয়ে বেঁধে রাখতে পারেন। সাপোর্ট এবং কমপ্রেশনের জন্য ক্রেপ ব্যান্ডেজ ব্যবহার করুন। ফোলাভাব, প্রদাহ এবং ব্যথা কমাতে আইস প্যাক ব্যবহার করুন। আল্ট্রাসাউন্ড এবং টেন্স (TENS) সহ ফিজিওথেরাপি আপনার জন্য সহায়ক হবে। দ্রুত সেরে ওঠার জন্য আপনি ট্যাব কোলিন [it C] এবং অ্যান্টি-ইনফ্ল্যামেটরি সহ অ্যান্টিঅক্সিডেন্ট [ট্যাব এনজাইমিক প্লাস] গ্রহণ করতে পারেন। যদি এতে কোনো উপশম না হয়, তবে আপনাকে পুনরায় ডাক্তারের পরামর্শ নিতে হতে পারে। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আপনার যদি আরও কোনো প্রশ্ন বা ফলো-আপ জিজ্ঞাসা থাকে, তবে আমাদের লিখতে দ্বিধা করবেন না। আমি আপনার প্রশ্নের উত্তর দিতে পেরে খুশি হব। আপনার সুস্বাস্থ্য কামনা করছি। ভালো থাকবেন।"
33419,26315,"হেলো, আমি আপনার প্রশ্নটি পড়েছি, কার্পাল টানেল সিনড্রোম নাসেনিয়া ডক। কার্পাল টানেলে ফ্লেক্সর রেটিনাকুলামের নিচে কব্জির টেন্ডনের ওপর এডিমা বা ফোলাভাব হয়। চাপের বৃদ্ধির কারণে মিডিয়ান নার্ভ সংকুচিত হয়, যার ফলে ব্যথা এবং জড়তা দেখা দেয়। আপনি আপনার ফিজিওথেরাপিস্টকে কার্পাল টানেলের থেরাপির জন্য জিজ্ঞাসা করতে পারেন। আল্ট্রাসাউন্ড এবং টেন্স (TENS) সহ ফিজিওথেরাপি আপনাকে সাহায্য করবে। দ্রুত নিরাময়ের জন্য আপনি ট্যাব কোলিন [it C] এবং অ্যান্টি-ইনফ্ল্যামেটরি সহ অ্যান্টিঅক্সিডেন্ট [ট্যাব এনজাইমিক প্লাস] নিতে পারেন। আরেকটি সম্ভাবনা হলো সার্ভিকাল ডিস্ক বাল্জ, যা হাতের জড়তার কারণ হতে পারে। আপনার ডাক্তারের ক্লিনিকাল পরীক্ষা রোগ নির্ণয় নিশ্চিত করবে। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আপনার যদি আরও কোনো প্রশ্ন বা ফলো-আপ জিজ্ঞাসা থাকে, তবে আমাদের লিখতে দ্বিধা করবেন না। আমি আপনার প্রশ্নের উত্তর দিতে পেরে খুশি হব। আপনার সুস্বাস্থ্য কামনা করছি। ভালো থাকবেন। শুভেচ্ছা।"
37011,78591,"হেলো, আপনার প্রশ্নটি পোস্ট করার জন্য ধন্যবাদ। আপনি যে লক্ষণগুলোর কথা উল্লেখ করছেন তা সম্পূর্ণ স্বাভাবিক। এই ধরনের ঝিঁঝিঁ ধরা অনুভূতি ১২-১৫ দিন বা তার বেশি সময় থাকতে পারে এবং ধীরে ধীরে কমে আসবে। যখন আপনার মাড়ি ও দাঁতের স্নায়ু দাঁত তোলার জায়গার খুব কাছাকাছি থাকে, তখন কিছুটা চাপ পড়ে এবং এর ফলে ঝিঁঝিঁ ধরার মতো অনুভূতি হতে পারে। একটি অর্থোপ্যান্টোমোগ্রাফ [OPG] এক্স-রে আপনাকে ক্ষতটির ব্যাপ্তি এবং সম্ভাব্য ফলাফল সম্পর্কে জানতে সাহায্য করবে। যদি অসাড়তা কোনো ফোড়ার কারণে হয়, তবে অ্যান্টিবায়োটিকের একটি কোর্স শেষ করার পর তা কমে যাওয়া উচিত। যদি এটি বিদ্যমান কোনো ক্ষতের কারণে হয়, তবে সেই অনুযায়ী চিকিৎসা করতে হবে। আমি আপনাকে এ বিষয়ে আপনার ডেন্টিস্টের সাথে পরামর্শ করার পরামর্শ দিচ্ছি। শুভেচ্ছা।"
46687,69129,"হেলো, ফিজিওথেরাপি মেশিন ব্যবহার করলে আপনার ব্যথা ও ফোলাভাব কমতে পারে, আপনি আপনার ফিজিওথেরাপিস্টকে সিটিএস (CTS)-এর থেরাপির জন্য জিজ্ঞাসা করতে পারেন। প্রদাহ কমাতে আইস প্যাক ব্যবহার করুন। আল্ট্রাসাউন্ড এবং টেন্স (TENS) সহ ফিজিওথেরাপি আপনাকে সাহায্য করবে। দ্রুত নিরাময়ের জন্য আপনি ট্যাব কোলিন [it C] এবং অ্যান্টি-ইনফ্ল্যামেটরি সহ অ্যান্টিঅক্সিডেন্ট [ট্যাব এনজাইমিক প্লাস] নিতে পারেন। যদি এতে উপশম না হয়, তবে আপনি কার্পাল টানেল রিলিজ সার্জারির কথা ভাবতে পারেন। এছাড়াও, কার্পাল টানেলের পুনরাবৃত্তি এড়াতে এর মূল কারণ কমানোর জন্য কাজ করুন। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আপনার যদি আরও কোনো প্রশ্ন বা ফলো-আপ জিজ্ঞাসা থাকে, তবে আমাদের লিখতে দ্বিধা করবেন না। আমি আপনার প্রশ্নের উত্তর দিতে পেরে খুশি হব। আপনার সুস্বাস্থ্য কামনা করছি। ভালো থাকবেন।"
54757,104639,"১. যেহেতু আপনার কোমরের নিচের অংশ [L4/L5] শরীরের বেশিরভাগ ওজন বহন করে, তাই এটি লো ব্যাক পেইন (LBA)-এর ক্ষেত্রে সবচেয়ে বেশি আক্রান্ত হয়। যেহেতু রক্ষণশীল চিকিৎসার পরেও লক্ষণগুলো আবার ফিরে এসেছে, তাই স্নায়ুর কোনো চাপ বা সরু হয়ে যাওয়ার সমস্যা আছে কিনা তা দেখার জন্য এক্স-রে এলএস-স্পাইন এবং এমআরআই করান।\n\n২. এমনকি যদি আপনি ডাক্তার দেখাতে পছন্দ না করেন, তবুও অস্ত্রোপচার বা রক্ষণশীল (দ্বিতীয় মতামত) চিকিৎসার আগে সমস্ত প্রাসঙ্গিক পরীক্ষা-নিরীক্ষা [যেমন প্রোল্যাপসড ইন্টারভার্টিব্রাল ডিস্ক বা স্নায়ুর ওপর কোনো চাপ আছে কিনা] নিশ্চিত করুন। এরপর আপনার রোগের জন্য আয়ুর্বেদিক চিকিৎসা পদ্ধতি নিচে নির্দেশিত হবে।"
57888,92592,"হেলো। নাসেনিয়া ডকে আপনাকে স্বাগতম। আমি আপনার প্রশ্নটি পড়েছি এবং আপনার উদ্বেগ বুঝতে পারছি। আপনার অভিযোগ অনুযায়ী মনে হচ্ছে যে, মুখ অতিরিক্ত হাঁ করা এবং ঝাকুনিপূর্ণ নড়াচড়ার কারণে আপনার চোয়ালের কন্ডাইল [চোয়ালের যে অংশটি মাথার খুলির নিচের অংশের সাথে সংযোগ তৈরি করে] স্থানচ্যুত হয়েছে। যেহেতু চোয়ালের কেবল এক পাশ স্থানচ্যুত হয়েছে, তাই আপনার চোয়াল বেঁকে গিয়েছিল। অনেক সময় স্থানচ্যুত চোয়াল নিজে থেকেই বা ডেন্টিস্টের মাধ্যমে ম্যানুয়ালি আগের অবস্থানে ফিরে আসে। তবে ক্লিকিং শব্দ হওয়ার কারণ হতে পারে আর্টিকুলার ডিস্কের কোনো অস্বাভাবিকতা, যা জয়েন্টের দুটি হাড়ের অংশের মধ্যে থাকা একটি নরম কুশন। এটি তার জায়গা থেকে সরে যেতে পারে বা ছিঁড়ে যেতে পারে, যার ফলে ক্লিকিং শব্দ হয়। আপনার সতর্ক থাকা উচিত, কারণ আপনি যদি আবার মুখ খুব বেশি হাঁ করেন, তবে চোয়াল আবারও স্থানচ্যুত হতে পারে। আমি আপনাকে একজন ওরাল ফিজিশিয়ানের সাথে পরামর্শ করার এবং একটি অর্থোপ্যান্টোমোগ্রাম [OPG] করিয়ে অস্বাভাবিকতা নির্ণয় করে সেই অনুযায়ী চিকিৎসা নেওয়ার পরামর্শ দিচ্ছি। আপনি জয়েন্টের ওপর গরম সেঁক দিতে পারেন। ক্লোরজোক্সাজোন-এর মতো মাসল রিলাক্স্যান্ট এবং আইবুপ্রোফেন-এর মতো ব্যথানাশক ওষুধের সংমিশ্রণ গ্রহণ করুন। নরম খাবার খান এবং মুখ খুব বেশি হাঁ করা থেকে বিরত থাকুন। আশা করি এই তথ্যটি আপনার উপকারে আসবে। ধন্যবাদ এবং শুভেচ্ছা। নাসেনিয়া ডক।"
58991,6588,"হেলো। মেটাকার্পাল বা ফ্যালাঞ্জিয়াল জয়েন্টের লিগামেন্টে আঘাতের সম্ভাবনা রয়েছে। এই ধরনের অভ্যাসের কারণে ভবিষ্যতে হাতের জয়েন্টে আর্থ্রাইটিস হতে পারে। ফোলাভাব, প্রদাহ এবং ব্যথা কমাতে আইস প্যাক ব্যবহার করুন। আল্ট্রাসাউন্ড এবং টেন্স (TENS) সহ ফিজিওথেরাপি আপনাকে সাহায্য করবে। দ্রুত নিরাময়ের জন্য আপনি ট্যাব কোলিন [it C] এবং অ্যান্টি-ইনফ্ল্যামেটরি সহ অ্যান্টিঅক্সিডেন্ট [ট্যাব এনজাইমিক প্লাস] নিতে পারেন। যদি কোনো উপশম না হয়, তবে আপনাকে এমআরআই (MRI) করতে হতে পারে। যখন এই ধরনের রোগীরা আমাদের হাসপাতালে আসেন, তখন আমি তাদের পলিআর্থ্রাইটিস নির্ণয়ের জন্য আরএ ফ্যাক্টর (RA factor), সিসিপি (CCP), ইএসআর (ESR), কমপ্লিট ব্লাড কাউন্ট, এইচএলএ বি২৭ (HLA B27)-এর মতো রক্ত পরীক্ষা করার পরামর্শ দিই। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আপনার যদি আরও কোনো প্রশ্ন বা ফলো-আপ জিজ্ঞাসা থাকে, তবে অনুগ্রহ করে আমাদের লিখতে দ্বিধা করবেন না। আমি আপনার প্রশ্নের উত্তর দিতে পেরে খুশি হব। আপনার সুস্বাস্থ্য কামনা করছি। ভালো থাকবেন।"
63782,104918,"হেলো, যেহেতু সিটিএস (CTS) সার্জারিতে কোনো আরাম পাওয়া যাচ্ছে না, তাই এর সাথে টেনোসিনোভাইটিস থাকার সম্ভাবনা রয়েছে। টেনোসিনোভাইটিস হলো টেন্ডনের প্রদাহ এবং ফোলাভাব। টেন্ডনের ফোলাভাব শুধুমাত্র ওষুধের মাধ্যমে নাও কমতে পারে। লোকাল স্টেরয়েড ইনজেকশন ভালো ফলাফল দিতে পারে, এর সাথে মেশিনের মাধ্যমে ফিজিওথেরাপি প্রোটোকল আপনার ব্যথা এবং ফোলাভাব কমাতে পারে, আপনি আপনার ফিজিওথেরাপিস্টকে ওয়াক্স বাথ থেরাপির কথা জিজ্ঞাসা করতে পারেন। ফোলাভাব, প্রদাহ এবং ব্যথা কমাতে আইস প্যাক ব্যবহার করুন। আল্ট্রাসাউন্ড এবং টেন্স (TENS) সহ ফিজিওথেরাপি আপনাকে সাহায্য করবে। দ্রুত নিরাময়ের জন্য আপনি ট্যাব কোলিন [it C] এবং অ্যান্টি-ইনফ্ল্যামেটরি সহ অ্যান্টিঅক্সিডেন্ট [ট্যাব এনজাইমিক প্লাস] নিতে পারেন। সার্ভিকাল স্পাইনের এমআরআই (MRI) সাহায্য করবে। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আপনার যদি আরও কোনো প্রশ্ন বা ফলো-আপ জিজ্ঞাসা থাকে, তবে আমাদের লিখতে দ্বিধা করবেন না। আমি আপনার প্রশ্নের উত্তর দিতে পেরে খুশি হব। আপনার সুস্বাস্থ্য কামনা করছি। ভালো থাকবেন।"
66243,36713,"চ্যাটডক্টরগুড-এ আপনাকে স্বাগতম। মেটাবলিক অ্যাসিডোসিস হলো এমন একটি অবস্থা যখন শরীরে অ্যাসিডের পরিমাণ বেড়ে যায়, যেমন ল্যাকটিক অ্যাসিড, কোপাসেটিক অ্যাসিড ইত্যাদি। এটি ল্যাকটিক অ্যাসিডোসিস এবং অনিয়ন্ত্রিত ডায়াবেটিসের মতো মেটাবলিক ব্যাধিতে ঘটে, যা যথাক্রমে ডায়াবেটিক কিটোঅ্যাসিডোসিসের কারণ হয়। অ্যানায়ন গ্যাপ হলো রক্তে পরিমাপযোগ্য নয় এমন অ্যানায়ন, যা অ্যাসিডোসিসে অবদান রাখে। এর সূত্র হলো [Na + K]-[Cl + HCO3] আয়ন। স্বাভাবিক মাত্রা ১০-১২ mEq। রক্তে অ্যাসিডের পরিমাণ যত বেশি হবে, অ্যানায়ন গ্যাপ তত বেশি হবে।"
68060,48244,"হেলো, হাতের ফোলাভাব কার্পাল টানেল সিনড্রোমের কারণে হতে পারে। ডাক্তারের সাথে কথা বলুন। আপনার ক্লিনিকাল পরীক্ষা এবং আরও তদন্তের প্রয়োজন হতে পারে। মেশিনের ব্যবহার আপনার ব্যথা এবং ফোলাভাব কমাতে পারে, আপনি আপনার ফিজিওথেরাপিস্টকে ওয়াক্স বাথ থেরাপির কথা জিজ্ঞাসা করতে পারেন। ফোলাভাব, প্রদাহ এবং ব্যথা কমাতে আইস প্যাক ব্যবহার করুন। আল্ট্রাসাউন্ড এবং টেন্স (TENS) সহ ফিজিওথেরাপি আপনাকে সাহায্য করবে। দ্রুত নিরাময়ের জন্য আপনি ট্যাব কোলিন [it C] এবং অ্যান্টি-ইনফ্ল্যামেটরি সহ অ্যান্টিঅক্সিডেন্ট [ট্যাব এনজাইমিক প্লাস] নিতে পারেন। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আপনার যদি আরও কোনো প্রশ্ন বা ফলো-আপ জিজ্ঞাসা থাকে তবে আমাদের লিখতে দ্বিধা করবেন না। আমি আপনার প্রশ্নের উত্তর দিতে পেরে খুশি হব। আপনার সুস্বাস্থ্য কামনা করছি। নিজের যত্ন নিন।"
70827,51963,"হেলো। নার্ভ কমপ্রেশন বা টেনোসিনোভাইটিস হওয়ার সম্ভাবনা রয়েছে। টেনোসিনোভাইটিস হলো টেন্ডনের প্রদাহ এবং ফোলাভাব। টেন্ডনের ফোলাভাব শুধুমাত্র ওষুধের মাধ্যমে নাও কমতে পারে। এর সাথে মেশিনের মাধ্যমে ফিজিওথেরাপি প্রোটোকল আপনার ব্যথা এবং ফোলাভাব কমাতে পারে, আপনি আপনার ফিজিওথেরাপিস্টকে ওয়াক্স বাথ থেরাপির কথা বলতে পারেন। ফোলাভাব, প্রদাহ এবং ব্যথা কমাতে আইস প্যাক ব্যবহার করুন। আল্ট্রাসাউন্ড এবং টেন্স (TENS) সহ ফিজিওথেরাপি আপনাকে সাহায্য করবে। দ্রুত নিরাময়ের জন্য আপনি ট্যাব কোলিন [it C] এবং অ্যান্টি-ইনফ্ল্যামেটরি সহ অ্যান্টিঅক্সিডেন্ট [ট্যাব এনজাইমিক প্লাস] নিতে পারেন। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আপনার যদি আরও কোনো প্রশ্ন বা ফলো-আপ জিজ্ঞাসা থাকে, তবে আমাদের লিখতে দ্বিধা করবেন না। আমি আপনার প্রশ্নের উত্তর দিতে পেরে খুশি হব। আপনার সুস্বাস্থ্য কামনা করছি। নিজের যত্ন নেবেন।"
75577,99765,"হেলো। আপনার অনুসন্ধানের জন্য ধন্যবাদ। ১৩ বছর বয়সী একটি মেয়ের ব্যথার কারণ নির্ণয় করা কখনও কখনও কঠিন এবং বাবা-মায়ের পক্ষে তা মেনে নেওয়া সহজ নয়। <অ্যাপেন্ডিক্স, কিডনি, গলব্লাডার পরীক্ষা এবং প্রচুর রক্ত পরীক্ষার সবকিছুই ভালো এসেছে> এটি নির্দেশ করে যে কোনো শারীরিক সমস্যা নাও থাকতে পারে। এটি আইবিএস (IBS) বা ইরিটেবল বাওয়েল সিনড্রোম হতে পারে। ডাক্তারের সাথে চ্যাট করুন। এছাড়া কোলোনোস্কোপি এবং পেটের সিটি স্ক্যান করিয়ে নিন। যদি সব পরীক্ষা নেতিবাচক আসে, তবে অ্যান্টি-সাইকোটিক ওষুধ দিয়ে চিকিৎসা শুরু করে দেখা যেতে পারে।"
82310,3675,"হেলো। প্রথমে আমি আপনাকে এক্স-রে করার পরামর্শ দেব যাতে আপনার বুড়ো আঙুল বা কবজিতে কোনো ইউনিকর্টিক্যাল ফ্র্যাকচার আছে কি না তা নিশ্চিত হওয়া যায়। আপনার ইতিহাস অনুযায়ী, মেটাকার্পাল বা ফ্যালাঞ্জ জয়েন্টের লিগামেন্টে আঘাত পাওয়ার সম্ভাবনা রয়েছে। যদি আপনার ফোলাভাব এবং ব্যথা থাকে, তবে জয়েন্টকে সঠিক বিশ্রাম দেওয়ার জন্য আপনি আপনার আঙুলটি স্ট্র্যাপ দিয়ে বেঁধে রাখতে পারেন। সাপোর্ট এবং কমপ্রেশনের জন্য ক্রেপ ব্যান্ডেজ ব্যবহার করুন। ফোলাভাব, প্রদাহ এবং ব্যথা কমাতে আইস প্যাক ব্যবহার করুন। আল্ট্রাসাউন্ড এবং টেন্স (TENS) সহ ফিজিওথেরাপি আপনাকে সাহায্য করবে। দ্রুত নিরাময়ের জন্য আপনি ট্যাব কোলিন [it C] এবং অ্যান্টি-ইনফ্ল্যামেটরি সহ অ্যান্টিঅক্সিডেন্ট [ট্যাব এনজাইমিক প্লাস] নিতে পারেন। যদি এতে কোনো উপশম না হয়, তবে আপনাকে এমআরআই (MRI) করতে হতে পারে। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আপনার যদি আরও কোনো প্রশ্ন বা ফলো-আপ জিজ্ঞাসা থাকে, তবে আমাদের লিখতে দ্বিধা করবেন না। আমি আপনার প্রশ্নের উত্তর দিতে পেরে খুশি হব। আপনার সুস্বাস্থ্য কামনা করছি। ভালো থাকবেন।"
82913,26010,"হেলো। নাসেনিয়া ডকে আপনাকে স্বাগতম। আমি আপনার প্রশ্নটি দেখেছি এবং আপনার উদ্বেগ বুঝতে পারছি। আপনার অভিযোগ অনুযায়ী, দাঁতে গভীর সংক্রমণের কারণে দাঁত থেকে মাথায় ব্যথা ছড়িয়ে পড়ছে, যা মাথার একপাশে ব্যথার সৃষ্টি করতে পারে। আপনার চিন্তার কিছু নেই, আপনি একজন ডেন্টিস্টের সাথে পরামর্শ করুন এবং দাঁতের সঠিক অবস্থা নির্ণয়ের জন্য একটি লেটেস্ট এক্স-রে [IOP AR] করান। যদি দাঁতটি বাঁচানো সম্ভব হয়, তবে রুট ক্যানেল ট্রিটমেন্ট করান এবং সেই সাথে অ্যান্টিবায়োটিক ও ব্যথানাশক ওষুধ সেবন করুন। আপাতত ব্যথার উপশমের জন্য আপনি আইবুপ্রোফেন [অ্যাডভিল বা মার্টিন]-এর মতো একটি অ্যান্টি-ইনফ্ল্যামেটরি ব্যথানাশক ওষুধ খেতে পারেন। ব্যথার দিকে দিয়ে চিবানো এবং খুব গরম বা খুব ঠান্ডা খাবার খাওয়া এড়িয়ে চলুন। আশা করি এই তথ্যটি আপনার উপকারে আসবে। যদি আপনি উত্তরটি সহায়ক মনে করেন, তবে অনুগ্রহ করে আমাকে ফাইভ-স্টার রিভিউ দিন এবং কৃতজ্ঞতাস্বরূপ 'ফাউন্ড দ্য অ্যানসার হেল্পফুল'-এ ক্লিক করুন। ধন্যবাদ ও শুভেচ্ছা। নাসেনিয়া ডক।"
90229,22133,"হেলো, লিভার সিরোসিসের একটি সাধারণ জটিলতা হলো হেপাটিক এনসেফালোপ্যাথি। এটি লিভার ফেইলিউরের সাথে সম্পর্কিত জৈব রাসায়নিক অস্বাভাবিকতার কারণে ঘটে। হেপাটিক এনসেফালোপ্যাথি [HE] বারবার ফিরে আসা এবং সাময়িক উপশমের একটি জটিল চক্র দ্বারা চিহ্নিত, যার পরে প্রায় অনিবার্যভাবে রোগটি আবার ফিরে আসে। তীব্র এনসেফালোপ্যাথির পর্বগুলো নিরাময় করা সম্ভব; তবে, দীর্ঘস্থায়ী লিভারের রোগে আক্রান্ত ব্যক্তিরা ভবিষ্যতে বারবার এই সমস্যায় আক্রান্ত হওয়ার ঝুঁকিতে থাকেন। যদি আপনার দাদি কোনো আয়ুর্বেদিক ওষুধ সেবন করে থাকেন [আমি একজন অ্যালোপ্যাথিক ডাক্তার হওয়ায় এ বিষয়ে খুব বেশি মন্তব্য করতে পারছি না], এবং যদি লিভারের কার্যকারিতা স্বাভাবিক অবস্থায় ফিরে আসে; তবে এটি সম্ভবত রোগের পুনরাবৃত্তি। কোমায় চলে গেলে প্রায় ৮০% (১০ জনের মধ্যে ৮ জন) রোগী মারা যান। সুস্থ হওয়া এবং রোগটি ফিরে আসার ঝুঁকি প্রতিটি রোগীর ক্ষেত্রে ভিন্ন হয়। যদি আপনি লিভারের মূল রোগটিকে নিয়ন্ত্রণে রাখতে পারেন, তবে পূর্বাভাস ভালো; অর্থাৎ HE আর ফিরে আসবে না বা বাড়বে না। নিজের যত্ন নেবেন। শুভেচ্ছা।"
100278,81494,"হেলো, গ্রেড ৩ এসি জয়েন্ট সেপারেশনের ক্ষেত্রে যদি উপসর্গ থাকে, তবে ক্লিনিকাল পরীক্ষার পর আপনার অস্ত্রোপচারের প্রয়োজন হতে পারে। ফোলা, প্রদাহ এবং ব্যথা কমাতে আইস প্যাক ব্যবহার করুন। আল্ট্রাসাউন্ড এবং টেন্স (TENS) সহ ফিজিওথেরাপি আপনাকে সাহায্য করবে। দ্রুত সেরে ওঠার জন্য আপনি ট্যাব কোলিন [it C] এবং অ্যান্টি-ইনফ্ল্যামেটরি সহ অ্যান্টিঅক্সিডেন্ট [ট্যাব এনজাইমিক প্লাস] গ্রহণ করতে পারেন। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আপনার যদি আরও কোনো প্রশ্ন বা ফলো-আপ জিজ্ঞাসা থাকে, তবে আমাদের লিখতে দ্বিধা করবেন না। আমি আপনার প্রশ্নের উত্তর দিতে পেরে খুশি হব। আপনার সুস্বাস্থ্য কামনা করছি। ভালো থাকবেন।"
100320,58186,"হেলো, আপনার কার্পাল টানেল সিনড্রোম হওয়ার সম্ভাবনা রয়েছে। আপনার এমআরআই (MRI) এবং এনসিভি (NCV) পরীক্ষার প্রয়োজন হতে পারে। মেশিন ব্যবহার করলে আপনার ব্যথা ও ফোলাভাব কমতে পারে, আপনি আপনার ফিজিওথেরাপিস্টকে ওয়াক্স বাথ থেরাপির বিষয়ে জিজ্ঞাসা করতে পারেন। ফোলাভাব, প্রদাহ এবং ব্যথা কমাতে আইস প্যাক ব্যবহার করুন। আল্ট্রাসাউন্ড এবং টেন্স (TENS) সহ ফিজিওথেরাপি আপনাকে সাহায্য করবে। দ্রুত সেরে ওঠার জন্য আপনি ট্যাব কোলিন [it C] এবং অ্যান্টি-ইনফ্ল্যামেটরি সহ অ্যান্টিঅক্সিডেন্ট [ট্যাব এনজাইমিক প্লাস] নিতে পারেন। আশা করি এটি আপনার প্রশ্নের উত্তর দিয়েছে। আপনার যদি আরও কোনো প্রশ্ন বা ফলো-আপ জিজ্ঞাসা থাকে, তবে আমাদের লিখতে দ্বিধা করবেন না। আমি আপনার প্রশ্নের উত্তর দিতে পেরে খুশি হব। আপনার সুস্বাস্থ্য কামনা করছি। ভালো থাকবেন।"
103130,90509,"হেলো। নাসেনিয়া ডকে আপনাকে স্বাগতম। আমি আপনার প্রশ্নটি দেখেছি এবং আপনার উদ্বেগ বুঝতে পারছি। আপনার অভিযোগ অনুযায়ী, অস্ত্রোপচারের পরে ব্যথা হওয়া অস্বাভাবিক কিছু নয় এবং এটি সাধারণত এক সপ্তাহ বা তার বেশি সময় ধরে থাকে, যা ক্ষত শুকানোর সাথে সাথে ধীরে ধীরে কমে যায়। অস্ত্রোপচারের পরবর্তী প্রাথমিক সময়ে ব্যথানাশক ওষুধ দিয়ে ব্যথা নিয়ন্ত্রণ করা প্রয়োজন, এবং দেখে মনে হচ্ছে আপনি ব্যথার জন্য কোনো ওষুধ খাচ্ছেন না। সংক্রমণ প্রতিরোধের জন্য আপনার অ্যামোক্সিসিলিন (Amoxicillin) বা অগমেন্টিন (Augmentin)-এর মতো অ্যান্টিবায়োটিকের একটি সংক্ষিপ্ত কোর্স নেওয়া উচিত। মাঝারি ব্যথার জন্য আইবুপ্রোফেন (Ibuprofen)-এর মতো ব্যথানাশক ওষুধ খান এবং ব্যথা তীব্র হলে ট্রামাডল (Tramadol) নেওয়া যেতে পারে। দ্রুত ব্যথা থেকে উপশম পেতে আপনি ভেটারান ইনজেকশন [ডাইক্লোফেনাক] (Veteran injection [diclofenac])-এর মতো ইনজেকশনযোগ্য ব্যথানাশকও নিতে পারেন। আশা করি এই তথ্যটি আপনাকে সাহায্য করবে। ধন্যবাদ এবং শুভেচ্ছা।"

============================================================
8. REPEATED SYMBOLS
============================================================

/tmp/ipykernel_189/1923704581.py:166: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df_cleaned[col].str.contains(

input: 0 rows

Empty DataFrame
Columns: [id, input]
Index: []

/tmp/ipykernel_189/1923704581.py:166: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df_cleaned[col].str.contains(

output: 0 rows

Empty DataFrame
Columns: [id, output]
Index: []

============================================================
9. REPEATED WORDS
============================================================

/tmp/ipykernel_189/1923704581.py:191: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df_cleaned[col].str.contains(

input: 41212 rows

,id,input
3,84959,"হেলো, আমার বয়স ২২, উচ্চতা ৫ ফুট ৯ ইঞ্চি এবং ওজন ১৭০ পাউন্ড। আমি সারা জীবন খুব সুস্থ ছিলাম, তেমন কোনো সমস্যা হয়নি। আমার উপরের ঠোঁটের ঠিক উপরে একটি ফোলা চাকা হয়েছে যা ঠোঁটকে স্পর্শ করে আছে। চাপ না দিলে এটি ব্যথা করে না, তবে আমি এটি অনুভব করতে পারছি এবং এটি আমাকে বিরক্ত করছে। বরফ দিলে ফোলা কিছুটা কমে। এটি কোনো খোলা ক্ষত নয়, শুধু একটি চাকা যা যাচ্ছে না। এটি প্রায় ৫ দিন ধরে আছে।"
4,65169,"হেলো, আমার নানি প্রায়ই অভিযোগ করেন যে তার হৃদপিণ্ডের চারপাশে গ্যাসের সমস্যা হচ্ছে, যার ফলে তিনি মাথা ঝিমঝিম এবং মাথা ঘোরার অনুভব করেন। তার বয়স ৭৭ বছর এবং তার হার্টের অপারেশন হয়েছে ও নতুন ভালভ বসানো হয়েছে। তিনি ডাক্তারকে বিষয়টি জানালেও ডাক্তার কোনো পদক্ষেপ নিচ্ছেন না। আমি চিন্তিত কারণ এর ফলে তার মাথা ঘোরে এবং এমনিতেই তার হাঁটাচলায় ভারসাম্যহীনতা রয়েছে। এর কারণ কী হতে পারে এবং কী করলে উপকার পাওয়া যাবে, তা কি জানাতে পারবেন? ধন্যবাদ।"
6,35213,"হেলো! আমি বহু বছর কোনো ব্যায়াম না করার পর আবার ব্যায়াম শুরু করার চেষ্টা করছি। আমি লক্ষ্য করছি যে, যখন আমি স্কোয়াট করি বা সিঁড়ি দিয়ে উঠি, তখন আমার হাঁটু থেকে মটমট শব্দ হয় এবং ব্যথা করে। আমি ভাবছি, আমার ওজন কি খুব বেশি এবং এই ধরনের ব্যায়াম করার আগে কি আমার ওজন কমানো প্রয়োজন?"
8,108198,হেলো স্যার। আমার মায়ের কিডনি বিকল হয়ে গেছে। আমি খুব দুঃখিত। কিন্তু আমার রক্তের গ্রুপ মিলছে না। একজন ব্যক্তি কিডনি দান করতে চান। কিন্তু ডাক্তার রাজি নন এবং তিনি কাগজপত্র দাবি করছেন। আমার মা সুস্থ না হলে আমিও মারা যাব। রোগীদের জন্য ডাক্তাররা ঈশ্বরের মতো। দয়া করে স্যার আমি কী করব? দয়া করে স্যার আমাকে সাহায্য করুন এবং আমার জীবন বাঁচান।
9,96344,"আমার ছেলের আজ ২ বছর পূর্ণ হলো এবং গতকাল থেকে সে স্বাভাবিকের চেয়ে বেশি দাঁত কিড়মিড় করছে, যা একটানা ছিল। সে আমার ওপর খুব বেশি নির্ভরশীল হয়ে পড়েছে এবং আমি খেয়াল করলাম তার শরীরের তাপমাত্রা ৩৮.৬ ডিগ্রি সেলসিয়াস। আমি তাকে প্যারাসিটামল দিয়েছি এবং হাইড্রোথেরাপিও করেছি (ঠান্ডা পানির কাছাকাছি তাপমাত্রার পানিতে গোসল করিয়েছি)। মনে হয়েছিল কয়েক মিনিটের জন্য কাজ হয়েছে, কিন্তু রাতে তার শরীর আবার গরম হয়ে গেছে। আমি এইমাত্র তার তাপমাত্রা মেপে দেখলাম তা এখন ৩৮.৮ ডিগ্রি। আমার ছেলের কী হয়েছে?"
...,...,...
235,13775,"আজ আমাদের প্রথম আল্ট্রাসাউন্ড ছিল। ফলাফল আমার ভালো লাগেনি। আমার বান্ধবীর শেষ মাসিকের প্রথম দিন থেকে আজ ৮ সপ্তাহ ২ দিন। আল্ট্রাসাউন্ডে ২৪ মিমি ব্যাসের একটি স্যাক দেখা গেছে, কিন্তু কোনো ভ্রূণ দেখা যায়নি। স্ত্রীরোগ বিশেষজ্ঞ বলেছেন যে এটি মাত্র ৬ সপ্তাহের সাধারণ গর্ভাবস্থার মতো দেখাচ্ছে। ৮ সপ্তাহে সাধারণত একটি ভ্রূণ এবং হৃদস্পন্দন দৃশ্যমান থাকে। এর অর্থ কী হতে পারে? শিশুটি প্রতিবন্ধী, বিকলাঙ্গ বা দীর্ঘস্থায়ী অসুস্থ হয়ে জন্ম নেওয়ার সম্ভাবনা কি খুব বেশি? আমার বান্ধবীর গর্ভাবস্থা ধীরগতির হওয়ার অর্থ কী?"
239,86071,"আমার বয়স ২৩ বছর, আমি একজন বাংলাদেশী পুরুষ এবং বর্তমানে লন্ডনে থাকি। গত কয়েক মাস ধরে আমার চোখের চারপাশের ত্বক র‍্যাশে ভরে গেছে। এটি খুব শুষ্ক এবং যখন খুব বেশি শুষ্ক হয়ে যায়, তখন চুলকানি হয়। আমি অ্যালার্জির ওষুধ খেয়েছি এবং ত্বক ময়েশ্চারাইজ করার জন্য ই৪ (E45) আনপারফিউমড ক্রিম ব্যবহার করছি। আমি কয়েকজন ডাক্তারকেও দেখিয়েছি, কিন্তু তারা কিছুই বলতে পারেননি। তবে আমার ত্বকের অবস্থা দিন দিন খারাপ হচ্ছে এবং এর ফলে আমাকে আমার বয়সের চেয়ে ১০ বছরের বড় দেখাচ্ছে। দয়া করে আমাকে সাহায্য করুন।"
242,23478,"আমার ৬ বছর বয়সী ছেলে সবসময়ই খাবার নিয়ে খুব খুঁতখুঁতে এবং কিছুদিন আগ পর্যন্ত তার ওজন কমের দিকে ছিল। তার চোখের নিচে সবসময়ই কালচে দাগ থাকে। তার অ্যালার্জি এবং হাঁপানি ধরা পড়েছে, যার চিকিৎসা চলছে। কিন্তু সে সবসময় খুব ফ্যাকাশে থাকে, যা বংশগত বলে মনে হয় না। তার বাবা পোলিশ, তাই গায়ের রঙ বেশ শ্যামলা। আমার নিজেরও চেরোকি পূর্বপুরুষ আছে এবং আমার গায়ের রঙও খুব ফর্সা নয়। জন্মের পর থেকেই সে অসুস্থ থাকে এবং মনে হয় তার রোগ প্রতিরোধ ক্ষমতা কম, কিন্তু ডাক্তাররা আমাকে পাত্তা না দিয়ে বলেন সে ঠিক আছে। এখন, এই বছরের ফেব্রুয়ারি থেকে তার দুবার খিঁচুনি হয়েছে। একজন নিউরোলজিস্টের সাথে তার অ্যাপয়েন্টমেন্ট আছে, কিন্তু তা এই বছরের জুলাইয়ের আগে নয়। লক্ষণগুলো হয়তো সম্পূর্ণ আলাদা হতে পারে, কিন্তু তাকে দেখে স্বাভাবিক, সুস্থ ৬ বছরের ছেলের মতো মনে হয় না। এমন কোনো রোগ, সিনড্রোম, সংক্রমণ বা নির্দিষ্ট কোনো শারীরিক অবস্থা কি আছে যা আমার খেয়াল রাখা উচিত বা পরীক্ষা করানো উচিত, যা আমি এখনো উল্লেখ করিনি এবং উদ্বেগের কারণ হতে পারে?"
243,36288,"আমি ১০ বছর ধরে সোরিয়াসিসে ভুগছি। এখন এটি খুব বিপজ্জনক হয়ে উঠেছে। এটি আমার শরীরের প্রায় সব অংশ ঢেকে ফেলেছে। আমি প্রতি সপ্তাহে ১৫ মিলিগ্রাম এমটিএক্স (MTX) নিই। আমি পিইউভিএ (PUVA) চিকিৎসাও নিয়েছি, কিন্তু কোনো কিছুই আমার সোরিয়াসিস নিয়ন্ত্রণ করতে পারছে না। আমার বয়স ২৫ বছর এবং আমি একজন বিবাহিত নারী। আমার শাশুড়ি এবং স্বামী সবসময় আমাকে মানসিকভাবে নির্যাতন করেন। আমার কোনো সন্তান নেই। আমার স্বামী এখন সন্তান চান। আমি কুয়েট (KUET) থেকে ইলেকট্রিক্যাল ইঞ্জিনিয়ার, কিন্তু আমার অসুস্থতার কারণে আমি কোনো চাকরিতে যোগ দিতে পারছি না। তাই আমি আর্থিকভাবে নিরাপত্তাহীনতায় ভুগছি। আমি খুব অসহায়। আমি এখন কী করতে পারি?"
244,110274,"হেলো, আপনার স্বামীর শারীরিক অবস্থার কথা শুনে আমি অত্যন্ত দুঃখিত। ৮৪ বছর বয়সে এন্ড-স্টেজ রেনাল ফেইলিওর একটি অত্যন্ত জটিল পরিস্থিতি। যেহেতু তিনি ডায়ালাইসিস নিতে ইচ্ছুক নন, তাই এই সময়ে তার আরাম এবং জীবনযাত্রার মান নিশ্চিত করাই সবচেয়ে গুরুত্বপূর্ণ। তিনি সারাদিন ঘুমিয়ে থাকছেন, এটি কিডনি অকেজো হওয়ার কারণে শরীরে বিষাক্ত পদার্থ জমে যাওয়ার একটি লক্ষণ হতে পারে। দয়া করে কোনো ঘরোয়া প্রতিকার বা সাপ্লিমেন্ট (যেমন CQ10 বা কিডনি টি) দেওয়ার আগে অবশ্যই তার চিকিৎসকের সাথে পরামর্শ করুন, কারণ এগুলো তার দুর্বল কিডনির ওপর বাড়তি চাপ সৃষ্টি করতে পারে। তার এই অবস্থায় প্যালিয়েটিভ কেয়ার বা উপশমকারী সেবা বিশেষজ্ঞের পরামর্শ নেওয়া সবচেয়ে ভালো হবে, যারা তার কষ্ট কমাতে এবং তাকে আরামদায়ক রাখতে সাহায্য করতে পারবেন। দয়া করে দ্রুত তার নিয়মিত চিকিৎসকের সাথে যোগাযোগ করুন এবং তার ঘুমের ধরণ ও শারীরিক অবস্থা সম্পর্কে বিস্তারিত জানান।"

/tmp/ipykernel_189/1923704581.py:191: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df_cleaned[col].str.contains(

output: 60858 rows

,id,output
0,45361,"হেলো, পিসিওডি (PCOD) হলো এমন একটি উপসর্গ যা অনিয়মিত বা অনুপস্থিত পিরিয়ড, বন্ধ্যাত্ব, স্থূলতা, অবাঞ্ছিত লোম বৃদ্ধি, ব্রণ, কিছু ক্ষেত্রে ইনসুলিন রেজিস্ট্যান্স, এলএইচ/এফএসএইচ (LH/FSH) অনুপাত উল্টে যাওয়া সহ অস্বাভাবিক হরমোনের প্রোফাইল, আরএইচইএএস (RHEAS) লেভেল বৃদ্ধি, কিছু ক্ষেত্রে অস্বাভাবিক জিটিটি (GTT), কখনও কখনও উচ্চ প্রোল্যাক্টিন এবং অস্বাভাবিক থাইরয়েড প্রোফাইলের সাথে যুক্ত থাকে। এতে ডিম্বাশয়ে একাধিক ফলিকল দেখা যায় কারণ অনেকগুলো ফলিকল একই সময়ে তৈরি হলেও সেগুলো পরিপক্ক হয় না। রোগ নির্ণয়ের জন্য আপনাকে সম্পূর্ণ পরীক্ষা-নিরীক্ষা করাতে হবে। ওভুলেশন বা ডিম্বস্ফোটন সম্ভব হলেও হরমোনের ভারসাম্যহীনতা, টিউব সংক্রান্ত সমস্যা বা পুরুষজনিত কারণের মতো অনেকগুলো বিষয়ের কারণে গর্ভধারণ নাও হতে পারে। আপনার একজন অভিজ্ঞ ইনফার্টিলিটি বিশেষজ্ঞের পরামর্শ নেওয়া উচিত। নিজের যত্ন নেবেন।"
2,98599,"হেলো কবিতা, লেখার জন্য ধন্যবাদ। স্কিন লাইটেনিং ক্রিমে ২% এইচওয়াই নাসেনিয়া ডক থাকে। এই উপাদানগুলো ত্বকে স্থায়ী পিগমেন্টেশন ঘটাতে পারে যার ফলে সাদা দাগ হতে পারে। এটি দীর্ঘ সময় ব্যবহার করা উচিত নয়। আমার পরামর্শ হলো - স্টেরয়েডযুক্ত ক্রিম ব্যবহার বন্ধ করুন। দিনের বেলা ভালো সানস্ক্রিন ব্যবহার করুন। আপনি রাতে কালো দাগের ওপর ক্লাইম্যাক্স ক্রিম লাগাতে পারেন, এটি নিরাপদ এবং কার্যকর। গায়ের রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। খাদ্যতালিকায় প্রচুর ভিটামিন সি রাখুন। রোদে যাওয়া এড়িয়ে চলুন। রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। ভবিষ্যতে যেকোনো এইচকিউ (HQ) এবং স্টেরয়েডযুক্ত ক্রিম এড়িয়ে চলুন। আশা করি এটি সাহায্য করবে। ফলো-আপের জন্য আমি উপলব্ধ থাকব। শুভেচ্ছা।"
3,84959,"হেলো প্রিয়, নাসেনিয়া ডকে আপনাকে স্বাগতম। আপনার উদ্বেগটি বুঝতে পারছি। আপনার প্রশ্ন অনুযায়ী, উপরের ঠোঁটের উপরে ফোলা অংশটি মূলত ঠোঁট কামড়ানোর কারণে হয়ে থাকে। অসাবধানতাবশত নিচের চোয়ালের দাঁত উপরের ঠোঁটে আঘাত করলে সেই জায়গায় অতিরিক্ত কোলাজেন ফাইবার জমা হয়ে ফোলাভাব সৃষ্টি হয়। এটি হারপিস সিমপ্লেক্স ভাইরাস সংক্রমণের কারণেও হতে পারে, যা ওই এলাকায় কোল্ড সোর বা ঘা সৃষ্টি করতে পারে। যদি আপনি অতিরিক্ত সূর্যের আলোতে থাকেন, তবে এই ফোসকা তার কারণেও হতে পারে। এটি নিয়ে আতঙ্কিত হওয়ার কিছু নেই। বরফের টুকরো নিয়ে এই জায়গায় ১০-১২ মিনিট বিরতি দিয়ে চেপে ধরুন। জায়গাটি পরিষ্কার রাখুন। নাসেনিয়া ডকের সাথেই থাকুন।"
4,65169,"হেলো, আমি আপনার প্রশ্নটি মনোযোগ সহকারে পড়েছি এবং ব্যাখ্যা করতে চাই যে তার হৃদযন্ত্রের কার্যকারিতা মূল্যায়ন করা এবং সম্ভাব্য হার্ট ফেইলিওর যা এই ক্লিনিকাল পরিস্থিতির অনুকরণ করতে পারে, তা বাদ দেওয়া প্রয়োজন। গ্যাস্ট্রোইসোফেজিয়াল রিফ্লাক্সও এই পরিস্থিতির অনুকরণ করতে পারে, যদিও মাথা ঘোরা এই রোগের সাধারণ লক্ষণ নয়। এই পর্যায়ে, আমি হার্ট ফেইলিওর আছে কিনা তা তদন্ত করার জন্য একটি কার্ডিয়াক আল্ট্রাসাউন্ড এবং এনটি-প্রো বিএনপি (NT-pro BNP) পরীক্ষা করার পরামর্শ দেব। বিবেচনা করার মতো অন্যান্য পরীক্ষাগুলো হলো"
5,12341,"হেলো, খারাপ খাদ্যাভ্যাস (চর্বিযুক্ত খাবার, মশলাদার খাবার), অ্যালকোহল গ্রহণ, কিছু ওষুধের ব্যবহার (বেশিরভাগ ব্যথানাশক), পিত্তথলির রোগ (যেমন পিত্তথলিতে পাথর), লিভারের ভাইরাল সংক্রমণ (এইচবিভি, এইচসিভি সংক্রমণ) ইত্যাদির কারণে লিভার এনজাইম বেড়ে যেতে পারে। যেহেতু আপনার জিজিপিটি (GGT) লেভেল আবার বেড়েছে, তাই খাদ্যাভ্যাস ছাড়াও এর বৃদ্ধির অন্যান্য সম্ভাব্য কারণগুলো খতিয়ে দেখা উচিত। জিটিপি, এপি, অ্যামাইলেজ, লাইপেজ, ইউরিন অ্যামাইলেজ, ব্যাগ, অ্যান্টিওক লেভেল পরীক্ষা করা উচিত। পেটের একটি আল্ট্রাসাউন্ডও করা প্রয়োজন। আপনার চর্বিযুক্ত খাবার, ভাজা খাবার, মশলাদার খাবার, অ্যালকোহল এবং ওষুধ এড়িয়ে চলা উচিত। প্রেসক্রিপশন ছাড়াই পাওয়া যায় এমন লিভারের কার্যকারিতা বৃদ্ধিকারী সাপ্লিমেন্টগুলোও লিভার পুনর্গঠনে সহায়ক হতে পারে। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি। আমি আপনাকে আরও কোনোভাবে সাহায্য করতে পারি কিনা তা জানাবেন।"
...,...,...
166,31953,"হেলো, কিডনিতে শ্যাডো একটি অনির্দিষ্ট ফলাফল এবং এটি অনেক কারণে হতে পারে। আল্ট্রাসাউন্ডে এটি কীভাবে দেখা যাচ্ছে, অর্থাৎ এটি হাইপো বা হাইপারইকোজেনিক কি না, তা জানা গুরুত্বপূর্ণ। এটি হাইপারট্রফাইড কলাম অফ বারটিনি, অ্যাডেনোমা, অ্যাবসেস ইত্যাদির মতো অনেক কারণে হতে পারে। আপনাকে কন্ট্রাস্ট সিটি স্ক্যান করার যে পরামর্শ দেওয়া হয়েছে তা সঠিক। ক্ষত মূল্যায়নের ক্ষেত্রে সিটি স্ক্যান খুব সহায়ক। প্রয়োজনে সিটি বা ইউএসজি গাইডেড এফএনএসি (FNAC) করা যেতে পারে। সঠিক চিকিৎসা ফলাফলের উপর নির্ভর করে। ভালো থাকবেন। নাসেনিয়া ডক।"
168,16957,"নাসেনিয়া ডকে আপনার প্রশ্নের জন্য ধন্যবাদ। আমি আপনার উদ্বেগ বুঝতে পারছি। যেহেতু আপনার বুকের ব্যথা নির্দিষ্ট নড়াচড়া এবং অবস্থানের সাথে সম্পর্কিত, তাই পেশী বা হাড়ের ব্যথার সম্ভাবনা বেশি। তাই ভালো উপশমের জন্য এই পদক্ষেপগুলো অনুসরণ করুন। ১. ব্যথা সৃষ্টি করে এমন নড়াচড়া এড়িয়ে চলুন। ২. ঘুমের সময় ভুল অঙ্গভঙ্গি এড়িয়ে চলুন। ৩. ভারী ওজন তোলা এবং কঠোর ব্যায়াম এড়িয়ে চলুন। ৪. নাসেনিয়া ডকের পরামর্শ অনুযায়ী ব্যথানাশক এবং পেশী শিথিলকারী ওষুধ সেবন করুন। ৫. আক্রান্ত স্থানে গরম পানির সেঁক দিন। চিন্তা করবেন না, এই সব মেনে চললে ২-৩ দিনের মধ্যে আপনি সুস্থ হয়ে উঠবেন। যদি উন্নতি না হয়, তবে ডাক্তারের পরামর্শ নিন। আশা করি আমি আপনার প্রশ্নের সমাধান করতে পেরেছি। আপনাকে আরও সাহায্য করতে পারলে আমি খুশি হব। আপনার সুস্বাস্থ্য কামনা করি। ধন্যবাদ।"
171,9817,"হেলো ভেলানকান্নান, হেলথ কেয়ার ম্যাজিক প্ল্যাটফর্মে আপনার প্রশ্নটি করার জন্য ধন্যবাদ। আমি আপনার রিপোর্টটি দেখেছি। আপনার বীর্যের পরিমাণ বেশ কম। যদিও প্রতি মিলিলিটারে শুক্রাণুর সংখ্যা স্বাভাবিক মনে হচ্ছে, কিন্তু পরিমাণের স্বল্পতার কারণে মোট শুক্রাণুর সংখ্যাও কম; তাছাড়া অস্বাভাবিক মরফোলজির সংখ্যাও উল্লেখযোগ্যভাবে বেশি। বীর্যে এবিসি (শ্বেত রক্তকণিকা, পুঁজ কোষ এবং এপিথেলিয়াল কোষ) এর উপস্থিতি কোনো সংক্রমণের ইঙ্গিত দেয়। তবে অনেক সময় অপরিণত শুক্রাণুকে বীর্যে পুঁজ কোষ হিসেবে ভুল ধরা হয়। এই সংক্রমণটি বীর্যের নিম্ন গুণমান এবং পরিমাণের কারণ হতে পারে। এই সংক্রমণের জন্য আপনাকে অ্যান্টিবায়োটিক নিতে হতে পারে। আপনি যদি নিচের জীবনধারা অনুসরণ করেন, তবে আপনাকে তা পরিবর্তন করতে হতে পারে কারণ এর যেকোনোটি বীর্যের গুণমানকে প্রভাবিত করে।"
172,91465,"হেলো, প্রস্রাবে স্কোয়ামাস কোষ স্বাভাবিকভাবেই দেখা যেতে পারে। এর খুব একটা গুরুত্ব নেই। পরবর্তী পরীক্ষার জন্য আমি আপনাকে নিচের পরীক্ষাগুলো করার পরামর্শ দিচ্ছি:\n_সেরাম ইউরিয়া, ক্রিয়েটিনিন পরিমাপ\n_পেটের আল্ট্রাসনোগ্রাফি\n_প্রস্রাবের রুটিন মাইক্রোস্কোপিক পরীক্ষা\n\nআপনি রিপোর্টগুলো নিয়ে আবার যোগাযোগ করতে পারেন, যাতে আমি আপনাকে আরও নির্দেশনা দিতে পারি। রিপোর্টের ফলাফলের ওপর ভিত্তি করে পরবর্তী মন্তব্য করা যাবে। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি। আমি আপনাকে আরও কোনোভাবে সাহায্য করতে পারি কি না, তা জানাবেন।"
174,29911,"হেলো, আমাদের সাথে যোগাযোগ করার জন্য ধন্যবাদ। প্রোস্টেটে ৩ মিমি সিস্ট সাধারণত উদ্বেগের কারণ নয়। প্রোস্ট্যাটিক ইউট্রিকল সিস্ট (PUC) হলো প্রোস্ট্যাটিক ইউট্রিকলের ভেতরে হওয়া এক ধরনের ফোকাল প্রসারণ। সংক্রমিত হলে ইউট্রিকল সিস্টে পুঁজ বা রক্তপাত হতে পারে এবং তখন ব্যথা ও অস্বস্তি অনুভূত হয়। এক বছর পর একটি ফলো-আপ স্ক্যান করা যেতে পারে। আপনার বয়স এবং মূত্রনালীর সাথে সম্পর্কিত কোনো উপসর্গ আছে কি না তা জানা গুরুত্বপূর্ণ। যেহেতু আপনার ডাক্তার বলেছেন যে কোনো সমস্যা নেই, তাই আমার মনে হয় সিস্ট নিয়ে আপনার খুব বেশি চিন্তা করা উচিত নয়। রক্তপাতের কারণ হতে পারে এমন কোনো সংক্রমণ নিরাময়ের জন্য আপনি অ্যান্টিবায়োটিক গ্রহণ করতে পারেন।"

============================================================
10. CONTROL CHARACTERS
============================================================
input: 0 rows

Empty DataFrame
Columns: [id, input]
Index: []

output: 0 rows

Empty DataFrame
Columns: [id, output]
Index: []

In [44]:
import re
import pandas as pd

# ============================================
# CLEAN TEXT
# Removes:
# - English + Bengali phone/contact numbers
# - Email addresses
# - WWW / HTTP / HTTPS URLs
# - Website/domain links
# - Markdown links
# ============================================

def clean_text(text):
    if pd.isna(text):
        return text

    text = str(text)

    # ------------------------------------------------
    # 1. Remove markdown links
    # Example:
    # [website](http://example.com)
    # [email](mailto:test@gmail.com)
    # ------------------------------------------------
    text = re.sub(
        r'\[[^\]]*\]\(\s*(?:https?://|mailto:)[^)]+\)',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    # ------------------------------------------------
    # 2. Remove email addresses
    # ------------------------------------------------
    text = re.sub(
        r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b',
        ' ',
        text
    )

    # ------------------------------------------------
    # 3. Remove URLs
    # http://
    # https://
    # www.
    # ------------------------------------------------
    text = re.sub(
        r'(?i)\b(?:https?://|www\.)[^\s<>()\[\]]+',
        ' ',
        text
    )

    # ------------------------------------------------
    # 4. Remove domain-style websites
    # Example:
    # ChatDoctor.com
    # example.org
    # website.net
    # ------------------------------------------------
    text = re.sub(
        r'(?i)\b(?:[a-z0-9-]+\.)+'
        r'(?:com|org|net|info|biz|io|co|in|bd|au)'
        r'(?:/[^\s]*)?',
        ' ',
        text
    )

    # ------------------------------------------------
    # 5. Remove phone/contact numbers
    #
    # Supports BOTH:
    # English digits: 0123456789
    # Bengali digits: ০১২৩৪৫৬৭৮৯
    #
    # Also handles:
    # +880 1712 345678
    # 01712-345678
    # ০১৭১২-৩৪৫৬৭৮
    # ০১৭১২ ৩৪৫৬৭৮
    # ------------------------------------------------

    english_digits = r'0-9'
    bengali_digits = r'০-৯'

    # English + Bengali digit character class
    digits = f'{english_digits}{bengali_digits}'

    # Numbers with spaces, -, brackets, +, dots
    phone_pattern = (
        rf'(?<![{digits}])'
        rf'\+?[{digits}]'
        rf'(?:[\s().-]*[{digits}]){{7,}}'
        rf'(?![{digits}])'
    )

    text = re.sub(phone_pattern, ' ', text)

    # ------------------------------------------------
    # 6. Remove leftover mailto
    # ------------------------------------------------
    text = re.sub(
        r'(?i)\bmailto\s*:\s*',
        ' ',
        text
    )

    # ------------------------------------------------
    # 7. Normalize spaces
    # ------------------------------------------------
    text = re.sub(r'[ \t]+', ' ', text)

    # ------------------------------------------------
    # 8. Clean spaces around newlines
    # ------------------------------------------------
    text = re.sub(r' *\n *', '\n', text)

    # ------------------------------------------------
    # 9. Remove excessive blank lines
    # ------------------------------------------------
    text = re.sub(r'\n{3,}', '\n\n', text)

    return text.strip()


# ============================================
# CREATE NEW DATAFRAME
# ============================================

df_final = df_cleaned.copy()


# ============================================
# CLEAN BOTH INPUT AND OUTPUT
# ============================================

df_final["input"] = df_final["input"].apply(clean_text)
df_final["output"] = df_final["output"].apply(clean_text)


# ============================================
# CHECK SHAPE
# ============================================

print("Before cleaning :", df_cleaned.shape)
print("After cleaning  :", df_final.shape)


# ============================================
# CHECK EXAMPLES
# ============================================

display(
    df_final[["id", "input", "output"]].head(10)
)

Before cleaning : (108391, 5)
After cleaning  : (108391, 5)

,id,input,output
0,45361,"হেলো, আমরা গত ৩ মাস ধরে গর্ভধারণের চেষ্টা করছি কিন্তু ফলাফল নেতিবাচক। এবার আমি ফলিকুলার মনিটরিং করিয়েছি এবং ১৭তম দিনে ওভুলেশন হয়েছে, কিন্তু তবুও আমি গর্ভবতী নই। যদিও আমার এলও-তে অনেকগুলো ছোট ফলিকল ছিল, এগুলো কি স্বাভাবিক নাকি পিসিওডি? আমি সত্যিই বিভ্রান্ত এবং বুঝতে পারছি না কী করব, আমার কি ডাক্তার পরিবর্তন করা উচিত?","হেলো, পিসিওডি (PCOD) হলো এমন একটি উপসর্গ যা অনিয়মিত বা অনুপস্থিত পিরিয়ড, বন্ধ্যাত্ব, স্থূলতা, অবাঞ্ছিত লোম বৃদ্ধি, ব্রণ, কিছু ক্ষেত্রে ইনসুলিন রেজিস্ট্যান্স, এলএইচ/এফএসএইচ (LH/FSH) অনুপাত উল্টে যাওয়া সহ অস্বাভাবিক হরমোনের প্রোফাইল, আরএইচইএএস (RHEAS) লেভেল বৃদ্ধি, কিছু ক্ষেত্রে অস্বাভাবিক জিটিটি (GTT), কখনও কখনও উচ্চ প্রোল্যাক্টিন এবং অস্বাভাবিক থাইরয়েড প্রোফাইলের সাথে যুক্ত থাকে। এতে ডিম্বাশয়ে একাধিক ফলিকল দেখা যায় কারণ অনেকগুলো ফলিকল একই সময়ে তৈরি হলেও সেগুলো পরিপক্ক হয় না। রোগ নির্ণয়ের জন্য আপনাকে সম্পূর্ণ পরীক্ষা-নিরীক্ষা করাতে হবে। ওভুলেশন বা ডিম্বস্ফোটন সম্ভব হলেও হরমোনের ভারসাম্যহীনতা, টিউব সংক্রান্ত সমস্যা বা পুরুষজনিত কারণের মতো অনেকগুলো বিষয়ের কারণে গর্ভধারণ নাও হতে পারে। আপনার একজন অভিজ্ঞ ইনফার্টিলিটি বিশেষজ্ঞের পরামর্শ নেওয়া উচিত। নিজের যত্ন নেবেন।"
1,95550,"প্রায় এক মাস আগে আমার পিঠের ডান দিকের কাঁধের হাড়ের কাছে বৈদ্যুতিক স্রোতের মতো এক ধরনের অনুভূতি হতে শুরু করেছে। এটি বেশ বিরক্তিকর এবং আমি জানি না কীভাবে এর চিকিৎসা করব। প্রায় ১২ বছর আগে আমার ঘাড়ে সি-৬ এবং সি-৭ ফিউশন হয়েছিল। কী হচ্ছে আমার? আমার বয়স ৬০, আমি বিশেষ চাহিদাসম্পন্ন শিশুদের নিয়ে কাজ করি এবং শারীরিকভাবে সক্রিয় থাকি। প্রায় এক মাস ধরে চলা হাড়কাঁপানো ঠান্ডার সাথে কি এর কোনো সম্পর্ক থাকতে পারে? ধন্যবাদ।","হেলো, প্রথমে আমাকে আপনাকে ব্যাখ্যা করতে দিন যে আপনার মতো একটি নির্দিষ্ট মেডিকেল লক্ষণের বিভিন্ন কারণ থাকতে পারে। পিঠে ব্যথা এবং বিদ্যুৎ প্রবাহের মতো অনুভূতি সার্ভিকাল স্পাইনাল কর্ডের স্পনডাইলোসিস বা অন্যান্য কারণে (যেমন কোনো টিউমার, অবক্ষয়, মেরুদণ্ডের সমস্যা) হতে পারে। বার্ধক্যে এটি স্পনডাইলোসিসের কারণে হতে পারে। সঠিক স্নায়বিক সমস্যা নির্ণয়ের জন্য আপনার একটি বিস্তারিত স্নায়বিক পরীক্ষা প্রয়োজন। বিদ্যুৎ প্রবাহের মতো অনুভূতির উপস্থিতি উদ্বেগের বিষয়, কারণ এটি নির্দেশ করে যে মেরুদণ্ডের কোনো একটি অংশ সংকুচিত হচ্ছে। তাই, জরুরি ভিত্তিতে একজন স্নায়ুরোগ বিশেষজ্ঞের মূল্যায়ন প্রয়োজন এবং পরবর্তীতে পুনরায় ইমেজিং ও নার্ভ কন্ডাকশন স্টাডি (প্রাথমিক মূল্যায়নের ওপর ভিত্তি করে এটি ঐচ্ছিক হতে পারে) করার প্রয়োজন হতে পারে। আপনার চিকিৎসা মূলত কারণের ওপর নির্ভর করবে। আশা করি এই ব্যাখ্যাটি আপনাকে সাহায্য করবে। শুভকামনা।"
2,98599,"হেলো, আমি ২৫ বছর বয়সী অবিবাহিত মেয়ে। আমার কপাল, ঘাড় এবং হাতে কালচে দাগ হয়েছে। আগে এটি রোদে পোড়া দাগের মতো ছিল, কিন্তু আমি এর জন্য চিকিৎসা নিয়েছিলাম এবং ডাক্তার যে মলম দিয়েছিলেন তা স্টেরয়েডযুক্ত ছিল। এর ফলে সমস্যাটি আরও বেড়ে গেছে। আগে এটি খুব একটা বোঝা যেত না, কিন্তু এখন এটি দেখতে খুব খারাপ লাগে। আপনি কি দয়া করে আমাকে কিছু পরামর্শ দিতে পারেন? আমি রোদ এড়িয়ে চলি, কিন্তু কোনো সানস্ক্রিন ব্যবহার করি না কারণ এতে রাসায়নিক থাকে।","হেলো কবিতা, লেখার জন্য ধন্যবাদ। স্কিন লাইটেনিং ক্রিমে ২% এইচওয়াই নাসেনিয়া ডক থাকে। এই উপাদানগুলো ত্বকে স্থায়ী পিগমেন্টেশন ঘটাতে পারে যার ফলে সাদা দাগ হতে পারে। এটি দীর্ঘ সময় ব্যবহার করা উচিত নয়। আমার পরামর্শ হলো - স্টেরয়েডযুক্ত ক্রিম ব্যবহার বন্ধ করুন। দিনের বেলা ভালো সানস্ক্রিন ব্যবহার করুন। আপনি রাতে কালো দাগের ওপর ক্লাইম্যাক্স ক্রিম লাগাতে পারেন, এটি নিরাপদ এবং কার্যকর। গায়ের রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। খাদ্যতালিকায় প্রচুর ভিটামিন সি রাখুন। রোদে যাওয়া এড়িয়ে চলুন। রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। ভবিষ্যতে যেকোনো এইচকিউ (HQ) এবং স্টেরয়েডযুক্ত ক্রিম এড়িয়ে চলুন। আশা করি এটি সাহায্য করবে। ফলো-আপের জন্য আমি উপলব্ধ থাকব। শুভেচ্ছা।"
3,84959,"হেলো, আমার বয়স ২২, উচ্চতা ৫ ফুট ৯ ইঞ্চি এবং ওজন ১৭০ পাউন্ড। আমি সারা জীবন খুব সুস্থ ছিলাম, তেমন কোনো সমস্যা হয়নি। আমার উপরের ঠোঁটের ঠিক উপরে একটি ফোলা চাকা হয়েছে যা ঠোঁটকে স্পর্শ করে আছে। চাপ না দিলে এটি ব্যথা করে না, তবে আমি এটি অনুভব করতে পারছি এবং এটি আমাকে বিরক্ত করছে। বরফ দিলে ফোলা কিছুটা কমে। এটি কোনো খোলা ক্ষত নয়, শুধু একটি চাকা যা যাচ্ছে না। এটি প্রায় ৫ দিন ধরে আছে।","হেলো প্রিয়, নাসেনিয়া ডকে আপনাকে স্বাগতম। আপনার উদ্বেগটি বুঝতে পারছি। আপনার প্রশ্ন অনুযায়ী, উপরের ঠোঁটের উপরে ফোলা অংশটি মূলত ঠোঁট কামড়ানোর কারণে হয়ে থাকে। অসাবধানতাবশত নিচের চোয়ালের দাঁত উপরের ঠোঁটে আঘাত করলে সেই জায়গায় অতিরিক্ত কোলাজেন ফাইবার জমা হয়ে ফোলাভাব সৃষ্টি হয়। এটি হারপিস সিমপ্লেক্স ভাইরাস সংক্রমণের কারণেও হতে পারে, যা ওই এলাকায় কোল্ড সোর বা ঘা সৃষ্টি করতে পারে। যদি আপনি অতিরিক্ত সূর্যের আলোতে থাকেন, তবে এই ফোসকা তার কারণেও হতে পারে। এটি নিয়ে আতঙ্কিত হওয়ার কিছু নেই। বরফের টুকরো নিয়ে এই জায়গায় ১০-১২ মিনিট বিরতি দিয়ে চেপে ধরুন। জায়গাটি পরিষ্কার রাখুন। নাসেনিয়া ডকের সাথেই থাকুন।"
4,65169,"হেলো, আমার নানি প্রায়ই অভিযোগ করেন যে তার হৃদপিণ্ডের চারপাশে গ্যাসের সমস্যা হচ্ছে, যার ফলে তিনি মাথা ঝিমঝিম এবং মাথা ঘোরার অনুভব করেন। তার বয়স ৭৭ বছর এবং তার হার্টের অপারেশন হয়েছে ও নতুন ভালভ বসানো হয়েছে। তিনি ডাক্তারকে বিষয়টি জানালেও ডাক্তার কোনো পদক্ষেপ নিচ্ছেন না। আমি চিন্তিত কারণ এর ফলে তার মাথা ঘোরে এবং এমনিতেই তার হাঁটাচলায় ভারসাম্যহীনতা রয়েছে। এর কারণ কী হতে পারে এবং কী করলে উপকার পাওয়া যাবে, তা কি জানাতে পারবেন? ধন্যবাদ।","হেলো, আমি আপনার প্রশ্নটি মনোযোগ সহকারে পড়েছি এবং ব্যাখ্যা করতে চাই যে তার হৃদযন্ত্রের কার্যকারিতা মূল্যায়ন করা এবং সম্ভাব্য হার্ট ফেইলিওর যা এই ক্লিনিকাল পরিস্থিতির অনুকরণ করতে পারে, তা বাদ দেওয়া প্রয়োজন। গ্যাস্ট্রোইসোফেজিয়াল রিফ্লাক্সও এই পরিস্থিতির অনুকরণ করতে পারে, যদিও মাথা ঘোরা এই রোগের সাধারণ লক্ষণ নয়। এই পর্যায়ে, আমি হার্ট ফেইলিওর আছে কিনা তা তদন্ত করার জন্য একটি কার্ডিয়াক আল্ট্রাসাউন্ড এবং এনটি-প্রো বিএনপি (NT-pro BNP) পরীক্ষা করার পরামর্শ দেব। বিবেচনা করার মতো অন্যান্য পরীক্ষাগুলো হলো"
5,12341,"হেলো, আমার এক বন্ধুর অ্যালকোহলের আসক্তি আছে এবং তার রক্ত পরীক্ষায় জিজিপি (GGT) লেভেল ৩৭0, যেখানে স্বাভাবিক মাত্রা ০-৬০। তার এখন আর কোনো ক্ষুধা নেই এবং সে দিনে প্রায় ৩০ গ্লাস ওয়াইন পান করে। তার পায়ে কোনো অনুভূতি নেই এবং পা ফুলে গেছে। সে দিনে ৫টি ৮০০ মিলিগ্রামের গ্যাবাফেন্টিন বড়ি খায়। সে আর কী করতে পারে? সে ডাক্তারের কাছে গিয়েছিল এবং ডাক্তার তাকে মদ্যপান বন্ধ করে সাহায্য নিতে বলেছিলেন, কিন্তু সে তা প্রত্যাখ্যান করছে।","হেলো, খারাপ খাদ্যাভ্যাস (চর্বিযুক্ত খাবার, মশলাদার খাবার), অ্যালকোহল গ্রহণ, কিছু ওষুধের ব্যবহার (বেশিরভাগ ব্যথানাশক), পিত্তথলির রোগ (যেমন পিত্তথলিতে পাথর), লিভারের ভাইরাল সংক্রমণ (এইচবিভি, এইচসিভি সংক্রমণ) ইত্যাদির কারণে লিভার এনজাইম বেড়ে যেতে পারে। যেহেতু আপনার জিজিপিটি (GGT) লেভেল আবার বেড়েছে, তাই খাদ্যাভ্যাস ছাড়াও এর বৃদ্ধির অন্যান্য সম্ভাব্য কারণগুলো খতিয়ে দেখা উচিত। জিটিপি, এপি, অ্যামাইলেজ, লাইপেজ, ইউরিন অ্যামাইলেজ, ব্যাগ, অ্যান্টিওক লেভেল পরীক্ষা করা উচিত। পেটের একটি আল্ট্রাসাউন্ডও করা প্রয়োজন। আপনার চর্বিযুক্ত খাবার, ভাজা খাবার, মশলাদার খাবার, অ্যালকোহল এবং ওষুধ এড়িয়ে চলা উচিত। প্রেসক্রিপশন ছাড়াই পাওয়া যায় এমন লিভারের কার্যকারিতা বৃদ্ধিকারী সাপ্লিমেন্টগুলোও লিভার পুনর্গঠনে সহায়ক হতে পারে। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি। আমি আপনাকে আরও কোনোভাবে সাহায্য করতে পারি কিনা তা জানাবেন।"
6,35213,"হেলো! আমি বহু বছর কোনো ব্যায়াম না করার পর আবার ব্যায়াম শুরু করার চেষ্টা করছি। আমি লক্ষ্য করছি যে, যখন আমি স্কোয়াট করি বা সিঁড়ি দিয়ে উঠি, তখন আমার হাঁটু থেকে মটমট শব্দ হয় এবং ব্যথা করে। আমি ভাবছি, আমার ওজন কি খুব বেশি এবং এই ধরনের ব্যায়াম করার আগে কি আমার ওজন কমানো প্রয়োজন?","হেলো, যেহেতু আপনি আবার ব্যায়াম শুরু করার পরিকল্পনা করছেন, তাই আমি আপনাকে এখন নিজের জন্য একটি রুটিন তৈরি করার পরামর্শ দেব। প্রথমে আপনার শরীরকে মূল্যায়ন করুন। কোন পেশীগুলো দুর্বল এবং কোন অংশে বেশি ব্যায়ামের প্রয়োজন তা দেখুন। এরপর, সবসময় ম্যাট এক্সারসাইজ দিয়ে ব্যায়াম শুরু করুন, যার মধ্যে রয়েছে সাধারণ লেগ রেইজ, হ্যান্ড রেইজ, স্ট্যাটিক কোয়াডস, স্ট্যাটিক হ্যামস, স্ট্যাটিক ট্রাইসেপস এবং স্ট্যাটিক বাইসেপস, শ্বাস-প্রশ্বাসের ব্যায়াম এবং কোর স্ট্যাবিলিটি। এর পরে সাধারণ দাঁড়িয়ে করার ব্যায়ামগুলো শুরু করুন। তারপর অ্যারোবিক্স এবং সবশেষে অ্যানেরোবিক ব্যায়ামে যান। শুধুমাত্র নিবন্ধ দেখে ব্যায়াম করার চেয়ে আগে থেকে ধাপে ধাপে ব্যায়ামের পরিকল্পনা করা সবসময় ভালো। কোনো ক্ষতি হলে তা অপূরণীয় হতে পারে। তাই অনেক সতর্কতা অবলম্বন করে ব্যায়াম শুরু করুন। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি। আমি আপনাকে আরও কোনোভাবে সাহায্য করতে পারি কিনা তা জানাবেন। জে ইন নাসেনিয়া ডক।"
7,18267,"আমার বয়স ৫৯ বছর এবং আমি একজন পুরুষ, আমার টি৭-টি১১ প্যারাপ্লেজিয়া রয়েছে। আমার বাম নিতম্বে ৫ সেমি বাই ৫ সেমি বাই ৩.৫ সেমি গভীর একটি ক্ষত রয়েছে। একটি শক্ত পিণ্ড থেকে এই ক্ষতের সৃষ্টি হয়েছিল, যা কাটার পর সংক্রমিত হয়। আমি বর্তমানে একটি উন্ড ভ্যাক (wound vac) ব্যবহার করছি এবং এটি ছোট হয়ে আসছে বলে মনে হচ্ছে, তবে প্রতিদিন বিকেল ৩টার দিকে আমার কাঁপুনি দিয়ে জ্বর আসে এবং বিকেল ৫টার মধ্যে তাপমাত্রা ১০০ ডিগ্রি ফারেনহাইটের কাছাকাছি পৌঁছায়। আমি টাইলেনল গ্রহণ করলে জ্বর স্বাভাবিক হয়ে যায়, কিন্তু রাতে আমার প্রচণ্ড ঘাম হয়। আমি কি এর জন্য কিছু করতে পারি?","হেলো। আপনার অনুসন্ধানের জন্য এবং বিস্তারিত ইতিহাস জানানোর জন্য ধন্যবাদ। এটি নিশ্চিতভাবে ক্ষতস্থানে বা মূত্রনালীতে কোনো সক্রিয় সংক্রমণের ইঙ্গিত দেয়। আমি আপনাকে রক্ত/প্রস্রাবের রুটিন পরীক্ষা, মাইক্রোস্কোপি, কালচার এবং সেনসিটিভিটি পরীক্ষা করার পরামর্শ দেব। যদি ক্ষতস্থানে পুঁজ থাকে, তবে গ্রাম স্টেইনিং, কালচার এবং সেনসিটিভিটির জন্য সোয়াব পরীক্ষা করান। নমুনা সংগ্রহের পর একজন ডাক্তারের পরামর্শ অনুযায়ী ব্রড-স্পেকট্রাম অ্যান্টিবায়োটিক শুরু করুন।"
8,108198,হেলো স্যার। আমার মায়ের কিডনি বিকল হয়ে গেছে। আমি খুব দুঃখিত। কিন্তু আমার রক্তের গ্রুপ মিলছে না। একজন ব্যক্তি কিডনি দান করতে চান। কিন্তু ডাক্তার রাজি নন এবং তিনি কাগজপত্র দাবি করছেন। আমার মা সুস্থ না হলে আমিও মারা যাব। রোগীদের জন্য ডাক্তাররা ঈশ্বরের মতো। দয়া করে স্যার আমি কী করব? দয়া করে স্যার আমাকে সাহায্য করুন এবং আমার জীবন বাঁচান।,"হেলো, নাসেনিয়া ডক ফোরামে আপনাকে স্বাগতম। কিডনি প্রতিস্থাপন কেবল দাতা প্রস্তুত থাকলেই করা যায় না, এটি এগিয়ে নেওয়ার আগে কিছু নিয়ম অনুসরণ করতে হয়। তাই, আপনার পরিবার ও বন্ধুদের সাথে এটি নিয়ে আলোচনা করুন এবং অন্যান্য পারিবারিক চিকিৎসকদের কাছ থেকেও পরামর্শ নিন, তারা সবাই আপনাকে সাহায্য করবেন এবং পরিশেষে, আশা হারাবেন না। আপনার সমস্যাগুলো সংশ্লিষ্ট চিকিৎসকের সাথেও আলোচনা করুন। আপনার মা সুস্থ হয়ে উঠবেন। আপনার জন্য শুভকামনা রইল, নিজের যত্ন নেবেন।"
9,96344,"আমার ছেলের আজ ২ বছর পূর্ণ হলো এবং গতকাল থেকে সে স্বাভাবিকের চেয়ে বেশি দাঁত কিড়মিড় করছে, যা একটানা ছিল। সে আমার ওপর খুব বেশি নির্ভরশীল হয়ে পড়েছে এবং আমি খেয়াল করলাম তার শরীরের তাপমাত্রা ৩৮.৬ ডিগ্রি সেলসিয়াস। আমি তাকে প্যারাসিটামল দিয়েছি এবং হাইড্রোথেরাপিও করেছি (ঠান্ডা পানির কাছাকাছি তাপমাত্রার পানিতে গোসল করিয়েছি)। মনে হয়েছিল কয়েক মিনিটের জন্য কাজ হয়েছে, কিন্তু রাতে তার শরীর আবার গরম হয়ে গেছে। আমি এইমাত্র তার তাপমাত্রা মেপে দেখলাম তা এখন ৩৮.৮ ডিগ্রি। আমার ছেলের কী হয়েছে?","হেলো এবং স্বাগতম। প্রদত্ত ইতিহাস অনুযায়ী, মনে হচ্ছে আপনার সন্তানের সাময়িক কালশিটে পড়েছে। এই বয়সে এটি খুবই স্বাভাবিক। নতুন দাঁত ওঠার কারণে শিশুদের মুখে ক্রমাগত অস্বস্তি হয়। তাই তারা দাঁত ঘষার মতো অভ্যাস গড়ে তোলে। এটি খুব ভালো যে আপনি সচেতন এবং তার কার্যকলাপের ওপর ভালো নজর রাখছেন। ধীরে ধীরে শিশু এই অভ্যাস ত্যাগ করবে। যদি দেখেন তিন বছর বয়সের পরেও এটি অব্যাহত রয়েছে, তবে এই বিষয়ে অবশ্যই একজন পেরিওডনটিস্টের (শিশু বিশেষজ্ঞ) পরামর্শ নেবেন। তাপমাত্রা বৃদ্ধির বিষয়ে, আপনি একবার আপনার ডেন্টিস্টের সাথে দেখা করতে পারেন। দাঁত ওঠার সময় সামান্য তাপমাত্রা বৃদ্ধি স্বাভাবিক, তবে ক্লিনিকাল মূল্যায়নের জন্য একবার ডেন্টিস্টকে দেখানো ভালো। ধন্যবাদ। ভালো থাকবেন।"

test

In [45]:
import re
import pandas as pd

# ============================================
# CLEAN TEXT
# Removes:
# - English + Bengali phone/contact numbers
# - Email addresses
# - WWW / HTTP / HTTPS URLs
# - Website/domain links
# - Markdown links
# ============================================

def clean_text(text):
    if pd.isna(text):
        return text

    text = str(text)

    # ------------------------------------------------
    # 1. Remove markdown links
    # Example:
    # [website](http://example.com)
    # [email](mailto:test@gmail.com)
    # ------------------------------------------------
    text = re.sub(
        r'\[[^\]]*\]\(\s*(?:https?://|mailto:)[^)]+\)',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    # ------------------------------------------------
    # 2. Remove email addresses
    # ------------------------------------------------
    text = re.sub(
        r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b',
        ' ',
        text
    )

    # ------------------------------------------------
    # 3. Remove URLs
    # http://
    # https://
    # www.
    # ------------------------------------------------
    text = re.sub(
        r'(?i)\b(?:https?://|www\.)[^\s<>()\[\]]+',
        ' ',
        text
    )

    # ------------------------------------------------
    # 4. Remove domain-style websites
    # Example:
    # ChatDoctor.com
    # example.org
    # website.net
    # ------------------------------------------------
    text = re.sub(
        r'(?i)\b(?:[a-z0-9-]+\.)+'
        r'(?:com|org|net|info|biz|io|co|in|bd|au)'
        r'(?:/[^\s]*)?',
        ' ',
        text
    )

    # ------------------------------------------------
    # 5. Remove phone/contact numbers
    #
    # Supports BOTH:
    # English digits: 0123456789
    # Bengali digits: ০১২৩৪৫৬৭৮৯
    #
    # Also handles:
    # +880 1712 345678
    # 01712-345678
    # ০১৭১২-৩৪৫৬৭৮
    # ০১৭১২ ৩৪৫৬৭৮
    # ------------------------------------------------

    english_digits = r'0-9'
    bengali_digits = r'০-৯'

    # English + Bengali digit character class
    digits = f'{english_digits}{bengali_digits}'

    # Numbers with spaces, -, brackets, +, dots
    phone_pattern = (
        rf'(?<![{digits}])'
        rf'\+?[{digits}]'
        rf'(?:[\s().-]*[{digits}]){{7,}}'
        rf'(?![{digits}])'
    )

    text = re.sub(phone_pattern, ' ', text)

    # ------------------------------------------------
    # 6. Remove leftover mailto
    # ------------------------------------------------
    text = re.sub(
        r'(?i)\bmailto\s*:\s*',
        ' ',
        text
    )

    # ------------------------------------------------
    # 7. Normalize spaces
    # ------------------------------------------------
    text = re.sub(r'[ \t]+', ' ', text)

    # ------------------------------------------------
    # 8. Clean spaces around newlines
    # ------------------------------------------------
    text = re.sub(r' *\n *', '\n', text)

    # ------------------------------------------------
    # 9. Remove excessive blank lines
    # ------------------------------------------------
    text = re.sub(r'\n{3,}', '\n\n', text)

    return text.strip()


# ============================================
# CREATE NEW DATAFRAME
# ============================================

df_final_test = test.copy()


# ============================================
# CLEAN BOTH INPUT AND OUTPUT
# ============================================

df_final_test["input"] = df_final_test["input"].apply(clean_text)
# df_final["output"] = df_final["output"].apply(clean_text)


# ============================================
# CHECK SHAPE
# ============================================

print("Before cleaning :", test.shape)
print("After cleaning  :", df_final_test.shape)


# ============================================
# CHECK EXAMPLES
# ============================================

display(
    df_final_test[["id", "input"]].head(5)
)

Before cleaning : (1000, 3)
After cleaning  : (1000, 3)

,id,input
0,34654,"আমার লাইপেজ লেভেল ১৫৮, যা বেশি। অ্যামাইলেজ লেভেল ৮২, যা স্বাভাবিক। এর কারণ কী হতে পারে? আমার বর্তমান ডাক্তার এবং আগের প্রাইমারি কেয়ার ডাক্তার কেউই এ নিয়ে চিন্তিত নন। অন্তত ১১ বছর ধরে এমনটাই চলছে। আমার গ্লুটেন এবং গমের প্রতি সংবেদনশীলতা আছে। এর সাথে কি কোনো সম্পর্ক থাকতে পারে? আমার পেটে কোনো ব্যথা নেই, শুধু গম, গ্লুটেন এবং কিছু দুগ্ধজাত খাবারের প্রতি সংবেদনশীলতা আছে। অনেক ধন্যবাদ! ক্যারল অ্যান ট্রাইফিলিটি।"
1,3116,"তিন সপ্তাহ আগে আমার দাঁতে খুব ব্যথা ছিল, ৮ দিন ধরে ৫০০ মিলিগ্রামের অ্যামোক্সিসিলিন ক্যাপসুল খেয়েছিলাম, এখন তিন দিন ধরে আমার মুখে খুব বাজে স্বাদ লাগছে। রাতে একই সময়ে প্রায় ২০ মিনিটের জন্য আমার শ্বাসকষ্ট হয় এবং এখন দিন যত যাচ্ছে আমার বমি বমি ভাব বাড়ছে। আমার কি চিন্তিত হওয়া উচিত?"
2,59478,"আমার স্বামীর বয়স ৫৬ বছর, তিনি খুব একটা মিশুক নন। তিনি সবসময় আমার চরিত্রের ওপর সন্দেহ করেন। তিনি আমাকে কখনোই একা বাইরে যেতে দেন না এবং বাড়িতে কোনো পুরুষ কর্মচারী রাখতে দেন না। তিনি সবসময় অন্যদের কাছে বলেন যে তিনি তার স্ত্রীকে নিয়ে বিরক্ত। এমনকি তিনি আমার প্রতিবেশী, তার নিজের ভাই, এমনকি প্রতিবেশী শিশুদের নিয়েও সন্দেহ করেন। অথচ আমার পরিবারের সবাই জানে যে এসবের কোনো ভিত্তি নেই। আমার সন্দেহ হচ্ছে তার কোনো মানসিক সমস্যা আছে। তিনি সুপ্রিম কোর্ট অফ ইন্ডিয়ার একজন অত্যন্ত সফল এবং ধনী আইনজীবী। দয়া করে সাহায্য করুন।"
3,56450,"হেলো, আমার বয়স ৩৮ বছর। আমার বাম পায়ে, একই দিকের উরুতে, নিতম্বে এবং কোমরের নিচের অংশে ব্যথা আছে। আমি অনেক ডাক্তার দেখিয়েছি, তারা ব্যথার জন্য আমাকে অক্সিকন্টিন ১০ মিগ্রা দিয়েছেন। ৪ থেকে ৫ বার এমআরআই করা হয়েছে, কিন্তু কিছু ধরা পড়েনি। এখন আমার ত্বকে মাঝে মাঝে খুব চুলকানি হয় এবং চুলকানোর পর র‍্যাশ বের হয়। দয়া করে সাহায্য করুন, আমার এখন কী করা উচিত?"
4,86380,"গত মঙ্গলবার আমি ফ্লু শট এবং টিবি পরীক্ষা করিয়েছিলাম, শুক্রবার থেকে আমার জিহ্বায় একটি অদ্ভুত অনুভূতি লক্ষ্য করছি। এটি অনেকটা অসাড়, ঝিনঝিন না করা এক ধরনের অনুভূতি এবং জিহ্বার বাম দিকে এটি বেশি বোঝা যাচ্ছে। এছাড়া, এখন আমার ঠোঁটের বাম দিকেও এই অনুভূতি হচ্ছে। আমার বয়স ৩৮ বছর এবং আমার অন্য কোনো লক্ষণ বা উপসর্গ নেই। এটি কি কোনো ইনজেকশনের পার্শ্বপ্রতিক্রিয়া হতে পারে? টিবি পরীক্ষার জায়গাটি লাল হয়ে ফুলে গিয়েছিল। আমার প্রথম টিবি পরীক্ষাটি নেগেটিভ ছিল (১০ বছরেরও বেশি আগে), দ্বিতীয়টি পজিটিভ, তৃতীয়টি নেগেটিভ এবং এই সাম্প্রতিক পরীক্ষাটি পজিটিভ এসেছে। আমি পড়েছি যে নির্দিষ্ট প্রস্তুতকারকের ওষুধের প্রতি অ্যালার্জির কারণে দ্বিতীয়বার এটি পজিটিভ হতে পারে। ধন্যবাদ।"

In [46]:
import re
import pandas as pd

# ============================================================
# FINAL DATASET AUDIT
# Does NOT delete anything
# ============================================================

df_base = df_final.copy()

print("=" * 60)
print("FINAL DATASET AUDIT")
print("=" * 60)

print("\nShape:", df_base.shape)
print("Rows:", len(df_base))
print("Columns:", len(df_base.columns))


# ============================================================
# 1. NULL / EMPTY
# ============================================================

for col in ["input", "output"]:
    null_count = df_base[col].isna().sum()
    empty_count = (
        df_base[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(f"\n{col.upper()}")
    print("Null:", null_count)
    print("Empty:", empty_count)


# ============================================================
# 2. URL CHECK
# ============================================================

url_pattern = re.compile(
    r'(?i)(?:https?://|www\.)'
)

domain_pattern = re.compile(
    r'(?i)\b(?:[a-z0-9-]+\.)+'
    r'(?:com|org|net|info|biz|io|co|in|bd|au)'
)

for col in ["input", "output"]:

    url_rows = df_base[
        df_base[col].fillna("").astype(str).str.contains(
            url_pattern, regex=True
        )
    ]

    domain_rows = df_base[
        df_base[col].fillna("").astype(str).str.contains(
            domain_pattern, regex=True
        )
    ]

    print(f"\n{col.upper()} URL CHECK")
    print("HTTP/WWW rows:", len(url_rows))
    print("Domain rows:", len(domain_rows))

    if len(url_rows) > 0:
        display(url_rows[["id", col]].head(20))

    if len(domain_rows) > 0:
        display(domain_rows[["id", col]].head(20))


# ============================================================
# 3. EMAIL CHECK
# ============================================================

email_pattern = re.compile(
    r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b'
)

for col in ["input", "output"]:

    email_rows = df_base[
        df_base[col].fillna("").astype(str).str.contains(
            email_pattern, regex=True
        )
    ]

    print(f"\n{col.upper()} EMAIL CHECK")
    print("Email rows:", len(email_rows))

    if len(email_rows) > 0:
        display(email_rows[["id", col]].head(20))


# ============================================================
# 4. PHONE NUMBER CHECK
# English + Bengali digits
# ============================================================

digits = "0-9০-৯"

phone_pattern = re.compile(
    rf'(?<![{digits}])'
    rf'\+?[{digits}]'
    rf'(?:[\s().-]*[{digits}]){{7,}}'
    rf'(?![{digits}])'
)

for col in ["input", "output"]:

    phone_rows = df_base[
        df_base[col].fillna("").astype(str).str.contains(
            phone_pattern, regex=True
        )
    ]

    print(f"\n{col.upper()} PHONE CHECK")
    print("Possible phone rows:", len(phone_rows))

    if len(phone_rows) > 0:
        display(phone_rows[["id", col]].head(20))


# ============================================================
# 5. MARKDOWN / HTML ARTIFACTS
# ============================================================

artifact_pattern = re.compile(
    r'(?i)(?:\[[^\]]*\]\([^)]+\)|'
    r'<[^>]+>|'
    r'\\mailto|'
    r'&nbsp;|'
    r'&lt;|'
    r'&gt;)'
)

for col in ["input", "output"]:

    artifact_rows = df_base[
        df_base[col].fillna("").astype(str).str.contains(
            artifact_pattern, regex=True
        )
    ]

    print(f"\n{col.upper()} MARKDOWN/HTML CHECK")
    print("Possible artifact rows:", len(artifact_rows))

    if len(artifact_rows) > 0:
        display(artifact_rows[["id", col]].head(20))


# ============================================================
# 6. EXTRA SPACES
# ============================================================

for col in ["input", "output"]:

    # Multiple normal spaces
    multiple_space = df_base[
        df_base[col].fillna("").astype(str).str.contains(
            r'[ \t]{2,}',
            regex=True
        )
    ]

    # Space before punctuation
    space_before_punct = df_base[
        df_base[col].fillna("").astype(str).str.contains(
            r'\s+[,.!?;:।]',
            regex=True
        )
    ]

    print(f"\n{col.upper()} SPACE CHECK")
    print("Multiple spaces:", len(multiple_space))
    print("Space before punctuation:", len(space_before_punct))


# ============================================================
# 7. VERY SHORT TEXT
# ============================================================

for col in ["input", "output"]:

    short_rows = df_base[
        df_base[col].fillna("").astype(str).str.strip().str.len() <= 2
    ]

    print(f"\n{col.upper()} VERY SHORT TEXT")
    print("Rows <= 2 characters:", len(short_rows))

    if len(short_rows) > 0:
        display(short_rows[["id", col]].head(30))


# ============================================================
# 8. DUPLICATE INPUT
# ============================================================

duplicate_input = df_base[
    df_base["input"].duplicated(keep=False)
].sort_values("input")

print("\nDUPLICATE INPUT")
print("----------------")
print("Rows involved:", len(duplicate_input))

if len(duplicate_input) > 0:
    display(
        duplicate_input[
            ["id", "input", "output"]
        ].head(30)
    )


# ============================================================
# 9. EXACT DUPLICATE INPUT + OUTPUT
# ============================================================

duplicate_pairs = df_base[
    df_base.duplicated(
        subset=["input", "output"],
        keep=False
    )
]

print("\nDUPLICATE INPUT + OUTPUT PAIRS")
print("--------------------------------")
print("Rows involved:", len(duplicate_pairs))

if len(duplicate_pairs) > 0:
    display(
        duplicate_pairs[
            ["id", "input", "output"]
        ].head(30)
    )


# ============================================================
# 10. LENGTH DISTRIBUTION
# ============================================================

df_base["input_len"] = (
    df_base["input"]
    .fillna("")
    .astype(str)
    .str.len()
)

df_base["output_len"] = (
    df_base["output"]
    .fillna("")
    .astype(str)
    .str.len()
)

print("\nLENGTH SUMMARY")
print("----------------")

display(
    df_base[
        ["input_len", "output_len"]
    ].describe()
)


# ============================================================
# 11. EXTREMELY LONG ROWS
# ============================================================

print("\nLONGEST INPUTS")
print("----------------")

display(
    df_base.nlargest(
        10,
        "input_len"
    )[["id", "input_len", "input"]]
)

print("\nLONGEST OUTPUTS")
print("-----------------")

display(
    df_base.nlargest(
        10,
        "output_len"
    )[["id", "output_len", "output"]]
)


# ============================================================
# 12. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 60)
print("AUDIT COMPLETE")
print("=" * 60)
print("No rows were removed.")
print("Review the flagged examples above before training.")

============================================================
FINAL DATASET AUDIT
============================================================

Shape: (108391, 5)
Rows: 108391
Columns: 5

INPUT
Null: 0
Empty: 0

OUTPUT
Null: 0
Empty: 0

INPUT URL CHECK
HTTP/WWW rows: 0
Domain rows: 0

OUTPUT URL CHECK
HTTP/WWW rows: 21
Domain rows: 0

,id,output
35,48796,"পায়ের নখের অস্ত্রোপচারের পর এই লক্ষণগুলো থাকা অস্বাভাবিক। প্রদত্ত তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনাকে বিস্তারিতভাবে পরীক্ষা ও পর্যবেক্ষণ করতে চাই। ডায়াবেটিস, উচ্চ রক্তচাপ বা অন্য কোনো বিপাকীয় ব্যাধি আছে কিনা তা নিশ্চিত করুন। যাই হোক, আপনি সংক্রমণ নিয়ন্ত্রণে অ্যান্টিবায়োটিক ব্যবহার করে দেখতে পারেন। লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে, ৫ দিনের জন্য। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিনের জন্য। (এই ওষুধগুলো পেতে আপনার স্থানীয় ডাক্তারের সাহায্য নিতে পারেন।) গরম সেঁক দিন। নরম বিছানায় শক্ত বিছানায় ঘুমান। বেদনাদায়ক কাজ ও কার্যকলাপ এড়িয়ে চলুন। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন।) মাথার নিচে কোনো বালিশ ব্যবহার করবেন না। অবহেলা করবেন না, এটি যেন কোনো বড় সমস্যার শুরু না হয়। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে উপশম না হলে, আমার সাথে আবার যোগাযোগ করুন। (ফোন: ) অনুগ্রহ করে নিশ্চিত করুন যে এই ওষুধগুলোর কোনোটিতে আপনার অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন।) জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি, আপনার আরও কোনো প্রশ্ন থাকলে আমি সাহায্য করতে পেরে খুশি হব। অনুগ্রহ করে প্রশ্নটি রেট করুন। আপনার দ্রুত আরোগ্য ও সুস্বাস্থ্য কামনা করি।"
2053,64568,"আপনার বয়স কত? প্রদত্ত তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনাকে বিস্তারিতভাবে পরীক্ষা ও পর্যবেক্ষণ করতে চাই। টেলবোনের এক্স-রে করার নির্দেশ দেওয়া হলো। উচ্চ রক্তচাপ, ডায়াবেটিস বা অন্য কোনো বিপাকীয় ব্যাধি আছে কি না তা নিশ্চিত করুন। যাই হোক, আপনি চেষ্টা করতে পারেন---। লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে। ৫ দিন। --। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিন। (এই ওষুধগুলো পাওয়ার জন্য আপনার স্থানীয় ডাক্তারের সাহায্য নিতে পারেন।) --। ১৫-২০ মিনিট উষ্ণ গরম পানিতে বসে থাকুন। --। কোষ্ঠকাঠিন্য এড়িয়ে চলুন। --। নরম বিছানাসহ শক্ত বিছানায় ঘুমান। --। বেদনাদায়ক কাজ ও কার্যকলাপ এড়িয়ে চলুন। --। পেরিনিয়াল ব্যায়াম করুন --। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন)। অবহেলা করবেন না, এটি যেন কোনো বড় সমস্যার শুরু না হয়। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে উপশম না হলে, আমার সাথে পুনরায় যোগাযোগ করুন। (ফোন: ৯১ xxxxx)। অনুগ্রহ করে নিশ্চিত করুন যে এই ওষুধগুলোর কোনোটিতে আপনার অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন)। জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান। -আশা করি আমি আপনার প্রশ্নের উত্তর দিয়েছি, আপনার যদি আরও কোনো প্রশ্ন থাকে, আমি সাহায্য করতে পেরে খুশি হব। -অনুগ্রহ করে উত্তরটি রেট করুন। -আপনার দ্রুত আরোগ্য ও সুস্বাস্থ্য কামনা করি।"
12090,99834,"প্রদত্ত তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনাকে বিস্তারিতভাবে পরীক্ষা ও পর্যবেক্ষণ করতে চাই। উচ্চ রক্তচাপ, ডায়াবেটিস বা অন্য কোনো বিপাকীয় ব্যাধি আছে কি না তা নিশ্চিত করুন। যাই হোক, আপনি চেষ্টা করতে পারেন---। লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে। ৫ দিন। --। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিন। (এই ওষুধগুলো পেতে আপনার স্থানীয় ডাক্তারের সাহায্য নিতে পারেন।) --। গরম পানি দিয়ে সেঁক দিন। --। নরম বিছানাসহ শক্ত বিছানায় ঘুমান। --। বেদনাদায়ক কাজ ও কার্যকলাপ এড়িয়ে চলুন। --। পা ও গোড়ালির জন্য হালকা ব্যায়াম করুন। --। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন)। অবহেলা করবেন না, এটিকে বড় কোনো সমস্যার শুরু হতে দেবেন না। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে উপশম না হলে, আমার সাথে আবার যোগাযোগ করুন। (ফোন: xxxxx) অনুগ্রহ করে নিশ্চিত করুন যে, এই ওষুধগুলোর কোনোটিতে আপনার অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন)। জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান। -আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি, আপনার যদি আরও কোনো প্রশ্ন থাকে, আমি সাহায্য করতে পেরে খুশি হব। -অনুগ্রহ করে প্রশ্নটির রেটিং দিন। -আপনার দ্রুত আরোগ্য ও সুস্বাস্থ্য কামনা করি।"
30566,24492,"আপনার বয়স কত? অনুগ্রহ করে ডিস্ক ডিজেনারেশন, স্পন্ডাইলোসিস ইত্যাদির পরিবর্তে আপনার উপসর্গগুলো বর্ণনা করুন। প্রদত্ত তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনাকে বিস্তারিতভাবে পরীক্ষা ও পর্যবেক্ষণ করতে চাই। ডায়াবেটিস বা অন্য কোনো বিপাকীয় ব্যাধি আছে কিনা তা নিশ্চিত করুন। যাই হোক, আপনি চেষ্টা করে দেখতে পারেন---। লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে। ৫ দিনের জন্য। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিনের জন্য। (এই ওষুধগুলো পাওয়ার জন্য আপনি আপনার স্থানীয় ডাক্তারের সাহায্য নিতে পারেন)। গরম পানি দিয়ে সেঁক দিন। এসির বা কুলারের সরাসরি বাতাস এড়িয়ে চলুন। নরম বিছানা এড়িয়ে শক্ত বিছানায় ঘুমান। কষ্টদায়ক কাজ ও কার্যকলাপ এড়িয়ে চলুন। পিঠ, ঘাড়, কাঁধ, হাঁটু ও পায়ের জন্য হালকা ব্যায়াম করুন। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন)। মাথার নিচে কোনো বালিশ ব্যবহার করবেন না। অবহেলা করবেন না, এটি যেন কোনো বড় সমস্যার শুরু না হয়। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে উপশম না হলে, আমার সাথে পুনরায় যোগাযোগ করুন। (ফোন: )। অনুগ্রহ করে নিশ্চিত করুন যে এই ওষুধগুলোর কোনোটিতে আপনার অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন)। জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান। আশা করি আমি আপনার প্রশ্নের উত্তর দিয়েছি, আপনার আরও কোনো প্রশ্ন থাকলে আমি সাহায্য করতে পেরে খুশি হব। অনুগ্রহ করে প্রশ্নটি রেট করুন। আপনার দ্রুত আরোগ্য ও সুস্বাস্থ্য কামনা করি।"
31653,20970,"আপনার বয়স কত? এটি সম্ভবত অঙ্গের দৈর্ঘ্যের পার্থক্যের কারণে হচ্ছে। বাম দিকে ১.৭৫ ইঞ্চি অতিরিক্ত হিল ব্যবহার করুন। প্রদত্ত তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনাকে বিস্তারিতভাবে পরীক্ষা ও পর্যবেক্ষণ করতে চাই। উচ্চ রক্তচাপ, ডায়াবেটিস বা অন্য কোনো বিপাকীয় ব্যাধি আছে কিনা তা নিশ্চিত করুন। যাই হোক, আপনি চেষ্টা করতে পারেন---। লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে। ৫ দিন। --। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিন। (এই ওষুধগুলো পাওয়ার জন্য আপনার স্থানীয় ডাক্তারের সাহায্য নিতে পারেন)। --। গরম পানি দিয়ে সেঁক দিন। --। নরম বিছানাসহ শক্ত বিছানায় ঘুমান। --। বেদনাদায়ক কাজ ও কার্যকলাপ এড়িয়ে চলুন। --। পিঠ, হাঁটু, পা, পায়ের পাতা ও গোড়ালির জন্য হালকা ব্যায়াম করুন। --। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন)। অবহেলা করবেন না, এটিকে বড় কোনো সমস্যার শুরু হতে দেবেন না। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে আরাম না পেলে, আমার সাথে পুনরায় যোগাযোগ করুন। (ফোন. xxxix) অনুগ্রহ করে নিশ্চিত করুন যে, এই ওষুধগুলোর কোনোটিতে আপনার অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন)। জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান। -আশা করি আমি আপনার প্রশ্নের উত্তর দিয়েছি, আপনার আরও কোনো প্রশ্ন থাকলে আমি সাহায্য করতে পেরে খুশি হব। -অনুগ্রহ করে উত্তরটি রেট করুন। -আপনার দ্রুত আরোগ্য ও সুস্বাস্থ্য কামনা করি।"
34785,33585,"প্রদত্ত তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনাকে বিস্তারিতভাবে পরীক্ষা ও পর্যবেক্ষণ করতে চাই। ডায়াবেটিস আছে কি না তা নিশ্চিত করুন। যাই হোক, এটি চেষ্টা করে দেখা যেতে পারে। লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে। ৫ দিনের জন্য। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিনের জন্য। (এই ওষুধগুলো পাওয়ার জন্য আপনার স্থানীয় ডাক্তারের সাহায্য নিতে হতে পারে।) গরম পানি দিয়ে সেঁক দিন। এসি বা কুলারের সরাসরি বাতাস এড়িয়ে চলুন। নরম বিছানায় শক্ত বিছানায় ঘুমান। বেদনাদায়ক কাজ ও কার্যকলাপ এড়িয়ে চলুন। পিঠের জন্য হালকা ব্যায়াম করুন। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন।) মাথার নিচে কোনো বালিশ ব্যবহার করবেন না। অবহেলা করবেন না, এটি যেন কোনো বড় সমস্যার শুরু না হয়। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে উপশম না হলে, আমার সাথে পুনরায় যোগাযোগ করুন। (ফোন: ) অনুগ্রহ করে নিশ্চিত করুন যে, এই ওষুধগুলোর কোনোটিতে আপনার অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন।) জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান।"
34854,54257,"আপনার বয়স কত? ফাইব্রোমায়ালজিয়া শব্দটি প্রায়শই পেশীর ব্যথা বোঝাতে ব্যবহৃত হয়। এটি ব্যথার কারণ সম্পর্কে কিছু বলে না। আপনার দেওয়া তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনাকে বিস্তারিতভাবে পরীক্ষা ও পর্যবেক্ষণ করতে চাই। ডায়াবেটিস আছে কি না তা নিশ্চিত করুন। যাই হোক, এটি চেষ্টা করে দেখা যেতে পারে,--। লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে। ৫ দিন। --। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিন। (এই ওষুধগুলো পাওয়ার জন্য আপনার স্থানীয় ডাক্তারের সাহায্য নিতে পারেন।) --। গরম পানি দিয়ে সেঁক দিন। এসি বা কুলারের সরাসরি বাতাস এড়িয়ে চলুন। --। নরম বিছানায় শক্ত বিছানায় ঘুমান। --। বেদনাদায়ক কাজ ও কার্যকলাপ এড়িয়ে চলুন। --। সব জয়েন্টের জন্য হালকা ব্যায়াম করুন। --। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন)। --। মাথার নিচে কোনো বালিশ ব্যবহার করবেন না। অবহেলা করবেন না, এটিকে বড় কোনো সমস্যার শুরু হতে দেবেন না। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে উপশম না হলে, আমার সাথে আবার যোগাযোগ করুন। (ফোন: ) অনুগ্রহ করে নিশ্চিত করুন যে, এই ওষুধগুলোর কোনোটিতে আপনার অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন)। জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান। -আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি, আপনার যদি আরও কোনো প্রশ্ন থাকে, আমি সাহায্য করতে পেরে খুশি হব। -অনুগ্রহ করে প্রশ্নটি রেট করুন। -আপনার দ্রুত আরোগ্য ও সুস্বাস্থ্য কামনা করি।"
37989,44124,"সাধারণত মেরুদণ্ড স্পাইনাল ফ্লুইড (CSF) দ্বারা পরিবেষ্টিত থাকে। এটি না থাকা অত্যন্ত উদ্বেগের বিষয়। আপনি যে লক্ষণগুলোর কথা বর্ণনা করেছেন তা সার্ভিকাল স্পন্ডাইলোসিস, র‍্যাডিকুলোপ্যাথি সহ বা ছাড়া হতে পারে। প্রদত্ত তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনাকে বিস্তারিত পরীক্ষা ও পর্যবেক্ষণ করতে চাই। উচ্চ রক্তচাপ, ডায়াবেটিস বা অন্য কোনো বিপাকীয় ব্যাধি আছে কিনা তা নিশ্চিত করুন। যাই হোক, আপনি চেষ্টা করতে পারেন---। লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে। ৫ দিন। --। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিন। (এই ওষুধগুলো পাওয়ার জন্য আপনার স্থানীয় ডাক্তারের সাহায্য নিতে পারেন।) --। গরম পানি দিয়ে সেঁক দিন। --। নরম বিছানাসহ শক্ত বিছানায় ঘুমান। --। বেদনাদায়ক কাজ ও কার্যকলাপ এড়িয়ে চলুন। --। পিঠ, ঘাড় ও কাঁধের জন্য হালকা ব্যায়াম করুন। --। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন)। --। মাথার নিচে কোনো বালিশ ব্যবহার করবেন না। অবহেলা করবেন না, এটি যেন কোনো বড় সমস্যার শুরু না হয়। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে উপশম না হলে, আমার সাথে পুনরায় যোগাযোগ করুন। (ফোন: ) অনুগ্রহ করে নিশ্চিত করুন যে, এই ওষুধগুলোর কোনোটিতে আপনার অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন)। জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান। আশা করি আমি আপনার প্রশ্নের উত্তর দিয়েছি, আপনার আরও কোনো প্রশ্ন থাকলে আমি সাহায্য করতে পেরে খুশি হব। অনুগ্রহ করে প্রশ্নটি রেট করুন। আপনার দ্রুত আরোগ্য ও সুস্বাস্থ্য কামনা করি।"
49630,24238,"হেলো, নাসেনিয়া ডক ফোরামে আপনাকে স্বাগতম। আপনার মায়ের ইউএসজি (USG) এবং এমআরআই (MRI) রিপোর্টে কী উল্লেখ আছে তা আমরা জানতে চাই, তবেই আমরা আপনাকে কিছু পরামর্শ দিতে পারব। যেহেতু আপনি উল্লেখ করেছেন যে তার চোখ হলুদ হয়ে যাচ্ছে এবং পেটে ফোলাভাব রয়েছে, এটি নির্দেশ করে যে লিভার সম্পর্কিত কোনো গুরুতর সমস্যা রয়েছে, তবে এর সাথে আরও অন্যান্য জটিলতা থাকতে পারে। অনুগ্রহ করে রিপোর্টে কী আছে তা জানান। আরও তথ্যের জন্য আমাদের এ মেইল করুন অথবা আমাদের ওয়েবসাইট WWW. ভিজিট করুন।"
53918,17368,"হেলো, নাসেনিয়া ডক ফোরামে আপনাকে স্বাগতম। হ্যাঁ, পিত্তথলির পাথর ওষুধের মাধ্যমে গলানো সম্ভব, তবে শুধুমাত্র হোমিওপ্যাথিক ওষুধের মাধ্যমেই। আপনি যদি অ্যালোপ্যাথিক চিকিৎসা নিতে যান, তবে তারা আপনাকে পিত্তথলি অপসারণ করতে বলবে, যা করা উচিত নয় কারণ এর অনেক পার্শ্বপ্রতিক্রিয়া রয়েছে এবং এটি ভবিষ্যতে আপনার হজম প্রক্রিয়াকে ব্যাহত করবে। তাই হোমিওপ্যাথিক চিকিৎসা নেওয়াই ভালো। আরও তথ্যের জন্য আপনি আমাদের এ মেইল করতে পারেন অথবা আমাদের ওয়েবসাইট WWW. ভিজিট করতে পারেন।"
66687,11547,"আপনার বয়স কত? সম্ভবত আপনার কাঁধের জয়েন্টে অস্টিওফাইট তৈরি হয়েছে। প্রদত্ত তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনাকে বিস্তারিত পরীক্ষা ও পর্যবেক্ষণ করতে চাই। উচ্চ রক্তচাপ, ডায়াবেটিস বা অন্য কোনো বিপাকীয় ব্যাধি আছে কি না তা নিশ্চিত করুন। যাই হোক, আপনি চেষ্টা করতে পারেন---। লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে। ৫ দিন। --। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিন। (এই ওষুধগুলো পাওয়ার জন্য আপনার স্থানীয় ডাক্তারের সাহায্য নিতে পারেন।) --। গরম পানি দিয়ে সেঁক দিন। --। নরম বিছানাসহ শক্ত বিছানায় ঘুমান। --। বেদনাদায়ক কাজ ও কার্যকলাপ এড়িয়ে চলুন। --। ঘাড় ও কাঁধের জন্য হালকা ব্যায়াম করুন। --। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন)। - অবহেলা করবেন না, এটি যেন কোনো বড় সমস্যার শুরু না হয়। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে উপশম না হলে, আমার সাথে পুনরায় যোগাযোগ করুন। (ফোন. xxxix) অনুগ্রহ করে নিশ্চিত করুন যে, এই ওষুধগুলোর কোনোটিতে আপনার অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন)। জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান। - আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি, আপনার আরও কোনো প্রশ্ন থাকলে আমি সাহায্য করতে পেরে খুশি হব। - অনুগ্রহ করে প্রশ্নটি রেট করুন। - আপনার দ্রুত আরোগ্য ও সুস্বাস্থ্য কামনা করি।"
78078,22235,"হেলো, আপনাকে প্রথমেই জানিয়ে রাখি যে লিপোমা মূলত একটি বংশগত সমস্যা এবং যদি এটি ক্যানসারযুক্ত না হয় তবে আপনার এটি নিয়ে চিন্তিত হওয়ার প্রয়োজন নেই। অ্যালোপ্যাথিতে লিপোমার কোনো নিরাময় নেই, তবে আপনি হোমিওপ্যাথি ওষুধ সেবনের মাধ্যমে আপনার শরীরে লিপোমার আরও বৃদ্ধি রোধ করতে পারেন। যেহেতু আপনার অন্যান্য উপসর্গও রয়েছে এবং হোমিওপ্যাথিতে আমরা রোগীকে সামগ্রিকভাবে চিকিৎসা করি, তাই আপনার সমস্ত উপসর্গ একই চিকিৎসার আওতায় আসবে এবং আপনি আগের চেয়ে অনেক ভালো বোধ করবেন। আরও তথ্যের জন্য আপনি আমাদের এ মেইল করতে পারেন অথবা আমাদের ওয়েবসাইট WWW. ভিজিট করতে পারেন।"
80870,30212,"হেলো, নাসেনিয়া ডক ফোরামে আপনাকে স্বাগতম। আপনার সন্তানের জন্য হোমিওপ্যাথিক চিকিৎসা শুরু করা ভালো, ইনহেলার কখনোই কাজ করবে না কারণ এটি কেবল সাময়িক আরাম দেয় এবং এতে স্টেরয়েড থাকায় এর অনেক পার্শ্বপ্রতিক্রিয়া রয়েছে যা রোগটিকে কেবল চেপে রাখে, যা তার ভবিষ্যতের স্বাস্থ্যের জন্য ভালো নয়। হোমিওপ্যাথি নিরাপদ, নির্ভরযোগ্য এবং এর কোনো পার্শ্বপ্রতিক্রিয়া নেই। এই ক্ষেত্রে সঠিক হোমিওপ্যাথিক ওষুধের প্রয়োজন হবে, তাই আরও তথ্যের জন্য আপনি আমাদের এ মেইল করতে পারেন অথবা আমাদের ওয়েবসাইট WWW. ভিজিট করতে পারেন।"
85103,108089,"হাতে ঝিনঝিন বা অবশ ভাবটি কাকতালীয় এবং এর সাথে ম্যামোগ্রাফির কোনো সম্পর্ক নেই। আপনার এই বয়সে এটি সার্ভিকাল স্পন্ডাইলোসিসের কারণে হতে পারে। প্রদত্ত তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনাকে বিস্তারিত পরীক্ষা ও পর্যবেক্ষণ করতে চাই। ডায়াবেটিস আছে কি না তা নিশ্চিত করুন। যাই হোক, এটি চেষ্টা করে দেখা যেতে পারে,--। লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে। ৫ দিনের জন্য। --। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিনের জন্য। (এই ওষুধগুলো পাওয়ার জন্য আপনার স্থানীয় ডাক্তারের সাহায্য নিতে পারেন।) --। গরম পানি দিয়ে সেঁক দিন। এসি বা কুলারের সরাসরি বাতাস এড়িয়ে চলুন। --। নরম বিছানাসহ শক্ত বিছানায় ঘুমান। --। ঘাড় ও কাঁধের জন্য হালকা ব্যায়াম করুন। --। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন)। --। মাথার নিচে কোনো বালিশ ব্যবহার করবেন না। অবহেলা করবেন না, এটি যেন কোনো বড় সমস্যার শুরু না হয়। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে আরাম না পেলে আমার সাথে পুনরায় যোগাযোগ করুন। (ফোন: ) অনুগ্রহ করে নিশ্চিত করুন যে এই ওষুধগুলোর কোনোটিতে আপনার অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন)। জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান। -আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি, আপনার আরও কোনো প্রশ্ন থাকলে আমি সাহায্য করতে পেরে খুশি হব। -অনুগ্রহ করে প্রশ্নটির রেটিং দিন। -আপনার সুস্বাস্থ্য কামনা করি।"
95868,65136,"হেলো, নাসেনিয়া ডক ফোরামে আপনাকে স্বাগতম। ৫ মাস বয়সী শিশুর ক্ষেত্রে একজিমা খুব একটা দেখা যায় না, তাই আপনার শিশুর ত্বকের ক্ষতগুলোর ছবি আমাদের প্রয়োজন, যাতে আমরা সঠিকভাবে রোগ নির্ণয় করতে পারি। স্টেরয়েডযুক্ত মলম দিয়ে ত্বকের রোগের চিকিৎসা আপনার শিশুর জন্য ক্ষতিকর হতে পারে এবং এটি কেবল ত্বকের সমস্যাকে সাময়িকভাবে দমিয়ে রাখবে, পুরোপুরি সারিয়ে তুলবে না। যেকোনো চর্মরোগের সম্পূর্ণ এবং স্থায়ী নিরাময়ের জন্য আপনার হোমিওপ্যাথিক চিকিৎসা নেওয়া উচিত। আরও তথ্যের জন্য আমাদের এ ইমেইল করুন অথবা আমাদের ওয়েবসাইট WWW. ভিজিট করুন।"
97943,94053,"আপনার বয়স কত? হাঁটু থেকে যে নরম শব্দ হচ্ছে তা টেন্ডন ছিঁড়ে যাওয়ার কারণে হতে পারে। প্রদত্ত তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনাকে বিস্তারিতভাবে পরীক্ষা ও পর্যবেক্ষণ করতে চাই। উচ্চ রক্তচাপ, ডায়াবেটিস বা অন্য কোনো বিপাকীয় ব্যাধি আছে কিনা তা নিশ্চিত করুন। যাই হোক, আপনি চেষ্টা করতে পারেন---। লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে। ৫ দিন। --। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিন। (এই ওষুধগুলো পাওয়ার জন্য আপনার স্থানীয় ডাক্তারের সাহায্য নিতে পারেন।) --। গরম পানি দিয়ে সেঁক দিন। --। নরম বিছানাসহ শক্ত বিছানায় ঘুমান। --। বেদনাদায়ক কাজ ও কার্যকলাপ এড়িয়ে চলুন। --। হাঁটু ও পায়ের জন্য হালকা ব্যায়াম করুন। --। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন)। অবহেলা করবেন না, এটি যেন কোনো বড় সমস্যার শুরু না হয়। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে উপশম না হলে, আমার সাথে পুনরায় যোগাযোগ করুন। (ফোন: )। অনুগ্রহ করে নিশ্চিত করুন যে এই ওষুধগুলোর কোনোটিতে আপনার অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন)। জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান। আশা করি আমি আপনার প্রশ্নের উত্তর দিয়েছি, আপনার আরও কোনো প্রশ্ন থাকলে আমি সাহায্য করতে পেরে খুশি হব। অনুগ্রহ করে উত্তরটি রেট করুন। আপনার দ্রুত আরোগ্য ও সুস্বাস্থ্য কামনা করি।"
99713,106433,"প্রদত্ত তথ্যের ভিত্তিতে এই চিকিৎসার পরামর্শ দেওয়া হচ্ছে। আমি আপনার স্ত্রীকে বিস্তারিতভাবে পরীক্ষা ও পর্যবেক্ষণ করতে চাই। ঘাড় সামনের দিকে ও পেছনের দিকে নাড়াচাড়ার এই লক্ষণটি কোনো অর্থোপেডিক লক্ষণের সাথে খাপ খায় না (অন্তত আমার জানা মতে)। অনুগ্রহ করে একজন মনোরোগ বিশেষজ্ঞের পরামর্শ নিন। উচ্চ রক্তচাপ, ডায়াবেটিস বা অন্য কোনো বিপাকীয় ব্যাধি আছে কিনা তা নিশ্চিত করুন। যাই হোক, আপনি চেষ্টা করতে পারেন--- লুকিং প্লাস (ম্যানকাইন্ড) [ডাইক্লোফেনাক ১০০ মিগ্রা + প্যারাসিটামল ৩৫০ মিগ্রা] ১টি ট্যাবলেট দিনে একবার এবং প্রয়োজনে। ৫ দিন। ক্যালসিফাইড প্লাস (ম্যানকাইন্ড) ১টি ট্যাবলেট দিনে একবার, ১০ দিন। (এই ওষুধগুলো পাওয়ার জন্য আপনার স্থানীয় ডাক্তারের সাহায্য নিতে পারেন।) গরম পানি দিয়ে সেঁক দিন। শক্ত বিছানায় নরম তোশক ব্যবহার করে ঘুমান। মাথার নিচে কোনো বালিশ ব্যবহার করবেন না। ব্যথাদায়ক কাজ ও কার্যকলাপ এড়িয়ে চলুন। ঘাড় ও কাঁধের জন্য হালকা ব্যায়াম করুন। (একজন ফিজিওথেরাপিস্টের সাহায্য নিন অথবা WWW. Chat Doctor. Com ভিজিট করুন)। অবহেলা করবেন না, এটি যেন কোনো বড় সমস্যার শুরু না হয়। বিস্তারিত চিকিৎসা পরিকল্পনার জন্য জিজ্ঞাসা করুন। ২-৩ দিনের মধ্যে উপশম না হলে, আমার সাথে পুনরায় যোগাযোগ করুন। (এই প্ল্যাটফর্মের মাধ্যমে।) অনুগ্রহ করে নিশ্চিত করুন যে, এই ওষুধগুলোর কোনোটিতে অ্যালার্জি নেই। (প্রয়োজনে পারিবারিক ডাক্তারের সাথে যোগাযোগ করুন)। জরুরি চিকিৎসার জন্য নিকটস্থ হাসপাতালে যান। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি, আপনার আরও কোনো প্রশ্ন থাকলে আমি সাহায্য করতে পেরে খুশি হব। অনুগ্রহ করে উত্তরটিকে রেটিং দিন। আপনার স্ত্রীর দ্রুত আরোগ্য ও সুস্বাস্থ্য কামনা করি।"

INPUT EMAIL CHECK
Email rows: 0

OUTPUT EMAIL CHECK
Email rows: 0

INPUT PHONE CHECK
Possible phone rows: 0

OUTPUT PHONE CHECK
Possible phone rows: 0

INPUT MARKDOWN/HTML CHECK
Possible artifact rows: 0

OUTPUT MARKDOWN/HTML CHECK
Possible artifact rows: 3

,id,output
26098,21029,"হেলো, আমাদের কাছে লেখার জন্য ধন্যবাদ। রেনাল অ্যাঞ্জিওমায়োলিপোমা হলো চর্বি, পেশী এবং রক্তনালী দ্বারা গঠিত এক ধরনের বিনাইন বা নিরীহ টিউমার। এর চিকিৎসা নির্ভর করে অ্যাঞ্জিওমায়োলিপোমার আকারের ওপর। ছোট এবং উপসর্গহীন টিউমারগুলো (< ৪ সেমি) সাধারণত স্থিতিশীল থাকে, তবে পর্যায়ক্রমে সেগুলোর মূল্যায়ন করা উচিত। মাঝারি আকারের টিউমারগুলোর (৪-৮ সেমি) ক্ষেত্রে আচরণ সবচেয়ে পরিবর্তনশীল হতে পারে। এই টিউমারগুলোকে নিয়মিত ইমেজিং পরীক্ষার মাধ্যমে নিবিড় পর্যবেক্ষণে রাখা উচিত। যদি আকারে উল্লেখযোগ্য পরিবর্তন বা কোনো উপসর্গ দেখা দেয়, অথবা রোগীর কোমরের দিকে আঘাত পাওয়ার ঝুঁকি থাকে, তবে কিডনি বাঁচানোর সম্ভাবনা বাড়াতে দ্রুত ঐচ্ছিক চিকিৎসার ব্যবস্থা নেওয়া উচিত। বড় আকারের উপসর্গহীন অ্যাঞ্জিওমায়োলিপোমাগুলো (> ৮ সেমি) খুব সম্ভবত ভবিষ্যতে উপসর্গ তৈরি করবে, তাই উপসর্গ এবং সম্ভাব্য জটিলতা দেখা দেওয়ার আগেই সেগুলোর ঐচ্ছিক চিকিৎসা করা উচিত। যেহেতু আপনার মায়ের টিউমারটির আকার ৬.৭ সেমি, তাই অস্ত্রোপচারের কথা ভাবার আগে আগামী ৬ মাস এর আকার বৃদ্ধি এবং মূত্রনালীর কোনো উপসর্গ আছে কি না, তা পর্যবেক্ষণ করার জন্য অপেক্ষা করা যেতে পারে।"
31303,97939,"হেলো স্যার/ম্যাডাম। শুভ সন্ধ্যা। অনুসন্ধানের জন্য ধন্যবাদ। আপনার দেওয়া তথ্য অনুযায়ী, দুটি বিষয় স্পষ্ট ১. ডায়াবেটিক ২. রক্তস্বল্পতা <হিমোগ্লোবিন ৭>। কিন্তু সিবিসি <টিএলসি, ডিএলসি>, এলএফটি, কেএফটি এবং বুকের এক্স-রে সম্পর্কে কোনো তথ্য নেই, তাই মৃত্যুর কারণ সম্পর্কে মন্তব্য করা খুব কঠিন। তিনি ইনসুলিন নিচ্ছিলেন কি না বা উল্লিখিত সমস্যার জন্য কী চিকিৎসা নিচ্ছিলেন তা স্পষ্ট নয়। অনিয়ন্ত্রিত ডায়াবেটিস রোগীদের ক্ষেত্রে সংক্রমণ, হাইপোগ্লাইসেমিক এপিসোড এবং সাইলেন্ট হার্ট অ্যাটাক সাধারণ বিষয়। কম হিমোগ্লোবিনের মাত্রা, মুখ দিয়ে ফেনা ওঠা এবং হাত-পা ঠান্ডা হয়ে যাওয়া সাইলেন্ট হার্ট অ্যাটাকের দিকে ইঙ্গিত করে। ধন্যবাদ।"
75577,99765,"হেলো। আপনার অনুসন্ধানের জন্য ধন্যবাদ। ১৩ বছর বয়সী একটি মেয়ের ব্যথার কারণ নির্ণয় করা কখনও কখনও কঠিন এবং বাবা-মায়ের পক্ষে তা মেনে নেওয়া সহজ নয়। <অ্যাপেন্ডিক্স, কিডনি, গলব্লাডার পরীক্ষা এবং প্রচুর রক্ত পরীক্ষার সবকিছুই ভালো এসেছে> এটি নির্দেশ করে যে কোনো শারীরিক সমস্যা নাও থাকতে পারে। এটি আইবিএস (IBS) বা ইরিটেবল বাওয়েল সিনড্রোম হতে পারে। ডাক্তারের সাথে চ্যাট করুন। এছাড়া কোলোনোস্কোপি এবং পেটের সিটি স্ক্যান করিয়ে নিন। যদি সব পরীক্ষা নেতিবাচক আসে, তবে অ্যান্টি-সাইকোটিক ওষুধ দিয়ে চিকিৎসা শুরু করে দেখা যেতে পারে।"

INPUT SPACE CHECK
Multiple spaces: 0
Space before punctuation: 188

OUTPUT SPACE CHECK
Multiple spaces: 0
Space before punctuation: 226

INPUT VERY SHORT TEXT
Rows <= 2 characters: 0

OUTPUT VERY SHORT TEXT
Rows <= 2 characters: 0

DUPLICATE INPUT
----------------
Rows involved: 92

,id,input,output
69923,95419,আমার এমআরআই রিপোর্টে দেখা গেছে,"হেলো, স্নায়বিক দুর্বলতা যা কমপ্রেশনের কারণে হচ্ছে তার ওপর ভিত্তি করে অস্ত্রোপচারের প্রয়োজনীয়তা মূল্যায়ন করা হয়। যদি এটি কোনো দুর্বলতা সৃষ্টি করে তবে অস্ত্রোপচারের পরামর্শ অবশ্যই দেওয়া হয়। যদি ব্যথা নিয়ন্ত্রণহীন হয় তবে অস্ত্রোপচারের কথা বিবেচনা করা যেতে পারে। চিকিৎসার অন্যান্য পদ্ধতির মধ্যে রয়েছে কঠোরভাবে বিছানায় বিশ্রাম এবং ফিজিওথেরাপি। কখনও কখনও স্থানীয় এলাকায় ইনজেকশন দীর্ঘস্থায়ী আরাম দিতে পারে। ডিস্ক বাল্জের অবস্থানের ওপর ভিত্তি করে অস্ত্রোপচারের ধরন নির্ধারণ করা হয়। মূলত ডিস্কের যে অংশটি স্নায়ুর ওপর চাপ সৃষ্টি করছে তা কেটে অপসারণ করা হয়। শুভকামনা।"
70098,83684,আমার এমআরআই রিপোর্টে দেখা গেছে,"আপনি যদি অন্তত আপনার বয়স এবং আপনার কিছু ক্লিনিকাল ইতিহাস আমাদের জানাতেন তবে এটি অনেক সহজ হতো। সেই রিপোর্টের কোনো ফলাফলই জীবন-হুমকিস্বরূপ নয়। প্রথম অংশটি কিছু পুরনো আঘাতের অবশিষ্টাংশকে নির্দেশ করে, অনেকটা ছোট ক্ষতের মতো, যা আর সক্রিয় নয় এবং এর উৎস নির্ণয় করা কঠিন; এটি অতীতে কোনো সংক্রমণ বা রক্ত প্রবাহের অভাবের কারণে ছোট রক্তনালী সরু হয়ে যাওয়ার ফলে সামান্য আঘাত হতে পারে। বয়স ৬৫-এর বেশি হলে পরেরটি হওয়ার সম্ভাবনা বেশি, তাই উচ্চ রক্তচাপ, ডায়াবেটিস, ধূমপান, উচ্চ কোলেস্টেরল ইত্যাদির মতো বিষয়গুলোর দিকে নজর দেওয়া উচিত, যা ভবিষ্যতে আপনার রক্তনালীর আরও ক্ষতির ঝুঁকি বাড়ায়। মাইক্রোহেমোরেজের ক্ষেত্রে, এটি মস্তিষ্কে একটি ছোট রক্তপাত। এরও বেশ কয়েকটি কারণ থাকতে পারে, রিপোর্টটি কারণ হিসেবে একটি ক্যাভারনোমার কথা উল্লেখ করেছে, এটি একটি রক্তনালীর অস্বাভাবিকতা, যা ছোট রক্তপাত বা খিঁচুনি সৃষ্টি করতে পারে, তবে খুব নির্দিষ্ট কিছু স্থানে না হলে এটি সাধারণত জীবন-হুমকিস্বরূপ নয়, আপনার ক্ষেত্রে তেমনটি মনে হচ্ছে না। সাধারণত এটি যেমন আছে তেমনই রাখা হয়, খুব কম ক্ষেত্রেই অস্ত্রোপচার বা খিঁচুনির জন্য চিকিৎসার প্রয়োজন হয়।"
86201,41769,আমার এমআরআই রিপোর্টে দেখা গেছে,"হেলো, নাসেনিয়া ডকে লেখার জন্য ধন্যবাদ। সাধারণত, এক্সট্রুডেড ডিস্কের কারণে যে উপসর্গগুলো দেখা দেয়, তা রক্ষণশীল চিকিৎসায় পুরোপুরি সেরে ওঠে না। যদি আপনার উদ্বেগের কারণ শুধুমাত্র ঝিঁঝিঁ ধরা বা অসাড়তা হয়, তবে প্রেগাবালিন এবং মিথাইলকোবালামিনের সংমিশ্রণ কিছুটা সাহায্য করতে পারে, কিন্তু এটি সম্পূর্ণ নিরাময় প্রদান করবে না। আমি ব্যক্তিগতভাবে মনে করি যে আপনার ক্ষেত্রে সার্জিক্যাল ডিকম্প্রেশন (যেহেতু সংশ্লিষ্ট পেশীগুলোতে দুর্বলতা রয়ে গেছে) প্রয়োজন, যা এন্ডোস্কোপিক ডিসেক্টমি বা মাইক্রোলুম্বার ডিসেক্টমির মাধ্যমে করা যেতে পারে এবং এর ফলাফল চমৎকার। তাই, পরবর্তী চিকিৎসার জন্য আমি আপনাকে একজন স্পাইন সার্জনের সাথে পরামর্শ করার পরামর্শ দিচ্ছি। আশা করি এই তথ্যটি আপনার জন্য সহায়ক হবে। আপনার দিনটি ভালো কাটুক।"
53681,13138,"আমার ওপরের চোয়ালের একটি দাঁতে রুট ক্যানেল করা হয়েছিল। চিকিৎসার পর, রুট ক্যানেল করা দাঁতের মাড়ির সংলগ্ন গর্তগুলোর চারপাশে খাবার আটকে যাওয়ার সমস্যা হচ্ছিল।","হেলো, আমি আপনার প্রশ্নটি দেখেছি। যদি দাঁতের গঠনের ৭৫%-এর বেশি নষ্ট হয়ে যায়, তবে ভাঙা দাঁতের ওপর ক্রাউন (ক্যাপ) বসানোর পরামর্শ দেওয়া হয় না। অন্যথায়, দাঁতে পোস্ট এবং কোর বসানোর একটি সম্ভাবনা থাকে। দাঁতের অবস্থার ওপর ভিত্তি করে আপনার ডেন্টিস্টকে সেই সিদ্ধান্ত নিতে হবে। এছাড়া, আমি ভাঙা দাঁতটিকে ক্রাউন ছাড়া ফেলে রাখার পরামর্শ দেব না। আর ডেন্টাল ইমপ্ল্যান্ট এবং ব্রিজের মধ্যে, আমি ডেন্টাল ইমপ্ল্যান্টের পরামর্শ দেব, যদি হাড়ের অবস্থা ভালো থাকে, কারণ এতে পাশের দাঁতগুলো কাটার প্রয়োজন হয় না। আশা করি এই উত্তরটি আপনার উপকারে আসবে।"
30958,96578,"আমার ওপরের চোয়ালের একটি দাঁতে রুট ক্যানেল করা হয়েছিল। চিকিৎসার পর, রুট ক্যানেল করা দাঁতের মাড়ির সংলগ্ন গর্তগুলোর চারপাশে খাবার আটকে যাওয়ার সমস্যা হচ্ছিল।","নাসেনিয়া ডক ব্যবহার করার জন্য ধন্যবাদ। আপনার প্রশ্নটি পড়েছি। আপনার সামনে যে চিকিৎসার বিকল্পগুলো রাখা হয়েছে, তার ভিত্তিতে দাঁতটিকে বর্তমান অবস্থায় ফেলে রাখা বুদ্ধিমানের কাজ হবে না। এটিকে পুনর্গঠন করা প্রয়োজন। আমার কাছে যদি একই অবস্থার কোনো রোগী আসতেন, তবে আমি সেই নির্দিষ্ট দাঁতের ক্যাপটি পুনরায় প্রতিস্থাপনের পরামর্শ দিতাম, যদি দাঁতের পর্যাপ্ত সুস্থ অংশ অবশিষ্ট থাকত। যদি দাঁতের খুব সামান্য অংশ অবশিষ্ট থাকে, তবে ইমপ্ল্যান্ট করা একটি বিকল্প হতে পারে, যদি ইমপ্ল্যান্ট বসানোর সমস্ত শর্ত পূরণ হয়। ইমপ্ল্যান্ট বসানো পার্শ্ববর্তী ভালো দাঁতগুলোকে প্রভাবিত করবে না। আপনার ডেন্টিস্টের মাধ্যমে এটি মূল্যায়ন করিয়ে চিকিৎসা শুরু করুন। আশা করি এটি আপনার কাজে আসবে। ধন্যবাদ ও শুভেচ্ছা।"
5141,90164,আমার বীর্য বিশ্লেষণে দেখা গেছে,"হেলো, নাসেনিয়া ডকে আপনাকে স্বাগতম। আমি আপনার প্রশ্নটি দেখেছি। আপনার সিমেন অ্যানালাইসিসে কাউন্ট স্বাভাবিক এবং লিকুইফ্যাকশন টাইম ৬০-এর নিচে! কিন্তু সঠিক সময়টি কত? স্বাভাবিক লিকুইফ্যাকশন টাইম হলো ২০-৩০ মিনিট, এর বেশি হওয়া অস্বাভাবিক। ৫-৬টি পুস সেল সংক্রমণের ইঙ্গিত দেয়। মটিলিটি স্বাভাবিকের কাছাকাছি। মরফোলজি স্বাভাবিকের চেয়ে কম। এটি অন্তত ৭০% হওয়া উচিত। আমি আপনাকে ১০ দিনের জন্য ফ্লুরোকুইনোলন গ্রুপের অ্যান্টিবায়োটিক সেবনের পরামর্শ দেব এবং একজন ইউরোলজিস্টের সাথে পরামর্শ করে ১০ দিন পর পুনরায় পরীক্ষা করার পরামর্শ দিচ্ছি। আশা করি আপনার প্রশ্নের উত্তর দিতে পেরেছি। আপনাকে আরও সাহায্য করতে পারলে খুশি হব। ভালো থাকবেন।"
104780,55504,আমার বীর্য বিশ্লেষণে দেখা গেছে,"হেলো, আমার মনে হয় আপনার শুক্রাণুর সংখ্যা কিছুটা কম। এর কাট-অফ হলো প্রতি মিলিলিটারে ১৫ মিলিয়ন। তাই, আপনি স্বাভাবিকভাবে গর্ভধারণের চেষ্টা করতে পারেন। আপনার শুক্রাণুর গতি স্বাভাবিক। ৩ মাস অ্যান্টিঅক্সিডেন্ট এবং ভিটামিন সাপ্লিমেন্ট গ্রহণ করুন। ৩ থেকে ৫ দিন শারীরিক মিলন থেকে বিরত থাকার পর এক মাস পরে পুনরায় সিমেন অ্যানালাইসিস করান। স্ত্রীর পিরিয়ড শেষ হওয়ার পর প্রতি ২ থেকে ৩ দিন অন্তর শারীরিক সম্পর্ক বজায় রাখুন। এটি গর্ভধারণের সম্ভাবনা বাড়াবে। আপনি ৩ থেকে ৬টি সাইকেল পর্যন্ত চেষ্টা করতে পারেন। যদি এতে কাজ না হয়, তবে আপনি আইইউআই (IUI)-এর কথা ভাবতে পারেন। এ বিষয়ে আপনার ডাক্তারের সাথে কথা বলুন। আশা করি এটি সাহায্য করবে।"
57825,55265,"আমার বুকে হালকা ব্যথা হচ্ছে। আমি যখন হাত প্রসারিত করি বা নিচু হই, তখন আমার ডান বুকের উপরের অংশে ব্যথা করে। এটি একটি নির্দিষ্ট স্থানে ব্যথা করে। গত ১ বা ২ মাস ধরে এই ব্যথা আসা-যাওয়ার মধ্যে ছিল। কিন্তু গত ৩ বা ৪ দিন ধরে এটি বেড়েছে। আমার এখন কী করা উচিত?","নাসেনিয়া ডকে আপনার প্রশ্নের জন্য ধন্যবাদ। আমি আপনার উদ্বেগ বুঝতে পারছি। যেহেতু নড়াচড়া করলে আপনার ব্যথা বেড়ে যায়, তাই এটি মাস্কুলোস্কেলিটাল বা পেশি ও হাড়ের ব্যথার হওয়ার সম্ভাবনাই বেশি। মাস্কুলোস্কেলিটাল ব্যথার উপশমের জন্য নিচের পদক্ষেপগুলো অনুসরণ করুন:\n\n১. যে নড়াচড়ায় ব্যথা হয় তা এড়িয়ে চলুন। বুকের হঠাৎ কোনো ঝাঁকুনিপূর্ণ নড়াচড়া এড়িয়ে চলুন।\n২. বুকের আক্রান্ত স্থানে গরম পানির সেঁক দিন।\n৩. নাসেনিয়া ডকের পরামর্শ অনুযায়ী ব্যথানাশক এবং মাসল রিলাক্স্যান্ট ওষুধ সেবন করুন।\n৪. ভারী ওজন তোলা এবং কঠোর ব্যায়াম এড়িয়ে চলুন।\n\nচিন্তা করবেন না, এই নিয়মগুলো মেনে চললে ১ সপ্তাহের মধ্যে আপনি সুস্থ হয়ে উঠবেন। আশা করি আমি আপনার প্রশ্নের সমাধান দিতে পেরেছি। আপনাকে আরও সাহায্য করতে পারলে আমি খুশি হব। আপনার সুস্বাস্থ্য কামনা করি। ধন্যবাদ।"
19317,12919,"আমার বুকে হালকা ব্যথা হচ্ছে। আমি যখন হাত প্রসারিত করি বা নিচু হই, তখন আমার ডান বুকের উপরের অংশে ব্যথা করে। এটি একটি নির্দিষ্ট স্থানে ব্যথা করে। গত ১ বা ২ মাস ধরে এই ব্যথা আসা-যাওয়ার মধ্যে ছিল। কিন্তু গত ৩ বা ৪ দিন ধরে এটি বেড়েছে। আমার এখন কী করা উচিত?","নাসেনিয়া ডকে আপনার প্রশ্নের জন্য ধন্যবাদ। আমি আপনার উদ্বেগ বুঝতে পারছি। আপনার ইতিহাস এবং বর্ণনা অনুযায়ী, মাস্কুলোস্কেলিটাল ব্যথার সম্ভাবনা বেশি, কারণ আপনার ব্যথা হাত প্রসারিত করা এবং নড়াচড়ার (বাঁকানো) সাথে সম্পর্কিত। তাই মাস্কুলোস্কেলিটাল ব্যথার লক্ষণ থেকে উপশমের জন্য এই পদক্ষেপগুলো অনুসরণ করুন। ১. ভারী ওজন তোলা এবং কঠোর ব্যায়াম এড়িয়ে চলুন। ২. ব্যথা সৃষ্টি করে এমন নড়াচড়া এড়িয়ে চলুন। ৩. বুকের হঠাৎ ঝাঁকুনিপূর্ণ নড়াচড়া এড়িয়ে চলুন। ৪. বুকের আক্রান্ত স্থানে গরম পানির সেঁক দিন। ৫. নাসেনিয়া ডকের পরামর্শ অনুযায়ী ব্যথানাশক এবং মাসল রিলাক্স্যান্ট ওষুধ সেবন করুন। চিন্তা করবেন না, এই সবকিছুর মাধ্যমে আপনি সুস্থ হয়ে উঠবেন। আশা করি আমি আপনার প্রশ্নের সমাধান করতে পেরেছি। আপনাকে আরও সাহায্য করতে পারলে আমি খুশি হব। আপনার সুস্বাস্থ্য কামনা করি। ধন্যবাদ।"
100717,20688,"আমার বয়স ৪৮ বছর। পেশা শিক্ষকতা, হৃদস্পন্দন অনিয়মিত, রক্তচাপ স্বাভাবিক নয়, সর্বশেষ রক্তচাপের পরিমাপ","হেলো, আপনার অনুসন্ধানের জন্য ধন্যবাদ। আপনার অনুসন্ধান এবং রিপোর্টের ভিত্তিতে আমার মতামত নিচে দেওয়া হলো:\n\n১. অনিয়ন্ত্রিত রক্তচাপের কারণে রক্তচাপ ওঠানামা করে। উচ্চ রক্তচাপ নিয়ন্ত্রণে ওষুধের পাশাপাশি নিয়মিত ব্যায়াম, পুষ্টিকর খাবার, চর্বিযুক্ত খাবার কম খাওয়া, রক্তের কোলেস্টেরল স্বাভাবিক মাত্রায় রাখা, দুশ্চিন্তামুক্ত জীবনযাপন এবং জীবনযাত্রায় পরিবর্তন আনা প্রয়োজন।\n\n২. ওষুধ সেবন করা সত্ত্বেও আপনার রক্তচাপ কিছুটা বেশি, তাই শরীরে লিপিডের মাত্রা জানা জরুরি। একটি লিপিড প্রোফাইল পরীক্ষা করান এবং ফলাফলের ওপর ভিত্তি করে ব্যবস্থা নিন।\n\n৩. পুনরায় রক্তে শর্করার মাত্রা পরীক্ষা করুন এবং ডায়াবেটিসের ওষুধের বিষয়ে আপনার পরামর্শকারী চিকিৎসকের সাথে আলোচনা করুন।\n\n৪. নিয়মিত ওষুধ সেবন করুন, কারণ অনিয়ন্ত্রিত উচ্চ রক্তচাপ এবং ডায়াবেটিস সময়ের সাথে সাথে শরীরের বিভিন্ন অঙ্গের ক্ষতি করতে পারে।\n\nআশা করি এটি আপনাকে সাহায্য করবে। আপনার সুস্বাস্থ্য কামনা করি।\n\nশুভেচ্ছান্তে।"
78385,98739,"আমার বয়স ৪৮ বছর। পেশা শিক্ষকতা, হৃদস্পন্দন অনিয়মিত, রক্তচাপ স্বাভাবিক নয়, সর্বশেষ রক্তচাপের পরিমাপ","হেলো, অনিয়মিত হৃদস্পন্দনের বিষয়টি বিবেচনা করে, কার্ডিয়াক অ্যারিথমিয়ার ধরন নির্ণয়ের জন্য কিছু পরীক্ষা করা প্রয়োজন। এই বিষয়ে, আমি এই পরীক্ষাগুলো করার পরামর্শ দিচ্ছি।"
84561,34418,আমি একটি সিমেন অ্যানালাইসিস করিয়েছিলাম এবং এর ফলাফল এটি।,"হেলো, আপনার অনুসন্ধানের জন্য ধন্যবাদ। আমি আপনার অনুসন্ধানটি পড়েছি এবং আপনার উদ্বেগগুলো বুঝতে পেরেছি। আপনার রিপোর্টটি সম্পূর্ণ স্বাভাবিক। আপনার প্রজনন ক্ষমতা নিয়ে কোনো সন্দেহ নেই। আমি নিশ্চিত যে বর্তমান বীর্য বিশ্লেষণের রিপোর্ট অনুযায়ী আপনি সন্তান ধারণে সক্ষম হবেন। প্রজনন ক্ষমতার জন্য আপনার কোনো চিকিৎসার প্রয়োজন নেই। আপনি যদি দ্রুত সন্তান নিতে চান, তবে জিইউআই (GUI)-এর মতো সহায়ক প্রজনন প্রযুক্তির সাহায্য নিতে পারেন। আমার বিশ্বাস, উপরের নির্দেশাবলী অনুসরণ করলে এবং ৩ মাস পর পুনরায় পরীক্ষা করালে আপনার শুক্রাণুর গতিশীলতা বৃদ্ধি পাবে। আপনার জন্য শুভকামনা রইল। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি। আপনার পরবর্তী যেকোনো প্রশ্নের জন্য আমি উপলব্ধ থাকব। চ্যাট ডাক্তার।"
20191,77361,আমি একটি সিমেন অ্যানালাইসিস করিয়েছিলাম এবং এর ফলাফল এটি।,"হেলো, নাসেনিয়া ডকে আপনাকে স্বাগতম। এই রিপোর্টে শুক্রাণুর গতিশীলতা (motility) ছাড়া বাকি সব প্যারামিটার স্বাভাবিক। শুক্রাণুর গতিশীলতা ৫০% হওয়া উচিত, যার মধ্যে ২৫% দ্রুত প্রগতিশীল হওয়া প্রয়োজন। এছাড়া, প্রচুর পরিমাণে এবিসি (ABCs) রয়েছে যা সংক্রমণের ইঙ্গিত দেয়। একজন ইউরোলজিস্টের সাথে পরামর্শ করুন। সংক্রমণ দূর করার জন্য তিনি আপনাকে অ্যান্টিবায়োটিক কোর্সের পরামর্শ দিতে পারেন। অ্যান্টিঅক্সিডেন্ট উপকারী হবে। সংক্রমণ সেরে গেলে শুক্রাণুর গতিশীলতাও উন্নত হবে। আরএস (ROS) টেস্ট করিয়ে নিলে ভালো হয়। নিজের যত্ন নেবেন।"
68726,7246,আমি গত ৩ মাস ধরে পেটে ব্যথায় ভুগছি।,"হেলো এবং নাসেনিয়া ডকে আপনাকে স্বাগতম। পেটের যেকোনো অঙ্গের বৃদ্ধি, প্রদাহ বা অন্য কোনো রোগের কারণে পেটে ব্যথা হতে পারে। পেটের অঙ্গগুলোর অবস্থা দেখার জন্য পেটের আল্ট্রাসাউন্ড করা প্রয়োজন। আল্ট্রাসাউন্ডের ফলাফলের ওপর ভিত্তি করে পরবর্তী পরীক্ষা-নিরীক্ষার সিদ্ধান্ত নেওয়া হবে। ক্লিনিক্যাল মূল্যায়ন এবং প্রয়োজনীয় পরীক্ষার জন্য একজন সার্জনের পরামর্শ নিন। ধন্যবাদ এবং ভালো থাকবেন, নাসেনিয়া ডক।"
61175,46703,আমি গত ৩ মাস ধরে পেটে ব্যথায় ভুগছি।,হেলো। আপনার অনুসন্ধানের জন্য ধন্যবাদ। ৩ মাস ধরে পেটে ব্যথা থাকার সবচেয়ে সম্ভাব্য কারণগুলো হলো
50838,95662,উপসর্গ,"হেলো। আপনার অনুসন্ধানের জন্য এবং বিস্তারিত ইতিহাস জানানোর জন্য ধন্যবাদ। আপনার উপসর্গ এবং চিকিৎসার বিস্তারিত ইতিহাস আমি নোট করেছি। এটি ভালো যে আপনাকে আইবিএস-সি (IBS-C) এর চিকিৎসা পদ্ধতিতে রাখা হয়েছে, তবে বিষয়টি নিশ্চিত হওয়া প্রয়োজন। একই ধরনের ইতিহাস থাকা সকল রোগীদের ক্ষেত্রে আমি নিম্নলিখিত পরামর্শগুলো দিয়ে থাকি।"
103497,30717,উপসর্গ,"হেলো! আমি আপনার প্রশ্নটি মনোযোগ সহকারে পড়েছি এবং এটি ব্যাখ্যা করতে চাই যে আপনার লক্ষণগুলো সম্ভবত কোনো দীর্ঘস্থায়ী সংক্রমণ বা প্রদাহজনিত সমস্যার সাথে সম্পর্কিত। এই কারণে, আমি আপনাকে একজন সংক্রামক রোগ বিশেষজ্ঞের সাথে পরামর্শ করার এবং কিছু পরীক্ষা করার পরামর্শ দিচ্ছি।"
49147,24813,থেকে,"হেলো প্রিয়, আপনি ঠিকই বলেছেন; আপনার যৌন মিলনের দিনটি ডিম্বস্ফোটনের দিনের খুব কাছাকাছি ছিল; তাই আপনি উর্বর সময়েই মিলন করেছেন। প্রকৃতপক্ষে, এই অনিরাপদ মিলনকে কভার করার জন্য, মিলনের ৭২ ঘণ্টার মধ্যে আপনার জরুরি গর্ভনিরোধক পিল গ্রহণ করা উচিত ছিল। যাই হোক, আপনি করভেট-এর ৪টি পিল খেয়েছেন, যা জরুরি গর্ভনিরোধক পিলের মাত্রার খুব কাছাকাছি। পরবর্তীতে দুইবার পিলগুলো পুনরায় খাওয়ার কোনো প্রয়োজন ছিল না। এই নির্দিষ্ট মিলনের কারণে আপনি গর্ভধারণ থেকে সুরক্ষিত আছেন। তবে, এত বেশি পিল খাওয়ার কারণে আপনার পরবর্তী মাসিক এক সপ্তাহ বা তার বেশি বিলম্বিত হতে পারে। এ নিয়ে চিন্তিত হওয়ার প্রয়োজন নেই। তবুও যদি আপনি গর্ভধারণের সম্ভাবনা নিয়ে উদ্বিগ্ন থাকেন, তবে মাসিক মিস হওয়ার এক সপ্তাহ পর আপনার সকালের প্রথম প্রস্রাবের নমুনা দিয়ে প্রেগন্যান্সি টেস্ট করতে পারেন; এর আগে পরীক্ষা করলে ভুল নেগেটিভ ফলাফল আসতে পারে। এছাড়া, এত বেশি পিল খাওয়ার কারণে আপনার পেটে অতিরিক্ত অ্যাসিডিটি, বমি বমি ভাব এবং বমি হতে পারে। প্যান্টোপ্রাজলের মতো কোনো প্রোটন পাম্প ইনহিবিটর অ্যান্টাসিড এই লক্ষণগুলো থেকে আপনাকে মুক্তি দেবে। ভবিষ্যতে, অনুগ্রহ করে এমন পরিস্থিতির জন্য কিছু জরুরি গর্ভনিরোধক পিল হাতের কাছে রাখার বিষয়টি নিশ্চিত করবেন। আশা করি এই পরামর্শে আপনি এখন সন্তুষ্ট।"
89585,92398,থেকে,"হেলো। পুঁজটি এএফবি কালচার এবং সেনসিটিভিটির জন্য পাঠানো উচিত। এটি লিম্ফ নোডের যক্ষ্মা সংক্রমণ, তাই রোগীর অন্তত ৬-৯ মাস নিবিড় এবং বিশেষ চিকিৎসার প্রয়োজন। যদি ফোলা স্থান থেকে পুঁজ পড়া শুরু হয়, তবে রোগীর সম্পূর্ণ চিকিৎসা না হওয়া পর্যন্ত তা সারিয়ে তোলা খুব কঠিন হবে। এএফবি কালচার এবং সেনসিটিভিটি রিপোর্ট থেকে জানা যাবে যে প্রথম সারির ওষুধ কাজ করবে কি না।"
29662,98604,"বীর্য পরীক্ষা সম্পন্ন করেছি। সন্তান নেওয়ার চেষ্টা করছি। সাহায্য করুন। হেলো ডাক্তার, আমার বয়স ৩০ বছর, ২০১২ সালের এপ্রিলে বিয়ে করেছি এবং ৬ মাস ধরে স্ত্রীকে গর্ভবতী করার চেষ্টা করছি। আমি জানি তার ডিম্বস্ফোটনের সময় মাসিক চক্রের ১২তম থেকে ১৮তম দিন। আমার ১০ বছর ধরে আর্থ্রাইটিস আছে এবং আমি ২৫ মিগ্রা ডাইক্লোফেনাক সোডিয়াম দিনে তিনবার সেবন করছি। এমনকি যৌন মিলনের সময় নিতম্বের নিচে বালিশ রাখি এবং ডিম্বস্ফোটনের সঠিক সময়ে মিলন করি। আমার বীর্য পরীক্ষার রিপোর্টে ভলিউম","হেলো, নাসেনিয়া ডকে আপনাকে স্বাগতম। আমি নাসেনিয়া ডক। আপনার সিমেন অ্যানালাইসিস রিপোর্ট অনুযায়ী আপনার স্পার্ম কাউন্ট কম (ডব্লিউএইচও ২০১০ অনুযায়ী স্বাভাবিক মাত্রা হলো > ১৫ মিলিয়ন/মিলি অথবা মোট ৩৯ মিলিয়ন)। আপনার স্পার্মের গতিশীলতা স্বাভাবিক সীমার মধ্যে আছে (ডব্লিউএইচও ২০১০ অনুযায়ী স্বাভাবিক গতিশীলতা > ৫০%)। মরফোলজি বা গঠনও স্বাভাবিক সীমার মধ্যে আছে (ডব্লিউএইচও ২০১০ অনুযায়ী স্বাভাবিক মরফোলজি > ০৪%)। সুতরাং, আপনার শুধুমাত্র স্পার্ম কাউন্ট কম। ডাইক্লোফেনাক সেবনের কারণে এটি হয়নি। আপনার নাসেনিয়া ডকের পরামর্শ অনুযায়ী কোএনজাইম কিউ এবং ভিটামিন ই গ্রুপের ওষুধ সেবন করা উচিত। এছাড়া অন্য কিছুর প্রয়োজন নেই। ধন্যবাদ।"
5831,6563,"বীর্য পরীক্ষা সম্পন্ন করেছি। সন্তান নেওয়ার চেষ্টা করছি। সাহায্য করুন। হেলো ডাক্তার, আমার বয়স ৩০ বছর, ২০১২ সালের এপ্রিলে বিয়ে করেছি এবং ৬ মাস ধরে স্ত্রীকে গর্ভবতী করার চেষ্টা করছি। আমি জানি তার ডিম্বস্ফোটনের সময় মাসিক চক্রের ১২তম থেকে ১৮তম দিন। আমার ১০ বছর ধরে আর্থ্রাইটিস আছে এবং আমি ২৫ মিগ্রা ডাইক্লোফেনাক সোডিয়াম দিনে তিনবার সেবন করছি। এমনকি যৌন মিলনের সময় নিতম্বের নিচে বালিশ রাখি এবং ডিম্বস্ফোটনের সঠিক সময়ে মিলন করি। আমার বীর্য পরীক্ষার রিপোর্টে ভলিউম","হেলো, বিশ্ব স্বাস্থ্য সংস্থার (WHO) সর্বশেষ মানদণ্ড অনুযায়ী, আপনার সিমেন অ্যানালাইসিস স্বাভাবিক। (WHO ২০১০)। গর্ভধারণের জন্য আপনার শুক্রাণু ও তার ডিম্বাণু (ওভুলেশন) ছাড়াও স্বাভাবিক খোলা ফ্যালোপিয়ান টিউব থাকা প্রয়োজন। এছাড়া, ৬ মাস চেষ্টার পর গর্ভধারণের সম্ভাবনা প্রায় ৭০% (১২ মাস পর ৮৫-৯০%)। তাই আপনারা যথেষ্ট চেষ্টা করেননি এবং টিউবগুলোও এখনো পরীক্ষা করা হয়নি। যদি আপনারা গর্ভধারণের জন্য খুব উদ্বিগ্ন হন, তবে একজন ইনফার্টিলিটি বিশেষজ্ঞের পরামর্শ নিতে পারেন, যিনি আপনাদের পরীক্ষা-নিরীক্ষা করে নির্দেশনা দেবেন; অন্যথায় আপনারা আরও ৬ মাস অপেক্ষা করতে পারেন। আপনার সুস্বাস্থ্য কামনা করি।"
82993,66806,"স্যার, আমার দাঁত হলুদ হয়ে গেছে যার কারণে আমি অনেক সমস্যার সম্মুখীন হচ্ছি। এটি দূর করার জন্য আপনি কি কোনো পরামর্শ দিতে পারেন?","হেলো, আপনার প্রশ্নটি পোস্ট করার জন্য ধন্যবাদ। আমাদের দাঁত হলুদ হয়ে যাওয়ার পেছনে বেশ কিছু কারণ রয়েছে। কিছু মানুষের দাঁত প্রাকৃতিকভাবেই কিছুটা হলুদ হয় এবং শুধুমাত্র ভিনিয়ার্সের মতো কৃত্রিম দন্তচিকিৎসার মাধ্যমেই তা ঠিক করা সম্ভব। মানুষের দাঁত কিছুটা হলদেটে হওয়া সম্পূর্ণ স্বাভাবিক। সমস্যা হলো সময়ের সাথে সাথে দাঁত আরও বেশি হলুদ হয়ে যায়। দাঁত হলুদ হওয়ার প্রধান কারণ হলো খাবার থেকে হওয়া দাগ, নাসেনিয়া ডক। দাঁত চারটি স্তরের টিস্যু দিয়ে গঠিত। সবচেয়ে ভেতরের স্তরটি হলো সিমেন্টাম। এটি দাঁতের মূলকে চোয়ালের হাড়ের সাথে সংযুক্ত করে। এর পরের স্তরটি হলো পাল্প। পাল্পে দাঁতের রক্তনালী এবং স্নায়ুর প্রান্ত থাকে। আমি আপনাকে আপনার ডেন্টিস্টের কাছে যাওয়ার পরামর্শ দিচ্ছি যাতে তিনি পরীক্ষা করে নির্ধারণ করতে পারেন এবং দাঁত সাদা করার জন্য কোন পণ্যটি সবচেয়ে ভালো তা সুপারিশ করতে পারেন। আশা করি এই তথ্যটি তথ্যবহুল এবং সহায়ক হয়েছে। শুভেচ্ছা।"
23448,90575,"স্যার, আমার দাঁত হলুদ হয়ে গেছে যার কারণে আমি অনেক সমস্যার সম্মুখীন হচ্ছি। এটি দূর করার জন্য আপনি কি কোনো পরামর্শ দিতে পারেন?","হেলো, নাসেনিয়া ডক ফোরামে আপনাকে স্বাগতম। স্কেলিং এবং পলিশিং দাঁতের বাইরের হলুদ দাগ দূর করবে। দাঁত ব্রাশ করা দাঁতের ভেতরের দাগ দূর করতে সাহায্য করবে না, তাই আপনি ব্লিচিং করাতে পারেন। বর্তমানে, সঠিক রোগী নির্বাচনের মাধ্যমে ব্লিচিং একটি নিরাপদ, সহজ এবং সাশ্রয়ী পদ্ধতি, যা দাঁতের অনেক ধরণের বিবর্ণতা দূর করতে ব্যবহৃত হয়। অথবা আপনি পার্শিয়াল (যেমন, ল্যামিনেট ভিনিয়ার্স) টুথ কভারেজ রেস্টোরেশন করাতে পারেন, যা দাঁতের ভেতরের সাধারণ বিবর্ণতা দূর করতে ব্যবহৃত হয়, যেখানে ব্লিচিং কার্যকর নয় বা ব্লিচিংয়ের নান্দনিক ফলাফল রোগীর প্রত্যাশা পূরণ করতে ব্যর্থ হয়। দিনে দুবার ব্রাশ করুন। ভালো থাকবেন।"
87137,3081,স্যার; আমার মৌলিক বিশ্লেষণ নিম্নরূপ,"হেলো, চ্যাটডক্টরকে বিশ্বাস করার জন্য আপনাকে ধন্যবাদ। প্রিয়, চিন্তার কিছু নেই, আপনার সিমেন অ্যানালাইসিস বা বীর্য পরীক্ষা স্বাভাবিক। নিচে সিমেন অ্যানালাইসিসের কিছু মান দেওয়া হলো: ভলিউম"
13880,93404,স্যার; আমার মৌলিক বিশ্লেষণ নিম্নরূপ,"হেলো, নাসেনিয়া ডকে আপনাকে স্বাগতম। শুক্রাণুর সচলতার হার কম, স্বাভাবিক হার ৬৫%-এর বেশি হওয়া উচিত। পিএইচ (PH) ক্ষারীয় হওয়া প্রয়োজন, কিন্তু আপনার ক্ষেত্রে এটি অম্লীয়। সাধারণত শুক্রাণুর প্যাথলজিক্যাল হার ৫%-এর কম থাকে, কিন্তু আপনার ক্ষেত্রে এটি ৩৫%, যা অনেক বেশি। আপনি গিফট (GIFT - গ্যামেট ইন্ট্রাফ্যালোপিয়ান ট্রান্সফার) বা জাইগোট ইন ভিট্রো ফার্টিলাইজেশন পদ্ধতির চেষ্টা করতে পারেন। এই পদ্ধতিগুলোর মাধ্যমে আপনার নিজের শুক্রাণু ব্যবহার করে আপনার স্ত্রীর ডিম্বাণু নিষিক্ত করা হবে এবং জাইগোট তৈরি হওয়ার পর তা আপনার স্ত্রীর জরায়ুতে স্থানান্তর করা হবে।"
73467,13372,হেলো,"হেলো, নাসেনিয়া ডক ব্যবহার করার জন্য ধন্যবাদ। সাইনাস এবং নাক বন্ধ হয়ে যাওয়ার বিভিন্ন কারণ থাকতে পারে, তবে সবচেয়ে সাধারণ কারণ হলো সংক্রমণ (সাধারণত ভাইরাল বা ব্যাকটেরিয়াল) অথবা অ্যালার্জি। যদি আপনার অ্যালার্জির কোনো ইতিহাস না থাকে, তবে আপনার উপসর্গগুলো সম্ভবত কোনো ভাইরাল সংক্রমণের কারণে হচ্ছে। এমন কিছু ওষুধ আছে যা আপনাকে সাহায্য করতে পারে, যেমন ওরাল বা টপিক্যাল ডিকনজেস্ট্যান্ট। টপিক্যাল ডিকনজেস্ট্যান্টের উদাহরণ হলো স্ট্রাইভিং এবং নরমাল স্যালাইন। ওরাল ডিকনজেস্ট্যান্টগুলো সাধারণত অ্যান্টিহিস্টামিনের সাথে মিশ্রিত অবস্থায় বিক্রি হয়, যা বেশ কার্যকর। আশা করি এটি আপনাকে সাহায্য করবে।"
73902,54576,হেলো,"হেলো, আমি আপনার প্রশ্নটি দেখেছি। আমি আপনার উদ্বেগ বুঝতে পারছি। তার লিভার বা গ্যাস্ট্রিকের কোনো সমস্যা থাকতে পারে। তার বয়সে পিত্তথলির রোগের সম্ভাবনা কম। কারণটি খুঁজে বের করার জন্য তার পেটের আল্ট্রাসাউন্ড করা উচিত। এরপর সেই অনুযায়ী তার চিকিৎসা নেওয়া প্রয়োজন। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি, যদি আপনার কোনো সন্দেহ থাকে তবে আমি উত্তর দিতে পেরে খুশি হব। নাসেনিয়া ডক ব্যবহার করার জন্য ধন্যবাদ। আপনার সুস্বাস্থ্য কামনা করি।"
97602,2812,হেলো,"হেলো, আপনার ব্যথার কথা শুনে খুব খারাপ লাগছে। অস্টিওআর্থ্রাইটিস এমন একটি রোগ যা বয়সের সাথে সাথে বাড়তে থাকে, তাই ব্যথা এবং আড়ষ্টতা সময়ের সাথে সাথে আরও খারাপ হওয়ার সম্ভাবনা থাকে। তবে, আপনি যদি মনে করেন যে ব্যথা নিয়ন্ত্রণ এবং ফিজিওথেরাপি সঠিক পথ, তবে তা চালিয়ে যেতে পারেন। কোনো এক পর্যায়ে, আমি আপনাকে একজন অর্থোপেডিক সার্জনের সাথে দেখা করার পরামর্শ দেব, যাতে সম্ভাব্য অস্ত্রোপচারের বিকল্পগুলো, বিশেষ করে হিপ রিপ্লেসমেন্ট নিয়ে আলোচনা করা যায়। আরেকটি বিকল্প হলো হিপে ইনজেকশন দেওয়া - এটি একটি বিশেষ পদ্ধতি যা সাধারণত অর্থোপেডিক সার্জন বা বিশেষ রেডিওলজিস্টরা করে থাকেন এবং এটি সাময়িক ব্যথা থেকে মুক্তি দেয়।"
75403,15285,হেলো,"হেলো, আমি আপনার দেওয়া বিবরণটি পড়েছি এবং আপনাকে সাহায্য করতে পারি। যদি এর আকার ছোট হয়ে আসে, তবে এটি গরম খাবারের কারণে হওয়া ফোসকা হতে পারে। এটি কি রক্তপাত করছে বা ব্যথা হচ্ছে? যদি এর সাথে রক্তপাত হয়, তবে এটি মাড়ি বা দাঁতের চারপাশের টিস্যু সংক্রান্ত সমস্যা (gingival or periodontal problem) হতে পারে। যদি ব্যথার সাথে রক্তপাত বা পুঁজ থাকে, তবে এটি মাড়ির ফোড়া (gum abscess) হতে পারে এবং যদি দাঁত নড়বড়ে মনে হয়, তবে এটি পেরিওডন্টাল ফোড়া (periodontal abscess) হতে পারে। যদি ওই অঞ্চলে দাঁতে গর্ত থাকে, তবে চ্যাট ডাক্তারের সাথে কথা বলতে পারেন। তাই ওই জায়গাটি পরীক্ষা করলেই নিশ্চিত হওয়া যাবে। সবচেয়ে ভালো পরামর্শ হলো একজন ডেন্টিস্টের সাথে পরামর্শ করা। ততক্ষণ পর্যন্ত, আপনি নিচের কাজগুলো করতে পারেন।"

DUPLICATE INPUT + OUTPUT PAIRS
--------------------------------
Rows involved: 0

LENGTH SUMMARY
----------------

           input_len     output_len
count  108391.000000  108391.000000
mean      441.246985     634.143684
std       246.402508     244.976155
min         4.000000       4.000000
25%       302.000000     492.000000
50%       373.000000     594.000000
75%       504.000000     747.000000
max     10814.000000    3322.000000

LONGEST INPUTS
----------------

           id  input_len  \
66735   77438      10814
46294   90025       5742
48818   57639       5453
41769    5072       5235
66760    2459       5026
88678   29379       4687
31681  105898       4437
85061   54372       4287
17047  111831       4259
29429  105042       4197

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                input

LONGEST OUTPUTS
-----------------

,id,output_len,output
106569,68705,3322,"৩.০ মিই/লিটারের বেশি সিরাম পটাশিয়ামের মাত্রাকে বিপজ্জনক বা খুব উদ্বেগের বিষয় বলে মনে করা হয় না; এগুলি মুখ দিয়ে পটাশিয়াম গ্রহণের মাধ্যমে চিকিৎসা করা যেতে পারে। রোগীর শারীরিক অবস্থা, অন্যান্য চিকিৎসা সংক্রান্ত সমস্যা এবং রোগীর উপসর্গের উপর নির্ভর করে, ৩.০ মিই/লিটারের কম সিরাম মাত্রার জন্য শিরায় পটাশিয়াম প্রতিস্থাপনের প্রয়োজন হতে পারে। সিদ্ধান্তগুলি রোগী-নির্দিষ্ট এবং রোগ নির্ণয়, অসুস্থতার পরিস্থিতি এবং মুখ দিয়ে তরল ও ওষুধ গ্রহণ করার রোগীর ক্ষমতার উপর নির্ভর করে। স্বল্পমেয়াদে, গ্যাস্ট্রোএন্টেরাইটিস বা বমি ও ডায়রিয়ার মতো স্ব-সীমাবদ্ধ অসুস্থতার ক্ষেত্রে, শরীর নিজেই পটাশিয়ামের মাত্রা নিয়ন্ত্রণ ও পুনরুদ্ধার করতে সক্ষম। তবে, যদি হাইপোক্যালেমিয়া গুরুতর হয় বা পটাশিয়ামের ক্ষয় অব্যাহত থাকার সম্ভাবনা থাকে, তবে পটাশিয়াম প্রতিস্থাপন বা সাপ্লিমেন্টের প্রয়োজন হতে পারে। যারা মূত্রবর্ধক ওষুধ গ্রহণ করছেন, তাদের ক্ষেত্রে প্রায়শই অল্প পরিমাণে পটাশিয়াম মুখে খাওয়ার পরামর্শ দেওয়া হতে পারে, কারণ ওষুধ সেবন চলাকালীন পটাশিয়ামের ক্ষয় অব্যাহত থাকবে। ওরাল সাপ্লিমেন্টগুলি বড়ি বা তরল আকারে হতে পারে এবং ডোজগুলি মিই (মিলিইকুইভ্যালেন্ট) এককে পরিমাপ করা হয়। সাধারণ ডোজ হলো প্রতিদিন ১০-২০ মিই। বিকল্পভাবে, পটাশিয়াম সমৃদ্ধ খাবার গ্রহণ পটাশিয়াম প্রতিস্থাপনের প্রথম বিকল্প হতে পারে। কলা, এপ্রিকট, কমলা এবং টমেটোতে প্রচুর পরিমাণে পটাশিয়াম থাকে। যেহেতু পটাশিয়াম কিডনির মাধ্যমে নির্গত হয়, তাই পটাশিয়ামের মাত্রা খুব বেশি বেড়ে যাওয়া রোধ করতে এবং তা অনুমান করার জন্য কিডনির কার্যকারিতা পর্যবেক্ষণকারী রক্ত পরীক্ষার নির্দেশ দেওয়া হতে পারে। যখন শিরায় পটাশিয়াম দেওয়ার প্রয়োজন হয়, তখন তা অবশ্যই ধীরে ধীরে দিতে হবে। পটাশিয়াম শিরার জন্য বিরক্তিকর এবং সাধারণত প্রতি ঘন্টায় সর্বোচ্চ ১০ মিই হারে দেওয়া হয়। অধিকন্তু, খুব দ্রুত পটাশিয়াম ইনফিউশন হৃদপিণ্ডে অস্বস্তি সৃষ্টি করতে পারে এবং ভেন্ট্রিকুলার ট্যাকিকার্ডিয়ার মতো সম্ভাব্য বিপজ্জনক ছন্দ তৈরি করতে পারে। খাদ্যে পর্যাপ্ত পটাশিয়াম থাকলে শরীর সাধারণত পটাশিয়ামের মাত্রা স্বাভাবিক সীমার মধ্যে রাখতে সক্ষম। যখন শরীর স্বল্পমেয়াদী অসুস্থতার কারণে পটাশিয়াম হারায়, তখন শরীর সেই ক্ষতি পূরণ করতে পারে। যখন পটাশিয়ামের ক্ষয় অব্যাহত থাকে, তখন রোগী এবং স্বাস্থ্যসেবা পেশাজীবীর জন্য সেই ক্ষয় অনুমান করা এবং নিয়মিত পটাশিয়াম প্রতিস্থাপনের কথা বিবেচনা করা গুরুত্বপূর্ণ। সিওপিডি (COPD)-এর যেকোনো চিকিৎসা পরিকল্পনার সবচেয়ে অপরিহার্য পদক্ষেপ হলো ধূমপান পুরোপুরি বন্ধ করা। এটিই সিওপিডি-কে আরও খারাপ হওয়া থেকে আটকানোর একমাত্র উপায়, যা শেষ পর্যন্ত আপনার শ্বাস নেওয়ার ক্ষমতা হ্রাস করতে পারে। কিন্তু ধূমপান ত্যাগ করা সহজ নয়। এবং আপনি যদি ধূমপান ছাড়ার চেষ্টা করে ব্যর্থ হয়ে থাকেন, তবে এই কাজটি বিশেষ করে কঠিন মনে হতে পারে। নিকোটিন প্রতিস্থাপন পণ্য এবং ওষুধ যা সাহায্য করতে পারে, সেইসাথে কীভাবে পুনরায় ধূমপানে ফিরে আসা রোধ করা যায় সে সম্পর্কে আপনার ডাক্তারের সাথে কথা বলুন। আপনার ডাক্তার ধূমপান ত্যাগ করতে ইচ্ছুক ব্যক্তিদের জন্য একটি সাপোর্ট গ্রুপের সুপারিশও করতে পারেন। যথাসম্ভব পরোক্ষ ধূমপানের সংস্পর্শ এড়িয়ে চলাই ভালো। ওষুধ: ডাক্তাররা সিওপিডি-এর লক্ষণ এবং জটিলতার চিকিৎসার জন্য বিভিন্ন ধরণের ওষুধ ব্যবহার করেন। আপনি কিছু ওষুধ নিয়মিত এবং অন্যগুলো প্রয়োজন অনুযায়ী গ্রহণ করতে পারেন। ব্রঙ্কোডাইলেটর: এই ওষুধগুলি, যা সাধারণত ইনহেলার হিসেবে আসে, আপনার শ্বাসনালীর চারপাশের পেশীগুলোকে শিথিল করে। এটি কাশি এবং শ্বাসকষ্ট উপশম করতে এবং শ্বাস-প্রশ্বাস সহজ করতে সাহায্য করতে পারে। আপনার রোগের তীব্রতার উপর নির্ভর করে, আপনার কার্যকলাপের আগে একটি স্বল্প-মেয়াদী ব্রঙ্কোডাইলেটর, প্রতিদিন ব্যবহারের জন্য একটি দীর্ঘ-মেয়াদী ব্রঙ্কোডাইলেটর বা উভয়ই প্রয়োজন হতে পারে। শুভেচ্ছা, নাসেনিয়া ডক।"
101560,2843,3038,"হেলো, আপনার আঘাতের তালিকার কথা শুনে খুব খারাপ লাগছে। মূল কথায় আসি, আপনি উল্লেখ করেছেন যে এমআরআই-তে লাম্বার এবং সার্ভিকাল ডিস্ক ডিজেনারেটিভ পরিবর্তনের ইঙ্গিত পাওয়া গেছে। আসুন প্রথমে এটি নিয়ে আলোচনা করি এবং তারপর বাকিগুলো নিয়ে। ১২ বছর ধরে আপনার মতো আঘাতপ্রাপ্ত রোগীদের নিয়ে কাজ করার অভিজ্ঞতা থেকে আমি আমার পরামর্শ দিচ্ছি। সবার আগে, একটি সফট নেক কলার কিনুন এবং ব্যবহার শুরু করুন। এটি সার্ভিকাল অঞ্চলের হাড়কে স্থিতিশীল করবে এবং পেশী তন্ত্রকে সহায়তা করবে, যাতে স্নায়ুর ওপর চাপ কম পড়ে। ডিস্কের আঘাতগুলো বেশিরভাগ সময় নিজে থেকেই সেরে যায়, প্রদাহ কমে গেলে আপনার খুব একটা ব্যথা অনুভব হওয়ার কথা নয়। নেক কলার ব্যবহারের সময় আমি আপনাকে গরম পানির সেঁক দেওয়ার পরামর্শ দেব, যাতে যে পেশীগুলোতে খিঁচুনি হয়েছে তা শিথিল হয় এবং ব্যথা ধীরে ধীরে কমে আসে। এর পাশাপাশি, আপনার লাম্বার ডিস্ক ডিজেনারেটিভ পরিবর্তন রয়েছে, তাই প্রথমে লাম্বার অঞ্চলে গরম পানির সেঁক নিন যাতে ওই অঞ্চলের পেশীগুলো শিথিল হয় এবং আপনি অন্তত স্থিতিশীল বোধ করেন। এরপর ৩-৪টি বালিশ ব্যবহার করে প্যাসিভ উপায়ে ম্যাকেঞ্জি ম্যানুভার করার চেষ্টা করুন। ম্যাকেঞ্জি সম্পর্কে বিস্তারিত আপনি ইন্টারনেটে খুঁজে পাবেন। এটি ব্যথাকে কেন্দ্রীভূত করতে সাহায্য করবে এবং ব্যথা কেন্দ্রীভূত হয়ে গেলে আপনি আবার গরম পানির ব্যাগ ব্যবহার করে স্নায়ুর মূলগুলোকে শান্ত করতে পারেন। স্নায়ুর মূল শিথিল হয়ে গেলে এর পথে যে ব্যথা ছড়িয়ে পড়ে তা স্বয়ংক্রিয়ভাবে কমে যাবে। এটি ৫-৭ দিন করার পর আপনি ব্যায়ামের দিকে মনোযোগ দিতে পারেন, তবে উপরের পরামর্শগুলোও চালিয়ে যাবেন। ব্যায়ামের ক্ষেত্রে কোর স্ট্যাবিলিটি, নিম্ন অঙ্গের শক্তি বৃদ্ধি, ঊর্ধ্ব অঙ্গের শক্তি বৃদ্ধি এবং ঘাড়ের পেশীর শক্তি বৃদ্ধির ওপর জোর দেওয়া উচিত। ধীরে ধীরে আপনার শক্তি বাড়বে এবং স্নায়ুর মূলের প্রদাহ কমে আসবে, যার ফলে জীবনযাত্রার মান উন্নত হবে। যদি আপনার ব্যথার লক্ষণ খুব বেশি হয়, তবে নার্ভ ব্লকের মাধ্যমে কয়েক মাসের জন্য ব্যথার অনুভূতি বন্ধ করা যেতে পারে। কিন্তু পেশী দুর্বল থাকলে ব্যথা আবার ফিরে আসবে, তাই ব্যথার পুনরাবৃত্তি এড়াতে উল্লিখিত ব্যায়ামগুলো করা জরুরি। অস্ত্রোপচারের বিষয়ে বলতে গেলে, ক্ষতিগ্রস্ত ডিস্ক অপসারণ এবং মেরুদণ্ড ফিউজ করার সম্ভাবনা থাকে, তবে এটি দীর্ঘমেয়াদে আপনাকে পুরোপুরি ব্যথা থেকে মুক্তি নাও দিতে পারে। ব্যথা সারাজীবন থাকতে পারে এবং এর জন্য ব্যায়ামের প্রয়োজন হবে। যতক্ষণ না মোটর ফাংশন ক্ষতিগ্রস্ত হচ্ছে, ততক্ষণ আমি এই বিকল্পটি সুপারিশ করি না। এছাড়া, খাদ্যাভ্যাস খুবই গুরুত্বপূর্ণ, আপনি কী খাচ্ছেন সেদিকে নজর দিতে হবে। এমন খাবার খাওয়া উচিত যা দ্রুত হজম হয় এবং গ্যাস্ট্রাইটিস সৃষ্টি করে না। কারণ গ্যাস্ট্রাইটিসের কারণে দুটি লক্ষণ দেখা দিতে পারে, একটি হলো মেরুদণ্ডের নিচের অংশে স্নায়ুর ওপর চাপ এবং অন্যটি মাথাব্যথা। একটি ভালো ডায়েট প্ল্যান অনুসরণ করা ভালো। দয়া করে আপনার হিপ এবং হাঁটুর পেশীগুলোকে উপেক্ষা করবেন না, যেহেতু অতীতে আপনার রিপ্লেসমেন্ট হয়েছে এবং পেশীগুলো দুর্বল, তাই এটি মেরুদণ্ডের বক্রতাকে প্রভাবিত করে অন্যান্য উপসর্গের কারণ হতে পারে। আপনার গোড়ালির বিষয়ে আমি খুব বেশি কিছু বলতে পারছি না কারণ আপনার ইতিহাস খুব সংক্ষিপ্ত। এর জন্য আমি দুঃখিত। অনুগ্রহ করে স্থানীয় একজন ফিজিওথেরাপিস্টের সাথে যোগাযোগ করুন যিনি আপনাকে যথাযথভাবে সাহায্য করতে পারবেন। আমি আমার সাধ্যমতো সেরা চিকিৎসা পরিকল্পনাটি তুলে ধরার চেষ্টা করেছি যা আপনাকে সাহায্য করবে। আশা করি আমি আপনার প্রশ্নের উত্তর দিতে পেরেছি। আরও কোনো সাহায্যের প্রয়োজন হলে জানাবেন। জে ইন নাসেনিয়া ডক।"
12202,59679,3020,"হেলো প্রিয়। লাইম রোগ বগল এবং উরুতে বেদনাদায়ক র‍্যাশের সাথে সম্পর্কিত, তবে এটি মস্তিষ্কের ক্ষত বা দাগের সাথে সম্পর্কিত নাও হতে পারে। লাইম রোগ সাধারণত অ্যান্টিবায়োটিক দিয়ে নিরাময়যোগ্য। এটি এতটাই সত্য যে লাইম রোগের গবেষণার কিছু লেখক বলেছেন যে অ্যান্টিবায়োটিকের প্রতি লাইম রোগের সাড়া না পাওয়ার সবচেয়ে সাধারণ কারণ হলো শুরুতে লাইম রোগই ছিল না! অ্যান্টিবায়োটিকের ধরন রোগের পর্যায় (প্রাথমিক বা পরবর্তী) এবং শরীরের কোন অংশ আক্রান্ত তার ওপর নির্ভর করে। প্রাথমিক অসুস্থতা সাধারণত মুখে খাওয়ার ওষুধ দিয়ে কার্যকরভাবে চিকিৎসা করা হয়, উদাহরণস্বরূপ, ডক্সিসাইক্লিন (টোব্রামাইসিন), অ্যামোক্সিসিলিন (মোবিল), বা সেফুরোক্সিম অ্যাসিটিক (সারটেইন)। এগুলো সাধারণত লাইম রোগের দ্রুত নিরাময় ঘটায়। অতএব, যদি কোনো ব্যক্তি টিক কামড়ের জায়গায় একটি সাধারণ বুলস-আই ত্বকের র‍্যাশ (উপরে বর্ণিত) হতে দেখেন, তবে তাদের যত দ্রুত সম্ভব চিকিৎসকের পরামর্শ নেওয়া উচিত। সাধারণত, অ্যান্টিবায়োটিক চিকিৎসা এক বা দুই সপ্তাহের মধ্যে র‍্যাশ দূর করে এবং এর কোনো দীর্ঘমেয়াদী প্রভাব থাকে না। পরবর্তী অসুস্থতা যেমন স্নায়ুতন্ত্রের রোগের জন্য ইন্ট্রাভেনাস চ্যাট ডাক্তারের প্রয়োজন হতে পারে। লাইম রোগের চিকিৎসার জন্য কোনো ঘরোয়া প্রতিকার নেই। যেসব মানুষের মধ্যে এরিথেমা মাইগ্র্যান্ট র‍্যাশের দুই বা ততোধিক পর্ব দেখা যায়, এমনকি কয়েক বছরের ব্যবধানেও, মনে করা হয় যে এই পর্বগুলো মূল সংক্রমণের স্থায়িত্বের পরিবর্তে ভিন্ন সংক্রমণ বা পুনরায় সংক্রমণের প্রতিনিধিত্ব করে। লাইম রোগের উপসর্গের উপশমের জন্য ব্যথা উপশমকারী ওষুধ যোগ করা যেতে পারে। ফোলা জয়েন্টগুলো থেকে ডাক্তার তরল অপসারণ করে (আর্থ্রোসেন্টেসিস) ফোলা কমাতে পারেন। আর্থ্রোসেন্টেসিস হলো এমন একটি পদ্ধতি যার মাধ্যমে জীবাণুমুক্ত অবস্থায় সুঁই এবং সিরিঞ্জ ব্যবহার করে জয়েন্ট থেকে তরল অপসারণ করা হয়। এটি সাধারণত ডাক্তারের চেম্বারে করা হয়। খুব কম ক্ষেত্রে, উপযুক্ত অ্যান্টিবায়োটিক থাকা সত্ত্বেও আর্থ্রাইটিস চলতে থাকে। গবেষকদের দ্বারা পরামর্শ দেওয়া হয়েছে যে কখনও কখনও লাইম ব্যাকটেরিয়া নির্মূল হওয়ার পরেও জয়েন্টের প্রদাহ বজায় থাকতে পারে। এই জটিলতাটিকে একটি চলমান অটোইমিউন প্রতিক্রিয়া হিসেবে ব্যাখ্যা করা হয়েছে যা জয়েন্টের প্রদাহ সৃষ্টি করে, যা প্রাথমিকভাবে মূল ব্যাকটেরিয়া সংক্রমণের দ্বারা উদ্দীপিত হয়েছিল। আইবুপ্রোফেন (মোটরিন, টুরিন)-এর মতো ওরাল ওষুধগুলোও প্রদাহ কমাতে এবং কার্যকারিতা উন্নত করতে ব্যবহার করা যেতে পারে। লাইম রোগের চিকিৎসার পর যে অনির্দিষ্ট ক্লান্তি বজায় থাকে তা যে দীর্ঘস্থায়ী সংক্রমণের সাথে সম্পর্কিত, তার কোনো প্রমাণ নেই। এই পরিস্থিতিতে অ্যান্টিবায়োটিকের দীর্ঘমেয়াদী চিকিৎসার ঝুঁকি যেকোনো সুবিধার চেয়ে অনেক বেশি। উল্লেখ্য, লাইম রোগের দীর্ঘস্থায়ী উপসর্গের দীর্ঘমেয়াদী অ্যান্টিবায়োটিক চিকিৎসা স্বল্পমেয়াদী চিকিৎসার চেয়ে ভালো কোনো ফলাফল দেয় কিনা তা নিয়ে সাম্প্রতিক গবেষণা করা হয়েছে। গবেষণায় দেখা গেছে যে দীর্ঘমেয়াদী অ্যান্টিবায়োটিক চিকিৎসার ফলে স্বল্পমেয়াদী চিকিৎসার চেয়ে স্বাস্থ্য-সম্পর্কিত জীবনযাত্রার মানের ওপর কোনো অতিরিক্ত উপকারী প্রভাব পড়েনি। বিশেষ করে, গবেষকরা নির্ধারণ করেছেন যে এই দীর্ঘমেয়াদী অ্যান্টিবায়োটিক চিকিৎসার ক্লান্তি, বা লাইম রোগ থেকে পেশী-কঙ্কাল, নিউরোসাইকোলজিক্যাল বা জ্ঞানীয় উপসর্গ এবং ব্যাধির ওপর প্লাসিবোর চেয়ে বেশি কোনো উপকারী প্রভাব নেই। আশা করি আমি আপনার প্রশ্নের উত্তর দিয়েছি। আপনার আরও কোনো প্রশ্ন থাকলে নির্দ্বিধায় আমার সাথে যোগাযোগ করুন। আমি আপনাকে সাহায্য করতে পারলে খুশি হব। শুভকামনা।"
93762,73638,2959,"হেলো, প্রিয়, নাসেনিয়া ডকে আপনার অনুসন্ধানের জন্য ধন্যবাদ। প্রিয়, আমি আপনার অনুসন্ধানের বিষয়গুলো পড়েছি এবং আপনার জমা দেওয়া স্বাস্থ্য সমস্যাগুলোর প্রেক্ষাপটে তা পর্যালোচনা করেছি। আমি আপনার স্বাস্থ্য সংক্রান্ত উদ্বেগগুলো বুঝতে পেরেছি এবং এ বিষয়ে উদ্বিগ্ন। আপনার অনুসন্ধানের তথ্যের ভিত্তিতে উত্তরটি হলো- আপনার বর্তমান স্বাস্থ্য সমস্যাগুলো দীর্ঘস্থায়ী এবং উন্নত ভ্যারিকোস ভেইনস অফ দ্য স্ক্রোটাম (অণ্ডকোষের শিরা স্ফীতি)-এর কারণে বলে মনে হচ্ছে, যা হয়তো আগে লক্ষ্য করা যায়নি বা অবহেলা করা হয়েছে। অণ্ডকোষ বড় হওয়ার অন্যান্য কারণগুলোর সাথে এটি যাচাই করা প্রয়োজন, যা ইনগুইনো-স্ক্রোটাল হার্নিয়া বা ফাইলেরিয়াল স্ক্রোটাল এনলার্জমেন্টের কারণে হতে পারে। আপনার ক্ষেত্রে এর কারণ অনুসন্ধান করা প্রয়োজন। উপরে আলোচিত অন্যান্য কারণগুলোও যাচাই করা দরকার। এর জন্য আপনাকে সার্জিক্যাল বিভাগের সার্জন এবং ইউরোলজিস্টের সাথে পরামর্শ করতে হবে। প্রতিকার- আপনার ক্ষেত্রে করণীয়- ডাক্তারের সাথে পরামর্শ করুন- বিশ্রাম নিন- কয়েক দিন- ৪-৫ দিন- মাথা নিচু করে শুয়ে থাকলে তা ভ্যারিকোস রাপচার সাইটকে শক্তিশালী করতে সাহায্য করবে এবং ভবিষ্যতে পুনরায় হওয়া রোধ করবে। আপনার ভ্যারিকোসেলে ভ্যারিকোস ভেইনস ঠিক করার জন্য জরুরি ভিত্তিতে মাইক্রো-ভাস্কুলার সার্জারির পরিকল্পনা করতে হবে, যার জন্য ইএলভিটি (এন্ডোস্কোপিক লেজার অ্যাবলেশন) এবং ফোম কেমোথেরাপির প্রয়োজন হতে পারে, কারণ আপনার ভ্যারিকোসেলে উন্নত পর্যায়ের। স্ক্রোটাল ভ্যারিকোস ভেইনস থেকে রক্তপাত স্বাভাবিক প্রক্রিয়া নয় এবং এটি নির্দেশ করে যে দীর্ঘস্থায়ী ভ্যারিকোস ভেইনসের কারণে চামড়া পাতলা হয়ে গেছে, যার ফলে সামান্য আঘাতেই রক্তপাত হচ্ছে- যেমনটি আপনার ক্ষেত্রে ঘটেছে। পুষ্টিবিদ এবং পারিবারিক জিপি-র পরামর্শ অনুযায়ী কঠোর ডায়েট প্ল্যান মেনে স্থূলতা কমান। টেস্টোস্টেরন, এলএইচ, এফএসএইচ, থাইরয়েড এবং রক্তে শর্করার মাত্রা পরীক্ষা করুন, যা দীর্ঘস্থায়ী ভ্যারিকোসেলে-এর কারণে কম হতে পারে এবং যদি আপনার স্থূলতার কারণ ডায়াবেটিস বা হাইপোথাইরয়েডিজম হয় তবে তা ঠিক করুন। ইউরোলজিস্টের মাধ্যমে শারীরিক পরীক্ষা করান, যিনি ইউএসজি এবং কালার ডপলার স্টাডির মাধ্যমে ভ্যারিকোসেলে-এর তীব্রতা এবং অণ্ডকোষের অ্যাট্রোফি আছে কিনা তা মূল্যায়ন করবেন। আপনার ক্ষেত্রে নির্দিষ্ট অস্ত্রোপচারের পরিকল্পনা করার আগে উপরে আলোচিত কারণগুলোর মধ্যে কোনটি আপনার ক্ষেত্রে প্রযোজ্য তা যাচাই করা প্রয়োজন। শরীরের পেশী গঠন এবং স্থূলতা কমাতে উচ্চ প্রোটিন, কম ক্যালোরি, কম চর্বি এবং উচ্চ ফাইবারযুক্ত খাবার খান। সঠিক ব্যায়াম এবং হাঁটা আপনাকে অনেক সাহায্য করবে, তবে চিকিৎসকের পরামর্শ অনুযায়ী করবেন- যাতে অনিয়ন্ত্রিত ব্যায়ামের কারণে পেটের এবং শিরার চাপ বেড়ে আরও রক্তপাত না হয়। বিএমআর বৃদ্ধি এবং স্থূলতা কমাতে ভিটামিন বি১২ এবং ফলিক অ্যাসিড গ্রহণ করুন। সুতরাং, আপনার ইউরোলজিস্ট এবং চিকিৎসকের সাথে পরামর্শ করা উচিত। এটি আপনার অভিযোগগুলো সমাধান করবে। দীর্ঘমেয়াদী সুস্থতার জন্য স্থানীয় পারিবারিক চিকিৎসক বা বিশেষজ্ঞ ইউরোলজিস্টের সাথে নিয়মিত ফলো-আপ করুন, যা আপনার স্বাস্থ্যের উন্নতির ওপর নির্ভর করবে। চিন্তা করবেন না, ধৈর্য ধরুন এবং আপনার চিকিৎসকদের সাথে সহযোগিতা করুন। দ্রুত সুস্থতার জন্য উপরের পরামর্শগুলো মেনে চলুন, যা আপনার জটিল স্বাস্থ্য সমস্যাগুলো সমাধান করবে। আশা করি এটি আপনাকে আপনার স্বাস্থ্য সমস্যাগুলো সর্বোত্তম উপায়ে মোকাবিলা করতে সাহায্য করবে। এ বিষয়ে আরও কোনো প্রশ্ন থাকলে নিচের লিঙ্কে স্বাগতম- http"
30702,34040,2958,"হেলো, প্রিয়, নাসেনিয়া ডকে আপনার অনুসন্ধানের জন্য ধন্যবাদ। প্রিয়, আমি আপনার অনুসন্ধানটি পড়েছি এবং আপনার তথ্যের প্রেক্ষাপটে তা পর্যালোচনা করেছি। আমি আপনার স্বাস্থ্য সংক্রান্ত উদ্বেগগুলো বুঝতে পেরেছি এবং এ বিষয়ে উদ্বিগ্ন। আপনার তথ্যের ভিত্তিতে, আপনি সম্ভবত ক্রনিক ব্যাকটেরিয়াল প্রোস্টাটাইটিস (সিবিপি) এবং ইউরেথ্রাইটিসে ভুগছেন, যার সাথে সম্ভবত অর্কাইটিস রয়েছে। এটি অসম্পূর্ণ বা অলক্ষ্য এসটিডি (STD) সংক্রমণের পুনরাবৃত্তির কারণে হতে পারে অথবা পুরনো কিডনি পাথর, এসটিডি এবং সিবিপি ইউরেথ্রাইটিসের সাথে ইউটিআই (UTI) থাকতে পারে। যেহেতু আপনার প্রথমবার তীব্র বাম দিকের নিচের পিঠে ব্যথা এবং বমি বমি ভাব হয়েছে, যা পিঠের নিচ থেকে সামনের তলপেটে ছড়িয়ে পড়েছে, এটি সিস্টো-ইউরেথ্রাইটিস এবং সম্ভবত অর্কাইটিসের ইঙ্গিত দেয়। বীর্যপাতের সময় মূত্রনালীতে ব্যথা না থাকা নির্দেশ করে যে, অতীতে হওয়া এসটিডি থেকে ক্রনিক সাব-অ্যাকিউট সিবিপি সংক্রমণ হয়েছে, যা সম্প্রতি আবার দেখা দিয়েছে। পেটে ব্যথা এবং বমি বমি ভাব পাইলোনেফ্রাইটিস বা এপিডিডাইমো-অর্কাইটিসের দিকে নির্দেশ করে। কিডনি পাথরের সাথে পাইলোনেফ্রাইটিস এবং সিস্টো-প্রোস্টাটাইটিস এই লক্ষণগুলোর অনুকরণ করতে পারে, তাই এটি পরীক্ষা করে চিকিৎসা করা প্রয়োজন। বীর্যের স্থায়ী বাদামী রঙ নিশ্চিতভাবে প্রোস্টাটাইটিসের ইঙ্গিত দেয় এবং এটি দীর্ঘস্থায়ী সাব-অ্যাকিউট প্রোস্টাটাইটিস ও সাম্প্রতিক এপিডিডাইমো-অর্কাইটিসের সম্ভাবনা নির্দেশ করে। সিটি স্ক্যানের অপেক্ষায় আছি। প্রস্তাবিত প্রতিকার - প্রচুর পরিমাণে তরল পান করুন, ভালো যৌন স্বাস্থ্যবিধি মেনে চলুন এবং পুনরায় সংক্রমণের ঝুঁকি এড়াতে অনিরাপদ যৌন সম্পর্ক এড়িয়ে চলুন। ভালো খাদ্যাভ্যাস, দিনে ৮ ঘণ্টা পূর্ণ বিশ্রাম এবং ব্যাকটেরিয়াল কালচারের জন্য নমুনা পাঠানোর পর সাপ্লিমেন্টারি ভিটামিন ও অ্যান্টিবায়োটিক গ্রহণ করুন। এই জটিল পরিস্থিতিতে, আমি প্রোস্ট্যাটিক ম্যাসাজ থেকে প্রাপ্ত বীর্যের এলসিআর (LCR) টেস্ট করার পরামর্শ দেব, যা অতীতে অসম্পূর্ণভাবে চিকিৎসা করা গনোরিয়া এবং ক্ল্যামাইডিয়া সংক্রমণ দূর করতে সাহায্য করবে। ইউরিন কালচার বা প্রোস্ট্যাটিক ম্যাসাজ থেকে প্রাপ্ত বীর্যের কালচার সঠিক অ্যান্টিবায়োটিক ব্যবহারের নিশ্চিত নির্দেশনা দেবে, কারণ আপনার ক্ষেত্রে রোগটি ক্লিনিকাল লক্ষণ ছাড়াই সুপ্ত অবস্থায় রয়েছে বলে মনে হচ্ছে। সিটি প্রোস্টেট, অণ্ডকোষ এবং কর্ডের সাথে সিস্টো-ইউরেথ্রোগ্রাফি রোগের কারণগুলো সঠিকভাবে মূল্যায়নে সাহায্য করবে। এটি সেই অনুযায়ী চিকিৎসা শুরু করতে সহায়তা করবে। প্রাথমিক পর্যায়ে পেটের ইউএসজি (USG) এবং প্রস্রাব ও বীর্যের এলসিআর টেস্ট সঠিক অ্যান্টিবায়োটিক চিকিৎসা শুরু করতে সাহায্য করবে—হয় মুখে খাওয়ার মাধ্যমে অথবা ইন্ট্রাপ্রোস্ট্যাটিক ইনজেকশনের মাধ্যমে, সাথে হাইয়ালুরোনিক অ্যাসিড ইনফিউশন যা ক্রনিক ফাইব্রোটিক প্রোস্ট্যাটিক টিস্যুতে অ্যান্টিবায়োটিকের কার্যকারিতা বাড়াবে, যা আপনাকে বর্তমানে কষ্ট দিচ্ছে। ট্যামসুলোসিন/ফ্লোম্যাক্স এবং পাইজিয়ামের সাথে কোরাল ফোর্ট এবং ডাইক্লোফেনাক সোডিয়াম ২-৬ সপ্তাহের জন্য সেবন করলে আপনার অস্বস্তি কমবে এবং ভালো ফলাফল পাওয়া যাবে। আশা করি উপরের আলোচনা এবং পয়েন্টগুলো আপনাকে দ্রুত আপনার ইউরোলজিস্টের কাছ থেকে পরবর্তী চিকিৎসার পরিকল্পনা করতে সাহায্য করবে। আশা করি এটি আপনার স্বাস্থ্য সমস্যার সর্বোত্তম উপায়ে চিকিৎসায় সাহায্য করবে। এ বিষয়ে যেকোনো পরবর্তী প্রশ্নের জন্য স্বাগতম। দিনটি ভালো কাটুক!! নাসেনিয়া ডক। এন. সিনিয়র সার্জিক্যাল স্পেশালিস্ট। এস. জেনারেল-সিভিটিএস।"
95976,1844,2898,"হেলো, চ্যাটডক্টরে আপনাকে স্বাগতম। আপনার পিঠের নিচের দিকের ব্যথা এবং এর বিভাগ সম্পর্কিত আপনার প্রশ্নটি আমি দেখেছি। এটি উদ্বেগের বিষয়। কার্ট জেন (Cart Gen) সম্পর্কে বলতে চাই, আপনার ডাক্তারের পরামর্শ ছাড়া কোনো ওষুধ শুরু বা বন্ধ করবেন না। পিঠের বেশিরভাগ সমস্যাই ক্লান্ত বা টান পড়া পেশি থেকে হয়। আপনার চিন্তার কিছু নেই, জীবনের কোনো না কোনো পর্যায়ে প্রায় সবাই পিঠের ব্যথায় ভোগেন। আপনার অবগতির জন্য, প্রতিদিন আমরা আমাদের পরিবেশ এবং খাবারের মাধ্যমে বিষাক্ত পদার্থের সংস্পর্শে আসি, যে কারণে ডিটক্সিফিকেশন বা শরীর থেকে বিষাক্ত পদার্থ বের করে দেওয়া আপনার শরীরের জন্য অত্যন্ত গুরুত্বপূর্ণ এবং রোগ প্রতিরোধ ক্ষমতা দুর্বল হওয়ার ক্ষেত্রে এটি জরুরি। যদি ডিটক্স প্রক্রিয়া বাধাগ্রস্ত হয়, তবে শরীরে বিষাক্ত পদার্থ জমা হয়ে শেষ পর্যন্ত অ্যাসিডিটি এবং টক্সিমিয়া সৃষ্টি করে। এগুলো প্রায় সব রোগের মূল কারণ, যার জন্য জীবনধারা এবং খাদ্যাভ্যাসের পরিবর্তন প্রয়োজন। আপনি যদি আপনার জীবনধারা এবং খাদ্যাভ্যাস পরিবর্তন না করেন তবে কেবল ওষুধ খেয়ে কোনো লাভ হবে না। কিছু সহজ পদক্ষেপ অনুসরণ করে আপনি মাত্র কয়েক দিনের মধ্যেই সুস্থ হয়ে উঠতে পারেন। সমস্যা থাকা পর্যন্ত ধীরগতির নড়াচড়া করার অনুমতি আছে। শারীরিক ব্যায়ামের চেয়ে ভালো কোনো বিকল্প নেই। হাঁটা শুরু করার জন্য সেরা ব্যায়াম এবং এটি আপনাকে সুঠাম দেহও দেয়। সব প্রয়োজনীয় পুষ্টি উপাদান যেমন ফাইবার, প্রোটিন, ভিটামিন, খনিজ উপাদান প্রাকৃতিক আকারে এবং অ্যান্টিঅক্সিডেন্ট সমৃদ্ধ সুষম খাবার গ্রহণ করুন। ডাবের পানি, লেবুর রস, আদা, রসুন, অ্যালোভেরা জুস, ঘুমানোর আগে এক কাপ গরম দুধের সাথে হলুদের গুঁড়ো—এগুলো শক্তিশালী রোগ প্রতিরোধ ক্ষমতা অর্জনে, রোগ থেকে সুরক্ষা পেতে এবং সব ধরনের ব্যথা থেকে মুক্তি পেতে সাহায্য করে। আপনার শারীরিক সক্রিয়তা বাড়ান। যোগব্যায়াম করুন। পিঠকে শিথিল রাখতে এবং আঘাত এড়াতে পিঠের স্ট্রেচিং করুন। সমস্যা থাকা পর্যন্ত ধীরগতির নড়াচড়া করার অনুমতি আছে। শারীরিক ব্যায়ামের চেয়ে ভালো কোনো বিকল্প নেই। হাঁটা শুরু করার জন্য সেরা ব্যায়াম এবং এটি আপনাকে সুঠাম দেহও দেয়। সামনের দিকে ঝুঁকে স্ট্রেচিং এবং ব্যায়াম করা এড়িয়ে চলুন। দাঁড়িয়ে বা চিৎ হয়ে শুয়ে বাম থেকে ডানে স্ট্রেচিং করুন, অথবা যে অবস্থানে আপনি আরাম বোধ করেন। সামনের দিকে ঝোঁকা যাবে না। সকালে ও সন্ধ্যায় হোমিওপ্যাথিক আরনিকা ৩০ এবং ঘুমানোর আগে ক্যামোমিল ৩০-এর ১ ডোজ গ্রহণ করুন। কেবল পেছনের দিকে বাঁকানো ব্যায়াম ব্যথা কমাতে সাহায্য করবে। গরম জলপাই তেল বা ব্যথানাশক মলম দিয়ে মালিশ করুন। ভালো অঙ্গভঙ্গি বজায় রাখুন। আমি আপনাকে প্রক্রিয়াজাত খাবার, কার্বোহাইড্রেট, চিনি, ভাজা পোড়া, ফাস্ট ফুড, চা, কফি, অ্যালকোহল এবং ধূমপান, মানসিক চাপ এবং কোষ্ঠকাঠিন্য এড়িয়ে চলার পরামর্শ দিচ্ছি। এগুলো আপনার শরীরে জৈব রাসায়নিক এবং বিপাকীয় অবস্থার সৃষ্টি করবে যা আপনার রোগ প্রতিরোধ ক্ষমতা কমিয়ে দেবে, তাই এগুলো এড়িয়ে চলা শরীরকে ডিটক্স করা এবং রোগ প্রতিরোধ ক্ষমতা বাড়ানোর সঠিক পথে প্রথম পদক্ষেপ। এগুলো সবই আমাদের শক্তিশালী রোগ প্রতিরোধ ব্যবস্থার স্তম্ভ, যা সুস্থ ও রোগমুক্ত জীবনের জন্য দায়ী। সবসময় মনে রাখবেন, যদি ব্যথা তীব্র হয় বা আপনাকে অচল করে দেয়, তবে অনুগ্রহ করে আপনার ডাক্তার বা পেশাজীবীর সাথে দেখা করুন। আশা করি এটি আপনার প্রশ্নের সমাধান করবে। নিজের যত্ন নিন। শুভকামনা। দ্রুত সুস্থ হয়ে উঠুন, কোনো প্রশ্ন থাকলে দ্বিধা না করে আবার যোগাযোগ করুন।"

============================================================
AUDIT COMPLETE
============================================================
No rows were removed.
Review the flagged examples above before training.

In [47]:
df_train = df_base[["input", "output"]].copy()

print(df_train.shape)
print(df_train.columns.tolist())

display(df_train.head())

(108391, 2)
['input', 'output']

,input,output
0,"হেলো, আমরা গত ৩ মাস ধরে গর্ভধারণের চেষ্টা করছি কিন্তু ফলাফল নেতিবাচক। এবার আমি ফলিকুলার মনিটরিং করিয়েছি এবং ১৭তম দিনে ওভুলেশন হয়েছে, কিন্তু তবুও আমি গর্ভবতী নই। যদিও আমার এলও-তে অনেকগুলো ছোট ফলিকল ছিল, এগুলো কি স্বাভাবিক নাকি পিসিওডি? আমি সত্যিই বিভ্রান্ত এবং বুঝতে পারছি না কী করব, আমার কি ডাক্তার পরিবর্তন করা উচিত?","হেলো, পিসিওডি (PCOD) হলো এমন একটি উপসর্গ যা অনিয়মিত বা অনুপস্থিত পিরিয়ড, বন্ধ্যাত্ব, স্থূলতা, অবাঞ্ছিত লোম বৃদ্ধি, ব্রণ, কিছু ক্ষেত্রে ইনসুলিন রেজিস্ট্যান্স, এলএইচ/এফএসএইচ (LH/FSH) অনুপাত উল্টে যাওয়া সহ অস্বাভাবিক হরমোনের প্রোফাইল, আরএইচইএএস (RHEAS) লেভেল বৃদ্ধি, কিছু ক্ষেত্রে অস্বাভাবিক জিটিটি (GTT), কখনও কখনও উচ্চ প্রোল্যাক্টিন এবং অস্বাভাবিক থাইরয়েড প্রোফাইলের সাথে যুক্ত থাকে। এতে ডিম্বাশয়ে একাধিক ফলিকল দেখা যায় কারণ অনেকগুলো ফলিকল একই সময়ে তৈরি হলেও সেগুলো পরিপক্ক হয় না। রোগ নির্ণয়ের জন্য আপনাকে সম্পূর্ণ পরীক্ষা-নিরীক্ষা করাতে হবে। ওভুলেশন বা ডিম্বস্ফোটন সম্ভব হলেও হরমোনের ভারসাম্যহীনতা, টিউব সংক্রান্ত সমস্যা বা পুরুষজনিত কারণের মতো অনেকগুলো বিষয়ের কারণে গর্ভধারণ নাও হতে পারে। আপনার একজন অভিজ্ঞ ইনফার্টিলিটি বিশেষজ্ঞের পরামর্শ নেওয়া উচিত। নিজের যত্ন নেবেন।"
1,"প্রায় এক মাস আগে আমার পিঠের ডান দিকের কাঁধের হাড়ের কাছে বৈদ্যুতিক স্রোতের মতো এক ধরনের অনুভূতি হতে শুরু করেছে। এটি বেশ বিরক্তিকর এবং আমি জানি না কীভাবে এর চিকিৎসা করব। প্রায় ১২ বছর আগে আমার ঘাড়ে সি-৬ এবং সি-৭ ফিউশন হয়েছিল। কী হচ্ছে আমার? আমার বয়স ৬০, আমি বিশেষ চাহিদাসম্পন্ন শিশুদের নিয়ে কাজ করি এবং শারীরিকভাবে সক্রিয় থাকি। প্রায় এক মাস ধরে চলা হাড়কাঁপানো ঠান্ডার সাথে কি এর কোনো সম্পর্ক থাকতে পারে? ধন্যবাদ।","হেলো, প্রথমে আমাকে আপনাকে ব্যাখ্যা করতে দিন যে আপনার মতো একটি নির্দিষ্ট মেডিকেল লক্ষণের বিভিন্ন কারণ থাকতে পারে। পিঠে ব্যথা এবং বিদ্যুৎ প্রবাহের মতো অনুভূতি সার্ভিকাল স্পাইনাল কর্ডের স্পনডাইলোসিস বা অন্যান্য কারণে (যেমন কোনো টিউমার, অবক্ষয়, মেরুদণ্ডের সমস্যা) হতে পারে। বার্ধক্যে এটি স্পনডাইলোসিসের কারণে হতে পারে। সঠিক স্নায়বিক সমস্যা নির্ণয়ের জন্য আপনার একটি বিস্তারিত স্নায়বিক পরীক্ষা প্রয়োজন। বিদ্যুৎ প্রবাহের মতো অনুভূতির উপস্থিতি উদ্বেগের বিষয়, কারণ এটি নির্দেশ করে যে মেরুদণ্ডের কোনো একটি অংশ সংকুচিত হচ্ছে। তাই, জরুরি ভিত্তিতে একজন স্নায়ুরোগ বিশেষজ্ঞের মূল্যায়ন প্রয়োজন এবং পরবর্তীতে পুনরায় ইমেজিং ও নার্ভ কন্ডাকশন স্টাডি (প্রাথমিক মূল্যায়নের ওপর ভিত্তি করে এটি ঐচ্ছিক হতে পারে) করার প্রয়োজন হতে পারে। আপনার চিকিৎসা মূলত কারণের ওপর নির্ভর করবে। আশা করি এই ব্যাখ্যাটি আপনাকে সাহায্য করবে। শুভকামনা।"
2,"হেলো, আমি ২৫ বছর বয়সী অবিবাহিত মেয়ে। আমার কপাল, ঘাড় এবং হাতে কালচে দাগ হয়েছে। আগে এটি রোদে পোড়া দাগের মতো ছিল, কিন্তু আমি এর জন্য চিকিৎসা নিয়েছিলাম এবং ডাক্তার যে মলম দিয়েছিলেন তা স্টেরয়েডযুক্ত ছিল। এর ফলে সমস্যাটি আরও বেড়ে গেছে। আগে এটি খুব একটা বোঝা যেত না, কিন্তু এখন এটি দেখতে খুব খারাপ লাগে। আপনি কি দয়া করে আমাকে কিছু পরামর্শ দিতে পারেন? আমি রোদ এড়িয়ে চলি, কিন্তু কোনো সানস্ক্রিন ব্যবহার করি না কারণ এতে রাসায়নিক থাকে।","হেলো কবিতা, লেখার জন্য ধন্যবাদ। স্কিন লাইটেনিং ক্রিমে ২% এইচওয়াই নাসেনিয়া ডক থাকে। এই উপাদানগুলো ত্বকে স্থায়ী পিগমেন্টেশন ঘটাতে পারে যার ফলে সাদা দাগ হতে পারে। এটি দীর্ঘ সময় ব্যবহার করা উচিত নয়। আমার পরামর্শ হলো - স্টেরয়েডযুক্ত ক্রিম ব্যবহার বন্ধ করুন। দিনের বেলা ভালো সানস্ক্রিন ব্যবহার করুন। আপনি রাতে কালো দাগের ওপর ক্লাইম্যাক্স ক্রিম লাগাতে পারেন, এটি নিরাপদ এবং কার্যকর। গায়ের রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। খাদ্যতালিকায় প্রচুর ভিটামিন সি রাখুন। রোদে যাওয়া এড়িয়ে চলুন। রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। ভবিষ্যতে যেকোনো এইচকিউ (HQ) এবং স্টেরয়েডযুক্ত ক্রিম এড়িয়ে চলুন। আশা করি এটি সাহায্য করবে। ফলো-আপের জন্য আমি উপলব্ধ থাকব। শুভেচ্ছা।"
3,"হেলো, আমার বয়স ২২, উচ্চতা ৫ ফুট ৯ ইঞ্চি এবং ওজন ১৭০ পাউন্ড। আমি সারা জীবন খুব সুস্থ ছিলাম, তেমন কোনো সমস্যা হয়নি। আমার উপরের ঠোঁটের ঠিক উপরে একটি ফোলা চাকা হয়েছে যা ঠোঁটকে স্পর্শ করে আছে। চাপ না দিলে এটি ব্যথা করে না, তবে আমি এটি অনুভব করতে পারছি এবং এটি আমাকে বিরক্ত করছে। বরফ দিলে ফোলা কিছুটা কমে। এটি কোনো খোলা ক্ষত নয়, শুধু একটি চাকা যা যাচ্ছে না। এটি প্রায় ৫ দিন ধরে আছে।","হেলো প্রিয়, নাসেনিয়া ডকে আপনাকে স্বাগতম। আপনার উদ্বেগটি বুঝতে পারছি। আপনার প্রশ্ন অনুযায়ী, উপরের ঠোঁটের উপরে ফোলা অংশটি মূলত ঠোঁট কামড়ানোর কারণে হয়ে থাকে। অসাবধানতাবশত নিচের চোয়ালের দাঁত উপরের ঠোঁটে আঘাত করলে সেই জায়গায় অতিরিক্ত কোলাজেন ফাইবার জমা হয়ে ফোলাভাব সৃষ্টি হয়। এটি হারপিস সিমপ্লেক্স ভাইরাস সংক্রমণের কারণেও হতে পারে, যা ওই এলাকায় কোল্ড সোর বা ঘা সৃষ্টি করতে পারে। যদি আপনি অতিরিক্ত সূর্যের আলোতে থাকেন, তবে এই ফোসকা তার কারণেও হতে পারে। এটি নিয়ে আতঙ্কিত হওয়ার কিছু নেই। বরফের টুকরো নিয়ে এই জায়গায় ১০-১২ মিনিট বিরতি দিয়ে চেপে ধরুন। জায়গাটি পরিষ্কার রাখুন। নাসেনিয়া ডকের সাথেই থাকুন।"
4,"হেলো, আমার নানি প্রায়ই অভিযোগ করেন যে তার হৃদপিণ্ডের চারপাশে গ্যাসের সমস্যা হচ্ছে, যার ফলে তিনি মাথা ঝিমঝিম এবং মাথা ঘোরার অনুভব করেন। তার বয়স ৭৭ বছর এবং তার হার্টের অপারেশন হয়েছে ও নতুন ভালভ বসানো হয়েছে। তিনি ডাক্তারকে বিষয়টি জানালেও ডাক্তার কোনো পদক্ষেপ নিচ্ছেন না। আমি চিন্তিত কারণ এর ফলে তার মাথা ঘোরে এবং এমনিতেই তার হাঁটাচলায় ভারসাম্যহীনতা রয়েছে। এর কারণ কী হতে পারে এবং কী করলে উপকার পাওয়া যাবে, তা কি জানাতে পারবেন? ধন্যবাদ।","হেলো, আমি আপনার প্রশ্নটি মনোযোগ সহকারে পড়েছি এবং ব্যাখ্যা করতে চাই যে তার হৃদযন্ত্রের কার্যকারিতা মূল্যায়ন করা এবং সম্ভাব্য হার্ট ফেইলিওর যা এই ক্লিনিকাল পরিস্থিতির অনুকরণ করতে পারে, তা বাদ দেওয়া প্রয়োজন। গ্যাস্ট্রোইসোফেজিয়াল রিফ্লাক্সও এই পরিস্থিতির অনুকরণ করতে পারে, যদিও মাথা ঘোরা এই রোগের সাধারণ লক্ষণ নয়। এই পর্যায়ে, আমি হার্ট ফেইলিওর আছে কিনা তা তদন্ত করার জন্য একটি কার্ডিয়াক আল্ট্রাসাউন্ড এবং এনটি-প্রো বিএনপি (NT-pro BNP) পরীক্ষা করার পরামর্শ দেব। বিবেচনা করার মতো অন্যান্য পরীক্ষাগুলো হলো"

Test

In [48]:
import re
import pandas as pd
#test df
# ============================================================
# FINAL DATASET AUDIT
# Does NOT delete anything
# ============================================================

df_base_test = df_final_test.copy()

print("=" * 60)
print("FINAL DATASET AUDIT")
print("=" * 60)

print("\nShape:", df_base.shape)
print("Rows:", len(df_base))
print("Columns:", len(df_base.columns))


# ============================================================
# 1. NULL / EMPTY
# ============================================================

for col in ["input"]:
    null_count = df_base_test[col].isna().sum()
    empty_count = (
        df_base_test[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(f"\n{col.upper()}")
    print("Null:", null_count)
    print("Empty:", empty_count)


# ============================================================
# 2. URL CHECK
# ============================================================

url_pattern = re.compile(
    r'(?i)(?:https?://|www\.)'
)

domain_pattern = re.compile(
    r'(?i)\b(?:[a-z0-9-]+\.)+'
    r'(?:com|org|net|info|biz|io|co|in|bd|au)'
)

for col in ["input"]:

    url_rows = df_base_test[
        df_base_test[col].fillna("").astype(str).str.contains(
            url_pattern, regex=True
        )
    ]

    domain_rows = df_base_test[
        df_base_test[col].fillna("").astype(str).str.contains(
            domain_pattern, regex=True
        )
    ]

    print(f"\n{col.upper()} URL CHECK")
    print("HTTP/WWW rows:", len(url_rows))
    print("Domain rows:", len(domain_rows))

    if len(url_rows) > 0:
        display(url_rows[["id", col]].head(20))

    if len(domain_rows) > 0:
        display(domain_rows[["id", col]].head(20))


# ============================================================
# 3. EMAIL CHECK
# ============================================================

email_pattern = re.compile(
    r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b'
)

for col in ["input"]:

    email_rows = df_base_test[
        df_base_test[col].fillna("").astype(str).str.contains(
            email_pattern, regex=True
        )
    ]

    print(f"\n{col.upper()} EMAIL CHECK")
    print("Email rows:", len(email_rows))

    if len(email_rows) > 0:
        display(email_rows[["id", col]].head(20))


# ============================================================
# 4. PHONE NUMBER CHECK
# English + Bengali digits
# ============================================================

digits = "0-9০-৯"

phone_pattern = re.compile(
    rf'(?<![{digits}])'
    rf'\+?[{digits}]'
    rf'(?:[\s().-]*[{digits}]){{7,}}'
    rf'(?![{digits}])'
)

for col in ["input"]:

    phone_rows = df_base_test[
        df_base_test[col].fillna("").astype(str).str.contains(
            phone_pattern, regex=True
        )
    ]

    print(f"\n{col.upper()} PHONE CHECK")
    print("Possible phone rows:", len(phone_rows))

    if len(phone_rows) > 0:
        display(phone_rows[["id", col]].head(20))


# ============================================================
# 5. MARKDOWN / HTML ARTIFACTS
# ============================================================

artifact_pattern = re.compile(
    r'(?i)(?:\[[^\]]*\]\([^)]+\)|'
    r'<[^>]+>|'
    r'\\mailto|'
    r'&nbsp;|'
    r'&lt;|'
    r'&gt;)'
)

for col in ["input"]:

    artifact_rows = df_base_test[
        df_base_test[col].fillna("").astype(str).str.contains(
            artifact_pattern, regex=True
        )
    ]

    print(f"\n{col.upper()} MARKDOWN/HTML CHECK")
    print("Possible artifact rows:", len(artifact_rows))

    if len(artifact_rows) > 0:
        display(artifact_rows[["id", col]].head(20))


# ============================================================
# 6. EXTRA SPACES
# ============================================================

for col in ["input"]:

    # Multiple normal spaces
    multiple_space = df_base_test[
        df_base_test[col].fillna("").astype(str).str.contains(
            r'[ \t]{2,}',
            regex=True
        )
    ]

    # Space before punctuation
    space_before_punct = df_base_test[
        df_base_test[col].fillna("").astype(str).str.contains(
            r'\s+[,.!?;:।]',
            regex=True
        )
    ]

    print(f"\n{col.upper()} SPACE CHECK")
    print("Multiple spaces:", len(multiple_space))
    print("Space before punctuation:", len(space_before_punct))


# ============================================================
# 7. VERY SHORT TEXT
# ============================================================

for col in ["input"]:

    short_rows = df_base_test[
        df_base_test[col].fillna("").astype(str).str.strip().str.len() <= 2
    ]

    print(f"\n{col.upper()} VERY SHORT TEXT")
    print("Rows <= 2 characters:", len(short_rows))

    if len(short_rows) > 0:
        display(short_rows[["id", col]].head(30))


# ============================================================
# 8. DUPLICATE INPUT
# ============================================================

duplicate_input = df_base_test[
    df_base_test["input"].duplicated(keep=False)
].sort_values("input")

print("\nDUPLICATE INPUT")
print("----------------")
print("Rows involved:", len(duplicate_input))

if len(duplicate_input) > 0:
    display(
        duplicate_input[
            ["id", "input"]
        ].head(30)
    )


# ============================================================
# 9. EXACT DUPLICATE INPUT + OUTPUT
# ============================================================

duplicate_pairs = df_base_test[
    df_base_test.duplicated(
        subset=["input"],
        keep=False
    )
]

print("\nDUPLICATE INPUT + OUTPUT PAIRS")
print("--------------------------------")
print("Rows involved:", len(duplicate_pairs))

if len(duplicate_pairs) > 0:
    display(
        duplicate_pairs[
            ["id", "input"]
        ].head(30)
    )


# ============================================================
# 10. LENGTH DISTRIBUTION
# ============================================================

df_base_test["input_len"] = (
    df_base["input"]
    .fillna("")
    .astype(str)
    .str.len()
)



print("\nLENGTH SUMMARY")
print("----------------")

display(
    df_base_test[
        ["input_len"]
    ].describe()
)


# ============================================================
# 11. EXTREMELY LONG ROWS
# ============================================================

print("\nLONGEST INPUTS")
print("----------------")

display(
    df_base_test.nlargest(
        10,
        "input_len"
    )[["id", "input_len", "input"]]
)



# ============================================================
# 12. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 60)
print("AUDIT COMPLETE")
print("=" * 60)
print("No rows were removed.")
print("Review the flagged examples above before training.")

============================================================
FINAL DATASET AUDIT
============================================================

Shape: (108391, 6)
Rows: 108391
Columns: 6

INPUT
Null: 0
Empty: 0

INPUT URL CHECK
HTTP/WWW rows: 0
Domain rows: 0

INPUT EMAIL CHECK
Email rows: 0

INPUT PHONE CHECK
Possible phone rows: 0

INPUT MARKDOWN/HTML CHECK
Possible artifact rows: 0

INPUT SPACE CHECK
Multiple spaces: 0
Space before punctuation: 5

INPUT VERY SHORT TEXT
Rows <= 2 characters: 0

DUPLICATE INPUT
----------------
Rows involved: 0

DUPLICATE INPUT + OUTPUT PAIRS
--------------------------------
Rows involved: 0

LENGTH SUMMARY
----------------

         input_len
count   995.000000
mean    453.891457
std     254.307713
min      46.000000
25%     302.000000
50%     379.000000
75%     537.500000
max    2237.000000

LONGEST INPUTS
----------------

,id,input_len,input
611,57985,2237.0,"হেলো, গত বুধবার আমার ৯টি দাঁত তোলা হয়েছে। আমাকে দিনে তিনবার ৫০০ মিলিগ্রামের অ্যামোক্সিসিলিন দেওয়া হয়েছিল। এখন আমার শরীরে র‍্যাশ উঠেছে। ডেন্টিস্ট আমাকে ওষুধটি বন্ধ করতে বলেছেন, কিন্তু এখন আমার আমবাতের মতো র‍্যাশ হয়েছে। চুলকানি কমানোর জন্য আমার কিছু প্রয়োজন এবং এই চুলকানি কতদিন থাকবে তা জানতে চাই। ধন্যবাদ।"
347,6243,2185.0,আমি বেশ কয়েক মাস ধরে প্রতি ৬ সপ্তাহ অন্তর ভেসপিডের অ্যালার্জি শট নিচ্ছি (কয়েক বছর ধরে সাপ্তাহিক এবং তারপর আরও কয়েক বছর মাসিক শট নেওয়ার পর - আমাকে খুব কম ডোজ থেকে শুরু করতে হয়েছিল কারণ হুল ফোটার পর আমার অ্যানাফিল্যাকটিক শক হয়েছিল এবং আমাকে ৩ দিন নিবিড় পরিচর্যা কেন্দ্রে থাকতে হয়েছিল)। আমার ডাক্তার বলেছেন যে আমি কখনোই এই শট নেওয়া বন্ধ করতে পারব না - কখনোই না! এটা কি সত্যি?
388,48911,2117.0,"এক সপ্তাহ আগে আমি আমার বাম পাঁজরের ওপর পড়ে গিয়েছিলাম। পাঁজরের হাড় ভাঙা বা ফাটল আছে কি না তা নিশ্চিত হতে আমি বুকের এক্স-রে করিয়েছি। সৃষ্টিকর্তাকে ধন্যবাদ যে রিপোর্ট নেগেটিভ এসেছে। আমার সমস্যাটি হলো, পড়ে যাওয়ার পর থেকে আমার পাঁজরের নিচে এবং পিঠের দিকে পাঁজরের চারপাশে গ্যাসের বুদবুদ অনুভূত হচ্ছে। এটি কী হতে পারে? শ্বাস নিতে এবং পাশ ফিরে বা পিঠের ওপর ভর দিয়ে শুতে আমার এখনও কিছুটা অস্বস্তি হয়, কিন্তু এই গ্যাসের বুদবুদগুলো কেন হচ্ছে? আমি চিন্তিত যে আমার বাম পাঁজরের নিচে কোনো অঙ্গের ক্ষতি হয়েছে কি না। ধন্যবাদ।"
906,107241,2091.0,"আমার বাবার বয়স ৬৯ বছর এবং ওজন ৯০ কেজি। গত সপ্তাহে তার হার্টে বাইপাস সার্জারি হয়েছে। এরপর থেকেই তার পা খুব ফুলে গেছে, তিনি নিজে নিজে দাঁড়াতে পারছেন না, কারো সাহায্য ছাড়া হাঁটতে পারছেন না এবং সামান্য পরিশ্রমেই খুব ক্লান্ত হয়ে পড়ছেন। তার ডায়াবেটিস ও উচ্চ রক্তচাপের ইতিহাস রয়েছে। অস্ত্রোপচারের পর কি এটি স্বাভাবিক, নাকি তার কোনো সমস্যা হচ্ছে?"
260,75550,1977.0,"আমার জিহ্বার ডগায় জ্বালাপোড়া, ঠোঁট অবশ হয়ে যাওয়া এবং মুখে ধাতব স্বাদের কারণ কী? আমি ইতিমধ্যেই জিইআরডি (GERD) ডায়েট মেনে চলছি এবং ওষুধ খাচ্ছি। আমার পেটে ব্যথা বা খাবার উঠে আসার মতো সমস্যা নেই, তবে মুখে অস্বস্তি বোধ করছি।"
857,9198,1974.0,"আমি বদহজমের জন্য টারট্রাজিনযুক্ত ওমেজল ২০ মিগ্রা ব্যবহার করছি। আমি যে আরাম পেয়েছি তা চমৎকার ..... কিন্তু আমি জানতে চাই যে এর কোনো প্রাকৃতিক বিকল্প আছে কি যা আমি চেষ্টা করতে পারি এবং যা সমান কার্যকর হতে পারে, অথবা এমন অন্য কোনো ওষুধ আছে কি যাতে টারট্রাজিন নেই।"
459,72542,1900.0,"আমি আমার শিশুকে প্রথম দুধ হিসেবে S26 SMA গোল্ড দিয়েছিলাম, কিন্তু ১০ দিন পর তার পায়খানা খুব শক্ত হয়ে যাওয়ায় আমি দুধ পরিবর্তন করি। আমি তাকে NAN খাওয়াতে শুরু করি, কিন্তু এখন সে যখনই দুধ খায়, তার ১ ঘণ্টা পরেই পায়খানা করে এবং তা খুব নরম ও দুর্গন্ধযুক্ত হয়, সেই সাথে সে দুধ বমিও করে দেয়। আমার শিশুর এমনটা কেন হচ্ছে? দুধ পরিবর্তন করলে কি এমন হওয়া স্বাভাবিক? আপনি কি শিশুদের জন্য ভালো কোনো দুধের ব্র্যান্ডের পরামর্শ দিতে পারেন? ধন্যবাদ।"
877,80214,1748.0,তিন সপ্তাহ আগে আমার বাম কিডনি ল্যাপারোস্কোপিক হ্যান্ড-অ্যাসিস্টেড পদ্ধতিতে অপসারণ করা হয়েছে। এখন আমার পেটে অদ্ভুত দেখতে একটি ফোলা অংশ দেখা যাচ্ছে। এটি আমার নাভির ডান দিকে একটি বড় ভাঁজসহ অদ্ভুতভাবে বেরিয়ে আছে। এটি কী? এটি কি কখনো চলে যাবে? সেখানে এখন ব্যথা করছে এবং এমনকি যেখানে কাটা হয়েছিল তার চেয়েও বেশি সংবেদনশীল। এটি কী?
385,81436,1666.0,"আমি চার্চের ক্যয়ারে গান গাইতে পছন্দ করি এবং শেষের দিকে আমার সামান্য শ্বাসকষ্ট হয়, তারপর বুকে চাপ অনুভব করি। আমার কিছু হৃদরোগের সমস্যা ছিল কিন্তু আমার কার্ডিওলজিস্ট সম্প্রতি একটি ক্যাথ করেছেন এবং বলেছেন কোনো সমস্যা নেই। এরপর আমি একটি এন্ডোস্কোপি করিয়েছি এবং ডাক্তার কিছুই পাননি। আমি বেশ কিছুদিন ধরে এই সমস্যায় ভুগছি এবং এখনও সমস্যাটি কী তা নির্ধারণ করার চেষ্টা করছি।"
642,75059,1631.0,"১. আমি ভারত থেকে ৬৫ বছর বয়সী একজন পুরুষ। ২০০৭ সালে আমার বাইপাস সার্জারি এবং ২০০৮ সালে এআইসিডি (AICD) ইমপ্লান্টেশন হয়েছিল। ২০১৩ সালে একটি প্রতিস্থাপন এআইসিডি বসানো হয়। আমি কার্ডোরোন ১৫০/জার্ব ১৫০/কার্ডিভাস ১২.৫ মিগ্রা/স্টোরভাস ২০ মিগ্রা/ইকোস্প্রিন ১৫০ সেবন করছিলাম। জানুয়ারি মাসে জার্ব বন্ধ করে দেওয়া হয় এবং আমাকে বলা হয় যে রক্তচাপ ১৫০/৯০ এর বেশি হলে সিলিকার ১০ মিগ্রা এসওএস (SOS) নিতে। ২. আজ সকালে আমার রক্তচাপ ১৬৭/৯৫ এ পৌঁছে যায় এবং আমি বাম কাঁধে (এআইসিডি ইমপ্লান্টেশনের স্থান থেকে ৩ ইঞ্চি দূরে) ধড়ফড়ানি অনুভব করছিলাম। ৩০ মিনিটের মধ্যে দ্বিতীয়বার পরিমাপে রক্তচাপ ১৫৫/৮৭ পাওয়া যায়। আমি প্রায় এক ঘণ্টা আগে পরামর্শ অনুযায়ী সিলিকার গ্রহণ করেছি। ৩. এটি কি কোনো গুরুতর শারীরিক অবস্থা? নাড়ির গতি ৬০। শুভেচ্ছা, ব্রিগেডিয়ার সুনীল অরোরা, মুম্বাই, ভারত।"

============================================================
AUDIT COMPLETE
============================================================
No rows were removed.
Review the flagged examples above before training.

In [49]:
df_base.head()

,id,input,output,input_length,input_len,output_len
0,45361,"হেলো, আমরা গত ৩ মাস ধরে গর্ভধারণের চেষ্টা করছি কিন্তু ফলাফল নেতিবাচক। এবার আমি ফলিকুলার মনিটরিং করিয়েছি এবং ১৭তম দিনে ওভুলেশন হয়েছে, কিন্তু তবুও আমি গর্ভবতী নই। যদিও আমার এলও-তে অনেকগুলো ছোট ফলিকল ছিল, এগুলো কি স্বাভাবিক নাকি পিসিওডি? আমি সত্যিই বিভ্রান্ত এবং বুঝতে পারছি না কী করব, আমার কি ডাক্তার পরিবর্তন করা উচিত?","হেলো, পিসিওডি (PCOD) হলো এমন একটি উপসর্গ যা অনিয়মিত বা অনুপস্থিত পিরিয়ড, বন্ধ্যাত্ব, স্থূলতা, অবাঞ্ছিত লোম বৃদ্ধি, ব্রণ, কিছু ক্ষেত্রে ইনসুলিন রেজিস্ট্যান্স, এলএইচ/এফএসএইচ (LH/FSH) অনুপাত উল্টে যাওয়া সহ অস্বাভাবিক হরমোনের প্রোফাইল, আরএইচইএএস (RHEAS) লেভেল বৃদ্ধি, কিছু ক্ষেত্রে অস্বাভাবিক জিটিটি (GTT), কখনও কখনও উচ্চ প্রোল্যাক্টিন এবং অস্বাভাবিক থাইরয়েড প্রোফাইলের সাথে যুক্ত থাকে। এতে ডিম্বাশয়ে একাধিক ফলিকল দেখা যায় কারণ অনেকগুলো ফলিকল একই সময়ে তৈরি হলেও সেগুলো পরিপক্ক হয় না। রোগ নির্ণয়ের জন্য আপনাকে সম্পূর্ণ পরীক্ষা-নিরীক্ষা করাতে হবে। ওভুলেশন বা ডিম্বস্ফোটন সম্ভব হলেও হরমোনের ভারসাম্যহীনতা, টিউব সংক্রান্ত সমস্যা বা পুরুষজনিত কারণের মতো অনেকগুলো বিষয়ের কারণে গর্ভধারণ নাও হতে পারে। আপনার একজন অভিজ্ঞ ইনফার্টিলিটি বিশেষজ্ঞের পরামর্শ নেওয়া উচিত। নিজের যত্ন নেবেন।",317,317,769
1,95550,"প্রায় এক মাস আগে আমার পিঠের ডান দিকের কাঁধের হাড়ের কাছে বৈদ্যুতিক স্রোতের মতো এক ধরনের অনুভূতি হতে শুরু করেছে। এটি বেশ বিরক্তিকর এবং আমি জানি না কীভাবে এর চিকিৎসা করব। প্রায় ১২ বছর আগে আমার ঘাড়ে সি-৬ এবং সি-৭ ফিউশন হয়েছিল। কী হচ্ছে আমার? আমার বয়স ৬০, আমি বিশেষ চাহিদাসম্পন্ন শিশুদের নিয়ে কাজ করি এবং শারীরিকভাবে সক্রিয় থাকি। প্রায় এক মাস ধরে চলা হাড়কাঁপানো ঠান্ডার সাথে কি এর কোনো সম্পর্ক থাকতে পারে? ধন্যবাদ।","হেলো, প্রথমে আমাকে আপনাকে ব্যাখ্যা করতে দিন যে আপনার মতো একটি নির্দিষ্ট মেডিকেল লক্ষণের বিভিন্ন কারণ থাকতে পারে। পিঠে ব্যথা এবং বিদ্যুৎ প্রবাহের মতো অনুভূতি সার্ভিকাল স্পাইনাল কর্ডের স্পনডাইলোসিস বা অন্যান্য কারণে (যেমন কোনো টিউমার, অবক্ষয়, মেরুদণ্ডের সমস্যা) হতে পারে। বার্ধক্যে এটি স্পনডাইলোসিসের কারণে হতে পারে। সঠিক স্নায়বিক সমস্যা নির্ণয়ের জন্য আপনার একটি বিস্তারিত স্নায়বিক পরীক্ষা প্রয়োজন। বিদ্যুৎ প্রবাহের মতো অনুভূতির উপস্থিতি উদ্বেগের বিষয়, কারণ এটি নির্দেশ করে যে মেরুদণ্ডের কোনো একটি অংশ সংকুচিত হচ্ছে। তাই, জরুরি ভিত্তিতে একজন স্নায়ুরোগ বিশেষজ্ঞের মূল্যায়ন প্রয়োজন এবং পরবর্তীতে পুনরায় ইমেজিং ও নার্ভ কন্ডাকশন স্টাডি (প্রাথমিক মূল্যায়নের ওপর ভিত্তি করে এটি ঐচ্ছিক হতে পারে) করার প্রয়োজন হতে পারে। আপনার চিকিৎসা মূলত কারণের ওপর নির্ভর করবে। আশা করি এই ব্যাখ্যাটি আপনাকে সাহায্য করবে। শুভকামনা।",409,409,817
2,98599,"হেলো, আমি ২৫ বছর বয়সী অবিবাহিত মেয়ে। আমার কপাল, ঘাড় এবং হাতে কালচে দাগ হয়েছে। আগে এটি রোদে পোড়া দাগের মতো ছিল, কিন্তু আমি এর জন্য চিকিৎসা নিয়েছিলাম এবং ডাক্তার যে মলম দিয়েছিলেন তা স্টেরয়েডযুক্ত ছিল। এর ফলে সমস্যাটি আরও বেড়ে গেছে। আগে এটি খুব একটা বোঝা যেত না, কিন্তু এখন এটি দেখতে খুব খারাপ লাগে। আপনি কি দয়া করে আমাকে কিছু পরামর্শ দিতে পারেন? আমি রোদ এড়িয়ে চলি, কিন্তু কোনো সানস্ক্রিন ব্যবহার করি না কারণ এতে রাসায়নিক থাকে।","হেলো কবিতা, লেখার জন্য ধন্যবাদ। স্কিন লাইটেনিং ক্রিমে ২% এইচওয়াই নাসেনিয়া ডক থাকে। এই উপাদানগুলো ত্বকে স্থায়ী পিগমেন্টেশন ঘটাতে পারে যার ফলে সাদা দাগ হতে পারে। এটি দীর্ঘ সময় ব্যবহার করা উচিত নয়। আমার পরামর্শ হলো - স্টেরয়েডযুক্ত ক্রিম ব্যবহার বন্ধ করুন। দিনের বেলা ভালো সানস্ক্রিন ব্যবহার করুন। আপনি রাতে কালো দাগের ওপর ক্লাইম্যাক্স ক্রিম লাগাতে পারেন, এটি নিরাপদ এবং কার্যকর। গায়ের রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। খাদ্যতালিকায় প্রচুর ভিটামিন সি রাখুন। রোদে যাওয়া এড়িয়ে চলুন। রঙ ফিরে আসবে, তবে প্রক্রিয়াটি ধীর এবং চিকিৎসার জন্য ২-৩ মাস সময় লাগতে পারে। ভবিষ্যতে যেকোনো এইচকিউ (HQ) এবং স্টেরয়েডযুক্ত ক্রিম এড়িয়ে চলুন। আশা করি এটি সাহায্য করবে। ফলো-আপের জন্য আমি উপলব্ধ থাকব। শুভেচ্ছা।",424,424,726
3,84959,"হেলো, আমার বয়স ২২, উচ্চতা ৫ ফুট ৯ ইঞ্চি এবং ওজন ১৭০ পাউন্ড। আমি সারা জীবন খুব সুস্থ ছিলাম, তেমন কোনো সমস্যা হয়নি। আমার উপরের ঠোঁটের ঠিক উপরে একটি ফোলা চাকা হয়েছে যা ঠোঁটকে স্পর্শ করে আছে। চাপ না দিলে এটি ব্যথা করে না, তবে আমি এটি অনুভব করতে পারছি এবং এটি আমাকে বিরক্ত করছে। বরফ দিলে ফোলা কিছুটা কমে। এটি কোনো খোলা ক্ষত নয়, শুধু একটি চাকা যা যাচ্ছে না। এটি প্রায় ৫ দিন ধরে আছে।","হেলো প্রিয়, নাসেনিয়া ডকে আপনাকে স্বাগতম। আপনার উদ্বেগটি বুঝতে পারছি। আপনার প্রশ্ন অনুযায়ী, উপরের ঠোঁটের উপরে ফোলা অংশটি মূলত ঠোঁট কামড়ানোর কারণে হয়ে থাকে। অসাবধানতাবশত নিচের চোয়ালের দাঁত উপরের ঠোঁটে আঘাত করলে সেই জায়গায় অতিরিক্ত কোলাজেন ফাইবার জমা হয়ে ফোলাভাব সৃষ্টি হয়। এটি হারপিস সিমপ্লেক্স ভাইরাস সংক্রমণের কারণেও হতে পারে, যা ওই এলাকায় কোল্ড সোর বা ঘা সৃষ্টি করতে পারে। যদি আপনি অতিরিক্ত সূর্যের আলোতে থাকেন, তবে এই ফোসকা তার কারণেও হতে পারে। এটি নিয়ে আতঙ্কিত হওয়ার কিছু নেই। বরফের টুকরো নিয়ে এই জায়গায় ১০-১২ মিনিট বিরতি দিয়ে চেপে ধরুন। জায়গাটি পরিষ্কার রাখুন। নাসেনিয়া ডকের সাথেই থাকুন।",376,376,593
4,65169,"হেলো, আমার নানি প্রায়ই অভিযোগ করেন যে তার হৃদপিণ্ডের চারপাশে গ্যাসের সমস্যা হচ্ছে, যার ফলে তিনি মাথা ঝিমঝিম এবং মাথা ঘোরার অনুভব করেন। তার বয়স ৭৭ বছর এবং তার হার্টের অপারেশন হয়েছে ও নতুন ভালভ বসানো হয়েছে। তিনি ডাক্তারকে বিষয়টি জানালেও ডাক্তার কোনো পদক্ষেপ নিচ্ছেন না। আমি চিন্তিত কারণ এর ফলে তার মাথা ঘোরে এবং এমনিতেই তার হাঁটাচলায় ভারসাম্যহীনতা রয়েছে। এর কারণ কী হতে পারে এবং কী করলে উপকার পাওয়া যাবে, তা কি জানাতে পারবেন? ধন্যবাদ।","হেলো, আমি আপনার প্রশ্নটি মনোযোগ সহকারে পড়েছি এবং ব্যাখ্যা করতে চাই যে তার হৃদযন্ত্রের কার্যকারিতা মূল্যায়ন করা এবং সম্ভাব্য হার্ট ফেইলিওর যা এই ক্লিনিকাল পরিস্থিতির অনুকরণ করতে পারে, তা বাদ দেওয়া প্রয়োজন। গ্যাস্ট্রোইসোফেজিয়াল রিফ্লাক্সও এই পরিস্থিতির অনুকরণ করতে পারে, যদিও মাথা ঘোরা এই রোগের সাধারণ লক্ষণ নয়। এই পর্যায়ে, আমি হার্ট ফেইলিওর আছে কিনা তা তদন্ত করার জন্য একটি কার্ডিয়াক আল্ট্রাসাউন্ড এবং এনটি-প্রো বিএনপি (NT-pro BNP) পরীক্ষা করার পরামর্শ দেব। বিবেচনা করার মতো অন্যান্য পরীক্ষাগুলো হলো",432,432,500

In [50]:
# Run this cell in your notebook to audit df_base
print("=" * 45)
print("       DF_BASE CLEANLINESS AUDIT          ")
print("=" * 45)

print(f"Total Rows: {len(df_base):,}\n")

# 1. Missing Values
nulls = df_base[["input", "output"]].isnull().sum()
print("1. Missing Values:")
print(nulls.to_string())
print("-" * 45)

# 2. Exact Duplicates & Conflicts
exact_dups = df_base.duplicated(subset=["input", "output"]).sum()
input_dups = df_base["input"].duplicated().sum()
conflicting = (df_base.groupby("input")["output"].nunique() > 1).sum()

print("2. Duplicates & Noise:")
print(f"   • Exact Duplicate Pairs (input + output): {exact_dups}")
print(f"   • Total Duplicate Inputs                 : {input_dups}")
print(f"   • Conflicting Prompts (1 input -> >1 output): {conflicting}")
print("-" * 45)

# 3. Truncated / Short Prompts (< 25 characters)
short_prompts = df_base[df_base["input"].str.strip().str.len() < 25]
print(f"3. Truncated / Incomplete Prompts (< 25 chars): {len(short_prompts)}")
if len(short_prompts) > 0:
    print("\n   ⚠️ Examples of incomplete prompts found:")
    for idx, text in enumerate(short_prompts["input"].head(5), 1):
        print(f"      {idx}. \"{text}\"")
print("-" * 45)

# 4. Length Summary
in_lens = df_base["input"].str.len()
out_lens = df_base["output"].str.len()
print("4. Character Length Statistics:")
print(f"   • Input Length  -> Min: {in_lens.min()} | Median: {in_lens.median():.0f} | Max: {in_lens.max():,}")
print(f"   • Output Length -> Min: {out_lens.min()} | Median: {out_lens.median():.0f} | Max: {out_lens.max():,}")
print("=" * 45)

=============================================
       DF_BASE CLEANLINESS AUDIT
=============================================
Total Rows: 108,391

1. Missing Values:
input     0
output    0
---------------------------------------------
2. Duplicates & Noise:
   • Exact Duplicate Pairs (input + output): 0
   • Total Duplicate Inputs                 : 73
   • Conflicting Prompts (1 input -> >1 output): 19
---------------------------------------------
3. Truncated / Incomplete Prompts (< 25 chars): 88

   ⚠️ Examples of incomplete prompts found:
      1. "গোড়ালির মচকানো"
      2. "হেলো"
      3. "হেলো"
      4. "মানসিক সমস্যা"
      5. "হেলো"
---------------------------------------------
4. Character Length Statistics:
   • Input Length  -> Min: 4 | Median: 373 | Max: 10,814
   • Output Length -> Min: 4 | Median: 594 | Max: 3,322
=============================================

In [51]:
print(f"Rows before final polish: {len(df_base):,}")

# 1. Remove short inputs (< 25 chars) AND incomplete doctor outputs (< 20 chars)
df_cleaned_base = df_base[
    (df_base["input"].str.strip().str.len() >= 25) & 
    (df_base["output"].str.strip().str.len() >= 20)
].copy()

# 2. Resolve conflicting inputs by keeping the first complete example
df_cleaned_base = df_cleaned_base.drop_duplicates(subset=["input"], keep="first").reset_index(drop=True)

print(f"Rows after final polish : {len(df_cleaned_base):,}")

Rows before final polish: 108,391
Rows after final polish : 108,068

Load Qwen 2.5 3B in 4-bit

In [ ]:
!pip uninstall -y torchvision torchaudio trl unsloth unsloth_zoo transformers peft accelerate bitsandbytes

In [ ]:
!pip install --no-cache-dir "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

In [ ]:
!pip install --no-cache-dir --no-deps trl peft accelerate bitsandbytes

In [ ]:
import torch
from datasets import Dataset
from trl import SFTTrainer
from unsloth import FastLanguageModel

print("Imports successful!")

In [ ]:
!pip install --upgrade unsloth unsloth_zoo

In [ ]:
import unsloth
print(unsloth.__version__)

In [ ]:
# Temporary: measure real throughput before committing to the full run
# trainer.args.max_steps = 20
# trainer.train()

In [ ]:
# total_steps = 6310  # or recompute: len(train_ds) * 2 / 32
# projected_hours = total_steps / observed_it_per_sec / 3600
# print(projected_hours)

In [52]:
import os

# 1. OPTIONAL: Pin to GPU 0 to prevent dual-GPU overhead on Kaggle
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

# 2. IMPORTANT: Import unsloth FIRST before trl / transformers / peft
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import get_chat_template, train_on_responses_only

# 3. Now import trl, datasets, and transformers
import pandas as pd
import torch
from datasets import Dataset
from transformers import TrainingArguments
from trl import SFTTrainer

print(
    "🎉 Everything imported cleanly! Unsloth optimization is active and ready."
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
🎉 Everything imported cleanly! Unsloth optimization is active and ready.

In [ ]:
# 1. Load Data


# 2. Setup System Prompt & Chat Formatting
SYSTEM_PROMPT = (
    "আপনি একজন অভিজ্ঞ ও সহানুভূতিশীল চিকিৎসক। রোগীর বর্ণনা পড়ে "
    "স্পষ্ট, নির্ভুল এবং সহজবোধ্য ভাষায় চিকিৎসা পরামর্শ দিন।"
)

# 3. Model & Tokenizer Setup via Unsloth
MAX_SEQ_LENGTH = 1024
MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"
OUTPUT_DIR = "bn-doctor-lora"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_ID,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
)

tokenizer = get_chat_template(tokenizer, chat_template="qwen-2.5")


# 4. Format Labeled Train Dataset
def format_prompts(df_train):
    records = df_train.to_dict("records")
    formatted_texts = [
        tokenizer.apply_chat_template(
            [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": row["input"]},
                {"role": "assistant", "content": row["output"]},
            ],
            tokenize=False,
        )
        for row in records
    ]
    return pd.DataFrame({"text": formatted_texts})


df_formatted = format_prompts(df_cleaned_base)
ds = Dataset.from_pandas(df_formatted)

# Validation split
split = ds.train_test_split(test_size=500, seed=42)
train_ds, eval_ds = split["train"], split["test"]

print(
    f"Dataset ready! Training samples: {len(train_ds)} | Eval samples: {len(eval_ds)}"
)

In [ ]:
# check actual response-length distribution before assuming you need 1024
lengths = df_cleaned_base["output"].apply(lambda x: len(tokenizer(x)["input_ids"]))
print(lengths.describe())

In [ ]:
import torch
from transformers import TrainingArguments
from trl import SFTTrainer
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import train_on_responses_only

# 0. Subsample so this actually finishes within a Kaggle session
#    (only run this line once — if you rerun the cell, it'll re-shuffle from
#    the already-subsampled 35k, which is fine, just don't chain it further)
train_ds = train_ds.shuffle(seed=42).select(range(35000))

# 1. Add LoRA Adapters
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha=32,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
)

# 2. Setup SFTTrainer
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=train_ds,
    eval_dataset=eval_ds,
    dataset_text_field="text",
    max_seq_length=1024,
    dataset_num_proc=1,
    packing=False,
    args=TrainingArguments(
        per_device_train_batch_size=2,       # small enough to avoid CPU offload
        gradient_accumulation_steps=16,       # effective batch = 32
        warmup_steps=50,
        num_train_epochs=1,
        average_tokens_across_devices=False,  # fixes the 'int' object has no attribute 'mean' crash
        learning_rate=2e-4,
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=50,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="cosine",
        seed=42,
        output_dir=OUTPUT_DIR,
        eval_strategy="steps",
        eval_steps=250,
        save_strategy="steps",
        save_steps=250,
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        report_to="none",
    ),
)

# 3. Apply Response Masking (Train only on doctor responses)
trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
    num_proc=1,
)

# 4. Argument Hotfix (separate from the average_tokens_across_devices fix above —
#    this one guards num_items_in_batch typing, doesn't hurt to keep)
_orig_training_step = trainer.training_step
def safe_training_step(*args, **kwargs):
    args_list = list(args)
    if len(args_list) >= 3 and isinstance(args_list[2], int):
        args_list[2] = torch.tensor(args_list[2], dtype=torch.float32)
    if "num_items_in_batch" in kwargs and isinstance(kwargs["num_items_in_batch"], int):
        kwargs["num_items_in_batch"] = torch.tensor(kwargs["num_items_in_batch"], dtype=torch.float32)
    return _orig_training_step(*args_list, **kwargs)
trainer.training_step = safe_training_step

# 5. Start Training Loop
print("Starting Unsloth Fine-Tuning...")
trainer.train()

# 6. Save Adapter
model.save_pretrained(f"{OUTPUT_DIR}/final_adapter")
tokenizer.save_pretrained(f"{OUTPUT_DIR}/final_adapter")
print(f"🎉 Training Complete! Adapter saved to {OUTPUT_DIR}/final_adapter")

In [ ]:
import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

BASE_MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"
ADAPTER_PATH = "bn-doctor-lora/final_adapter"

SYSTEM_PROMPT = (
    "আপনি একজন অভিজ্ঞ ও সহানুভূতিশীল চিকিৎসক। রোগীর বর্ণনা পড়ে "
    "স্পষ্ট, নির্ভুল এবং সহজবোধ্য ভাষায় চিকিৎসা পরামর্শ দিন।"
)

# 1. Load Tokenizer & Base Model
print("Loading tokenizer and base model...")
tokenizer = AutoTokenizer.from_pretrained(ADAPTER_PATH)

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL_ID, torch_dtype=torch.float16, device_map="auto"
)

# 2. Load Fine-Tuned LoRA Adapter
print("Loading LoRA adapter...")
model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
model.eval()


# 3. Define Inference Function
def get_medical_advice(user_query: str) -> str:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_query},
    ]

    # Format using Qwen chat template with generation prompt
    prompt = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=512,
            temperature=0.7,
            top_p=0.9,
            repetition_penalty=1.1,
            do_sample=True,
            pad_token_id=tokenizer.pad_token_id,
        )

    # Extract only newly generated text (exclude the input prompt)
    generated_tokens = outputs[0][inputs.input_ids.shape[1] :]
    return tokenizer.decode(generated_tokens, skip_special_tokens=True)


# 4. Test Example
test_patient_query = (
    "আমার গত ৩ দিন ধরে হালকা জ্বর এবং গলা ব্যথা করছে। সাথে সামান্য কাশি আছে। "
    "আমার এখন কী করা উচিত?"
)

print(f"\n--- Patient Input ---\n{test_patient_query}\n")
response = get_medical_advice(test_patient_query)
print(f"--- Doctor Response ---\n{response}")

In [ ]:
import pandas as pd
import torch
from datasets import Dataset
from tqdm import tqdm
from unsloth import FastLanguageModel

# 1. Reconstruct the held-out split
ds_raw = Dataset.from_pandas(df_cleaned_base[["input", "output"]])
eval_raw = ds_raw.train_test_split(test_size=500, seed=42)["test"]

# 2. Configuration & Unsloth Model Loading
ADAPTER_PATH = (
    "/kaggle/input/datasets/towshintushi/adapter/bn-doctor-lora/final_adapter"
)
SYSTEM_PROMPT = (
    "আপনি একজন অভিজ্ঞ ও সহানুভূতিশীল চিকিৎসক। রোগীর বর্ণনা পড়ে "
    "স্পষ্ট, নির্ভুল এবং সহজবোধ্য ভাষায় চিকিৎসা পরামর্শ দিন।"
)

print("Loading model and adapter via Unsloth engine...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=ADAPTER_PATH,
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=False,
)
FastLanguageModel.for_inference(model)

# Configure left padding for batch generation
tokenizer.padding_side = "left"
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

eos_token_id = tokenizer.convert_tokens_to_ids("<|im_end|>")
if eos_token_id is None:
    eos_token_id = tokenizer.eos_token_id


def clean_doctor_response(text):
    if not isinstance(text, str) or not text:
        return ""
    stop_markers = [
        "<|im_end|>",
        "<|im_start|>",
        "<|endoftext|>",
        "user\n",
        "assistant\n",
    ]
    for marker in stop_markers:
        if marker in text:
            text = text.split(marker)[0]
    return text.strip()


# 3. Batch Generation
BATCH_SIZE = 16
inputs_list = eval_raw["input"]
outputs_list = eval_raw["output"]
preds = []

print(f"Generating responses for {len(inputs_list)} validation samples...")

for i in tqdm(range(0, len(inputs_list), BATCH_SIZE)):
    batch_prompts = inputs_list[i : i + BATCH_SIZE]
    texts = [
        tokenizer.apply_chat_template(
            [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": p},
            ],
            tokenize=False,
            add_generation_prompt=True,
        )
        for p in batch_prompts
    ]

    enc = tokenizer(
        texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=1024,
    ).to("cuda")

    with torch.no_grad():
        out = model.generate(
            **enc,
            max_new_tokens=650,
            do_sample=False,
            repetition_penalty=1.15,
            eos_token_id=eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    input_len = enc["input_ids"].shape[1]
    for j in range(len(batch_prompts)):
        raw_text = tokenizer.decode(
            out[j][input_len:], skip_special_tokens=True
        )
        preds.append(clean_doctor_response(raw_text))

# 4. Save CSV
val_predictions = pd.DataFrame({"output": outputs_list, "doctor_response": preds})
val_predictions.to_csv("val_predictions.csv", index=False)
print(f"\n🎉 Successfully saved {len(val_predictions)} rows to val_predictions.csv")

In [ ]:
# !pip install --upgrade torchao

In [ ]:
!unzip adapter.zip -d bn-doctor-lora

In [ ]:
import os
print("Files in current directory:", os.listdir("."))

In [ ]:
import os

print("--- Searching /kaggle/input ---")
input_files = []
for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        full_path = os.path.join(root, file)
        input_files.append(full_path)
        print(f"Found: {full_path}")

if not input_files:
    print(
        "❌ No files found in /kaggle/input. Did you attach your dataset/adapter via 'Add Data' on the right sidebar?"
    )

In [ ]:
!unzip /kaggle/input/datasets/towshintushi/adapter/bn-doctor-lora -d bn-doctor-lora

In [ ]:
import os
import pandas as pdVgFV{b/n; n]
njUY ' ;'9hm11] 
ukpgotv-[i 
        ,bki998-o9p9o9-9o oo lklkll[; l;;;l; l; liiw;d]]}
import torch
from tqdm import tqdm
from unsloth import FastLanguageModel

# Configuration
MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"
OUTPUT_DIR = "bn-doctor-lora"
# ADAPTER_PATH = f"{OUTPUT_DIR}/final_adapter"
#  CORRECT
ADAPTER_PATH = (
    "/kaggle/input/datasets/towshintushi/adapter/bn-doctor-lora/final_adapter"
)

SYSTEM_PROMPT = (
    "আপনি একজন অভিজ্ঞ ও সহানুভূতিশীল চিকিৎসক। রোগীর বর্ণনা পড়ে "
    "স্পষ্ট, নির্ভুল এবং সহজবোধ্য ভাষায় চিকিৎসা পরামর্শ দিন।"
)

# 1. Load Model with Unsloth Engine (Supports long context safety)
print("Loading model with Unsloth fast inference engine...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=ADAPTER_PATH,
    max_seq_length=2048,  # Prevents tensor dimension mismatches
    dtype=None,
    load_in_4bit=False,
)

# Enable Fast 2x CUDA Inference
FastLanguageModel.for_inference(model)

# Configure Left Padding for Batched Generation
tokenizer.padding_side = "left"
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Extract ChatML stop token (<|im_end|>)
eos_token_id = tokenizer.convert_tokens_to_ids("<|im_end|>")
if eos_token_id is None:
    eos_token_id = tokenizer.eos_token_id


# 2. Response Cleaning Function
def clean_doctor_response(text):
    if not isinstance(text, str) or not text:
        return ""

    # Cut off text immediately if ChatML tags or prompt leaks occur
    stop_markers = [
        "<|im_end|>",
        "<|im_start|>",
        "<|endoftext|>",
        "user\n",
        "assistant\n",
    ]
    for marker in stop_markers:
        if marker in text:
            text = text.split(marker)[0]

    return text.strip()


# 3. Batch Inference Loop
test_df = df_base_test
preds = []
BATCH_SIZE = 16  # Smooth VRAM usage

print(
    f"Generating responses for {len(test_df)} test queries in batches of {BATCH_SIZE}..."
)

for i in tqdm(range(0, len(test_df), BATCH_SIZE)):
    batch_prompts = test_df["input"].iloc[i : i + BATCH_SIZE].tolist()

    # Apply Qwen ChatML template
    texts = [
        tokenizer.apply_chat_template(
            [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": p},
            ],
            tokenize=False,
            add_generation_prompt=True,
        )
        for p in batch_prompts
    ]

    # Tokenize input prompts (truncates input prompt max context to 1024)
    inputs = tokenizer(
        texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=1024,
    ).to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=960,  # Full 960 token budget reserved for output
            do_sample=False,  # Greedily selects top tokens
            repetition_penalty=1.15,  # Prevents output loops
            eos_token_id=eos_token_id,  # Halts as soon as response finishes
            pad_token_id=tokenizer.pad_token_id,
        )

    # Extract only the newly generated response tokens
    input_len = inputs["input_ids"].shape[1]
    for j in range(len(batch_prompts)):
        gen_tokens = outputs[j][input_len:]
        raw_text = tokenizer.decode(gen_tokens, skip_special_tokens=True)
        cleaned_text = clean_doctor_response(raw_text)
        preds.append(cleaned_text)

# 4. Save Final Clean Submission CSV
submission = pd.DataFrame({"id": test_df["id"], "doctor_response": preds})

submission.to_csv("submission.csv", index=False)
print("\n🎉 Completed! Predictions saved cleanly to submission.csv")

In [ ]:
import os

# Zip the trained adapter folder
!zip -r final_adapter.zip bn-doctor-lora/final_adapter

# Display download link
from IPython.display import FileLink

display(FileLink("final_adapter.zip"))

Evaluation

In [ ]:
import os
import zipfile
from IPython.display import FileLink, display

csv_file = "submission.csv"
zip_file = "submission.zip"

# 1. Check if submission.csv exists and zip it
if os.path.exists(csv_file):
    with zipfile.ZipFile(
        zip_file, "w", compression=zipfile.ZIP_DEFLATED
    ) as zipf:
        zipf.write(csv_file)

    csv_size = os.path.getsize(csv_file) / (1024 * 1024)
    zip_size = os.path.getsize(zip_file) / (1024 * 1024)

    print(f" Successfully zipped '{csv_file}' ({csv_size:.2f} MB)")
    print(f" Archive size: '{zip_file}' ({zip_size:.2f} MB)\n")
    print("👇 Click the link below to download your file immediately:")

    # 2. Generate clickable download link
    display(FileLink(zip_file))

else:
    print(
        "❌ Error: 'submission.csv' was not found in the current directory."
    )
    print("Please wait for your generation loop to finish completely first.")

In [ ]:
!pip install bert-score rouge-score evaluate nltk sacrebleu

In [ ]:
import numpy as np
import pandas as pd
from collections import Counter
from bert_score import score as compute_bert_score
import evaluate

# ---------------------------------------------------------
# 1. Load Ground Truth vs Generated Predictions
# ---------------------------------------------------------
df_eval = pd.read_csv("val_predictions.csv")
references = df_eval["output"].tolist()
predictions = df_eval["doctor_response"].tolist()
print(f"Evaluating {len(predictions)} validation samples...\n")

# ---------------------------------------------------------
# 2. Compute BERTScore (F1, Precision, Recall)
# ---------------------------------------------------------
print("Computing BERTScore...")
P, R, F1 = compute_bert_score(
    predictions=predictions,
    references=references,
    lang="bn",
    verbose=True,
    batch_size=32,
    device="cuda",
)
bert_f1 = F1.mean().item()
bert_precision = P.mean().item()
bert_recall = R.mean().item()

# ---------------------------------------------------------
# 3. Compute ROUGE Scores
#    NOTE: must override the tokenizer — evaluate's default ROUGE
#    tokenizer strips non-ASCII characters, which silently zeroes
#    out every Bengali score without erroring.
# ---------------------------------------------------------
print("Computing ROUGE scores...")
rouge_metric = evaluate.load("rouge")
rouge_results = rouge_metric.compute(
    predictions=predictions,
    references=references,
    use_aggregator=True,
    tokenizer=lambda x: x.split(),
)

# ---------------------------------------------------------
# 4. Compute Token-level F1 (this is the 30% competition sub-metric —
#    NOT the same as BLEU or ROUGE-1, and wasn't computed before)
# ---------------------------------------------------------
print("Computing Token-level F1...")
def token_f1(pred, ref):
    p_toks, r_toks = pred.split(), ref.split()
    if not p_toks or not r_toks:
        return 0.0
    common = Counter(p_toks) & Counter(r_toks)
    num_common = sum(common.values())
    if num_common == 0:
        return 0.0
    precision = num_common / len(p_toks)
    recall = num_common / len(r_toks)
    return 2 * precision * recall / (precision + recall)

token_f1_scores = [token_f1(p, r) for p, r in zip(predictions, references)]
token_f1_mean = np.mean(token_f1_scores)

# ---------------------------------------------------------
# 5. Compute BLEU Score (informational only — not part of the
#    competition's actual scoring formula)
# ---------------------------------------------------------
print("Computing BLEU score...")
bleu_metric = evaluate.load("bleu")
bleu_results = bleu_metric.compute(
    predictions=predictions, references=references
)

# ---------------------------------------------------------
# 6. Composite Score — this is the real number to track,
#    approximates your Phase 1 leaderboard score
# ---------------------------------------------------------
composite_score = 0.5 * bert_f1 + 0.3 * token_f1_mean + 0.2 * rouge_results["rougeL"]

# ---------------------------------------------------------
# 7. Display Leaderboard Evaluation Summary
# ---------------------------------------------------------
print("=" * 50)
print("              COMPETITION METRICS              ")
print("=" * 50)
print(f"BERTScore F1        : {bert_f1:.4f}")
print(f"BERTScore Precision : {bert_precision:.4f}")
print(f"BERTScore Recall    : {bert_recall:.4f}")
print("-" * 50)
print(f"Token-level F1      : {token_f1_mean:.4f}")
print("-" * 50)
print(f"ROUGE-1             : {rouge_results['rouge1']:.4f}")
print(f"ROUGE-2             : {rouge_results['rouge2']:.4f}")
print(f"ROUGE-L             : {rouge_results['rougeL']:.4f}")
print("-" * 50)
print(f"BLEU-4 (info only)  : {bleu_results['bleu']:.4f}")
print("=" * 50)
print(f"ESTIMATED LEADERBOARD SCORE : {composite_score:.4f}")
print("=" * 50)

In [ ]:
import evaluate
import pandas as pd
from bert_score import score

# 1. Load predictions
df_val = pd.read_csv("val_predictions.csv")
predictions = df_val["doctor_response"].fillna("").tolist()
references = df_val["output"].fillna("").tolist()

print(f"Evaluating {len(predictions)} validation samples...\n")

# 2. Compute BERTScore
print("Computing BERTScore...")
P, R, F1 = score(
    cands=predictions, refs=references, lang="bn", verbose=False, batch_size=32
)

# 3. Compute ROUGE
print("Computing ROUGE...")
rouge = evaluate.load("rouge")
rouge_results = rouge.compute(predictions=predictions, references=references)

# 4. Display Final Evaluation Summary
print("\n" + "=" * 40)
print("🎯 FINAL VALIDATION METRICS")
print("=" * 40)
print(f"BERTScore Precision : {P.mean().item():.4f}")
print(f"BERTScore Recall    : {R.mean().item():.4f}")
print(f"BERTScore F1        : {F1.mean().item():.4f}")
print("-" * 40)
print(f"ROUGE-1             : {rouge_results['rouge1']:.4f}")
print(f"ROUGE-2             : {rouge_results['rouge2']:.4f}")
print(f"ROUGE-L             : {rouge_results['rougeL']:.4f}")
print("=" * 40)

In [ ]:
import pandas as pd

df_val = pd.read_csv("val_predictions.csv")

for i in [0, 5]:
    print(f"--- SAMPLE {i+1} ---")
    print("🎯 TARGET (GROUND TRUTH):\n", df_val["output"].iloc[i])
    print("\n🤖 MODEL GENERATED:\n", df_val["doctor_response"].iloc[i])
    print("=" * 60)

Qwen 2.5

In [ ]:
import re
import pandas as pd

def clean_medical_dataset(df):
    initial_count = len(df)
    
    # 1. Remove duplicates across input and output
    df = df.drop_duplicates(subset=["input"]).copy()
    df = df.drop_duplicates(subset=["output"]).copy()
    
    # 2. Filter out overly short or empty responses
    df = df[df["input"].str.strip().str.len() > 10]
    df = df[df["output"].str.strip().str.len() > 30]
    
    # 3. Remove phrase-repetition loops within a single response
    def has_repetition_loop(text):
        # Detects if a sequence of 3+ words repeats 3 or more times
        pattern = r'(\b[\u0980-\u09FF\w\s]{5,30}\b)\1{2,}'
        return bool(re.search(pattern, text))
    
    df = df[~df["output"].apply(has_repetition_loop)]
    
    # 4. Filter out common AI fluff/filler intros that cause repetitive patterns
    fluff_patterns = [
        r"^হেলো, আপনার প্রশ্নটি পোস্ট করার জন্য ধন্যবাদ।",
        r"^আমি আপনার উদ্বেগ বুঝতে পারছি।",
    ]
    
    for pattern in fluff_patterns:
        df["output"] = df["output"].str.replace(pattern, "", regex=True).str.strip()
        
    # 5. Remove hallucinated / non-sensical terms
    # Add any specific fabricated words you observed to this list
    hallucinated_terms = ["মায়োস্ট্রোমায়েড", "MYDOSIS"]
    for term in hallucinated_terms:
        df = df[~df["output"].str.contains(term, na=False)]

    print(f"Dataset cleaned: reduced from {initial_count} to {len(df)} samples.")
    return df.reset_index(drop=True)

# Clean your dataframe before formatting for SFTTrainer
df_cleaned_base = clean_medical_dataset(df_cleaned_base)

In [ ]:
import os
import torch
from datasets import Dataset
from transformers import TrainingArguments
from trl import SFTTrainer
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import get_chat_template, train_on_responses_only

# 1. Model Configuration
MODEL_NAME = "Qwen/Qwen2.5-3B-Instruct"
MAX_SEQ_LENGTH = 1024  # Reduced from 2048 to 1024 for 2x faster matrix ops
OUTPUT_DIR = "bn-doctor-qwen3b-lora"

SYSTEM_PROMPT = (
    "আপনি একজন অভিজ্ঞ ও সহানুভূতিশীল চিকিৎসক। রোগীর বর্ণনা পড়ে "
    "স্পষ্ট, নির্ভুল এবং সহজবোধ্য ভাষায় চিকিৎসা পরামর্শ দিন।"
)

# 2. Load Base Model and Tokenizer
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_NAME,
    max_seq_length=MAX_SEQ_LENGTH,
    load_in_4bit=True,
)

tokenizer = get_chat_template(
    tokenizer,
    chat_template="qwen-2.5",
)

# 3. Apply LoRA
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    lora_alpha=16,
    lora_dropout=0,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
)

# 4. Format Dataset
def format_prompts(examples):
    texts = []
    for inp, out in zip(examples["input"], examples["output"]):
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": inp},
            {"role": "assistant", "content": out},
        ]
        text = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=False
        )
        texts.append(text)
    return {"text": texts}

dataset = Dataset.from_pandas(df_cleaned_base)
dataset = dataset.map(format_prompts, batched=True, num_proc=1)

# 5. Fast Fine-Tuning Setup
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LENGTH,
    dataset_num_proc=1,
    packing=False,

    args=TrainingArguments(
        per_device_train_batch_size=8,      # Increased per-GPU batch size
        gradient_accumulation_steps=2,      # Effective Global Batch Size = 8 * 2 = 16
        warmup_steps=20,
        max_steps=400,                      # Reduced steps: model converges around 300–400 steps
        learning_rate=2e-4,
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=10,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="cosine",
        seed=42,
        output_dir="outputs",
        save_strategy="no",
        report_to="tensorboard",
    ),
)

# Mask loss to doctor responses
trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
    num_proc=1,
)

# 6. Train and Save Adapter
trainer.train()
model.save_pretrained(f"{OUTPUT_DIR}/final_adapter")
tokenizer.save_pretrained(f"{OUTPUT_DIR}/final_adapter")
print(f"\n🎉 Training complete! Adapter saved to {OUTPUT_DIR}/final_adapter")

In [ ]:
model.save_pretrained("bn-doctor-qwen3b-lora/step_1765")
tokenizer.save_pretrained("bn-doctor-qwen3b-lora/step_1765")

In [ ]:
import shutil

# Compress the final adapter directory into a zip file
shutil.make_archive("bn-doctor-qwen3b-adapter", "zip", "bn-doctor-qwen3b-lora/final_adapter")
print("✅ Adapter zipped successfully!")

In [ ]:
import shutil

# Zip only the final_adapter directory
shutil.make_archive("/kaggle/working/final_adapter", "zip", "/kaggle/working/bn-doctor-qwen3b-lora/final_adapter")
print("✅ final_adapter zipped successfully!")

In [ ]:
!pip install --upgrade --no-cache-dir unsloth transformers trl

In [ ]:
import os
import shutil

# Remove the compiled cache folder
cache_dir = "/kaggle/working/unsloth_compiled_cache"
if os.path.exists(cache_dir):
    shutil.rmtree(cache_dir)
    print("🧹 Cleared Unsloth cache successfully!")

test inference

In [ ]:
import torch
from unsloth import FastLanguageModel

# Path where you saved your adapter
ADAPTER_PATH = "bn-doctor-qwen3b-lora/step_1765"
MAX_SEQ_LENGTH = 2048

# Load Base Model + Saved LoRA Adapter
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=ADAPTER_PATH,
    max_seq_length=MAX_SEQ_LENGTH,
    load_in_4bit=True,
)

# Enable 2x faster inference engine
FastLanguageModel.for_inference(model)

In [ ]:
SYSTEM_PROMPT = (
    "আপনি একজন অভিজ্ঞ ও সহানুভূতিশীল চিকিৎসক। রোগীর বর্ণনা পড়ে "
    "স্পষ্ট, নির্ভুল এবং সহজবোধ্য ভাষায় চিকিৎসা পরামর্শ দিন।"
)

def ask_doctor(user_query: str):
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_query},
    ]

    # Format prompt using Qwen's template
    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,  # Crucial: adds <|im_start|>assistant\n
        return_tensors="pt"
    ).to("cuda")

    # Generate response
    outputs = model.generate(
        input_ids=inputs,
        max_new_tokens=512,
        temperature=0.3,       # Low temperature for factual/medical precision
        top_p=0.9,
        do_sample=True,
        use_cache=True,
    )

    # Decode and extract response
    response = tokenizer.decode(outputs[0][inputs.shape[1]:], skip_special_tokens=True)
    return response

# Test Query
query = "আমার গত ৩ দিন ধরে তীব্র মাথা ব্যথা করছে এবং সাথে হালকা বমি ভাব আছে। কি করা উচিত?"
print("--- Doctor's Response ---")
print(ask_doctor(query))

In [ ]:
import pandas as pd
import torch
from tqdm import tqdm
from unsloth import FastLanguageModel

# 1. Prepare Model for Inference
FastLanguageModel.for_inference(model)

tokenizer.padding_side = "left"
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

eos_token_id = tokenizer.convert_tokens_to_ids("<|im_end|>")
if eos_token_id is None:
    eos_token_id = tokenizer.eos_token_id

# 2. Get Held-Out Validation Split
val_inputs = eval_raw["input"]
val_outputs = eval_raw["output"]
preds = []
BATCH_SIZE = 16

print(f"Generating predictions for {len(val_inputs)} validation samples...")

for i in tqdm(range(0, len(val_inputs), BATCH_SIZE)):
    batch_prompts = val_inputs[i : i + BATCH_SIZE]
    texts = [
        tokenizer.apply_chat_template(
            [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": p},
            ],
            tokenize=False,
            add_generation_prompt=True,
        )
        for p in batch_prompts
    ]

    enc = tokenizer(
        texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=1024,
    ).to("cuda")

    with torch.no_grad():
        out = model.generate(
            **enc,
            max_new_tokens=400,
            no_repeat_ngram_size=4,  # Prevents repeating 4-word phrases
            repetition_penalty=1.25,  # Heavily penalizes token loops
            do_sample=True,
            temperature=0.3,  # Low temperature preserves factuality
            top_p=0.9,
            eos_token_id=eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    input_len = enc["input_ids"].shape[1]
    for j in range(len(batch_prompts)):
        raw_text = tokenizer.decode(
            out[j][input_len:], skip_special_tokens=True
        )
        clean_text = raw_text.split("<|im_end|>")[0].strip()
        preds.append(clean_text)

# 3. Save Predictions
val_predictions = pd.DataFrame({"output": val_outputs, "doctor_response": preds})
val_predictions.to_csv("val_predictions.csv", index=False)
print(" Saved val_predictions.csv successfully!")

In [54]:
import os
import pandas as pd
import torch
from tqdm import tqdm
from unsloth import FastLanguageModel

# 1. Paths & Configuration
LOCAL_ADAPTER = "/kaggle/working/bn-doctor-qwen3b-lora/final_adapter"
KAGGLE_ADAPTER = "/kaggle/input/datasets/towshintushi/new-adaptor"

ADAPTER_PATH = LOCAL_ADAPTER if os.path.exists(LOCAL_ADAPTER) else KAGGLE_ADAPTER

SYSTEM_PROMPT = (
    "আপনি একজন অভিজ্ঞ ও সহানুভূতিশীল চিকিৎসক। রোগীর বর্ণনা পড়ে "
    "স্পষ্ট, নির্ভুল এবং সহজবোধ্য ভাষায় চিকিৎসা পরামর্শ দিন।"
)

# 2. Load Model & Prepare for Fast Inference
try:
    FastLanguageModel.for_inference(model)
    print("Using model already loaded in memory.")
except NameError:
    print(f"Loading model from {ADAPTER_PATH}...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=ADAPTER_PATH,
        max_seq_length=1024,
        load_in_4bit=True,
    )
    FastLanguageModel.for_inference(model)

tokenizer.padding_side = "left"
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

eos_token_id = tokenizer.convert_tokens_to_ids("<|im_end|>")
if eos_token_id is None:
    eos_token_id = tokenizer.eos_token_id


def clean_doctor_response(text):
    if not isinstance(text, str) or not text:
        return ""
    stop_markers = [
        "<|im_end|>",
        "<|im_start|>",
        "<|endoftext|>",
        "user\n",
        "assistant\n",
    ]
    for marker in stop_markers:
        if marker in text:
            text = text.split(marker)[0]
    return text.strip()


# 3. Load Cleaned Test Data
test_df = df_base_test
preds = []
BATCH_SIZE = 16

print(
    f"Generating predictions for {len(test_df)} test queries in batches of {BATCH_SIZE}..."
)

# 4. Batch Inference Loop
for i in tqdm(range(0, len(test_df), BATCH_SIZE)):
    batch_df = test_df.iloc[i : i + BATCH_SIZE]
    batch_prompts = batch_df["input"].tolist()

    texts = [
        tokenizer.apply_chat_template(
            [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": p},
            ],
            tokenize=False,
            add_generation_prompt=True,
        )
        for p in batch_prompts
    ]

    inputs = tokenizer(
        texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=1024,
    ).to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=350,
            repetition_penalty=1.05,  # Lowered from 1.25 to prevent character distortion
            do_sample=True,
            temperature=0.2,          # Low temperature ensures high precision
            top_p=0.85,
            eos_token_id=eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
            # no_repeat_ngram_size REMOVED to prevent breaking multi-byte Bengali unicode subwords
        )

    # 5. Extract & Clean Generations per sample
    for j in range(len(batch_prompts)):
        sample_input_len = inputs["input_ids"][j].shape[0]
        gen_tokens = outputs[j][sample_input_len:]
        raw_text = tokenizer.decode(gen_tokens, skip_special_tokens=True)
        preds.append(clean_doctor_response(raw_text))

# 6. Save submission.csv
submission = pd.DataFrame({"id": test_df["id"], "output": preds})

submission.to_csv("submission.csv", index=False)

print("\n🎉 SUCCESS! submission.csv created successfully.")
print(f"Total rows: {len(submission)}")
print(submission.head(3))

Using model already loaded in memory.
Generating predictions for 1000 test queries in batches of 16...

  0%|          | 0/63 [00:00<?, ?it/s]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  2%|▏         | 1/63 [02:01<2:05:29, 121.45s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  3%|▎         | 2/63 [04:01<2:02:33, 120.55s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  5%|▍         | 3/63 [05:59<1:59:36, 119.61s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  6%|▋         | 4/63 [07:58<1:57:17, 119.28s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  8%|▊         | 5/63 [09:49<1:52:14, 116.11s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 10%|▉         | 6/63 [11:45<1:50:18, 116.12s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 11%|█         | 7/63 [13:45<1:49:36, 117.44s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 13%|█▎        | 8/63 [15:37<1:46:09, 115.81s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 14%|█▍        | 9/63 [17:34<1:44:24, 116.01s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 16%|█▌        | 10/63 [19:33<1:43:20, 116.99s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 17%|█▋        | 11/63 [21:33<1:42:15, 117.98s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 19%|█▉        | 12/63 [23:33<1:40:40, 118.45s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 21%|██        | 13/63 [25:30<1:38:26, 118.13s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 22%|██▏       | 14/63 [27:29<1:36:46, 118.49s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 24%|██▍       | 15/63 [29:25<1:34:04, 117.58s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 25%|██▌       | 16/63 [31:24<1:32:27, 118.03s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 27%|██▋       | 17/63 [33:23<1:30:41, 118.29s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 29%|██▊       | 18/63 [35:15<1:27:15, 116.34s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 30%|███       | 19/63 [37:14<1:25:55, 117.16s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 32%|███▏      | 20/63 [39:14<1:24:37, 118.08s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 33%|███▎      | 21/63 [41:13<1:22:57, 118.52s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 35%|███▍      | 22/63 [42:57<1:17:51, 113.94s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 37%|███▋      | 23/63 [44:56<1:16:57, 115.43s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 38%|███▊      | 24/63 [46:35<1:11:48, 110.49s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 40%|███▉      | 25/63 [48:19<1:08:52, 108.75s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 41%|████▏     | 26/63 [50:18<1:08:56, 111.81s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 43%|████▎     | 27/63 [52:15<1:07:57, 113.26s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 44%|████▍     | 28/63 [54:08<1:06:05, 113.29s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 46%|████▌     | 29/63 [55:56<1:03:20, 111.77s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 48%|████▊     | 30/63 [57:56<1:02:44, 114.08s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 49%|████▉     | 31/63 [59:53<1:01:23, 115.12s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 51%|█████     | 32/63 [1:01:52<1:00:03, 116.23s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 52%|█████▏    | 33/63 [1:03:41<56:55, 113.85s/it]  Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 54%|█████▍    | 34/63 [1:05:33<54:49, 113.42s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 56%|█████▌    | 35/63 [1:07:32<53:44, 115.15s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 57%|█████▋    | 36/63 [1:09:32<52:24, 116.45s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 59%|█████▊    | 37/63 [1:11:31<50:47, 117.20s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 60%|██████    | 38/63 [1:13:16<47:19, 113.56s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 62%|██████▏   | 39/63 [1:15:12<45:42, 114.27s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 63%|██████▎   | 40/63 [1:17:04<43:36, 113.77s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 65%|██████▌   | 41/63 [1:19:04<42:23, 115.63s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 67%|██████▋   | 42/63 [1:20:55<39:57, 114.17s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 68%|██████▊   | 43/63 [1:22:54<38:31, 115.59s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 70%|██████▉   | 44/63 [1:24:53<36:54, 116.55s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 71%|███████▏  | 45/63 [1:26:41<34:12, 114.03s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 73%|███████▎  | 46/63 [1:28:35<32:21, 114.22s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 75%|███████▍  | 47/63 [1:30:35<30:52, 115.75s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 76%|███████▌  | 48/63 [1:32:34<29:11, 116.76s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 78%|███████▊  | 49/63 [1:34:34<27:27, 117.70s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 79%|███████▉  | 50/63 [1:36:25<25:03, 115.62s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 81%|████████  | 51/63 [1:38:24<23:20, 116.73s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 83%|████████▎ | 52/63 [1:40:20<21:22, 116.56s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 84%|████████▍ | 53/63 [1:42:19<19:33, 117.33s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 86%|████████▌ | 54/63 [1:44:18<17:40, 117.80s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 87%|████████▋ | 55/63 [1:46:17<15:45, 118.17s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 89%|████████▉ | 56/63 [1:48:16<13:49, 118.44s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 90%|█████████ | 57/63 [1:50:09<11:40, 116.72s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 92%|█████████▏| 58/63 [1:52:08<09:46, 117.31s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 94%|█████████▎| 59/63 [1:54:03<07:46, 116.72s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 95%|█████████▌| 60/63 [1:55:54<05:44, 114.93s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 97%|█████████▋| 61/63 [1:57:53<03:52, 116.19s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 98%|█████████▊| 62/63 [1:59:47<01:55, 115.63s/it]Both `max_new_tokens` (=350) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
100%|██████████| 63/63 [2:00:56<00:00, 115.18s/it]

🎉 SUCCESS! submission.csv created successfully.
Total rows: 1000
      id  \
0  34654
1   3116
2  59478

                                                                                                                                                                                                                                                                                                                                           output
0        হেলো, আপনার উদ্বেগের বিষয়টি আমি বুঝতে পেরেছি। আপনার লাইপেজ বেশি এবং অ্যামাইলেজ স্বাভাবিক। আপনার গ্লুটেন এবং গমের প্রতি সংবেদনশীলতা আছে। আপনার প্রশ্নের উত্তর হলো, আপনার গ্লুটেন এবং গমের প্রতি সংবেদনশীলতা আছে। আপনার প্রশ্নের উত্তর হলো, আপনার গ্লুটেন এবং গমের প্রতি সংবেদনশীলতা আছে। আপনার প্রশ্নের উত্তর হলো, আপনার গ্লুটেন এবং গমে
1   হেলো, আপনার অনুসন্ধানের জন্য ধন্যবাদ। আপনার অনুসন্ধানটি পড়েছি এবং আপনার উদ্বেগগুলো বুঝতে পেরেছি। আমি আপনাকে জানাতে চাই যে, আপনার দাঁতের সংক্রমণ থাকতে পারে। আপনার দাঁতের সংক্রমণ থাকলে আপনার মুখে বমি বমি ভাব হতে পারে। আপনার দাঁতের সংক্রমণ থাকলে আপনার দাঁতের সংক্রমণের কারণে মুখের স্বাদ বাড়তে পারে। আপনার দাঁতের সংক্রমণ থাকলে আপনার ম�
2  হেলো, আপনার উদ্বেগের বিষয়টি আমি বুঝতে পেরেছি। আমি আপনাকে পরামর্শ দেব যে আপনার স্বামীর মানসিক সমস্যার জন্য একজন মনোরোগ বিশেষজ্ঞের পরামর্শ নেওয়া উচিত। তার মানসিক চাপ এবং অন্যান্য মানসিক সমস্যার কারণে এই ধরনের বিষয়গুলো হতে পারে। তার মানসিক চাপ কমানোর জন্য একটি মানসিক চেস্ট্রেটর বা মনোরোগ বিশেষজ্ঞের পরামর্শ নেওয়া উচিত। আশা করি আমি আ